### YamlMime:ManagedReference
items:
- uid: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder
  commentId: T:Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder
  id: IApizrResilienceContextOptionsBuilder
  parent: Apizr.Configuring.Shared.Context
  children:
  - Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder.ContinueOnCapturedContext(System.Boolean)
  - Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder.ReturnToPoolOnComplete(System.Boolean)
  langs:
  - csharp
  - vb
  name: IApizrResilienceContextOptionsBuilder
  nameWithType: IApizrResilienceContextOptionsBuilder
  fullName: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder
  type: Interface
  source:
    remote:
      path: Apizr/Src/Apizr/Configuring/Shared/Context/IApizrResilienceContextOptionsBuilder.cs
      branch: feat/resilience
      repo: https://github.com/Respawnsive/Apizr.git
    id: IApizrResilienceContextOptionsBuilder
    path: ../../Src/Apizr/Configuring/Shared/Context/IApizrResilienceContextOptionsBuilder.cs
    startLine: 2
  assemblies:
  - Apizr
  namespace: Apizr.Configuring.Shared.Context
  syntax:
    content: public interface IApizrResilienceContextOptionsBuilder
    content.vb: Public Interface IApizrResilienceContextOptionsBuilder
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder.ContinueOnCapturedContext(System.Boolean)
  commentId: M:Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder.ContinueOnCapturedContext(System.Boolean)
  id: ContinueOnCapturedContext(System.Boolean)
  parent: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder
  langs:
  - csharp
  - vb
  name: ContinueOnCapturedContext(Boolean)
  nameWithType: IApizrResilienceContextOptionsBuilder.ContinueOnCapturedContext(Boolean)
  fullName: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder.ContinueOnCapturedContext(System.Boolean)
  type: Method
  source:
    remote:
      path: Apizr/Src/Apizr/Configuring/Shared/Context/IApizrResilienceContextOptionsBuilder.cs
      branch: feat/resilience
      repo: https://github.com/Respawnsive/Apizr.git
    id: ContinueOnCapturedContext
    path: ../../Src/Apizr/Configuring/Shared/Context/IApizrResilienceContextOptionsBuilder.cs
    startLine: 6
  assemblies:
  - Apizr
  namespace: Apizr.Configuring.Shared.Context
  syntax:
    content: IApizrResilienceContextOptionsBuilder ContinueOnCapturedContext(bool continueOnCapturedContext)
    parameters:
    - id: continueOnCapturedContext
      type: System.Boolean
    return:
      type: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder
    content.vb: Function ContinueOnCapturedContext(continueOnCapturedContext As Boolean) As IApizrResilienceContextOptionsBuilder
  overload: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder.ContinueOnCapturedContext*
- uid: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder.ReturnToPoolOnComplete(System.Boolean)
  commentId: M:Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder.ReturnToPoolOnComplete(System.Boolean)
  id: ReturnToPoolOnComplete(System.Boolean)
  parent: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder
  langs:
  - csharp
  - vb
  name: ReturnToPoolOnComplete(Boolean)
  nameWithType: IApizrResilienceContextOptionsBuilder.ReturnToPoolOnComplete(Boolean)
  fullName: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder.ReturnToPoolOnComplete(System.Boolean)
  type: Method
  source:
    remote:
      path: Apizr/Src/Apizr/Configuring/Shared/Context/IApizrResilienceContextOptionsBuilder.cs
      branch: feat/resilience
      repo: https://github.com/Respawnsive/Apizr.git
    id: ReturnToPoolOnComplete
    path: ../../Src/Apizr/Configuring/Shared/Context/IApizrResilienceContextOptionsBuilder.cs
    startLine: 8
  assemblies:
  - Apizr
  namespace: Apizr.Configuring.Shared.Context
  syntax:
    content: IApizrResilienceContextOptionsBuilder ReturnToPoolOnComplete(bool returnToPoolOnComplete)
    parameters:
    - id: returnToPoolOnComplete
      type: System.Boolean
    return:
      type: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder
    content.vb: Function ReturnToPoolOnComplete(returnToPoolOnComplete As Boolean) As IApizrResilienceContextOptionsBuilder
  overload: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder.ReturnToPoolOnComplete*
references:
- uid: Apizr.Configuring.Shared.Context
  commentId: N:Apizr.Configuring.Shared.Context
  name: Apizr.Configuring.Shared.Context
  nameWithType: Apizr.Configuring.Shared.Context
  fullName: Apizr.Configuring.Shared.Context
- uid: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder.ContinueOnCapturedContext*
  commentId: Overload:Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder.ContinueOnCapturedContext
  name: ContinueOnCapturedContext
  nameWithType: IApizrResilienceContextOptionsBuilder.ContinueOnCapturedContext
  fullName: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder.ContinueOnCapturedContext
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder
  commentId: T:Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder
  parent: Apizr.Configuring.Shared.Context
  name: IApizrResilienceContextOptionsBuilder
  nameWithType: IApizrResilienceContextOptionsBuilder
  fullName: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder.ReturnToPoolOnComplete*
  commentId: Overload:Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder.ReturnToPoolOnComplete
  name: ReturnToPoolOnComplete
  nameWithType: IApizrResilienceContextOptionsBuilder.ReturnToPoolOnComplete
  fullName: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder.ReturnToPoolOnComplete
