### YamlMime:ManagedReference
items:
- uid: Apizr.Configuring.Request.IApizrRequestOptionsBase
  commentId: T:Apizr.Configuring.Request.IApizrRequestOptionsBase
  id: IApizrRequestOptionsBase
  parent: Apizr.Configuring.Request
  children:
  - Apizr.Configuring.Request.IApizrRequestOptionsBase.Context
  langs:
  - csharp
  - vb
  name: IApizrRequestOptionsBase
  nameWithType: IApizrRequestOptionsBase
  fullName: Apizr.Configuring.Request.IApizrRequestOptionsBase
  type: Interface
  source:
    remote:
      path: Apizr/Src/Apizr/Configuring/Request/IApizrRequestOptionsBase.cs
      branch: dev
      repo: https://github.com/Respawnsive/Apizr.git
    id: IApizrRequestOptionsBase
    path: ../../Src/Apizr/Configuring/Request/IApizrRequestOptionsBase.cs
    startLine: 8
  assemblies:
  - Apizr
  namespace: Apizr.Configuring.Request
  summary: "\nOptions available at request levels and for all (static and extended) registration types\n"
  example: []
  syntax:
    content: 'public interface IApizrRequestOptionsBase : IApizrGlobalSharedOptionsBase'
    content.vb: >-
      Public Interface IApizrRequestOptionsBase
          Inherits IApizrGlobalSharedOptionsBase
  inheritedMembers:
  - Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.HttpTracerMode
  - Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.TrafficVerbosity
  - Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.LogLevels
  - Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.OnException
  - Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.LetThrowOnExceptionWithEmptyCache
  - Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.HandlersParameters
  - Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.Headers
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Apizr.Configuring.Request.IApizrRequestOptionsBase.Context
  commentId: P:Apizr.Configuring.Request.IApizrRequestOptionsBase.Context
  id: Context
  parent: Apizr.Configuring.Request.IApizrRequestOptionsBase
  langs:
  - csharp
  - vb
  name: Context
  nameWithType: IApizrRequestOptionsBase.Context
  fullName: Apizr.Configuring.Request.IApizrRequestOptionsBase.Context
  type: Property
  source:
    remote:
      path: Apizr/Src/Apizr/Configuring/Request/IApizrRequestOptionsBase.cs
      branch: dev
      repo: https://github.com/Respawnsive/Apizr.git
    id: Context
    path: ../../Src/Apizr/Configuring/Request/IApizrRequestOptionsBase.cs
    startLine: 13
  assemblies:
  - Apizr
  namespace: Apizr.Configuring.Request
  summary: "\nThe Polly Context to pass through it all\n"
  example: []
  syntax:
    content: Context Context { get; }
    parameters: []
    return:
      type: Polly.Context
    content.vb: ReadOnly Property Context As Context
  overload: Apizr.Configuring.Request.IApizrRequestOptionsBase.Context*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
references:
- uid: Apizr.Configuring.Request
  commentId: N:Apizr.Configuring.Request
  name: Apizr.Configuring.Request
  nameWithType: Apizr.Configuring.Request
  fullName: Apizr.Configuring.Request
- uid: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.HttpTracerMode
  commentId: P:Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.HttpTracerMode
  parent: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase
  name: HttpTracerMode
  nameWithType: IApizrGlobalSharedOptionsBase.HttpTracerMode
  fullName: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.HttpTracerMode
- uid: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.TrafficVerbosity
  commentId: P:Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.TrafficVerbosity
  parent: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase
  name: TrafficVerbosity
  nameWithType: IApizrGlobalSharedOptionsBase.TrafficVerbosity
  fullName: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.TrafficVerbosity
- uid: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.LogLevels
  commentId: P:Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.LogLevels
  parent: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase
  name: LogLevels
  nameWithType: IApizrGlobalSharedOptionsBase.LogLevels
  fullName: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.LogLevels
- uid: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.OnException
  commentId: P:Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.OnException
  parent: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase
  name: OnException
  nameWithType: IApizrGlobalSharedOptionsBase.OnException
  fullName: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.OnException
- uid: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.LetThrowOnExceptionWithEmptyCache
  commentId: P:Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.LetThrowOnExceptionWithEmptyCache
  parent: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase
  name: LetThrowOnExceptionWithEmptyCache
  nameWithType: IApizrGlobalSharedOptionsBase.LetThrowOnExceptionWithEmptyCache
  fullName: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.LetThrowOnExceptionWithEmptyCache
- uid: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.HandlersParameters
  commentId: P:Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.HandlersParameters
  parent: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase
  name: HandlersParameters
  nameWithType: IApizrGlobalSharedOptionsBase.HandlersParameters
  fullName: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.HandlersParameters
- uid: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.Headers
  commentId: P:Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.Headers
  parent: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase
  name: Headers
  nameWithType: IApizrGlobalSharedOptionsBase.Headers
  fullName: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.Headers
- uid: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase
  commentId: T:Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase
  parent: Apizr.Configuring.Shared
  name: IApizrGlobalSharedOptionsBase
  nameWithType: IApizrGlobalSharedOptionsBase
  fullName: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase
- uid: Apizr.Configuring.Shared
  commentId: N:Apizr.Configuring.Shared
  name: Apizr.Configuring.Shared
  nameWithType: Apizr.Configuring.Shared
  fullName: Apizr.Configuring.Shared
- uid: Apizr.Configuring.Request.IApizrRequestOptionsBase.Context*
  commentId: Overload:Apizr.Configuring.Request.IApizrRequestOptionsBase.Context
  name: Context
  nameWithType: IApizrRequestOptionsBase.Context
  fullName: Apizr.Configuring.Request.IApizrRequestOptionsBase.Context
- uid: Polly.Context
  commentId: T:Polly.Context
  parent: Polly
  isExternal: true
  name: Context
  nameWithType: Context
  fullName: Polly.Context
- uid: Polly
  commentId: N:Polly
  isExternal: true
  name: Polly
  nameWithType: Polly
  fullName: Polly
