### YamlMime:ManagedReference
items:
- uid: Apizr.Extending.Configuring.IApizrExtendedOptionsBase
  commentId: T:Apizr.Extending.Configuring.IApizrExtendedOptionsBase
  id: IApizrExtendedOptionsBase
  parent: Apizr.Extending.Configuring
  children:
  - Apizr.Extending.Configuring.IApizrExtendedOptionsBase.HttpClientHandler
  langs:
  - csharp
  - vb
  name: IApizrExtendedOptionsBase
  nameWithType: IApizrExtendedOptionsBase
  fullName: Apizr.Extending.Configuring.IApizrExtendedOptionsBase
  type: Interface
  source:
    id: IApizrExtendedOptionsBase
    path: C:\Dev\Community\Apizr\Apizr\Apizr.Extensions.Microsoft.DependencyInjection\Extending\Configuring\IApizrExtendedOptionsBase.cs
    startLine: 7
  assemblies:
  - Apizr.Extensions.Microsoft.DependencyInjection
  namespace: Apizr.Extending.Configuring
  syntax:
    content: 'public interface IApizrExtendedOptionsBase : IApizrExtendedCommonOptionsBase, IApizrExtendedProperOptionsBase, IApizrExtendedSharedOptionsBase, IApizrOptionsBase, IApizrCommonOptionsBase, IApizrProperOptionsBase, IApizrSharedOptionsBase'
    content.vb: >-
      Public Interface IApizrExtendedOptionsBase
          Inherits IApizrExtendedCommonOptionsBase, IApizrExtendedProperOptionsBase, IApizrOptionsBase
  inheritedMembers:
  - Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptionsBase.DelegatingHandlersExtendedFactories
  - Apizr.Configuring.Common.IApizrCommonOptionsBase.RefitSettings
  - Apizr.Configuring.Proper.IApizrProperOptionsBase.WebApiType
  - Apizr.Configuring.Proper.IApizrProperOptionsBase.PolicyRegistryKeys
  - Apizr.Configuring.Proper.IApizrProperOptionsBase.Logger
  - Apizr.Configuring.Shared.IApizrSharedOptionsBase.BaseUri
  - Apizr.Configuring.Shared.IApizrSharedOptionsBase.BaseAddress
  - Apizr.Configuring.Shared.IApizrSharedOptionsBase.BasePath
  - Apizr.Configuring.Shared.IApizrSharedOptionsBase.HttpTracerMode
  - Apizr.Configuring.Shared.IApizrSharedOptionsBase.TrafficVerbosity
  - Apizr.Configuring.Shared.IApizrSharedOptionsBase.LogLevels
  extensionMethods:
  - System.Object.Apizr.Extending.ObjectExtensions.ToString(System.String,System.String)
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Apizr.Extending.Configuring.IApizrExtendedOptionsBase.HttpClientHandler
  commentId: P:Apizr.Extending.Configuring.IApizrExtendedOptionsBase.HttpClientHandler
  id: HttpClientHandler
  parent: Apizr.Extending.Configuring.IApizrExtendedOptionsBase
  langs:
  - csharp
  - vb
  name: HttpClientHandler
  nameWithType: IApizrExtendedOptionsBase.HttpClientHandler
  fullName: Apizr.Extending.Configuring.IApizrExtendedOptionsBase.HttpClientHandler
  type: Property
  source:
    id: HttpClientHandler
    path: C:\Dev\Community\Apizr\Apizr\Apizr.Extensions.Microsoft.DependencyInjection\Extending\Configuring\IApizrExtendedOptionsBase.cs
    startLine: 9
  assemblies:
  - Apizr.Extensions.Microsoft.DependencyInjection
  namespace: Apizr.Extending.Configuring
  syntax:
    content: HttpClientHandler HttpClientHandler { get; }
    parameters: []
    return:
      type: System.Net.Http.HttpClientHandler
    content.vb: ReadOnly Property HttpClientHandler As HttpClientHandler
  overload: Apizr.Extending.Configuring.IApizrExtendedOptionsBase.HttpClientHandler*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
references:
- uid: Apizr.Extending.Configuring
  commentId: N:Apizr.Extending.Configuring
  name: Apizr.Extending.Configuring
  nameWithType: Apizr.Extending.Configuring
  fullName: Apizr.Extending.Configuring
- uid: Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptionsBase.DelegatingHandlersExtendedFactories
  commentId: P:Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptionsBase.DelegatingHandlersExtendedFactories
  parent: Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptionsBase
  name: DelegatingHandlersExtendedFactories
  nameWithType: IApizrExtendedSharedOptionsBase.DelegatingHandlersExtendedFactories
  fullName: Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptionsBase.DelegatingHandlersExtendedFactories
- uid: Apizr.Configuring.Common.IApizrCommonOptionsBase.RefitSettings
  commentId: P:Apizr.Configuring.Common.IApizrCommonOptionsBase.RefitSettings
  parent: Apizr.Configuring.Common.IApizrCommonOptionsBase
  name: RefitSettings
  nameWithType: IApizrCommonOptionsBase.RefitSettings
  fullName: Apizr.Configuring.Common.IApizrCommonOptionsBase.RefitSettings
- uid: Apizr.Configuring.Proper.IApizrProperOptionsBase.WebApiType
  commentId: P:Apizr.Configuring.Proper.IApizrProperOptionsBase.WebApiType
  parent: Apizr.Configuring.Proper.IApizrProperOptionsBase
  name: WebApiType
  nameWithType: IApizrProperOptionsBase.WebApiType
  fullName: Apizr.Configuring.Proper.IApizrProperOptionsBase.WebApiType
- uid: Apizr.Configuring.Proper.IApizrProperOptionsBase.PolicyRegistryKeys
  commentId: P:Apizr.Configuring.Proper.IApizrProperOptionsBase.PolicyRegistryKeys
  parent: Apizr.Configuring.Proper.IApizrProperOptionsBase
  name: PolicyRegistryKeys
  nameWithType: IApizrProperOptionsBase.PolicyRegistryKeys
  fullName: Apizr.Configuring.Proper.IApizrProperOptionsBase.PolicyRegistryKeys
- uid: Apizr.Configuring.Proper.IApizrProperOptionsBase.Logger
  commentId: P:Apizr.Configuring.Proper.IApizrProperOptionsBase.Logger
  parent: Apizr.Configuring.Proper.IApizrProperOptionsBase
  name: Logger
  nameWithType: IApizrProperOptionsBase.Logger
  fullName: Apizr.Configuring.Proper.IApizrProperOptionsBase.Logger
- uid: Apizr.Configuring.Shared.IApizrSharedOptionsBase.BaseUri
  commentId: P:Apizr.Configuring.Shared.IApizrSharedOptionsBase.BaseUri
  parent: Apizr.Configuring.Shared.IApizrSharedOptionsBase
  name: BaseUri
  nameWithType: IApizrSharedOptionsBase.BaseUri
  fullName: Apizr.Configuring.Shared.IApizrSharedOptionsBase.BaseUri
- uid: Apizr.Configuring.Shared.IApizrSharedOptionsBase.BaseAddress
  commentId: P:Apizr.Configuring.Shared.IApizrSharedOptionsBase.BaseAddress
  parent: Apizr.Configuring.Shared.IApizrSharedOptionsBase
  name: BaseAddress
  nameWithType: IApizrSharedOptionsBase.BaseAddress
  fullName: Apizr.Configuring.Shared.IApizrSharedOptionsBase.BaseAddress
- uid: Apizr.Configuring.Shared.IApizrSharedOptionsBase.BasePath
  commentId: P:Apizr.Configuring.Shared.IApizrSharedOptionsBase.BasePath
  parent: Apizr.Configuring.Shared.IApizrSharedOptionsBase
  name: BasePath
  nameWithType: IApizrSharedOptionsBase.BasePath
  fullName: Apizr.Configuring.Shared.IApizrSharedOptionsBase.BasePath
- uid: Apizr.Configuring.Shared.IApizrSharedOptionsBase.HttpTracerMode
  commentId: P:Apizr.Configuring.Shared.IApizrSharedOptionsBase.HttpTracerMode
  parent: Apizr.Configuring.Shared.IApizrSharedOptionsBase
  name: HttpTracerMode
  nameWithType: IApizrSharedOptionsBase.HttpTracerMode
  fullName: Apizr.Configuring.Shared.IApizrSharedOptionsBase.HttpTracerMode
- uid: Apizr.Configuring.Shared.IApizrSharedOptionsBase.TrafficVerbosity
  commentId: P:Apizr.Configuring.Shared.IApizrSharedOptionsBase.TrafficVerbosity
  parent: Apizr.Configuring.Shared.IApizrSharedOptionsBase
  name: TrafficVerbosity
  nameWithType: IApizrSharedOptionsBase.TrafficVerbosity
  fullName: Apizr.Configuring.Shared.IApizrSharedOptionsBase.TrafficVerbosity
- uid: Apizr.Configuring.Shared.IApizrSharedOptionsBase.LogLevels
  commentId: P:Apizr.Configuring.Shared.IApizrSharedOptionsBase.LogLevels
  parent: Apizr.Configuring.Shared.IApizrSharedOptionsBase
  name: LogLevels
  nameWithType: IApizrSharedOptionsBase.LogLevels
  fullName: Apizr.Configuring.Shared.IApizrSharedOptionsBase.LogLevels
- uid: System.Object.Apizr.Extending.ObjectExtensions.ToString(System.String,System.String)
  commentId: M:Apizr.Extending.ObjectExtensions.ToString(System.Object,System.String,System.String)
  parent: Apizr.Extending.ObjectExtensions
  definition: Apizr.Extending.ObjectExtensions.ToString(System.Object,System.String,System.String)
  name: ToString(String, String)
  nameWithType: ObjectExtensions.ToString(String, String)
  fullName: Apizr.Extending.ObjectExtensions.ToString(System.String, System.String)
  spec.csharp:
  - uid: Apizr.Extending.ObjectExtensions.ToString(System.String,System.String)
    name: ToString
    nameWithType: ObjectExtensions.ToString
    fullName: Apizr.Extending.ObjectExtensions.ToString
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Apizr.Extending.ObjectExtensions.ToString(System.String,System.String)
    name: ToString
    nameWithType: ObjectExtensions.ToString
    fullName: Apizr.Extending.ObjectExtensions.ToString
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptionsBase
  commentId: T:Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptionsBase
  parent: Apizr.Extending.Configuring.Shared
  name: IApizrExtendedSharedOptionsBase
  nameWithType: IApizrExtendedSharedOptionsBase
  fullName: Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptionsBase
- uid: Apizr.Configuring.Common.IApizrCommonOptionsBase
  commentId: T:Apizr.Configuring.Common.IApizrCommonOptionsBase
  parent: Apizr.Configuring.Common
  name: IApizrCommonOptionsBase
  nameWithType: IApizrCommonOptionsBase
  fullName: Apizr.Configuring.Common.IApizrCommonOptionsBase
- uid: Apizr.Configuring.Proper.IApizrProperOptionsBase
  commentId: T:Apizr.Configuring.Proper.IApizrProperOptionsBase
  parent: Apizr.Configuring.Proper
  name: IApizrProperOptionsBase
  nameWithType: IApizrProperOptionsBase
  fullName: Apizr.Configuring.Proper.IApizrProperOptionsBase
- uid: Apizr.Configuring.Shared.IApizrSharedOptionsBase
  commentId: T:Apizr.Configuring.Shared.IApizrSharedOptionsBase
  parent: Apizr.Configuring.Shared
  name: IApizrSharedOptionsBase
  nameWithType: IApizrSharedOptionsBase
  fullName: Apizr.Configuring.Shared.IApizrSharedOptionsBase
- uid: Apizr.Extending.ObjectExtensions.ToString(System.Object,System.String,System.String)
  commentId: M:Apizr.Extending.ObjectExtensions.ToString(System.Object,System.String,System.String)
  isExternal: true
  name: ToString(Object, String, String)
  nameWithType: ObjectExtensions.ToString(Object, String, String)
  fullName: Apizr.Extending.ObjectExtensions.ToString(System.Object, System.String, System.String)
  spec.csharp:
  - uid: Apizr.Extending.ObjectExtensions.ToString(System.Object,System.String,System.String)
    name: ToString
    nameWithType: ObjectExtensions.ToString
    fullName: Apizr.Extending.ObjectExtensions.ToString
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Apizr.Extending.ObjectExtensions.ToString(System.Object,System.String,System.String)
    name: ToString
    nameWithType: ObjectExtensions.ToString
    fullName: Apizr.Extending.ObjectExtensions.ToString
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Apizr.Extending.ObjectExtensions
  commentId: T:Apizr.Extending.ObjectExtensions
  parent: Apizr.Extending
  name: ObjectExtensions
  nameWithType: ObjectExtensions
  fullName: Apizr.Extending.ObjectExtensions
- uid: Apizr.Extending.Configuring.Shared
  commentId: N:Apizr.Extending.Configuring.Shared
  name: Apizr.Extending.Configuring.Shared
  nameWithType: Apizr.Extending.Configuring.Shared
  fullName: Apizr.Extending.Configuring.Shared
- uid: Apizr.Configuring.Common
  commentId: N:Apizr.Configuring.Common
  name: Apizr.Configuring.Common
  nameWithType: Apizr.Configuring.Common
  fullName: Apizr.Configuring.Common
- uid: Apizr.Configuring.Proper
  commentId: N:Apizr.Configuring.Proper
  name: Apizr.Configuring.Proper
  nameWithType: Apizr.Configuring.Proper
  fullName: Apizr.Configuring.Proper
- uid: Apizr.Configuring.Shared
  commentId: N:Apizr.Configuring.Shared
  name: Apizr.Configuring.Shared
  nameWithType: Apizr.Configuring.Shared
  fullName: Apizr.Configuring.Shared
- uid: Apizr.Extending
  commentId: N:Apizr.Extending
  name: Apizr.Extending
  nameWithType: Apizr.Extending
  fullName: Apizr.Extending
- uid: Apizr.Extending.Configuring.IApizrExtendedOptionsBase.HttpClientHandler*
  commentId: Overload:Apizr.Extending.Configuring.IApizrExtendedOptionsBase.HttpClientHandler
  name: HttpClientHandler
  nameWithType: IApizrExtendedOptionsBase.HttpClientHandler
  fullName: Apizr.Extending.Configuring.IApizrExtendedOptionsBase.HttpClientHandler
- uid: System.Net.Http.HttpClientHandler
  commentId: T:System.Net.Http.HttpClientHandler
  parent: System.Net.Http
  isExternal: true
  name: HttpClientHandler
  nameWithType: HttpClientHandler
  fullName: System.Net.Http.HttpClientHandler
- uid: System.Net.Http
  commentId: N:System.Net.Http
  isExternal: true
  name: System.Net.Http
  nameWithType: System.Net.Http
  fullName: System.Net.Http
