### YamlMime:ManagedReference
items:
- uid: Apizr.Configuring.ApizrLifetimeScope
  commentId: T:Apizr.Configuring.ApizrLifetimeScope
  id: ApizrLifetimeScope
  parent: Apizr.Configuring
  children:
  - Apizr.Configuring.ApizrLifetimeScope.Api
  - Apizr.Configuring.ApizrLifetimeScope.Request
  langs:
  - csharp
  - vb
  name: ApizrLifetimeScope
  nameWithType: ApizrLifetimeScope
  fullName: Apizr.Configuring.ApizrLifetimeScope
  type: Enum
  source:
    remote:
      path: Apizr/Src/Apizr/Configuring/ApizrLifetimeScope.cs
      branch: master
      repo: https://github.com/Respawnsive/Apizr.git
    id: ApizrLifetimeScope
    path: ../../Src/Apizr/Configuring/ApizrLifetimeScope.cs
    startLine: 6
  assemblies:
  - Apizr
  namespace: Apizr.Configuring
  syntax:
    content: public enum ApizrLifetimeScope
    content.vb: Public Enum ApizrLifetimeScope
- uid: Apizr.Configuring.ApizrLifetimeScope.Api
  commentId: F:Apizr.Configuring.ApizrLifetimeScope.Api
  id: Api
  parent: Apizr.Configuring.ApizrLifetimeScope
  langs:
  - csharp
  - vb
  name: Api
  nameWithType: ApizrLifetimeScope.Api
  fullName: Apizr.Configuring.ApizrLifetimeScope.Api
  type: Field
  source:
    remote:
      path: Apizr/Src/Apizr/Configuring/ApizrLifetimeScope.cs
      branch: master
      repo: https://github.com/Respawnsive/Apizr.git
    id: Api
    path: ../../Src/Apizr/Configuring/ApizrLifetimeScope.cs
    startLine: 11
  assemblies:
  - Apizr
  namespace: Apizr.Configuring
  summary: Set once for all api requests (static values)
  example: []
  syntax:
    content: Api = 0
    return:
      type: Apizr.Configuring.ApizrLifetimeScope
- uid: Apizr.Configuring.ApizrLifetimeScope.Request
  commentId: F:Apizr.Configuring.ApizrLifetimeScope.Request
  id: Request
  parent: Apizr.Configuring.ApizrLifetimeScope
  langs:
  - csharp
  - vb
  name: Request
  nameWithType: ApizrLifetimeScope.Request
  fullName: Apizr.Configuring.ApizrLifetimeScope.Request
  type: Field
  source:
    remote:
      path: Apizr/Src/Apizr/Configuring/ApizrLifetimeScope.cs
      branch: master
      repo: https://github.com/Respawnsive/Apizr.git
    id: Request
    path: ../../Src/Apizr/Configuring/ApizrLifetimeScope.cs
    startLine: 16
  assemblies:
  - Apizr
  namespace: Apizr.Configuring
  summary: Refresh values for each api request (dynamic values)
  example: []
  syntax:
    content: Request = 1
    return:
      type: Apizr.Configuring.ApizrLifetimeScope
references:
- uid: Apizr.Configuring
  commentId: N:Apizr.Configuring
  href: Apizr.html
  name: Apizr.Configuring
  nameWithType: Apizr.Configuring
  fullName: Apizr.Configuring
  spec.csharp:
  - uid: Apizr
    name: Apizr
    href: Apizr.html
  - name: .
  - uid: Apizr.Configuring
    name: Configuring
    href: Apizr.Configuring.html
  spec.vb:
  - uid: Apizr
    name: Apizr
    href: Apizr.html
  - name: .
  - uid: Apizr.Configuring
    name: Configuring
    href: Apizr.Configuring.html
- uid: Apizr.Configuring.ApizrLifetimeScope
  commentId: T:Apizr.Configuring.ApizrLifetimeScope
  parent: Apizr.Configuring
  href: Apizr.Configuring.ApizrLifetimeScope.html
  name: ApizrLifetimeScope
  nameWithType: ApizrLifetimeScope
  fullName: Apizr.Configuring.ApizrLifetimeScope
