### YamlMime:ManagedReference
items:
- uid: Apizr.Configuring.Registry.IApizrExtendedUploadRegistryBuilder
  commentId: T:Apizr.Configuring.Registry.IApizrExtendedUploadRegistryBuilder
  id: IApizrExtendedUploadRegistryBuilder
  parent: Apizr.Configuring.Registry
  children: []
  langs:
  - csharp
  - vb
  name: IApizrExtendedUploadRegistryBuilder
  nameWithType: IApizrExtendedUploadRegistryBuilder
  fullName: Apizr.Configuring.Registry.IApizrExtendedUploadRegistryBuilder
  type: Interface
  source:
    id: IApizrExtendedUploadRegistryBuilder
    path: C:\Dev\Community\Apizr\Apizr\Src\Transferring\Apizr.Extensions.Microsoft.FileTransfer\Configuring\Registry\IApizrExtendedUploadRegistryBuilder.cs
    startLine: 6
  assemblies:
  - Apizr.Extensions.Microsoft.FileTransfer
  namespace: Apizr.Configuring.Registry
  syntax:
    content: 'public interface IApizrExtendedUploadRegistryBuilder : IApizrUploadRegistryBuilderBase<IApizrExtendedUploadRegistryBuilder, IApizrExtendedRegistryBuilder, IApizrExtendedProperOptionsBuilder, IApizrExtendedCommonOptionsBuilder>'
    content.vb: >-
      Public Interface IApizrExtendedUploadRegistryBuilder
          Inherits IApizrUploadRegistryBuilderBase(Of IApizrExtendedUploadRegistryBuilder, IApizrExtendedRegistryBuilder, IApizrExtendedProperOptionsBuilder, IApizrExtendedCommonOptionsBuilder)
  inheritedMembers:
  - Apizr.Configuring.Registry.IApizrUploadRegistryBuilderBase{Apizr.Configuring.Registry.IApizrExtendedUploadRegistryBuilder,Apizr.Extending.Configuring.Registry.IApizrExtendedRegistryBuilder,Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBuilder,Apizr.Extending.Configuring.Common.IApizrExtendedCommonOptionsBuilder}.AddFor``1(System.Action{Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBuilder})
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
references:
- uid: Apizr.Configuring.Registry
  commentId: N:Apizr.Configuring.Registry
  name: Apizr.Configuring.Registry
  nameWithType: Apizr.Configuring.Registry
  fullName: Apizr.Configuring.Registry
- uid: Apizr.Configuring.Registry.IApizrUploadRegistryBuilderBase{Apizr.Configuring.Registry.IApizrExtendedUploadRegistryBuilder,Apizr.Extending.Configuring.Registry.IApizrExtendedRegistryBuilder,Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBuilder,Apizr.Extending.Configuring.Common.IApizrExtendedCommonOptionsBuilder}.AddFor``1(System.Action{Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBuilder})
  commentId: M:Apizr.Configuring.Registry.IApizrUploadRegistryBuilderBase{Apizr.Configuring.Registry.IApizrExtendedUploadRegistryBuilder,Apizr.Extending.Configuring.Registry.IApizrExtendedRegistryBuilder,Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBuilder,Apizr.Extending.Configuring.Common.IApizrExtendedCommonOptionsBuilder}.AddFor``1(System.Action{Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBuilder})
  parent: Apizr.Configuring.Registry.IApizrUploadRegistryBuilderBase{Apizr.Configuring.Registry.IApizrExtendedUploadRegistryBuilder,Apizr.Extending.Configuring.Registry.IApizrExtendedRegistryBuilder,Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBuilder,Apizr.Extending.Configuring.Common.IApizrExtendedCommonOptionsBuilder}
  definition: Apizr.Configuring.Registry.IApizrUploadRegistryBuilderBase`4.AddFor``1(System.Action{`2})
  name: AddFor<TUploadApi>(Action<IApizrExtendedProperOptionsBuilder>)
  nameWithType: IApizrUploadRegistryBuilderBase<IApizrExtendedUploadRegistryBuilder, IApizrExtendedRegistryBuilder, IApizrExtendedProperOptionsBuilder, IApizrExtendedCommonOptionsBuilder>.AddFor<TUploadApi>(Action<IApizrExtendedProperOptionsBuilder>)
  fullName: Apizr.Configuring.Registry.IApizrUploadRegistryBuilderBase<Apizr.Configuring.Registry.IApizrExtendedUploadRegistryBuilder, Apizr.Extending.Configuring.Registry.IApizrExtendedRegistryBuilder, Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBuilder, Apizr.Extending.Configuring.Common.IApizrExtendedCommonOptionsBuilder>.AddFor<TUploadApi>(System.Action<Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBuilder>)
  nameWithType.vb: IApizrUploadRegistryBuilderBase(Of IApizrExtendedUploadRegistryBuilder, IApizrExtendedRegistryBuilder, IApizrExtendedProperOptionsBuilder, IApizrExtendedCommonOptionsBuilder).AddFor(Of TUploadApi)(Action(Of IApizrExtendedProperOptionsBuilder))
  fullName.vb: Apizr.Configuring.Registry.IApizrUploadRegistryBuilderBase(Of Apizr.Configuring.Registry.IApizrExtendedUploadRegistryBuilder, Apizr.Extending.Configuring.Registry.IApizrExtendedRegistryBuilder, Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBuilder, Apizr.Extending.Configuring.Common.IApizrExtendedCommonOptionsBuilder).AddFor(Of TUploadApi)(System.Action(Of Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBuilder))
  name.vb: AddFor(Of TUploadApi)(Action(Of IApizrExtendedProperOptionsBuilder))
  spec.csharp:
  - uid: Apizr.Configuring.Registry.IApizrUploadRegistryBuilderBase`4.AddFor``1(System.Action{`2})
    name: AddFor<TUploadApi>
    nameWithType: IApizrUploadRegistryBuilderBase<IApizrExtendedUploadRegistryBuilder, IApizrExtendedRegistryBuilder, IApizrExtendedProperOptionsBuilder, IApizrExtendedCommonOptionsBuilder>.AddFor<TUploadApi>
    fullName: Apizr.Configuring.Registry.IApizrUploadRegistryBuilderBase<Apizr.Configuring.Registry.IApizrExtendedUploadRegistryBuilder, Apizr.Extending.Configuring.Registry.IApizrExtendedRegistryBuilder, Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBuilder, Apizr.Extending.Configuring.Common.IApizrExtendedCommonOptionsBuilder>.AddFor<TUploadApi>
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBuilder
    name: IApizrExtendedProperOptionsBuilder
    nameWithType: IApizrExtendedProperOptionsBuilder
    fullName: Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBuilder
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Apizr.Configuring.Registry.IApizrUploadRegistryBuilderBase`4.AddFor``1(System.Action{`2})
    name: AddFor(Of TUploadApi)
    nameWithType: IApizrUploadRegistryBuilderBase(Of IApizrExtendedUploadRegistryBuilder, IApizrExtendedRegistryBuilder, IApizrExtendedProperOptionsBuilder, IApizrExtendedCommonOptionsBuilder).AddFor(Of TUploadApi)
    fullName: Apizr.Configuring.Registry.IApizrUploadRegistryBuilderBase(Of Apizr.Configuring.Registry.IApizrExtendedUploadRegistryBuilder, Apizr.Extending.Configuring.Registry.IApizrExtendedRegistryBuilder, Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBuilder, Apizr.Extending.Configuring.Common.IApizrExtendedCommonOptionsBuilder).AddFor(Of TUploadApi)
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBuilder
    name: IApizrExtendedProperOptionsBuilder
    nameWithType: IApizrExtendedProperOptionsBuilder
    fullName: Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBuilder
  - name: )
    nameWithType: )
    fullName: )
  - name: )
    nameWithType: )
    fullName: )
- uid: Apizr.Configuring.Registry.IApizrUploadRegistryBuilderBase`4.AddFor``1(System.Action{`2})
  commentId: M:Apizr.Configuring.Registry.IApizrUploadRegistryBuilderBase`4.AddFor``1(System.Action{`2})
  isExternal: true
  name: AddFor<TUploadApi>(Action<TApizrProperOptionsBuilder>)
  nameWithType: IApizrUploadRegistryBuilderBase<TApizrUploadRegistryBuilder, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder>.AddFor<TUploadApi>(Action<TApizrProperOptionsBuilder>)
  fullName: Apizr.Configuring.Registry.IApizrUploadRegistryBuilderBase<TApizrUploadRegistryBuilder, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder>.AddFor<TUploadApi>(System.Action<TApizrProperOptionsBuilder>)
  nameWithType.vb: IApizrUploadRegistryBuilderBase(Of TApizrUploadRegistryBuilder, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder).AddFor(Of TUploadApi)(Action(Of TApizrProperOptionsBuilder))
  fullName.vb: Apizr.Configuring.Registry.IApizrUploadRegistryBuilderBase(Of TApizrUploadRegistryBuilder, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder).AddFor(Of TUploadApi)(System.Action(Of TApizrProperOptionsBuilder))
  name.vb: AddFor(Of TUploadApi)(Action(Of TApizrProperOptionsBuilder))
  spec.csharp:
  - uid: Apizr.Configuring.Registry.IApizrUploadRegistryBuilderBase`4.AddFor``1(System.Action{`2})
    name: AddFor<TUploadApi>
    nameWithType: IApizrUploadRegistryBuilderBase<TApizrUploadRegistryBuilder, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder>.AddFor<TUploadApi>
    fullName: Apizr.Configuring.Registry.IApizrUploadRegistryBuilderBase<TApizrUploadRegistryBuilder, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder>.AddFor<TUploadApi>
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: TApizrProperOptionsBuilder
    nameWithType: TApizrProperOptionsBuilder
    fullName: TApizrProperOptionsBuilder
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Apizr.Configuring.Registry.IApizrUploadRegistryBuilderBase`4.AddFor``1(System.Action{`2})
    name: AddFor(Of TUploadApi)
    nameWithType: IApizrUploadRegistryBuilderBase(Of TApizrUploadRegistryBuilder, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder).AddFor(Of TUploadApi)
    fullName: Apizr.Configuring.Registry.IApizrUploadRegistryBuilderBase(Of TApizrUploadRegistryBuilder, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder).AddFor(Of TUploadApi)
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TApizrProperOptionsBuilder
    nameWithType: TApizrProperOptionsBuilder
    fullName: TApizrProperOptionsBuilder
  - name: )
    nameWithType: )
    fullName: )
  - name: )
    nameWithType: )
    fullName: )
- uid: Apizr.Configuring.Registry.IApizrUploadRegistryBuilderBase{Apizr.Configuring.Registry.IApizrExtendedUploadRegistryBuilder,Apizr.Extending.Configuring.Registry.IApizrExtendedRegistryBuilder,Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBuilder,Apizr.Extending.Configuring.Common.IApizrExtendedCommonOptionsBuilder}
  commentId: T:Apizr.Configuring.Registry.IApizrUploadRegistryBuilderBase{Apizr.Configuring.Registry.IApizrExtendedUploadRegistryBuilder,Apizr.Extending.Configuring.Registry.IApizrExtendedRegistryBuilder,Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBuilder,Apizr.Extending.Configuring.Common.IApizrExtendedCommonOptionsBuilder}
  parent: Apizr.Configuring.Registry
  definition: Apizr.Configuring.Registry.IApizrUploadRegistryBuilderBase`4
  name: IApizrUploadRegistryBuilderBase<IApizrExtendedUploadRegistryBuilder, IApizrExtendedRegistryBuilder, IApizrExtendedProperOptionsBuilder, IApizrExtendedCommonOptionsBuilder>
  nameWithType: IApizrUploadRegistryBuilderBase<IApizrExtendedUploadRegistryBuilder, IApizrExtendedRegistryBuilder, IApizrExtendedProperOptionsBuilder, IApizrExtendedCommonOptionsBuilder>
  fullName: Apizr.Configuring.Registry.IApizrUploadRegistryBuilderBase<Apizr.Configuring.Registry.IApizrExtendedUploadRegistryBuilder, Apizr.Extending.Configuring.Registry.IApizrExtendedRegistryBuilder, Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBuilder, Apizr.Extending.Configuring.Common.IApizrExtendedCommonOptionsBuilder>
  nameWithType.vb: IApizrUploadRegistryBuilderBase(Of IApizrExtendedUploadRegistryBuilder, IApizrExtendedRegistryBuilder, IApizrExtendedProperOptionsBuilder, IApizrExtendedCommonOptionsBuilder)
  fullName.vb: Apizr.Configuring.Registry.IApizrUploadRegistryBuilderBase(Of Apizr.Configuring.Registry.IApizrExtendedUploadRegistryBuilder, Apizr.Extending.Configuring.Registry.IApizrExtendedRegistryBuilder, Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBuilder, Apizr.Extending.Configuring.Common.IApizrExtendedCommonOptionsBuilder)
  name.vb: IApizrUploadRegistryBuilderBase(Of IApizrExtendedUploadRegistryBuilder, IApizrExtendedRegistryBuilder, IApizrExtendedProperOptionsBuilder, IApizrExtendedCommonOptionsBuilder)
  spec.csharp:
  - uid: Apizr.Configuring.Registry.IApizrUploadRegistryBuilderBase`4
    name: IApizrUploadRegistryBuilderBase
    nameWithType: IApizrUploadRegistryBuilderBase
    fullName: Apizr.Configuring.Registry.IApizrUploadRegistryBuilderBase
  - name: <
    nameWithType: <
    fullName: <
  - uid: Apizr.Configuring.Registry.IApizrExtendedUploadRegistryBuilder
    name: IApizrExtendedUploadRegistryBuilder
    nameWithType: IApizrExtendedUploadRegistryBuilder
    fullName: Apizr.Configuring.Registry.IApizrExtendedUploadRegistryBuilder
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: Apizr.Extending.Configuring.Registry.IApizrExtendedRegistryBuilder
    name: IApizrExtendedRegistryBuilder
    nameWithType: IApizrExtendedRegistryBuilder
    fullName: Apizr.Extending.Configuring.Registry.IApizrExtendedRegistryBuilder
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBuilder
    name: IApizrExtendedProperOptionsBuilder
    nameWithType: IApizrExtendedProperOptionsBuilder
    fullName: Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBuilder
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: Apizr.Extending.Configuring.Common.IApizrExtendedCommonOptionsBuilder
    name: IApizrExtendedCommonOptionsBuilder
    nameWithType: IApizrExtendedCommonOptionsBuilder
    fullName: Apizr.Extending.Configuring.Common.IApizrExtendedCommonOptionsBuilder
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Apizr.Configuring.Registry.IApizrUploadRegistryBuilderBase`4
    name: IApizrUploadRegistryBuilderBase
    nameWithType: IApizrUploadRegistryBuilderBase
    fullName: Apizr.Configuring.Registry.IApizrUploadRegistryBuilderBase
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: Apizr.Configuring.Registry.IApizrExtendedUploadRegistryBuilder
    name: IApizrExtendedUploadRegistryBuilder
    nameWithType: IApizrExtendedUploadRegistryBuilder
    fullName: Apizr.Configuring.Registry.IApizrExtendedUploadRegistryBuilder
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: Apizr.Extending.Configuring.Registry.IApizrExtendedRegistryBuilder
    name: IApizrExtendedRegistryBuilder
    nameWithType: IApizrExtendedRegistryBuilder
    fullName: Apizr.Extending.Configuring.Registry.IApizrExtendedRegistryBuilder
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBuilder
    name: IApizrExtendedProperOptionsBuilder
    nameWithType: IApizrExtendedProperOptionsBuilder
    fullName: Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBuilder
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: Apizr.Extending.Configuring.Common.IApizrExtendedCommonOptionsBuilder
    name: IApizrExtendedCommonOptionsBuilder
    nameWithType: IApizrExtendedCommonOptionsBuilder
    fullName: Apizr.Extending.Configuring.Common.IApizrExtendedCommonOptionsBuilder
  - name: )
    nameWithType: )
    fullName: )
- uid: Apizr.Configuring.Registry.IApizrUploadRegistryBuilderBase`4
  commentId: T:Apizr.Configuring.Registry.IApizrUploadRegistryBuilderBase`4
  name: IApizrUploadRegistryBuilderBase<TApizrUploadRegistryBuilder, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder>
  nameWithType: IApizrUploadRegistryBuilderBase<TApizrUploadRegistryBuilder, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder>
  fullName: Apizr.Configuring.Registry.IApizrUploadRegistryBuilderBase<TApizrUploadRegistryBuilder, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder>
  nameWithType.vb: IApizrUploadRegistryBuilderBase(Of TApizrUploadRegistryBuilder, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder)
  fullName.vb: Apizr.Configuring.Registry.IApizrUploadRegistryBuilderBase(Of TApizrUploadRegistryBuilder, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder)
  name.vb: IApizrUploadRegistryBuilderBase(Of TApizrUploadRegistryBuilder, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder)
  spec.csharp:
  - uid: Apizr.Configuring.Registry.IApizrUploadRegistryBuilderBase`4
    name: IApizrUploadRegistryBuilderBase
    nameWithType: IApizrUploadRegistryBuilderBase
    fullName: Apizr.Configuring.Registry.IApizrUploadRegistryBuilderBase
  - name: <
    nameWithType: <
    fullName: <
  - name: TApizrUploadRegistryBuilder
    nameWithType: TApizrUploadRegistryBuilder
    fullName: TApizrUploadRegistryBuilder
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TApizrRegistryBuilder
    nameWithType: TApizrRegistryBuilder
    fullName: TApizrRegistryBuilder
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TApizrProperOptionsBuilder
    nameWithType: TApizrProperOptionsBuilder
    fullName: TApizrProperOptionsBuilder
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TApizrCommonOptionsBuilder
    nameWithType: TApizrCommonOptionsBuilder
    fullName: TApizrCommonOptionsBuilder
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Apizr.Configuring.Registry.IApizrUploadRegistryBuilderBase`4
    name: IApizrUploadRegistryBuilderBase
    nameWithType: IApizrUploadRegistryBuilderBase
    fullName: Apizr.Configuring.Registry.IApizrUploadRegistryBuilderBase
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TApizrUploadRegistryBuilder
    nameWithType: TApizrUploadRegistryBuilder
    fullName: TApizrUploadRegistryBuilder
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TApizrRegistryBuilder
    nameWithType: TApizrRegistryBuilder
    fullName: TApizrRegistryBuilder
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TApizrProperOptionsBuilder
    nameWithType: TApizrProperOptionsBuilder
    fullName: TApizrProperOptionsBuilder
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TApizrCommonOptionsBuilder
    nameWithType: TApizrCommonOptionsBuilder
    fullName: TApizrCommonOptionsBuilder
  - name: )
    nameWithType: )
    fullName: )
