### YamlMime:ManagedReference
items:
- uid: Apizr.Optional.Configuring.Registry
  commentId: N:Apizr.Optional.Configuring.Registry
  id: Apizr.Optional.Configuring.Registry
  children:
  - Apizr.Optional.Configuring.Registry.ApizrOptionalMediationRegistry
  - Apizr.Optional.Configuring.Registry.ApizrOptionalMediationRegistryBase
  - Apizr.Optional.Configuring.Registry.IApizrOptionalMediationConcurrentRegistry
  - Apizr.Optional.Configuring.Registry.IApizrOptionalMediationEnumerableRegistry
  - Apizr.Optional.Configuring.Registry.IApizrOptionalMediationRegistry
  langs:
  - csharp
  - vb
  name: Apizr.Optional.Configuring.Registry
  nameWithType: Apizr.Optional.Configuring.Registry
  fullName: Apizr.Optional.Configuring.Registry
  type: Namespace
  assemblies:
  - Apizr.Integrations.Optional
references:
- uid: Apizr.Optional.Configuring.Registry.ApizrOptionalMediationRegistry
  commentId: T:Apizr.Optional.Configuring.Registry.ApizrOptionalMediationRegistry
  href: Apizr.Optional.Configuring.Registry.ApizrOptionalMediationRegistry.html
  name: ApizrOptionalMediationRegistry
  nameWithType: ApizrOptionalMediationRegistry
  fullName: Apizr.Optional.Configuring.Registry.ApizrOptionalMediationRegistry
- uid: Apizr.Optional.Configuring.Registry.ApizrOptionalMediationRegistryBase
  commentId: T:Apizr.Optional.Configuring.Registry.ApizrOptionalMediationRegistryBase
  parent: Apizr.Optional.Configuring.Registry
  href: Apizr.Optional.Configuring.Registry.ApizrOptionalMediationRegistryBase.html
  name: ApizrOptionalMediationRegistryBase
  nameWithType: ApizrOptionalMediationRegistryBase
  fullName: Apizr.Optional.Configuring.Registry.ApizrOptionalMediationRegistryBase
- uid: Apizr.Optional.Configuring.Registry.IApizrOptionalMediationConcurrentRegistry
  commentId: T:Apizr.Optional.Configuring.Registry.IApizrOptionalMediationConcurrentRegistry
  parent: Apizr.Optional.Configuring.Registry
  href: Apizr.Optional.Configuring.Registry.IApizrOptionalMediationConcurrentRegistry.html
  name: IApizrOptionalMediationConcurrentRegistry
  nameWithType: IApizrOptionalMediationConcurrentRegistry
  fullName: Apizr.Optional.Configuring.Registry.IApizrOptionalMediationConcurrentRegistry
- uid: Apizr.Optional.Configuring.Registry.IApizrOptionalMediationEnumerableRegistry
  commentId: T:Apizr.Optional.Configuring.Registry.IApizrOptionalMediationEnumerableRegistry
  parent: Apizr.Optional.Configuring.Registry
  href: Apizr.Optional.Configuring.Registry.IApizrOptionalMediationEnumerableRegistry.html
  name: IApizrOptionalMediationEnumerableRegistry
  nameWithType: IApizrOptionalMediationEnumerableRegistry
  fullName: Apizr.Optional.Configuring.Registry.IApizrOptionalMediationEnumerableRegistry
- uid: Apizr.Optional.Configuring.Registry.IApizrOptionalMediationRegistry
  commentId: T:Apizr.Optional.Configuring.Registry.IApizrOptionalMediationRegistry
  parent: Apizr.Optional.Configuring.Registry
  href: Apizr.Optional.Configuring.Registry.IApizrOptionalMediationRegistry.html
  name: IApizrOptionalMediationRegistry
  nameWithType: IApizrOptionalMediationRegistry
  fullName: Apizr.Optional.Configuring.Registry.IApizrOptionalMediationRegistry
- uid: Apizr.Optional.Configuring.Registry
  commentId: N:Apizr.Optional.Configuring.Registry
  href: Apizr.html
  name: Apizr.Optional.Configuring.Registry
  nameWithType: Apizr.Optional.Configuring.Registry
  fullName: Apizr.Optional.Configuring.Registry
  spec.csharp:
  - uid: Apizr
    name: Apizr
    href: Apizr.html
  - name: .
  - uid: Apizr.Optional
    name: Optional
    href: Apizr.Optional.html
  - name: .
  - uid: Apizr.Optional.Configuring
    name: Configuring
    href: Apizr.Optional.Configuring.html
  - name: .
  - uid: Apizr.Optional.Configuring.Registry
    name: Registry
    href: Apizr.Optional.Configuring.Registry.html
  spec.vb:
  - uid: Apizr
    name: Apizr
    href: Apizr.html
  - name: .
  - uid: Apizr.Optional
    name: Optional
    href: Apizr.Optional.html
  - name: .
  - uid: Apizr.Optional.Configuring
    name: Configuring
    href: Apizr.Optional.Configuring.html
  - name: .
  - uid: Apizr.Optional.Configuring.Registry
    name: Registry
    href: Apizr.Optional.Configuring.Registry.html
