### YamlMime:ManagedReference
items:
- uid: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBuilderBase
  commentId: T:Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBuilderBase
  id: IApizrGlobalSharedOptionsBuilderBase
  parent: Apizr.Configuring.Shared
  children: []
  langs:
  - csharp
  - vb
  name: IApizrGlobalSharedOptionsBuilderBase
  nameWithType: IApizrGlobalSharedOptionsBuilderBase
  fullName: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBuilderBase
  type: Interface
  source:
    id: IApizrGlobalSharedOptionsBuilderBase
    path: C:\Dev\Community\Apizr\Apizr\Apizr\Configuring\Shared\IApizrGlobalSharedOptionsBuilderBase.cs
    startLine: 10
  assemblies:
  - Apizr
  namespace: Apizr.Configuring.Shared
  summary: "\nBuilder options available at all (common, proper and request) levels and for all (static and extended) registration types\n"
  example: []
  syntax:
    content: public interface IApizrGlobalSharedOptionsBuilderBase
    content.vb: Public Interface IApizrGlobalSharedOptionsBuilderBase
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
references:
- uid: Apizr.Configuring.Shared
  commentId: N:Apizr.Configuring.Shared
  name: Apizr.Configuring.Shared
  nameWithType: Apizr.Configuring.Shared
  fullName: Apizr.Configuring.Shared
