### YamlMime:ManagedReference
items:
- uid: Apizr.Extending.Configuring.Common
  commentId: N:Apizr.Extending.Configuring.Common
  id: Apizr.Extending.Configuring.Common
  children:
  - Apizr.Extending.Configuring.Common.ApizrExtendedCommonOptions
  - Apizr.Extending.Configuring.Common.ApizrExtendedCommonOptionsBuilder
  - Apizr.Extending.Configuring.Common.IApizrExtendedCommonOptions
  - Apizr.Extending.Configuring.Common.IApizrExtendedCommonOptionsBase
  - Apizr.Extending.Configuring.Common.IApizrExtendedCommonOptionsBuilder
  - Apizr.Extending.Configuring.Common.IApizrExtendedCommonOptionsBuilder`2
  langs:
  - csharp
  - vb
  name: Apizr.Extending.Configuring.Common
  nameWithType: Apizr.Extending.Configuring.Common
  fullName: Apizr.Extending.Configuring.Common
  type: Namespace
  assemblies:
  - Apizr.Extensions.Microsoft.DependencyInjection
references:
- uid: Apizr.Extending.Configuring.Common.ApizrExtendedCommonOptions
  commentId: T:Apizr.Extending.Configuring.Common.ApizrExtendedCommonOptions
  parent: Apizr.Extending.Configuring.Common
  name: ApizrExtendedCommonOptions
  nameWithType: ApizrExtendedCommonOptions
  fullName: Apizr.Extending.Configuring.Common.ApizrExtendedCommonOptions
- uid: Apizr.Extending.Configuring.Common.ApizrExtendedCommonOptionsBuilder
  commentId: T:Apizr.Extending.Configuring.Common.ApizrExtendedCommonOptionsBuilder
  name: ApizrExtendedCommonOptionsBuilder
  nameWithType: ApizrExtendedCommonOptionsBuilder
  fullName: Apizr.Extending.Configuring.Common.ApizrExtendedCommonOptionsBuilder
- uid: Apizr.Extending.Configuring.Common.IApizrExtendedCommonOptions
  commentId: T:Apizr.Extending.Configuring.Common.IApizrExtendedCommonOptions
  parent: Apizr.Extending.Configuring.Common
  name: IApizrExtendedCommonOptions
  nameWithType: IApizrExtendedCommonOptions
  fullName: Apizr.Extending.Configuring.Common.IApizrExtendedCommonOptions
- uid: Apizr.Extending.Configuring.Common.IApizrExtendedCommonOptionsBase
  commentId: T:Apizr.Extending.Configuring.Common.IApizrExtendedCommonOptionsBase
  parent: Apizr.Extending.Configuring.Common
  name: IApizrExtendedCommonOptionsBase
  nameWithType: IApizrExtendedCommonOptionsBase
  fullName: Apizr.Extending.Configuring.Common.IApizrExtendedCommonOptionsBase
- uid: Apizr.Extending.Configuring.Common.IApizrExtendedCommonOptionsBuilder`2
  commentId: T:Apizr.Extending.Configuring.Common.IApizrExtendedCommonOptionsBuilder`2
  name: IApizrExtendedCommonOptionsBuilder<TApizrExtendedCommonOptions, TApizrExtendedCommonOptionsBuilder>
  nameWithType: IApizrExtendedCommonOptionsBuilder<TApizrExtendedCommonOptions, TApizrExtendedCommonOptionsBuilder>
  fullName: Apizr.Extending.Configuring.Common.IApizrExtendedCommonOptionsBuilder<TApizrExtendedCommonOptions, TApizrExtendedCommonOptionsBuilder>
  nameWithType.vb: IApizrExtendedCommonOptionsBuilder(Of TApizrExtendedCommonOptions, TApizrExtendedCommonOptionsBuilder)
  fullName.vb: Apizr.Extending.Configuring.Common.IApizrExtendedCommonOptionsBuilder(Of TApizrExtendedCommonOptions, TApizrExtendedCommonOptionsBuilder)
  name.vb: IApizrExtendedCommonOptionsBuilder(Of TApizrExtendedCommonOptions, TApizrExtendedCommonOptionsBuilder)
  spec.csharp:
  - uid: Apizr.Extending.Configuring.Common.IApizrExtendedCommonOptionsBuilder`2
    name: IApizrExtendedCommonOptionsBuilder
    nameWithType: IApizrExtendedCommonOptionsBuilder
    fullName: Apizr.Extending.Configuring.Common.IApizrExtendedCommonOptionsBuilder
  - name: <
    nameWithType: <
    fullName: <
  - name: TApizrExtendedCommonOptions
    nameWithType: TApizrExtendedCommonOptions
    fullName: TApizrExtendedCommonOptions
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TApizrExtendedCommonOptionsBuilder
    nameWithType: TApizrExtendedCommonOptionsBuilder
    fullName: TApizrExtendedCommonOptionsBuilder
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Apizr.Extending.Configuring.Common.IApizrExtendedCommonOptionsBuilder`2
    name: IApizrExtendedCommonOptionsBuilder
    nameWithType: IApizrExtendedCommonOptionsBuilder
    fullName: Apizr.Extending.Configuring.Common.IApizrExtendedCommonOptionsBuilder
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TApizrExtendedCommonOptions
    nameWithType: TApizrExtendedCommonOptions
    fullName: TApizrExtendedCommonOptions
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TApizrExtendedCommonOptionsBuilder
    nameWithType: TApizrExtendedCommonOptionsBuilder
    fullName: TApizrExtendedCommonOptionsBuilder
  - name: )
    nameWithType: )
    fullName: )
- uid: Apizr.Extending.Configuring.Common.IApizrExtendedCommonOptionsBuilder
  commentId: T:Apizr.Extending.Configuring.Common.IApizrExtendedCommonOptionsBuilder
  parent: Apizr.Extending.Configuring.Common
  name: IApizrExtendedCommonOptionsBuilder
  nameWithType: IApizrExtendedCommonOptionsBuilder
  fullName: Apizr.Extending.Configuring.Common.IApizrExtendedCommonOptionsBuilder
- uid: Apizr.Extending.Configuring.Common
  commentId: N:Apizr.Extending.Configuring.Common
  name: Apizr.Extending.Configuring.Common
  nameWithType: Apizr.Extending.Configuring.Common
  fullName: Apizr.Extending.Configuring.Common
