### YamlMime:ManagedReference
items:
- uid: Apizr.Configuring.Shared
  commentId: N:Apizr.Configuring.Shared
  id: Apizr.Configuring.Shared
  children:
  - Apizr.Configuring.Shared.ApizrSharedOptionsBase
  - Apizr.Configuring.Shared.IApizrExtendedSharedOptionsBuilderBase
  - Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBuilderBase
  - Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBuilderBase`2
  - Apizr.Configuring.Shared.IApizrSharedOptions
  - Apizr.Configuring.Shared.IApizrSharedOptionsBase
  - Apizr.Configuring.Shared.IApizrSharedOptionsBuilder`2
  - Apizr.Configuring.Shared.IApizrSharedOptionsBuilderBase
  - Apizr.Configuring.Shared.IApizrSharedOptionsBuilderBase`2
  langs:
  - csharp
  - vb
  name: Apizr.Configuring.Shared
  nameWithType: Apizr.Configuring.Shared
  fullName: Apizr.Configuring.Shared
  type: Namespace
  assemblies:
  - Apizr
references:
- uid: Apizr.Configuring.Shared.ApizrSharedOptionsBase
  commentId: T:Apizr.Configuring.Shared.ApizrSharedOptionsBase
  parent: Apizr.Configuring.Shared
  name: ApizrSharedOptionsBase
  nameWithType: ApizrSharedOptionsBase
  fullName: Apizr.Configuring.Shared.ApizrSharedOptionsBase
- uid: Apizr.Configuring.Shared.IApizrExtendedSharedOptionsBuilderBase
  commentId: T:Apizr.Configuring.Shared.IApizrExtendedSharedOptionsBuilderBase
  parent: Apizr.Configuring.Shared
  name: IApizrExtendedSharedOptionsBuilderBase
  nameWithType: IApizrExtendedSharedOptionsBuilderBase
  fullName: Apizr.Configuring.Shared.IApizrExtendedSharedOptionsBuilderBase
- uid: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBuilderBase
  commentId: T:Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBuilderBase
  parent: Apizr.Configuring.Shared
  name: IApizrGlobalSharedOptionsBuilderBase
  nameWithType: IApizrGlobalSharedOptionsBuilderBase
  fullName: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBuilderBase
- uid: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBuilderBase`2
  commentId: T:Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBuilderBase`2
  name: IApizrGlobalSharedOptionsBuilderBase<TApizrSharedOptions, TApizrSharedOptionsBuilder>
  nameWithType: IApizrGlobalSharedOptionsBuilderBase<TApizrSharedOptions, TApizrSharedOptionsBuilder>
  fullName: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBuilderBase<TApizrSharedOptions, TApizrSharedOptionsBuilder>
  nameWithType.vb: IApizrGlobalSharedOptionsBuilderBase(Of TApizrSharedOptions, TApizrSharedOptionsBuilder)
  fullName.vb: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBuilderBase(Of TApizrSharedOptions, TApizrSharedOptionsBuilder)
  name.vb: IApizrGlobalSharedOptionsBuilderBase(Of TApizrSharedOptions, TApizrSharedOptionsBuilder)
  spec.csharp:
  - uid: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBuilderBase`2
    name: IApizrGlobalSharedOptionsBuilderBase
    nameWithType: IApizrGlobalSharedOptionsBuilderBase
    fullName: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBuilderBase
  - name: <
    nameWithType: <
    fullName: <
  - name: TApizrSharedOptions
    nameWithType: TApizrSharedOptions
    fullName: TApizrSharedOptions
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TApizrSharedOptionsBuilder
    nameWithType: TApizrSharedOptionsBuilder
    fullName: TApizrSharedOptionsBuilder
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBuilderBase`2
    name: IApizrGlobalSharedOptionsBuilderBase
    nameWithType: IApizrGlobalSharedOptionsBuilderBase
    fullName: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBuilderBase
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TApizrSharedOptions
    nameWithType: TApizrSharedOptions
    fullName: TApizrSharedOptions
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TApizrSharedOptionsBuilder
    nameWithType: TApizrSharedOptionsBuilder
    fullName: TApizrSharedOptionsBuilder
  - name: )
    nameWithType: )
    fullName: )
- uid: Apizr.Configuring.Shared.IApizrSharedOptions
  commentId: T:Apizr.Configuring.Shared.IApizrSharedOptions
  parent: Apizr.Configuring.Shared
  name: IApizrSharedOptions
  nameWithType: IApizrSharedOptions
  fullName: Apizr.Configuring.Shared.IApizrSharedOptions
- uid: Apizr.Configuring.Shared.IApizrSharedOptionsBase
  commentId: T:Apizr.Configuring.Shared.IApizrSharedOptionsBase
  parent: Apizr.Configuring.Shared
  name: IApizrSharedOptionsBase
  nameWithType: IApizrSharedOptionsBase
  fullName: Apizr.Configuring.Shared.IApizrSharedOptionsBase
- uid: Apizr.Configuring.Shared.IApizrSharedOptionsBuilder`2
  commentId: T:Apizr.Configuring.Shared.IApizrSharedOptionsBuilder`2
  name: IApizrSharedOptionsBuilder<TApizrSharedOptions, TApizrSharedOptionsBuilder>
  nameWithType: IApizrSharedOptionsBuilder<TApizrSharedOptions, TApizrSharedOptionsBuilder>
  fullName: Apizr.Configuring.Shared.IApizrSharedOptionsBuilder<TApizrSharedOptions, TApizrSharedOptionsBuilder>
  nameWithType.vb: IApizrSharedOptionsBuilder(Of TApizrSharedOptions, TApizrSharedOptionsBuilder)
  fullName.vb: Apizr.Configuring.Shared.IApizrSharedOptionsBuilder(Of TApizrSharedOptions, TApizrSharedOptionsBuilder)
  name.vb: IApizrSharedOptionsBuilder(Of TApizrSharedOptions, TApizrSharedOptionsBuilder)
  spec.csharp:
  - uid: Apizr.Configuring.Shared.IApizrSharedOptionsBuilder`2
    name: IApizrSharedOptionsBuilder
    nameWithType: IApizrSharedOptionsBuilder
    fullName: Apizr.Configuring.Shared.IApizrSharedOptionsBuilder
  - name: <
    nameWithType: <
    fullName: <
  - name: TApizrSharedOptions
    nameWithType: TApizrSharedOptions
    fullName: TApizrSharedOptions
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TApizrSharedOptionsBuilder
    nameWithType: TApizrSharedOptionsBuilder
    fullName: TApizrSharedOptionsBuilder
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Apizr.Configuring.Shared.IApizrSharedOptionsBuilder`2
    name: IApizrSharedOptionsBuilder
    nameWithType: IApizrSharedOptionsBuilder
    fullName: Apizr.Configuring.Shared.IApizrSharedOptionsBuilder
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TApizrSharedOptions
    nameWithType: TApizrSharedOptions
    fullName: TApizrSharedOptions
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TApizrSharedOptionsBuilder
    nameWithType: TApizrSharedOptionsBuilder
    fullName: TApizrSharedOptionsBuilder
  - name: )
    nameWithType: )
    fullName: )
- uid: Apizr.Configuring.Shared.IApizrSharedOptionsBuilderBase
  commentId: T:Apizr.Configuring.Shared.IApizrSharedOptionsBuilderBase
  parent: Apizr.Configuring.Shared
  name: IApizrSharedOptionsBuilderBase
  nameWithType: IApizrSharedOptionsBuilderBase
  fullName: Apizr.Configuring.Shared.IApizrSharedOptionsBuilderBase
- uid: Apizr.Configuring.Shared.IApizrSharedOptionsBuilderBase`2
  commentId: T:Apizr.Configuring.Shared.IApizrSharedOptionsBuilderBase`2
  name: IApizrSharedOptionsBuilderBase<TApizrSharedOptions, TApizrSharedOptionsBuilder>
  nameWithType: IApizrSharedOptionsBuilderBase<TApizrSharedOptions, TApizrSharedOptionsBuilder>
  fullName: Apizr.Configuring.Shared.IApizrSharedOptionsBuilderBase<TApizrSharedOptions, TApizrSharedOptionsBuilder>
  nameWithType.vb: IApizrSharedOptionsBuilderBase(Of TApizrSharedOptions, TApizrSharedOptionsBuilder)
  fullName.vb: Apizr.Configuring.Shared.IApizrSharedOptionsBuilderBase(Of TApizrSharedOptions, TApizrSharedOptionsBuilder)
  name.vb: IApizrSharedOptionsBuilderBase(Of TApizrSharedOptions, TApizrSharedOptionsBuilder)
  spec.csharp:
  - uid: Apizr.Configuring.Shared.IApizrSharedOptionsBuilderBase`2
    name: IApizrSharedOptionsBuilderBase
    nameWithType: IApizrSharedOptionsBuilderBase
    fullName: Apizr.Configuring.Shared.IApizrSharedOptionsBuilderBase
  - name: <
    nameWithType: <
    fullName: <
  - name: TApizrSharedOptions
    nameWithType: TApizrSharedOptions
    fullName: TApizrSharedOptions
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TApizrSharedOptionsBuilder
    nameWithType: TApizrSharedOptionsBuilder
    fullName: TApizrSharedOptionsBuilder
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Apizr.Configuring.Shared.IApizrSharedOptionsBuilderBase`2
    name: IApizrSharedOptionsBuilderBase
    nameWithType: IApizrSharedOptionsBuilderBase
    fullName: Apizr.Configuring.Shared.IApizrSharedOptionsBuilderBase
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TApizrSharedOptions
    nameWithType: TApizrSharedOptions
    fullName: TApizrSharedOptions
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TApizrSharedOptionsBuilder
    nameWithType: TApizrSharedOptionsBuilder
    fullName: TApizrSharedOptionsBuilder
  - name: )
    nameWithType: )
    fullName: )
- uid: Apizr.Configuring.Shared
  commentId: N:Apizr.Configuring.Shared
  name: Apizr.Configuring.Shared
  nameWithType: Apizr.Configuring.Shared
  fullName: Apizr.Configuring.Shared
