### YamlMime:ManagedReference
items:
- uid: Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistryBase
  commentId: T:Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistryBase
  id: IApizrExtendedConcurrentRegistryBase
  parent: Apizr.Extending.Configuring.Registry
  children:
  - Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistryBase.AddOrUpdateFor(System.Type,System.Type)
  langs:
  - csharp
  - vb
  name: IApizrExtendedConcurrentRegistryBase
  nameWithType: IApizrExtendedConcurrentRegistryBase
  fullName: Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistryBase
  type: Interface
  source:
    remote:
      path: Apizr/Apizr.Extensions.Microsoft.DependencyInjection/Extending/Configuring/Registry/IApizrExtendedConcurrentRegistryBase.cs
      branch: lab
      repo: https://github.com/Respawnsive/Apizr.git
    id: IApizrExtendedConcurrentRegistryBase
    path: ../../Apizr.Extensions.Microsoft.DependencyInjection/Extending/Configuring/Registry/IApizrExtendedConcurrentRegistryBase.cs
    startLine: 4
  assemblies:
  - Apizr.Extensions.Microsoft.DependencyInjection
  namespace: Apizr.Extending.Configuring.Registry
  syntax:
    content: public interface IApizrExtendedConcurrentRegistryBase
    content.vb: Public Interface IApizrExtendedConcurrentRegistryBase
  extensionMethods:
  - System.Object.Apizr.Extending.ObjectExtensions.ToString(System.String,System.String)
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistryBase.AddOrUpdateFor(System.Type,System.Type)
  commentId: M:Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistryBase.AddOrUpdateFor(System.Type,System.Type)
  id: AddOrUpdateFor(System.Type,System.Type)
  parent: Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistryBase
  langs:
  - csharp
  - vb
  name: AddOrUpdateFor(Type, Type)
  nameWithType: IApizrExtendedConcurrentRegistryBase.AddOrUpdateFor(Type, Type)
  fullName: Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistryBase.AddOrUpdateFor(System.Type, System.Type)
  type: Method
  source:
    remote:
      path: Apizr/Apizr.Extensions.Microsoft.DependencyInjection/Extending/Configuring/Registry/IApizrExtendedConcurrentRegistryBase.cs
      branch: lab
      repo: https://github.com/Respawnsive/Apizr.git
    id: AddOrUpdateFor
    path: ../../Apizr.Extensions.Microsoft.DependencyInjection/Extending/Configuring/Registry/IApizrExtendedConcurrentRegistryBase.cs
    startLine: 6
  assemblies:
  - Apizr.Extensions.Microsoft.DependencyInjection
  namespace: Apizr.Extending.Configuring.Registry
  syntax:
    content: void AddOrUpdateFor(Type webApiType, Type serviceType)
    parameters:
    - id: webApiType
      type: System.Type
    - id: serviceType
      type: System.Type
    content.vb: Sub AddOrUpdateFor(webApiType As Type, serviceType As Type)
  overload: Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistryBase.AddOrUpdateFor*
references:
- uid: Apizr.Extending.Configuring.Registry
  commentId: N:Apizr.Extending.Configuring.Registry
  name: Apizr.Extending.Configuring.Registry
  nameWithType: Apizr.Extending.Configuring.Registry
  fullName: Apizr.Extending.Configuring.Registry
- uid: System.Object.Apizr.Extending.ObjectExtensions.ToString(System.String,System.String)
  commentId: M:Apizr.Extending.ObjectExtensions.ToString(System.Object,System.String,System.String)
  parent: Apizr.Extending.ObjectExtensions
  definition: Apizr.Extending.ObjectExtensions.ToString(System.Object,System.String,System.String)
  name: ToString(String, String)
  nameWithType: ObjectExtensions.ToString(String, String)
  fullName: Apizr.Extending.ObjectExtensions.ToString(System.String, System.String)
  spec.csharp:
  - uid: Apizr.Extending.ObjectExtensions.ToString(System.String,System.String)
    name: ToString
    nameWithType: ObjectExtensions.ToString
    fullName: Apizr.Extending.ObjectExtensions.ToString
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Apizr.Extending.ObjectExtensions.ToString(System.String,System.String)
    name: ToString
    nameWithType: ObjectExtensions.ToString
    fullName: Apizr.Extending.ObjectExtensions.ToString
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Apizr.Extending.ObjectExtensions.ToString(System.Object,System.String,System.String)
  commentId: M:Apizr.Extending.ObjectExtensions.ToString(System.Object,System.String,System.String)
  isExternal: true
  name: ToString(Object, String, String)
  nameWithType: ObjectExtensions.ToString(Object, String, String)
  fullName: Apizr.Extending.ObjectExtensions.ToString(System.Object, System.String, System.String)
  spec.csharp:
  - uid: Apizr.Extending.ObjectExtensions.ToString(System.Object,System.String,System.String)
    name: ToString
    nameWithType: ObjectExtensions.ToString
    fullName: Apizr.Extending.ObjectExtensions.ToString
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Apizr.Extending.ObjectExtensions.ToString(System.Object,System.String,System.String)
    name: ToString
    nameWithType: ObjectExtensions.ToString
    fullName: Apizr.Extending.ObjectExtensions.ToString
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Apizr.Extending.ObjectExtensions
  commentId: T:Apizr.Extending.ObjectExtensions
  parent: Apizr.Extending
  name: ObjectExtensions
  nameWithType: ObjectExtensions
  fullName: Apizr.Extending.ObjectExtensions
- uid: Apizr.Extending
  commentId: N:Apizr.Extending
  name: Apizr.Extending
  nameWithType: Apizr.Extending
  fullName: Apizr.Extending
- uid: Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistryBase.AddOrUpdateFor*
  commentId: Overload:Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistryBase.AddOrUpdateFor
  name: AddOrUpdateFor
  nameWithType: IApizrExtendedConcurrentRegistryBase.AddOrUpdateFor
  fullName: Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistryBase.AddOrUpdateFor
- uid: System.Type
  commentId: T:System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
