### YamlMime:ManagedReference
items:
- uid: Apizr.Configuring.Shared.Context
  commentId: N:Apizr.Configuring.Shared.Context
  id: Apizr.Configuring.Shared.Context
  children:
  - Apizr.Configuring.Shared.Context.ApizrResilienceContextOptions
  - Apizr.Configuring.Shared.Context.ApizrResilienceContextOptionsBuilder
  - Apizr.Configuring.Shared.Context.IApizrResilienceContextOptions
  - Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder
  langs:
  - csharp
  - vb
  name: Apizr.Configuring.Shared.Context
  nameWithType: Apizr.Configuring.Shared.Context
  fullName: Apizr.Configuring.Shared.Context
  type: Namespace
  assemblies:
  - Apizr
references:
- uid: Apizr.Configuring.Shared.Context.ApizrResilienceContextOptions
  commentId: T:Apizr.Configuring.Shared.Context.ApizrResilienceContextOptions
  parent: Apizr.Configuring.Shared.Context
  href: Apizr.Configuring.Shared.Context.ApizrResilienceContextOptions.html
  name: ApizrResilienceContextOptions
  nameWithType: ApizrResilienceContextOptions
  fullName: Apizr.Configuring.Shared.Context.ApizrResilienceContextOptions
- uid: Apizr.Configuring.Shared.Context.ApizrResilienceContextOptionsBuilder
  commentId: T:Apizr.Configuring.Shared.Context.ApizrResilienceContextOptionsBuilder
  href: Apizr.Configuring.Shared.Context.ApizrResilienceContextOptionsBuilder.html
  name: ApizrResilienceContextOptionsBuilder
  nameWithType: ApizrResilienceContextOptionsBuilder
  fullName: Apizr.Configuring.Shared.Context.ApizrResilienceContextOptionsBuilder
- uid: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptions
  commentId: T:Apizr.Configuring.Shared.Context.IApizrResilienceContextOptions
  parent: Apizr.Configuring.Shared.Context
  href: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptions.html
  name: IApizrResilienceContextOptions
  nameWithType: IApizrResilienceContextOptions
  fullName: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptions
- uid: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder
  commentId: T:Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder
  parent: Apizr.Configuring.Shared.Context
  href: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder.html
  name: IApizrResilienceContextOptionsBuilder
  nameWithType: IApizrResilienceContextOptionsBuilder
  fullName: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder
- uid: Apizr.Configuring.Shared.Context
  commentId: N:Apizr.Configuring.Shared.Context
  href: Apizr.html
  name: Apizr.Configuring.Shared.Context
  nameWithType: Apizr.Configuring.Shared.Context
  fullName: Apizr.Configuring.Shared.Context
  spec.csharp:
  - uid: Apizr
    name: Apizr
    href: Apizr.html
  - name: .
  - uid: Apizr.Configuring
    name: Configuring
    href: Apizr.Configuring.html
  - name: .
  - uid: Apizr.Configuring.Shared
    name: Shared
    href: Apizr.Configuring.Shared.html
  - name: .
  - uid: Apizr.Configuring.Shared.Context
    name: Context
    href: Apizr.Configuring.Shared.Context.html
  spec.vb:
  - uid: Apizr
    name: Apizr
    href: Apizr.html
  - name: .
  - uid: Apizr.Configuring
    name: Configuring
    href: Apizr.Configuring.html
  - name: .
  - uid: Apizr.Configuring.Shared
    name: Shared
    href: Apizr.Configuring.Shared.html
  - name: .
  - uid: Apizr.Configuring.Shared.Context
    name: Context
    href: Apizr.Configuring.Shared.Context.html
