### YamlMime:ManagedReference
items:
- uid: Apizr.Configuring
  commentId: N:Apizr.Configuring
  id: Apizr.Configuring
  children:
  - Apizr.Configuring.ApizrDuplicateStrategy
  - Apizr.Configuring.CreateHandlerParameterAttribute
  - Apizr.Configuring.CrudHandlerParameterAttribute
  - Apizr.Configuring.DeleteHandlerParameterAttribute
  - Apizr.Configuring.HandlerParameterAttribute
  - Apizr.Configuring.ReadAllHandlerParameterAttribute
  - Apizr.Configuring.ReadHandlerParameterAttribute
  - Apizr.Configuring.UpdateHandlerParameterAttribute
  langs:
  - csharp
  - vb
  name: Apizr.Configuring
  nameWithType: Apizr.Configuring
  fullName: Apizr.Configuring
  type: Namespace
  assemblies:
  - Apizr
references:
- uid: Apizr.Configuring.ApizrDuplicateStrategy
  commentId: T:Apizr.Configuring.ApizrDuplicateStrategy
  parent: Apizr.Configuring
  name: ApizrDuplicateStrategy
  nameWithType: ApizrDuplicateStrategy
  fullName: Apizr.Configuring.ApizrDuplicateStrategy
- uid: Apizr.Configuring.HandlerParameterAttribute
  commentId: T:Apizr.Configuring.HandlerParameterAttribute
  parent: Apizr.Configuring
  name: HandlerParameterAttribute
  nameWithType: HandlerParameterAttribute
  fullName: Apizr.Configuring.HandlerParameterAttribute
- uid: Apizr.Configuring.CrudHandlerParameterAttribute
  commentId: T:Apizr.Configuring.CrudHandlerParameterAttribute
  parent: Apizr.Configuring
  name: CrudHandlerParameterAttribute
  nameWithType: CrudHandlerParameterAttribute
  fullName: Apizr.Configuring.CrudHandlerParameterAttribute
- uid: Apizr.Configuring.ReadAllHandlerParameterAttribute
  commentId: T:Apizr.Configuring.ReadAllHandlerParameterAttribute
  parent: Apizr.Configuring
  name: ReadAllHandlerParameterAttribute
  nameWithType: ReadAllHandlerParameterAttribute
  fullName: Apizr.Configuring.ReadAllHandlerParameterAttribute
- uid: Apizr.Configuring.ReadHandlerParameterAttribute
  commentId: T:Apizr.Configuring.ReadHandlerParameterAttribute
  parent: Apizr.Configuring
  name: ReadHandlerParameterAttribute
  nameWithType: ReadHandlerParameterAttribute
  fullName: Apizr.Configuring.ReadHandlerParameterAttribute
- uid: Apizr.Configuring.CreateHandlerParameterAttribute
  commentId: T:Apizr.Configuring.CreateHandlerParameterAttribute
  name: CreateHandlerParameterAttribute
  nameWithType: CreateHandlerParameterAttribute
  fullName: Apizr.Configuring.CreateHandlerParameterAttribute
- uid: Apizr.Configuring.UpdateHandlerParameterAttribute
  commentId: T:Apizr.Configuring.UpdateHandlerParameterAttribute
  name: UpdateHandlerParameterAttribute
  nameWithType: UpdateHandlerParameterAttribute
  fullName: Apizr.Configuring.UpdateHandlerParameterAttribute
- uid: Apizr.Configuring.DeleteHandlerParameterAttribute
  commentId: T:Apizr.Configuring.DeleteHandlerParameterAttribute
  name: DeleteHandlerParameterAttribute
  nameWithType: DeleteHandlerParameterAttribute
  fullName: Apizr.Configuring.DeleteHandlerParameterAttribute
- uid: Apizr.Configuring
  commentId: N:Apizr.Configuring
  name: Apizr.Configuring
  nameWithType: Apizr.Configuring
  fullName: Apizr.Configuring
