### YamlMime:ManagedReference
items:
- uid: Apizr.Extending.Configuring
  commentId: N:Apizr.Extending.Configuring
  id: Apizr.Extending.Configuring
  children:
  - Apizr.Extending.Configuring.ApizrExtendedOptions
  - Apizr.Extending.Configuring.ApizrExtendedOptions`1
  - Apizr.Extending.Configuring.ApizrExtendedOptionsBase
  - Apizr.Extending.Configuring.ApizrExtendedOptionsBuilder
  - Apizr.Extending.Configuring.IApizrExtendedOptions
  - Apizr.Extending.Configuring.IApizrExtendedOptions`1
  - Apizr.Extending.Configuring.IApizrExtendedOptionsBase
  - Apizr.Extending.Configuring.IApizrExtendedOptionsBuilder
  - Apizr.Extending.Configuring.IApizrExtendedOptionsBuilder`2
  - Apizr.Extending.Configuring.IApizrExtendedOptionsBuilderBase
  - Apizr.Extending.Configuring.IApizrExtendedOptionsBuilderBase`2
  langs:
  - csharp
  - vb
  name: Apizr.Extending.Configuring
  nameWithType: Apizr.Extending.Configuring
  fullName: Apizr.Extending.Configuring
  type: Namespace
  assemblies:
  - Apizr.Extensions.Microsoft.DependencyInjection
references:
- uid: Apizr.Extending.Configuring.ApizrExtendedOptions
  commentId: T:Apizr.Extending.Configuring.ApizrExtendedOptions
  parent: Apizr.Extending.Configuring
  name: ApizrExtendedOptions
  nameWithType: ApizrExtendedOptions
  fullName: Apizr.Extending.Configuring.ApizrExtendedOptions
- uid: Apizr.Extending.Configuring.ApizrExtendedOptions`1
  commentId: T:Apizr.Extending.Configuring.ApizrExtendedOptions`1
  name: ApizrExtendedOptions<TWebApi>
  nameWithType: ApizrExtendedOptions<TWebApi>
  fullName: Apizr.Extending.Configuring.ApizrExtendedOptions<TWebApi>
  nameWithType.vb: ApizrExtendedOptions(Of TWebApi)
  fullName.vb: Apizr.Extending.Configuring.ApizrExtendedOptions(Of TWebApi)
  name.vb: ApizrExtendedOptions(Of TWebApi)
  spec.csharp:
  - uid: Apizr.Extending.Configuring.ApizrExtendedOptions`1
    name: ApizrExtendedOptions
    nameWithType: ApizrExtendedOptions
    fullName: Apizr.Extending.Configuring.ApizrExtendedOptions
  - name: <
    nameWithType: <
    fullName: <
  - name: TWebApi
    nameWithType: TWebApi
    fullName: TWebApi
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Apizr.Extending.Configuring.ApizrExtendedOptions`1
    name: ApizrExtendedOptions
    nameWithType: ApizrExtendedOptions
    fullName: Apizr.Extending.Configuring.ApizrExtendedOptions
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TWebApi
    nameWithType: TWebApi
    fullName: TWebApi
  - name: )
    nameWithType: )
    fullName: )
- uid: Apizr.Extending.Configuring.ApizrExtendedOptionsBase
  commentId: T:Apizr.Extending.Configuring.ApizrExtendedOptionsBase
  parent: Apizr.Extending.Configuring
  name: ApizrExtendedOptionsBase
  nameWithType: ApizrExtendedOptionsBase
  fullName: Apizr.Extending.Configuring.ApizrExtendedOptionsBase
- uid: Apizr.Extending.Configuring.ApizrExtendedOptionsBuilder
  commentId: T:Apizr.Extending.Configuring.ApizrExtendedOptionsBuilder
  name: ApizrExtendedOptionsBuilder
  nameWithType: ApizrExtendedOptionsBuilder
  fullName: Apizr.Extending.Configuring.ApizrExtendedOptionsBuilder
- uid: Apizr.Extending.Configuring.IApizrExtendedOptions
  commentId: T:Apizr.Extending.Configuring.IApizrExtendedOptions
  parent: Apizr.Extending.Configuring
  name: IApizrExtendedOptions
  nameWithType: IApizrExtendedOptions
  fullName: Apizr.Extending.Configuring.IApizrExtendedOptions
- uid: Apizr.Extending.Configuring.IApizrExtendedOptions`1
  commentId: T:Apizr.Extending.Configuring.IApizrExtendedOptions`1
  name: IApizrExtendedOptions<TWebApi>
  nameWithType: IApizrExtendedOptions<TWebApi>
  fullName: Apizr.Extending.Configuring.IApizrExtendedOptions<TWebApi>
  nameWithType.vb: IApizrExtendedOptions(Of TWebApi)
  fullName.vb: Apizr.Extending.Configuring.IApizrExtendedOptions(Of TWebApi)
  name.vb: IApizrExtendedOptions(Of TWebApi)
  spec.csharp:
  - uid: Apizr.Extending.Configuring.IApizrExtendedOptions`1
    name: IApizrExtendedOptions
    nameWithType: IApizrExtendedOptions
    fullName: Apizr.Extending.Configuring.IApizrExtendedOptions
  - name: <
    nameWithType: <
    fullName: <
  - name: TWebApi
    nameWithType: TWebApi
    fullName: TWebApi
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Apizr.Extending.Configuring.IApizrExtendedOptions`1
    name: IApizrExtendedOptions
    nameWithType: IApizrExtendedOptions
    fullName: Apizr.Extending.Configuring.IApizrExtendedOptions
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TWebApi
    nameWithType: TWebApi
    fullName: TWebApi
  - name: )
    nameWithType: )
    fullName: )
- uid: Apizr.Extending.Configuring.IApizrExtendedOptionsBase
  commentId: T:Apizr.Extending.Configuring.IApizrExtendedOptionsBase
  parent: Apizr.Extending.Configuring
  name: IApizrExtendedOptionsBase
  nameWithType: IApizrExtendedOptionsBase
  fullName: Apizr.Extending.Configuring.IApizrExtendedOptionsBase
- uid: Apizr.Extending.Configuring.IApizrExtendedOptionsBuilder`2
  commentId: T:Apizr.Extending.Configuring.IApizrExtendedOptionsBuilder`2
  name: IApizrExtendedOptionsBuilder<TApizrExtendedOptions, TApizrExtendedOptionsBuilder>
  nameWithType: IApizrExtendedOptionsBuilder<TApizrExtendedOptions, TApizrExtendedOptionsBuilder>
  fullName: Apizr.Extending.Configuring.IApizrExtendedOptionsBuilder<TApizrExtendedOptions, TApizrExtendedOptionsBuilder>
  nameWithType.vb: IApizrExtendedOptionsBuilder(Of TApizrExtendedOptions, TApizrExtendedOptionsBuilder)
  fullName.vb: Apizr.Extending.Configuring.IApizrExtendedOptionsBuilder(Of TApizrExtendedOptions, TApizrExtendedOptionsBuilder)
  name.vb: IApizrExtendedOptionsBuilder(Of TApizrExtendedOptions, TApizrExtendedOptionsBuilder)
  spec.csharp:
  - uid: Apizr.Extending.Configuring.IApizrExtendedOptionsBuilder`2
    name: IApizrExtendedOptionsBuilder
    nameWithType: IApizrExtendedOptionsBuilder
    fullName: Apizr.Extending.Configuring.IApizrExtendedOptionsBuilder
  - name: <
    nameWithType: <
    fullName: <
  - name: TApizrExtendedOptions
    nameWithType: TApizrExtendedOptions
    fullName: TApizrExtendedOptions
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TApizrExtendedOptionsBuilder
    nameWithType: TApizrExtendedOptionsBuilder
    fullName: TApizrExtendedOptionsBuilder
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Apizr.Extending.Configuring.IApizrExtendedOptionsBuilder`2
    name: IApizrExtendedOptionsBuilder
    nameWithType: IApizrExtendedOptionsBuilder
    fullName: Apizr.Extending.Configuring.IApizrExtendedOptionsBuilder
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TApizrExtendedOptions
    nameWithType: TApizrExtendedOptions
    fullName: TApizrExtendedOptions
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TApizrExtendedOptionsBuilder
    nameWithType: TApizrExtendedOptionsBuilder
    fullName: TApizrExtendedOptionsBuilder
  - name: )
    nameWithType: )
    fullName: )
- uid: Apizr.Extending.Configuring.IApizrExtendedOptionsBuilder
  commentId: T:Apizr.Extending.Configuring.IApizrExtendedOptionsBuilder
  parent: Apizr.Extending.Configuring
  name: IApizrExtendedOptionsBuilder
  nameWithType: IApizrExtendedOptionsBuilder
  fullName: Apizr.Extending.Configuring.IApizrExtendedOptionsBuilder
- uid: Apizr.Extending.Configuring.IApizrExtendedOptionsBuilderBase
  commentId: T:Apizr.Extending.Configuring.IApizrExtendedOptionsBuilderBase
  parent: Apizr.Extending.Configuring
  name: IApizrExtendedOptionsBuilderBase
  nameWithType: IApizrExtendedOptionsBuilderBase
  fullName: Apizr.Extending.Configuring.IApizrExtendedOptionsBuilderBase
- uid: Apizr.Extending.Configuring.IApizrExtendedOptionsBuilderBase`2
  commentId: T:Apizr.Extending.Configuring.IApizrExtendedOptionsBuilderBase`2
  name: IApizrExtendedOptionsBuilderBase<TApizrExtendedOptions, TApizrExtendedOptionsBuilder>
  nameWithType: IApizrExtendedOptionsBuilderBase<TApizrExtendedOptions, TApizrExtendedOptionsBuilder>
  fullName: Apizr.Extending.Configuring.IApizrExtendedOptionsBuilderBase<TApizrExtendedOptions, TApizrExtendedOptionsBuilder>
  nameWithType.vb: IApizrExtendedOptionsBuilderBase(Of TApizrExtendedOptions, TApizrExtendedOptionsBuilder)
  fullName.vb: Apizr.Extending.Configuring.IApizrExtendedOptionsBuilderBase(Of TApizrExtendedOptions, TApizrExtendedOptionsBuilder)
  name.vb: IApizrExtendedOptionsBuilderBase(Of TApizrExtendedOptions, TApizrExtendedOptionsBuilder)
  spec.csharp:
  - uid: Apizr.Extending.Configuring.IApizrExtendedOptionsBuilderBase`2
    name: IApizrExtendedOptionsBuilderBase
    nameWithType: IApizrExtendedOptionsBuilderBase
    fullName: Apizr.Extending.Configuring.IApizrExtendedOptionsBuilderBase
  - name: <
    nameWithType: <
    fullName: <
  - name: TApizrExtendedOptions
    nameWithType: TApizrExtendedOptions
    fullName: TApizrExtendedOptions
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TApizrExtendedOptionsBuilder
    nameWithType: TApizrExtendedOptionsBuilder
    fullName: TApizrExtendedOptionsBuilder
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Apizr.Extending.Configuring.IApizrExtendedOptionsBuilderBase`2
    name: IApizrExtendedOptionsBuilderBase
    nameWithType: IApizrExtendedOptionsBuilderBase
    fullName: Apizr.Extending.Configuring.IApizrExtendedOptionsBuilderBase
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TApizrExtendedOptions
    nameWithType: TApizrExtendedOptions
    fullName: TApizrExtendedOptions
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TApizrExtendedOptionsBuilder
    nameWithType: TApizrExtendedOptionsBuilder
    fullName: TApizrExtendedOptionsBuilder
  - name: )
    nameWithType: )
    fullName: )
- uid: Apizr.Extending.Configuring
  commentId: N:Apizr.Extending.Configuring
  name: Apizr.Extending.Configuring
  nameWithType: Apizr.Extending.Configuring
  fullName: Apizr.Extending.Configuring
