### YamlMime:ManagedReference
items:
- uid: Apizr.Configuring.Registry.IApizrRegistryBuilderBase
  commentId: T:Apizr.Configuring.Registry.IApizrRegistryBuilderBase
  id: IApizrRegistryBuilderBase
  parent: Apizr.Configuring.Registry
  children: []
  langs:
  - csharp
  - vb
  name: IApizrRegistryBuilderBase
  nameWithType: IApizrRegistryBuilderBase
  fullName: Apizr.Configuring.Registry.IApizrRegistryBuilderBase
  type: Interface
  source:
    remote:
      path: Apizr/Src/Apizr/Configuring/Registry/IApizrRegistryBuilderBase.cs
      branch: feat/resilience
      repo: https://github.com/Respawnsive/Apizr.git
    id: IApizrRegistryBuilderBase
    path: ../../Src/Apizr/Configuring/Registry/IApizrRegistryBuilderBase.cs
    startLine: 10
  assemblies:
  - Apizr
  namespace: Apizr.Configuring.Registry
  summary: "\nRegistry builder options available for both static and extended registrations\n"
  example: []
  syntax:
    content: public interface IApizrRegistryBuilderBase
    content.vb: Public Interface IApizrRegistryBuilderBase
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
references:
- uid: Apizr.Configuring.Registry
  commentId: N:Apizr.Configuring.Registry
  name: Apizr.Configuring.Registry
  nameWithType: Apizr.Configuring.Registry
  fullName: Apizr.Configuring.Registry
