### YamlMime:ManagedReference
items:
- uid: Apizr.Extending.Configuring.Registry
  commentId: N:Apizr.Extending.Configuring.Registry
  id: Apizr.Extending.Configuring.Registry
  children:
  - Apizr.Extending.Configuring.Registry.ApizrExtendedRegistry
  - Apizr.Extending.Configuring.Registry.ApizrExtendedRegistryBuilder
  - Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistry
  - Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistryBase
  - Apizr.Extending.Configuring.Registry.IApizrExtendedRegistry
  - Apizr.Extending.Configuring.Registry.IApizrExtendedRegistryBuilder
  - Apizr.Extending.Configuring.Registry.IApizrExtendedRegistryBuilder`4
  langs:
  - csharp
  - vb
  name: Apizr.Extending.Configuring.Registry
  nameWithType: Apizr.Extending.Configuring.Registry
  fullName: Apizr.Extending.Configuring.Registry
  type: Namespace
  assemblies:
  - Apizr.Extensions.Microsoft.DependencyInjection
references:
- uid: Apizr.Extending.Configuring.Registry.ApizrExtendedRegistry
  commentId: T:Apizr.Extending.Configuring.Registry.ApizrExtendedRegistry
  parent: Apizr.Extending.Configuring.Registry
  href: Apizr.Extending.Configuring.Registry.ApizrExtendedRegistry.html
  name: ApizrExtendedRegistry
  nameWithType: ApizrExtendedRegistry
  fullName: Apizr.Extending.Configuring.Registry.ApizrExtendedRegistry
- uid: Apizr.Extending.Configuring.Registry.ApizrExtendedRegistryBuilder
  commentId: T:Apizr.Extending.Configuring.Registry.ApizrExtendedRegistryBuilder
  href: Apizr.Extending.Configuring.Registry.ApizrExtendedRegistryBuilder.html
  name: ApizrExtendedRegistryBuilder
  nameWithType: ApizrExtendedRegistryBuilder
  fullName: Apizr.Extending.Configuring.Registry.ApizrExtendedRegistryBuilder
- uid: Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistry
  commentId: T:Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistry
  parent: Apizr.Extending.Configuring.Registry
  href: Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistry.html
  name: IApizrExtendedConcurrentRegistry
  nameWithType: IApizrExtendedConcurrentRegistry
  fullName: Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistry
- uid: Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistryBase
  commentId: T:Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistryBase
  parent: Apizr.Extending.Configuring.Registry
  href: Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistryBase.html
  name: IApizrExtendedConcurrentRegistryBase
  nameWithType: IApizrExtendedConcurrentRegistryBase
  fullName: Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistryBase
- uid: Apizr.Extending.Configuring.Registry.IApizrExtendedRegistry
  commentId: T:Apizr.Extending.Configuring.Registry.IApizrExtendedRegistry
  parent: Apizr.Extending.Configuring.Registry
  href: Apizr.Extending.Configuring.Registry.IApizrExtendedRegistry.html
  name: IApizrExtendedRegistry
  nameWithType: IApizrExtendedRegistry
  fullName: Apizr.Extending.Configuring.Registry.IApizrExtendedRegistry
- uid: Apizr.Extending.Configuring.Registry.IApizrExtendedRegistryBuilder`4
  commentId: T:Apizr.Extending.Configuring.Registry.IApizrExtendedRegistryBuilder`4
  href: Apizr.Extending.Configuring.Registry.IApizrExtendedRegistryBuilder-4.html
  name: IApizrExtendedRegistryBuilder<TApizrExtendedRegistry, TApizrExtendedRegistryBuilder, TApizrExtendedProperOptionsBuilder, TApizrExtendedCommonOptionsBuilder>
  nameWithType: IApizrExtendedRegistryBuilder<TApizrExtendedRegistry, TApizrExtendedRegistryBuilder, TApizrExtendedProperOptionsBuilder, TApizrExtendedCommonOptionsBuilder>
  fullName: Apizr.Extending.Configuring.Registry.IApizrExtendedRegistryBuilder<TApizrExtendedRegistry, TApizrExtendedRegistryBuilder, TApizrExtendedProperOptionsBuilder, TApizrExtendedCommonOptionsBuilder>
  nameWithType.vb: IApizrExtendedRegistryBuilder(Of TApizrExtendedRegistry, TApizrExtendedRegistryBuilder, TApizrExtendedProperOptionsBuilder, TApizrExtendedCommonOptionsBuilder)
  fullName.vb: Apizr.Extending.Configuring.Registry.IApizrExtendedRegistryBuilder(Of TApizrExtendedRegistry, TApizrExtendedRegistryBuilder, TApizrExtendedProperOptionsBuilder, TApizrExtendedCommonOptionsBuilder)
  name.vb: IApizrExtendedRegistryBuilder(Of TApizrExtendedRegistry, TApizrExtendedRegistryBuilder, TApizrExtendedProperOptionsBuilder, TApizrExtendedCommonOptionsBuilder)
  spec.csharp:
  - uid: Apizr.Extending.Configuring.Registry.IApizrExtendedRegistryBuilder`4
    name: IApizrExtendedRegistryBuilder
    href: Apizr.Extending.Configuring.Registry.IApizrExtendedRegistryBuilder-4.html
  - name: <
  - name: TApizrExtendedRegistry
  - name: ','
  - name: " "
  - name: TApizrExtendedRegistryBuilder
  - name: ','
  - name: " "
  - name: TApizrExtendedProperOptionsBuilder
  - name: ','
  - name: " "
  - name: TApizrExtendedCommonOptionsBuilder
  - name: '>'
  spec.vb:
  - uid: Apizr.Extending.Configuring.Registry.IApizrExtendedRegistryBuilder`4
    name: IApizrExtendedRegistryBuilder
    href: Apizr.Extending.Configuring.Registry.IApizrExtendedRegistryBuilder-4.html
  - name: (
  - name: Of
  - name: " "
  - name: TApizrExtendedRegistry
  - name: ','
  - name: " "
  - name: TApizrExtendedRegistryBuilder
  - name: ','
  - name: " "
  - name: TApizrExtendedProperOptionsBuilder
  - name: ','
  - name: " "
  - name: TApizrExtendedCommonOptionsBuilder
  - name: )
- uid: Apizr.Extending.Configuring.Registry.IApizrExtendedRegistryBuilder
  commentId: T:Apizr.Extending.Configuring.Registry.IApizrExtendedRegistryBuilder
  parent: Apizr.Extending.Configuring.Registry
  href: Apizr.Extending.Configuring.Registry.IApizrExtendedRegistryBuilder.html
  name: IApizrExtendedRegistryBuilder
  nameWithType: IApizrExtendedRegistryBuilder
  fullName: Apizr.Extending.Configuring.Registry.IApizrExtendedRegistryBuilder
- uid: Apizr.Extending.Configuring.Registry
  commentId: N:Apizr.Extending.Configuring.Registry
  href: Apizr.html
  name: Apizr.Extending.Configuring.Registry
  nameWithType: Apizr.Extending.Configuring.Registry
  fullName: Apizr.Extending.Configuring.Registry
  spec.csharp:
  - uid: Apizr
    name: Apizr
    href: Apizr.html
  - name: .
  - uid: Apizr.Extending
    name: Extending
    href: Apizr.Extending.html
  - name: .
  - uid: Apizr.Extending.Configuring
    name: Configuring
    href: Apizr.Extending.Configuring.html
  - name: .
  - uid: Apizr.Extending.Configuring.Registry
    name: Registry
    href: Apizr.Extending.Configuring.Registry.html
  spec.vb:
  - uid: Apizr
    name: Apizr
    href: Apizr.html
  - name: .
  - uid: Apizr.Extending
    name: Extending
    href: Apizr.Extending.html
  - name: .
  - uid: Apizr.Extending.Configuring
    name: Configuring
    href: Apizr.Extending.Configuring.html
  - name: .
  - uid: Apizr.Extending.Configuring.Registry
    name: Registry
    href: Apizr.Extending.Configuring.Registry.html
