### YamlMime:ManagedReference
items:
- uid: Apizr.Configuring
  commentId: N:Apizr.Configuring
  id: Apizr.Configuring
  children:
  - Apizr.Configuring.ApizrDuplicateStrategy
  langs:
  - csharp
  - vb
  name: Apizr.Configuring
  nameWithType: Apizr.Configuring
  fullName: Apizr.Configuring
  type: Namespace
  assemblies:
  - Apizr
references:
- uid: Apizr.Configuring.ApizrDuplicateStrategy
  commentId: T:Apizr.Configuring.ApizrDuplicateStrategy
  parent: Apizr.Configuring
  name: ApizrDuplicateStrategy
  nameWithType: ApizrDuplicateStrategy
  fullName: Apizr.Configuring.ApizrDuplicateStrategy
- uid: Apizr.Configuring
  commentId: N:Apizr.Configuring
  name: Apizr.Configuring
  nameWithType: Apizr.Configuring
  fullName: Apizr.Configuring
