### YamlMime:ManagedReference
items:
- uid: Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistryBase
  commentId: T:Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistryBase
  id: IApizrExtendedConcurrentRegistryBase
  parent: Apizr.Extending.Configuring.Registry
  children:
  - Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistryBase.AddOrUpdateManager(System.Type)
  langs:
  - csharp
  - vb
  name: IApizrExtendedConcurrentRegistryBase
  nameWithType: IApizrExtendedConcurrentRegistryBase
  fullName: Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistryBase
  type: Interface
  source:
    id: IApizrExtendedConcurrentRegistryBase
    path: C:\Dev\Community\Apizr\Apizr\Src\Apizr.Extensions.Microsoft.DependencyInjection\Extending\Configuring\Registry\IApizrExtendedConcurrentRegistryBase.cs
    startLine: 7
  assemblies:
  - Apizr.Extensions.Microsoft.DependencyInjection
  namespace: Apizr.Extending.Configuring.Registry
  summary: "\nRegistry options available for extended registrations\n"
  example: []
  syntax:
    content: public interface IApizrExtendedConcurrentRegistryBase
    content.vb: Public Interface IApizrExtendedConcurrentRegistryBase
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistryBase.AddOrUpdateManager(System.Type)
  commentId: M:Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistryBase.AddOrUpdateManager(System.Type)
  id: AddOrUpdateManager(System.Type)
  parent: Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistryBase
  langs:
  - csharp
  - vb
  name: AddOrUpdateManager(Type)
  nameWithType: IApizrExtendedConcurrentRegistryBase.AddOrUpdateManager(Type)
  fullName: Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistryBase.AddOrUpdateManager(System.Type)
  type: Method
  source:
    id: AddOrUpdateManager
    path: C:\Dev\Community\Apizr\Apizr\Src\Apizr.Extensions.Microsoft.DependencyInjection\Extending\Configuring\Registry\IApizrExtendedConcurrentRegistryBase.cs
    startLine: 9
  assemblies:
  - Apizr.Extensions.Microsoft.DependencyInjection
  namespace: Apizr.Extending.Configuring.Registry
  syntax:
    content: void AddOrUpdateManager(Type managerType)
    parameters:
    - id: managerType
      type: System.Type
    content.vb: Sub AddOrUpdateManager(managerType As Type)
  overload: Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistryBase.AddOrUpdateManager*
references:
- uid: Apizr.Extending.Configuring.Registry
  commentId: N:Apizr.Extending.Configuring.Registry
  name: Apizr.Extending.Configuring.Registry
  nameWithType: Apizr.Extending.Configuring.Registry
  fullName: Apizr.Extending.Configuring.Registry
- uid: Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistryBase.AddOrUpdateManager*
  commentId: Overload:Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistryBase.AddOrUpdateManager
  name: AddOrUpdateManager
  nameWithType: IApizrExtendedConcurrentRegistryBase.AddOrUpdateManager
  fullName: Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistryBase.AddOrUpdateManager
- uid: System.Type
  commentId: T:System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
