### YamlMime:ManagedReference
items:
- uid: Apizr.Extending.Configuring.IApizrExtendedOptions`1
  commentId: T:Apizr.Extending.Configuring.IApizrExtendedOptions`1
  id: IApizrExtendedOptions`1
  parent: Apizr.Extending.Configuring
  children: []
  langs:
  - csharp
  - vb
  name: IApizrExtendedOptions<TWebApi>
  nameWithType: IApizrExtendedOptions<TWebApi>
  fullName: Apizr.Extending.Configuring.IApizrExtendedOptions<TWebApi>
  type: Interface
  source:
    id: IApizrExtendedOptions
    path: C:\Dev\Community\Apizr\Apizr\Apizr.Extensions.Microsoft.DependencyInjection\Extending\Configuring\IApizrExtendedOptions.cs
    startLine: 16
  assemblies:
  - Apizr.Extensions.Microsoft.DependencyInjection
  namespace: Apizr.Extending.Configuring
  summary: "\nOptions available for extended registrations\n"
  example: []
  syntax:
    content: 'public interface IApizrExtendedOptions<TWebApi> : IApizrOptions<TWebApi>, IApizrExtendedOptionsBase, IApizrExtendedCommonOptionsBase, IApizrExtendedProperOptionsBase, IApizrExtendedSharedOptionsBase, IApizrOptionsBase, IApizrCommonOptionsBase, IApizrProperOptionsBase, IApizrSharedOptionsBase'
    typeParameters:
    - id: TWebApi
    content.vb: >-
      Public Interface IApizrExtendedOptions(Of TWebApi)
          Inherits IApizrOptions(Of TWebApi), IApizrExtendedOptionsBase
  inheritedMembers:
  - Apizr.Extending.Configuring.IApizrExtendedOptionsBase.HttpClientHandler
  - Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptionsBase.DelegatingHandlersExtendedFactories
  - Apizr.Configuring.Common.IApizrCommonOptionsBase.RefitSettings
  - Apizr.Configuring.Proper.IApizrProperOptionsBase.WebApiType
  - Apizr.Configuring.Proper.IApizrProperOptionsBase.PolicyRegistryKeys
  - Apizr.Configuring.Proper.IApizrProperOptionsBase.Logger
  - Apizr.Configuring.Shared.IApizrSharedOptionsBase.BaseUri
  - Apizr.Configuring.Shared.IApizrSharedOptionsBase.BaseAddress
  - Apizr.Configuring.Shared.IApizrSharedOptionsBase.BasePath
  - Apizr.Configuring.Shared.IApizrSharedOptionsBase.HttpTracerMode
  - Apizr.Configuring.Shared.IApizrSharedOptionsBase.TrafficVerbosity
  - Apizr.Configuring.Shared.IApizrSharedOptionsBase.LogLevels
  nameWithType.vb: IApizrExtendedOptions(Of TWebApi)
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
  fullName.vb: Apizr.Extending.Configuring.IApizrExtendedOptions(Of TWebApi)
  name.vb: IApizrExtendedOptions(Of TWebApi)
references:
- uid: Apizr.Extending.Configuring
  commentId: N:Apizr.Extending.Configuring
  name: Apizr.Extending.Configuring
  nameWithType: Apizr.Extending.Configuring
  fullName: Apizr.Extending.Configuring
- uid: Apizr.Extending.Configuring.IApizrExtendedOptionsBase.HttpClientHandler
  commentId: P:Apizr.Extending.Configuring.IApizrExtendedOptionsBase.HttpClientHandler
  parent: Apizr.Extending.Configuring.IApizrExtendedOptionsBase
  name: HttpClientHandler
  nameWithType: IApizrExtendedOptionsBase.HttpClientHandler
  fullName: Apizr.Extending.Configuring.IApizrExtendedOptionsBase.HttpClientHandler
- uid: Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptionsBase.DelegatingHandlersExtendedFactories
  commentId: P:Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptionsBase.DelegatingHandlersExtendedFactories
  parent: Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptionsBase
  name: DelegatingHandlersExtendedFactories
  nameWithType: IApizrExtendedSharedOptionsBase.DelegatingHandlersExtendedFactories
  fullName: Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptionsBase.DelegatingHandlersExtendedFactories
- uid: Apizr.Configuring.Common.IApizrCommonOptionsBase.RefitSettings
  commentId: P:Apizr.Configuring.Common.IApizrCommonOptionsBase.RefitSettings
  parent: Apizr.Configuring.Common.IApizrCommonOptionsBase
  name: RefitSettings
  nameWithType: IApizrCommonOptionsBase.RefitSettings
  fullName: Apizr.Configuring.Common.IApizrCommonOptionsBase.RefitSettings
- uid: Apizr.Configuring.Proper.IApizrProperOptionsBase.WebApiType
  commentId: P:Apizr.Configuring.Proper.IApizrProperOptionsBase.WebApiType
  parent: Apizr.Configuring.Proper.IApizrProperOptionsBase
  name: WebApiType
  nameWithType: IApizrProperOptionsBase.WebApiType
  fullName: Apizr.Configuring.Proper.IApizrProperOptionsBase.WebApiType
- uid: Apizr.Configuring.Proper.IApizrProperOptionsBase.PolicyRegistryKeys
  commentId: P:Apizr.Configuring.Proper.IApizrProperOptionsBase.PolicyRegistryKeys
  parent: Apizr.Configuring.Proper.IApizrProperOptionsBase
  name: PolicyRegistryKeys
  nameWithType: IApizrProperOptionsBase.PolicyRegistryKeys
  fullName: Apizr.Configuring.Proper.IApizrProperOptionsBase.PolicyRegistryKeys
- uid: Apizr.Configuring.Proper.IApizrProperOptionsBase.Logger
  commentId: P:Apizr.Configuring.Proper.IApizrProperOptionsBase.Logger
  parent: Apizr.Configuring.Proper.IApizrProperOptionsBase
  name: Logger
  nameWithType: IApizrProperOptionsBase.Logger
  fullName: Apizr.Configuring.Proper.IApizrProperOptionsBase.Logger
- uid: Apizr.Configuring.Shared.IApizrSharedOptionsBase.BaseUri
  commentId: P:Apizr.Configuring.Shared.IApizrSharedOptionsBase.BaseUri
  parent: Apizr.Configuring.Shared.IApizrSharedOptionsBase
  name: BaseUri
  nameWithType: IApizrSharedOptionsBase.BaseUri
  fullName: Apizr.Configuring.Shared.IApizrSharedOptionsBase.BaseUri
- uid: Apizr.Configuring.Shared.IApizrSharedOptionsBase.BaseAddress
  commentId: P:Apizr.Configuring.Shared.IApizrSharedOptionsBase.BaseAddress
  parent: Apizr.Configuring.Shared.IApizrSharedOptionsBase
  name: BaseAddress
  nameWithType: IApizrSharedOptionsBase.BaseAddress
  fullName: Apizr.Configuring.Shared.IApizrSharedOptionsBase.BaseAddress
- uid: Apizr.Configuring.Shared.IApizrSharedOptionsBase.BasePath
  commentId: P:Apizr.Configuring.Shared.IApizrSharedOptionsBase.BasePath
  parent: Apizr.Configuring.Shared.IApizrSharedOptionsBase
  name: BasePath
  nameWithType: IApizrSharedOptionsBase.BasePath
  fullName: Apizr.Configuring.Shared.IApizrSharedOptionsBase.BasePath
- uid: Apizr.Configuring.Shared.IApizrSharedOptionsBase.HttpTracerMode
  commentId: P:Apizr.Configuring.Shared.IApizrSharedOptionsBase.HttpTracerMode
  parent: Apizr.Configuring.Shared.IApizrSharedOptionsBase
  name: HttpTracerMode
  nameWithType: IApizrSharedOptionsBase.HttpTracerMode
  fullName: Apizr.Configuring.Shared.IApizrSharedOptionsBase.HttpTracerMode
- uid: Apizr.Configuring.Shared.IApizrSharedOptionsBase.TrafficVerbosity
  commentId: P:Apizr.Configuring.Shared.IApizrSharedOptionsBase.TrafficVerbosity
  parent: Apizr.Configuring.Shared.IApizrSharedOptionsBase
  name: TrafficVerbosity
  nameWithType: IApizrSharedOptionsBase.TrafficVerbosity
  fullName: Apizr.Configuring.Shared.IApizrSharedOptionsBase.TrafficVerbosity
- uid: Apizr.Configuring.Shared.IApizrSharedOptionsBase.LogLevels
  commentId: P:Apizr.Configuring.Shared.IApizrSharedOptionsBase.LogLevels
  parent: Apizr.Configuring.Shared.IApizrSharedOptionsBase
  name: LogLevels
  nameWithType: IApizrSharedOptionsBase.LogLevels
  fullName: Apizr.Configuring.Shared.IApizrSharedOptionsBase.LogLevels
- uid: Apizr.Extending.Configuring.IApizrExtendedOptionsBase
  commentId: T:Apizr.Extending.Configuring.IApizrExtendedOptionsBase
  parent: Apizr.Extending.Configuring
  name: IApizrExtendedOptionsBase
  nameWithType: IApizrExtendedOptionsBase
  fullName: Apizr.Extending.Configuring.IApizrExtendedOptionsBase
- uid: Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptionsBase
  commentId: T:Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptionsBase
  parent: Apizr.Extending.Configuring.Shared
  name: IApizrExtendedSharedOptionsBase
  nameWithType: IApizrExtendedSharedOptionsBase
  fullName: Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptionsBase
- uid: Apizr.Configuring.Common.IApizrCommonOptionsBase
  commentId: T:Apizr.Configuring.Common.IApizrCommonOptionsBase
  parent: Apizr.Configuring.Common
  name: IApizrCommonOptionsBase
  nameWithType: IApizrCommonOptionsBase
  fullName: Apizr.Configuring.Common.IApizrCommonOptionsBase
- uid: Apizr.Configuring.Proper.IApizrProperOptionsBase
  commentId: T:Apizr.Configuring.Proper.IApizrProperOptionsBase
  parent: Apizr.Configuring.Proper
  name: IApizrProperOptionsBase
  nameWithType: IApizrProperOptionsBase
  fullName: Apizr.Configuring.Proper.IApizrProperOptionsBase
- uid: Apizr.Configuring.Shared.IApizrSharedOptionsBase
  commentId: T:Apizr.Configuring.Shared.IApizrSharedOptionsBase
  parent: Apizr.Configuring.Shared
  name: IApizrSharedOptionsBase
  nameWithType: IApizrSharedOptionsBase
  fullName: Apizr.Configuring.Shared.IApizrSharedOptionsBase
- uid: Apizr.Extending.Configuring.Shared
  commentId: N:Apizr.Extending.Configuring.Shared
  name: Apizr.Extending.Configuring.Shared
  nameWithType: Apizr.Extending.Configuring.Shared
  fullName: Apizr.Extending.Configuring.Shared
- uid: Apizr.Configuring.Common
  commentId: N:Apizr.Configuring.Common
  name: Apizr.Configuring.Common
  nameWithType: Apizr.Configuring.Common
  fullName: Apizr.Configuring.Common
- uid: Apizr.Configuring.Proper
  commentId: N:Apizr.Configuring.Proper
  name: Apizr.Configuring.Proper
  nameWithType: Apizr.Configuring.Proper
  fullName: Apizr.Configuring.Proper
- uid: Apizr.Configuring.Shared
  commentId: N:Apizr.Configuring.Shared
  name: Apizr.Configuring.Shared
  nameWithType: Apizr.Configuring.Shared
  fullName: Apizr.Configuring.Shared
