### YamlMime:ManagedReference
items:
- uid: Apizr.Configuring.Shared
  commentId: N:Apizr.Configuring.Shared
  id: Apizr.Configuring.Shared
  children:
  - Apizr.Configuring.Shared.ApizrGlobalSharedOptionsBase
  - Apizr.Configuring.Shared.ApizrGlobalSharedRegistrationOptionsBase
  - Apizr.Configuring.Shared.IApizrExtendedSharedRegistrationOptionsBuilderBase
  - Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase
  - Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBuilderBase
  - Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBuilderBase`2
  - Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase
  - Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBuilderBase
  - Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBuilderBase`2
  - Apizr.Configuring.Shared.IApizrSharedRegistrationOptions
  - Apizr.Configuring.Shared.IApizrSharedRegistrationOptionsBase
  - Apizr.Configuring.Shared.IApizrSharedRegistrationOptionsBuilder
  - Apizr.Configuring.Shared.IApizrSharedRegistrationOptionsBuilder`2
  - Apizr.Configuring.Shared.IApizrSharedRegistrationOptionsBuilderBase
  - Apizr.Configuring.Shared.IApizrSharedRegistrationOptionsBuilderBase`2
  langs:
  - csharp
  - vb
  name: Apizr.Configuring.Shared
  nameWithType: Apizr.Configuring.Shared
  fullName: Apizr.Configuring.Shared
  type: Namespace
  assemblies:
  - Apizr
references:
- uid: Apizr.Configuring.Shared.ApizrGlobalSharedOptionsBase
  commentId: T:Apizr.Configuring.Shared.ApizrGlobalSharedOptionsBase
  parent: Apizr.Configuring.Shared
  name: ApizrGlobalSharedOptionsBase
  nameWithType: ApizrGlobalSharedOptionsBase
  fullName: Apizr.Configuring.Shared.ApizrGlobalSharedOptionsBase
- uid: Apizr.Configuring.Shared.ApizrGlobalSharedRegistrationOptionsBase
  commentId: T:Apizr.Configuring.Shared.ApizrGlobalSharedRegistrationOptionsBase
  parent: Apizr.Configuring.Shared
  name: ApizrGlobalSharedRegistrationOptionsBase
  nameWithType: ApizrGlobalSharedRegistrationOptionsBase
  fullName: Apizr.Configuring.Shared.ApizrGlobalSharedRegistrationOptionsBase
- uid: Apizr.Configuring.Shared.IApizrExtendedSharedRegistrationOptionsBuilderBase
  commentId: T:Apizr.Configuring.Shared.IApizrExtendedSharedRegistrationOptionsBuilderBase
  parent: Apizr.Configuring.Shared
  name: IApizrExtendedSharedRegistrationOptionsBuilderBase
  nameWithType: IApizrExtendedSharedRegistrationOptionsBuilderBase
  fullName: Apizr.Configuring.Shared.IApizrExtendedSharedRegistrationOptionsBuilderBase
- uid: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase
  commentId: T:Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase
  parent: Apizr.Configuring.Shared
  name: IApizrGlobalSharedOptionsBase
  nameWithType: IApizrGlobalSharedOptionsBase
  fullName: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase
- uid: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBuilderBase
  commentId: T:Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBuilderBase
  parent: Apizr.Configuring.Shared
  name: IApizrGlobalSharedOptionsBuilderBase
  nameWithType: IApizrGlobalSharedOptionsBuilderBase
  fullName: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBuilderBase
- uid: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBuilderBase`2
  commentId: T:Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBuilderBase`2
  name: IApizrGlobalSharedOptionsBuilderBase<TApizrOptions, TApizrOptionsBuilder>
  nameWithType: IApizrGlobalSharedOptionsBuilderBase<TApizrOptions, TApizrOptionsBuilder>
  fullName: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBuilderBase<TApizrOptions, TApizrOptionsBuilder>
  nameWithType.vb: IApizrGlobalSharedOptionsBuilderBase(Of TApizrOptions, TApizrOptionsBuilder)
  fullName.vb: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBuilderBase(Of TApizrOptions, TApizrOptionsBuilder)
  name.vb: IApizrGlobalSharedOptionsBuilderBase(Of TApizrOptions, TApizrOptionsBuilder)
  spec.csharp:
  - uid: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBuilderBase`2
    name: IApizrGlobalSharedOptionsBuilderBase
    nameWithType: IApizrGlobalSharedOptionsBuilderBase
    fullName: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBuilderBase
  - name: <
    nameWithType: <
    fullName: <
  - name: TApizrOptions
    nameWithType: TApizrOptions
    fullName: TApizrOptions
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TApizrOptionsBuilder
    nameWithType: TApizrOptionsBuilder
    fullName: TApizrOptionsBuilder
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBuilderBase`2
    name: IApizrGlobalSharedOptionsBuilderBase
    nameWithType: IApizrGlobalSharedOptionsBuilderBase
    fullName: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBuilderBase
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TApizrOptions
    nameWithType: TApizrOptions
    fullName: TApizrOptions
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TApizrOptionsBuilder
    nameWithType: TApizrOptionsBuilder
    fullName: TApizrOptionsBuilder
  - name: )
    nameWithType: )
    fullName: )
- uid: Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase
  commentId: T:Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase
  parent: Apizr.Configuring.Shared
  name: IApizrGlobalSharedRegistrationOptionsBase
  nameWithType: IApizrGlobalSharedRegistrationOptionsBase
  fullName: Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase
- uid: Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBuilderBase
  commentId: T:Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBuilderBase
  parent: Apizr.Configuring.Shared
  name: IApizrGlobalSharedRegistrationOptionsBuilderBase
  nameWithType: IApizrGlobalSharedRegistrationOptionsBuilderBase
  fullName: Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBuilderBase
- uid: Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBuilderBase`2
  commentId: T:Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBuilderBase`2
  name: IApizrGlobalSharedRegistrationOptionsBuilderBase<TApizrOptions, TApizrOptionsBuilder>
  nameWithType: IApizrGlobalSharedRegistrationOptionsBuilderBase<TApizrOptions, TApizrOptionsBuilder>
  fullName: Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBuilderBase<TApizrOptions, TApizrOptionsBuilder>
  nameWithType.vb: IApizrGlobalSharedRegistrationOptionsBuilderBase(Of TApizrOptions, TApizrOptionsBuilder)
  fullName.vb: Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBuilderBase(Of TApizrOptions, TApizrOptionsBuilder)
  name.vb: IApizrGlobalSharedRegistrationOptionsBuilderBase(Of TApizrOptions, TApizrOptionsBuilder)
  spec.csharp:
  - uid: Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBuilderBase`2
    name: IApizrGlobalSharedRegistrationOptionsBuilderBase
    nameWithType: IApizrGlobalSharedRegistrationOptionsBuilderBase
    fullName: Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBuilderBase
  - name: <
    nameWithType: <
    fullName: <
  - name: TApizrOptions
    nameWithType: TApizrOptions
    fullName: TApizrOptions
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TApizrOptionsBuilder
    nameWithType: TApizrOptionsBuilder
    fullName: TApizrOptionsBuilder
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBuilderBase`2
    name: IApizrGlobalSharedRegistrationOptionsBuilderBase
    nameWithType: IApizrGlobalSharedRegistrationOptionsBuilderBase
    fullName: Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBuilderBase
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TApizrOptions
    nameWithType: TApizrOptions
    fullName: TApizrOptions
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TApizrOptionsBuilder
    nameWithType: TApizrOptionsBuilder
    fullName: TApizrOptionsBuilder
  - name: )
    nameWithType: )
    fullName: )
- uid: Apizr.Configuring.Shared.IApizrSharedRegistrationOptions
  commentId: T:Apizr.Configuring.Shared.IApizrSharedRegistrationOptions
  parent: Apizr.Configuring.Shared
  name: IApizrSharedRegistrationOptions
  nameWithType: IApizrSharedRegistrationOptions
  fullName: Apizr.Configuring.Shared.IApizrSharedRegistrationOptions
- uid: Apizr.Configuring.Shared.IApizrSharedRegistrationOptionsBase
  commentId: T:Apizr.Configuring.Shared.IApizrSharedRegistrationOptionsBase
  parent: Apizr.Configuring.Shared
  name: IApizrSharedRegistrationOptionsBase
  nameWithType: IApizrSharedRegistrationOptionsBase
  fullName: Apizr.Configuring.Shared.IApizrSharedRegistrationOptionsBase
- uid: Apizr.Configuring.Shared.IApizrSharedRegistrationOptionsBuilder
  commentId: T:Apizr.Configuring.Shared.IApizrSharedRegistrationOptionsBuilder
  parent: Apizr.Configuring.Shared
  name: IApizrSharedRegistrationOptionsBuilder
  nameWithType: IApizrSharedRegistrationOptionsBuilder
  fullName: Apizr.Configuring.Shared.IApizrSharedRegistrationOptionsBuilder
- uid: Apizr.Configuring.Shared.IApizrSharedRegistrationOptionsBuilder`2
  commentId: T:Apizr.Configuring.Shared.IApizrSharedRegistrationOptionsBuilder`2
  name: IApizrSharedRegistrationOptionsBuilder<TApizrOptions, TApizrOptionsBuilder>
  nameWithType: IApizrSharedRegistrationOptionsBuilder<TApizrOptions, TApizrOptionsBuilder>
  fullName: Apizr.Configuring.Shared.IApizrSharedRegistrationOptionsBuilder<TApizrOptions, TApizrOptionsBuilder>
  nameWithType.vb: IApizrSharedRegistrationOptionsBuilder(Of TApizrOptions, TApizrOptionsBuilder)
  fullName.vb: Apizr.Configuring.Shared.IApizrSharedRegistrationOptionsBuilder(Of TApizrOptions, TApizrOptionsBuilder)
  name.vb: IApizrSharedRegistrationOptionsBuilder(Of TApizrOptions, TApizrOptionsBuilder)
  spec.csharp:
  - uid: Apizr.Configuring.Shared.IApizrSharedRegistrationOptionsBuilder`2
    name: IApizrSharedRegistrationOptionsBuilder
    nameWithType: IApizrSharedRegistrationOptionsBuilder
    fullName: Apizr.Configuring.Shared.IApizrSharedRegistrationOptionsBuilder
  - name: <
    nameWithType: <
    fullName: <
  - name: TApizrOptions
    nameWithType: TApizrOptions
    fullName: TApizrOptions
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TApizrOptionsBuilder
    nameWithType: TApizrOptionsBuilder
    fullName: TApizrOptionsBuilder
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Apizr.Configuring.Shared.IApizrSharedRegistrationOptionsBuilder`2
    name: IApizrSharedRegistrationOptionsBuilder
    nameWithType: IApizrSharedRegistrationOptionsBuilder
    fullName: Apizr.Configuring.Shared.IApizrSharedRegistrationOptionsBuilder
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TApizrOptions
    nameWithType: TApizrOptions
    fullName: TApizrOptions
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TApizrOptionsBuilder
    nameWithType: TApizrOptionsBuilder
    fullName: TApizrOptionsBuilder
  - name: )
    nameWithType: )
    fullName: )
- uid: Apizr.Configuring.Shared.IApizrSharedRegistrationOptionsBuilderBase
  commentId: T:Apizr.Configuring.Shared.IApizrSharedRegistrationOptionsBuilderBase
  parent: Apizr.Configuring.Shared
  name: IApizrSharedRegistrationOptionsBuilderBase
  nameWithType: IApizrSharedRegistrationOptionsBuilderBase
  fullName: Apizr.Configuring.Shared.IApizrSharedRegistrationOptionsBuilderBase
- uid: Apizr.Configuring.Shared.IApizrSharedRegistrationOptionsBuilderBase`2
  commentId: T:Apizr.Configuring.Shared.IApizrSharedRegistrationOptionsBuilderBase`2
  name: IApizrSharedRegistrationOptionsBuilderBase<TApizrOptions, TApizrOptionsBuilder>
  nameWithType: IApizrSharedRegistrationOptionsBuilderBase<TApizrOptions, TApizrOptionsBuilder>
  fullName: Apizr.Configuring.Shared.IApizrSharedRegistrationOptionsBuilderBase<TApizrOptions, TApizrOptionsBuilder>
  nameWithType.vb: IApizrSharedRegistrationOptionsBuilderBase(Of TApizrOptions, TApizrOptionsBuilder)
  fullName.vb: Apizr.Configuring.Shared.IApizrSharedRegistrationOptionsBuilderBase(Of TApizrOptions, TApizrOptionsBuilder)
  name.vb: IApizrSharedRegistrationOptionsBuilderBase(Of TApizrOptions, TApizrOptionsBuilder)
  spec.csharp:
  - uid: Apizr.Configuring.Shared.IApizrSharedRegistrationOptionsBuilderBase`2
    name: IApizrSharedRegistrationOptionsBuilderBase
    nameWithType: IApizrSharedRegistrationOptionsBuilderBase
    fullName: Apizr.Configuring.Shared.IApizrSharedRegistrationOptionsBuilderBase
  - name: <
    nameWithType: <
    fullName: <
  - name: TApizrOptions
    nameWithType: TApizrOptions
    fullName: TApizrOptions
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TApizrOptionsBuilder
    nameWithType: TApizrOptionsBuilder
    fullName: TApizrOptionsBuilder
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Apizr.Configuring.Shared.IApizrSharedRegistrationOptionsBuilderBase`2
    name: IApizrSharedRegistrationOptionsBuilderBase
    nameWithType: IApizrSharedRegistrationOptionsBuilderBase
    fullName: Apizr.Configuring.Shared.IApizrSharedRegistrationOptionsBuilderBase
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TApizrOptions
    nameWithType: TApizrOptions
    fullName: TApizrOptions
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TApizrOptionsBuilder
    nameWithType: TApizrOptionsBuilder
    fullName: TApizrOptionsBuilder
  - name: )
    nameWithType: )
    fullName: )
- uid: Apizr.Configuring.Shared
  commentId: N:Apizr.Configuring.Shared
  name: Apizr.Configuring.Shared
  nameWithType: Apizr.Configuring.Shared
  fullName: Apizr.Configuring.Shared
