### YamlMime:ManagedReference
items:
- uid: Apizr.Configuring.ApizrConfigurationSource
  commentId: T:Apizr.Configuring.ApizrConfigurationSource
  id: ApizrConfigurationSource
  parent: Apizr.Configuring
  children:
  - Apizr.Configuring.ApizrConfigurationSource.CommonAttribute
  - Apizr.Configuring.ApizrConfigurationSource.CommonOption
  - Apizr.Configuring.ApizrConfigurationSource.FinalConfiguration
  - Apizr.Configuring.ApizrConfigurationSource.ManagerAttribute
  - Apizr.Configuring.ApizrConfigurationSource.ManagerOption
  - Apizr.Configuring.ApizrConfigurationSource.ProperAttribute
  - Apizr.Configuring.ApizrConfigurationSource.ProperOption
  - Apizr.Configuring.ApizrConfigurationSource.RequestAttribute
  - Apizr.Configuring.ApizrConfigurationSource.RequestOption
  langs:
  - csharp
  - vb
  name: ApizrConfigurationSource
  nameWithType: ApizrConfigurationSource
  fullName: Apizr.Configuring.ApizrConfigurationSource
  type: Enum
  source:
    remote:
      path: Apizr/Src/Apizr/Configuring/ApizrConfigurationSource.cs
      branch: lab
      repo: https://github.com/Respawnsive/Apizr.git
    id: ApizrConfigurationSource
    path: ../../Src/Apizr/Configuring/ApizrConfigurationSource.cs
    startLine: 2
  assemblies:
  - Apizr
  namespace: Apizr.Configuring
  syntax:
    content: public enum ApizrConfigurationSource
    content.vb: Public Enum ApizrConfigurationSource
- uid: Apizr.Configuring.ApizrConfigurationSource.CommonAttribute
  commentId: F:Apizr.Configuring.ApizrConfigurationSource.CommonAttribute
  id: CommonAttribute
  parent: Apizr.Configuring.ApizrConfigurationSource
  langs:
  - csharp
  - vb
  name: CommonAttribute
  nameWithType: ApizrConfigurationSource.CommonAttribute
  fullName: Apizr.Configuring.ApizrConfigurationSource.CommonAttribute
  type: Field
  source:
    remote:
      path: Apizr/Src/Apizr/Configuring/ApizrConfigurationSource.cs
      branch: lab
      repo: https://github.com/Respawnsive/Apizr.git
    id: CommonAttribute
    path: ../../Src/Apizr/Configuring/ApizrConfigurationSource.cs
    startLine: 4
  assemblies:
  - Apizr
  namespace: Apizr.Configuring
  syntax:
    content: CommonAttribute = 0
    return:
      type: Apizr.Configuring.ApizrConfigurationSource
- uid: Apizr.Configuring.ApizrConfigurationSource.CommonOption
  commentId: F:Apizr.Configuring.ApizrConfigurationSource.CommonOption
  id: CommonOption
  parent: Apizr.Configuring.ApizrConfigurationSource
  langs:
  - csharp
  - vb
  name: CommonOption
  nameWithType: ApizrConfigurationSource.CommonOption
  fullName: Apizr.Configuring.ApizrConfigurationSource.CommonOption
  type: Field
  source:
    remote:
      path: Apizr/Src/Apizr/Configuring/ApizrConfigurationSource.cs
      branch: lab
      repo: https://github.com/Respawnsive/Apizr.git
    id: CommonOption
    path: ../../Src/Apizr/Configuring/ApizrConfigurationSource.cs
    startLine: 5
  assemblies:
  - Apizr
  namespace: Apizr.Configuring
  syntax:
    content: CommonOption = 1
    return:
      type: Apizr.Configuring.ApizrConfigurationSource
- uid: Apizr.Configuring.ApizrConfigurationSource.ProperAttribute
  commentId: F:Apizr.Configuring.ApizrConfigurationSource.ProperAttribute
  id: ProperAttribute
  parent: Apizr.Configuring.ApizrConfigurationSource
  langs:
  - csharp
  - vb
  name: ProperAttribute
  nameWithType: ApizrConfigurationSource.ProperAttribute
  fullName: Apizr.Configuring.ApizrConfigurationSource.ProperAttribute
  type: Field
  source:
    remote:
      path: Apizr/Src/Apizr/Configuring/ApizrConfigurationSource.cs
      branch: lab
      repo: https://github.com/Respawnsive/Apizr.git
    id: ProperAttribute
    path: ../../Src/Apizr/Configuring/ApizrConfigurationSource.cs
    startLine: 6
  assemblies:
  - Apizr
  namespace: Apizr.Configuring
  syntax:
    content: ProperAttribute = 2
    return:
      type: Apizr.Configuring.ApizrConfigurationSource
- uid: Apizr.Configuring.ApizrConfigurationSource.ProperOption
  commentId: F:Apizr.Configuring.ApizrConfigurationSource.ProperOption
  id: ProperOption
  parent: Apizr.Configuring.ApizrConfigurationSource
  langs:
  - csharp
  - vb
  name: ProperOption
  nameWithType: ApizrConfigurationSource.ProperOption
  fullName: Apizr.Configuring.ApizrConfigurationSource.ProperOption
  type: Field
  source:
    remote:
      path: Apizr/Src/Apizr/Configuring/ApizrConfigurationSource.cs
      branch: lab
      repo: https://github.com/Respawnsive/Apizr.git
    id: ProperOption
    path: ../../Src/Apizr/Configuring/ApizrConfigurationSource.cs
    startLine: 7
  assemblies:
  - Apizr
  namespace: Apizr.Configuring
  syntax:
    content: ProperOption = 3
    return:
      type: Apizr.Configuring.ApizrConfigurationSource
- uid: Apizr.Configuring.ApizrConfigurationSource.ManagerAttribute
  commentId: F:Apizr.Configuring.ApizrConfigurationSource.ManagerAttribute
  id: ManagerAttribute
  parent: Apizr.Configuring.ApizrConfigurationSource
  langs:
  - csharp
  - vb
  name: ManagerAttribute
  nameWithType: ApizrConfigurationSource.ManagerAttribute
  fullName: Apizr.Configuring.ApizrConfigurationSource.ManagerAttribute
  type: Field
  source:
    remote:
      path: Apizr/Src/Apizr/Configuring/ApizrConfigurationSource.cs
      branch: lab
      repo: https://github.com/Respawnsive/Apizr.git
    id: ManagerAttribute
    path: ../../Src/Apizr/Configuring/ApizrConfigurationSource.cs
    startLine: 8
  assemblies:
  - Apizr
  namespace: Apizr.Configuring
  syntax:
    content: ManagerAttribute = 4
    return:
      type: Apizr.Configuring.ApizrConfigurationSource
- uid: Apizr.Configuring.ApizrConfigurationSource.ManagerOption
  commentId: F:Apizr.Configuring.ApizrConfigurationSource.ManagerOption
  id: ManagerOption
  parent: Apizr.Configuring.ApizrConfigurationSource
  langs:
  - csharp
  - vb
  name: ManagerOption
  nameWithType: ApizrConfigurationSource.ManagerOption
  fullName: Apizr.Configuring.ApizrConfigurationSource.ManagerOption
  type: Field
  source:
    remote:
      path: Apizr/Src/Apizr/Configuring/ApizrConfigurationSource.cs
      branch: lab
      repo: https://github.com/Respawnsive/Apizr.git
    id: ManagerOption
    path: ../../Src/Apizr/Configuring/ApizrConfigurationSource.cs
    startLine: 9
  assemblies:
  - Apizr
  namespace: Apizr.Configuring
  syntax:
    content: ManagerOption = 5
    return:
      type: Apizr.Configuring.ApizrConfigurationSource
- uid: Apizr.Configuring.ApizrConfigurationSource.RequestAttribute
  commentId: F:Apizr.Configuring.ApizrConfigurationSource.RequestAttribute
  id: RequestAttribute
  parent: Apizr.Configuring.ApizrConfigurationSource
  langs:
  - csharp
  - vb
  name: RequestAttribute
  nameWithType: ApizrConfigurationSource.RequestAttribute
  fullName: Apizr.Configuring.ApizrConfigurationSource.RequestAttribute
  type: Field
  source:
    remote:
      path: Apizr/Src/Apizr/Configuring/ApizrConfigurationSource.cs
      branch: lab
      repo: https://github.com/Respawnsive/Apizr.git
    id: RequestAttribute
    path: ../../Src/Apizr/Configuring/ApizrConfigurationSource.cs
    startLine: 10
  assemblies:
  - Apizr
  namespace: Apizr.Configuring
  syntax:
    content: RequestAttribute = 6
    return:
      type: Apizr.Configuring.ApizrConfigurationSource
- uid: Apizr.Configuring.ApizrConfigurationSource.RequestOption
  commentId: F:Apizr.Configuring.ApizrConfigurationSource.RequestOption
  id: RequestOption
  parent: Apizr.Configuring.ApizrConfigurationSource
  langs:
  - csharp
  - vb
  name: RequestOption
  nameWithType: ApizrConfigurationSource.RequestOption
  fullName: Apizr.Configuring.ApizrConfigurationSource.RequestOption
  type: Field
  source:
    remote:
      path: Apizr/Src/Apizr/Configuring/ApizrConfigurationSource.cs
      branch: lab
      repo: https://github.com/Respawnsive/Apizr.git
    id: RequestOption
    path: ../../Src/Apizr/Configuring/ApizrConfigurationSource.cs
    startLine: 11
  assemblies:
  - Apizr
  namespace: Apizr.Configuring
  syntax:
    content: RequestOption = 7
    return:
      type: Apizr.Configuring.ApizrConfigurationSource
- uid: Apizr.Configuring.ApizrConfigurationSource.FinalConfiguration
  commentId: F:Apizr.Configuring.ApizrConfigurationSource.FinalConfiguration
  id: FinalConfiguration
  parent: Apizr.Configuring.ApizrConfigurationSource
  langs:
  - csharp
  - vb
  name: FinalConfiguration
  nameWithType: ApizrConfigurationSource.FinalConfiguration
  fullName: Apizr.Configuring.ApizrConfigurationSource.FinalConfiguration
  type: Field
  source:
    remote:
      path: Apizr/Src/Apizr/Configuring/ApizrConfigurationSource.cs
      branch: lab
      repo: https://github.com/Respawnsive/Apizr.git
    id: FinalConfiguration
    path: ../../Src/Apizr/Configuring/ApizrConfigurationSource.cs
    startLine: 12
  assemblies:
  - Apizr
  namespace: Apizr.Configuring
  syntax:
    content: FinalConfiguration = 8
    return:
      type: Apizr.Configuring.ApizrConfigurationSource
references:
- uid: Apizr.Configuring
  commentId: N:Apizr.Configuring
  href: Apizr.html
  name: Apizr.Configuring
  nameWithType: Apizr.Configuring
  fullName: Apizr.Configuring
  spec.csharp:
  - uid: Apizr
    name: Apizr
    href: Apizr.html
  - name: .
  - uid: Apizr.Configuring
    name: Configuring
    href: Apizr.Configuring.html
  spec.vb:
  - uid: Apizr
    name: Apizr
    href: Apizr.html
  - name: .
  - uid: Apizr.Configuring
    name: Configuring
    href: Apizr.Configuring.html
- uid: Apizr.Configuring.ApizrConfigurationSource
  commentId: T:Apizr.Configuring.ApizrConfigurationSource
  parent: Apizr.Configuring
  href: Apizr.Configuring.ApizrConfigurationSource.html
  name: ApizrConfigurationSource
  nameWithType: ApizrConfigurationSource
  fullName: Apizr.Configuring.ApizrConfigurationSource
