### YamlMime:ManagedReference
items:
- uid: Apizr.Configuring.Shared.Context
  commentId: N:Apizr.Configuring.Shared.Context
  id: Apizr.Configuring.Shared.Context
  children:
  - Apizr.Configuring.Shared.Context.ApizrResilienceContextOptions
  - Apizr.Configuring.Shared.Context.ApizrResilienceContextOptionsBuilder
  - Apizr.Configuring.Shared.Context.IApizrResilienceContextOptions
  - Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder
  langs:
  - csharp
  - vb
  name: Apizr.Configuring.Shared.Context
  nameWithType: Apizr.Configuring.Shared.Context
  fullName: Apizr.Configuring.Shared.Context
  type: Namespace
  assemblies:
  - Apizr
references:
- uid: Apizr.Configuring.Shared.Context.ApizrResilienceContextOptions
  commentId: T:Apizr.Configuring.Shared.Context.ApizrResilienceContextOptions
  parent: Apizr.Configuring.Shared.Context
  name: ApizrResilienceContextOptions
  nameWithType: ApizrResilienceContextOptions
  fullName: Apizr.Configuring.Shared.Context.ApizrResilienceContextOptions
- uid: Apizr.Configuring.Shared.Context.ApizrResilienceContextOptionsBuilder
  commentId: T:Apizr.Configuring.Shared.Context.ApizrResilienceContextOptionsBuilder
  name: ApizrResilienceContextOptionsBuilder
  nameWithType: ApizrResilienceContextOptionsBuilder
  fullName: Apizr.Configuring.Shared.Context.ApizrResilienceContextOptionsBuilder
- uid: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptions
  commentId: T:Apizr.Configuring.Shared.Context.IApizrResilienceContextOptions
  parent: Apizr.Configuring.Shared.Context
  name: IApizrResilienceContextOptions
  nameWithType: IApizrResilienceContextOptions
  fullName: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptions
- uid: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder
  commentId: T:Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder
  parent: Apizr.Configuring.Shared.Context
  name: IApizrResilienceContextOptionsBuilder
  nameWithType: IApizrResilienceContextOptionsBuilder
  fullName: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder
- uid: Apizr.Configuring.Shared.Context
  commentId: N:Apizr.Configuring.Shared.Context
  name: Apizr.Configuring.Shared.Context
  nameWithType: Apizr.Configuring.Shared.Context
  fullName: Apizr.Configuring.Shared.Context
