### YamlMime:ManagedReference
items:
- uid: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase
  commentId: T:Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase
  id: IApizrExtendedManagerOptionsBuilderBase
  parent: Apizr.Extending.Configuring.Manager
  children: []
  langs:
  - csharp
  - vb
  name: IApizrExtendedManagerOptionsBuilderBase
  nameWithType: IApizrExtendedManagerOptionsBuilderBase
  fullName: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase
  type: Interface
  source:
    remote:
      path: Apizr/Src/Apizr.Extensions.Microsoft.DependencyInjection/Extending/Configuring/Manager/IApizrExtendedManagerOptionsBuilderBase.cs
      branch: dev
      repo: https://github.com/Respawnsive/Apizr.git
    id: IApizrExtendedManagerOptionsBuilderBase
    path: ../../Src/Apizr.Extensions.Microsoft.DependencyInjection/Extending/Configuring/Manager/IApizrExtendedManagerOptionsBuilderBase.cs
    startLine: 9
  assemblies:
  - Apizr.Extensions.Microsoft.DependencyInjection
  namespace: Apizr.Extending.Configuring.Manager
  summary: Builder options available for extended registrations
  example: []
  syntax:
    content: 'public interface IApizrExtendedManagerOptionsBuilderBase : IApizrExtendedCommonOptionsBuilderBase, IApizrExtendedProperOptionsBuilderBase, IApizrGlobalManagerOptionsBuilderBase, IApizrGlobalCommonOptionsBuilderBase, IApizrGlobalProperOptionsBuilderBase, IApizrGlobalSharedRegistrationOptionsBuilderBase, IApizrGlobalSharedOptionsBuilderBase'
    content.vb: Public Interface IApizrExtendedManagerOptionsBuilderBase Inherits IApizrExtendedCommonOptionsBuilderBase, IApizrExtendedProperOptionsBuilderBase, IApizrGlobalManagerOptionsBuilderBase, IApizrGlobalCommonOptionsBuilderBase, IApizrGlobalProperOptionsBuilderBase, IApizrGlobalSharedRegistrationOptionsBuilderBase, IApizrGlobalSharedOptionsBuilderBase
  extensionMethods:
  - Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase.Apizr.MicrosoftCachingOptionsBuilderExtensions.WithDistributedCacheHandler``2
  - Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase.Apizr.MicrosoftCachingOptionsBuilderExtensions.WithInMemoryCacheHandler``1
references:
- uid: Apizr.Extending.Configuring.Manager
  commentId: N:Apizr.Extending.Configuring.Manager
  href: Apizr.html
  name: Apizr.Extending.Configuring.Manager
  nameWithType: Apizr.Extending.Configuring.Manager
  fullName: Apizr.Extending.Configuring.Manager
  spec.csharp:
  - uid: Apizr
    name: Apizr
    href: Apizr.html
  - name: .
  - uid: Apizr.Extending
    name: Extending
    href: Apizr.Extending.html
  - name: .
  - uid: Apizr.Extending.Configuring
    name: Configuring
    href: Apizr.Extending.Configuring.html
  - name: .
  - uid: Apizr.Extending.Configuring.Manager
    name: Manager
    href: Apizr.Extending.Configuring.Manager.html
  spec.vb:
  - uid: Apizr
    name: Apizr
    href: Apizr.html
  - name: .
  - uid: Apizr.Extending
    name: Extending
    href: Apizr.Extending.html
  - name: .
  - uid: Apizr.Extending.Configuring
    name: Configuring
    href: Apizr.Extending.Configuring.html
  - name: .
  - uid: Apizr.Extending.Configuring.Manager
    name: Manager
    href: Apizr.Extending.Configuring.Manager.html
- uid: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase.Apizr.MicrosoftCachingOptionsBuilderExtensions.WithDistributedCacheHandler``2
  commentId: M:Apizr.MicrosoftCachingOptionsBuilderExtensions.WithDistributedCacheHandler``2(``0)
  parent: Apizr.MicrosoftCachingOptionsBuilderExtensions
  definition: Apizr.MicrosoftCachingOptionsBuilderExtensions.WithDistributedCacheHandler``2(``0)
  href: Apizr.MicrosoftCachingOptionsBuilderExtensions.html#Apizr_MicrosoftCachingOptionsBuilderExtensions_WithDistributedCacheHandler__2___0_
  name: WithDistributedCacheHandler<IApizrExtendedManagerOptionsBuilderBase, TCache>(IApizrExtendedManagerOptionsBuilderBase)
  nameWithType: MicrosoftCachingOptionsBuilderExtensions.WithDistributedCacheHandler<IApizrExtendedManagerOptionsBuilderBase, TCache>(IApizrExtendedManagerOptionsBuilderBase)
  fullName: Apizr.MicrosoftCachingOptionsBuilderExtensions.WithDistributedCacheHandler<Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase, TCache>(Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase)
  nameWithType.vb: MicrosoftCachingOptionsBuilderExtensions.WithDistributedCacheHandler(Of IApizrExtendedManagerOptionsBuilderBase, TCache)(IApizrExtendedManagerOptionsBuilderBase)
  fullName.vb: Apizr.MicrosoftCachingOptionsBuilderExtensions.WithDistributedCacheHandler(Of Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase, TCache)(Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase)
  name.vb: WithDistributedCacheHandler(Of IApizrExtendedManagerOptionsBuilderBase, TCache)(IApizrExtendedManagerOptionsBuilderBase)
  spec.csharp:
  - uid: Apizr.MicrosoftCachingOptionsBuilderExtensions.WithDistributedCacheHandler``2(Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase)
    name: WithDistributedCacheHandler
    href: Apizr.MicrosoftCachingOptionsBuilderExtensions.html#Apizr_MicrosoftCachingOptionsBuilderExtensions_WithDistributedCacheHandler__2___0_
  - name: <
  - uid: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase
    name: IApizrExtendedManagerOptionsBuilderBase
    href: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase.html
  - name: ','
  - name: " "
  - name: TCache
  - name: '>'
  - name: (
  - uid: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase
    name: IApizrExtendedManagerOptionsBuilderBase
    href: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase.html
  - name: )
  spec.vb:
  - uid: Apizr.MicrosoftCachingOptionsBuilderExtensions.WithDistributedCacheHandler``2(Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase)
    name: WithDistributedCacheHandler
    href: Apizr.MicrosoftCachingOptionsBuilderExtensions.html#Apizr_MicrosoftCachingOptionsBuilderExtensions_WithDistributedCacheHandler__2___0_
  - name: (
  - name: Of
  - name: " "
  - uid: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase
    name: IApizrExtendedManagerOptionsBuilderBase
    href: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase.html
  - name: ','
  - name: " "
  - name: TCache
  - name: )
  - name: (
  - uid: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase
    name: IApizrExtendedManagerOptionsBuilderBase
    href: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase.html
  - name: )
- uid: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase.Apizr.MicrosoftCachingOptionsBuilderExtensions.WithInMemoryCacheHandler``1
  commentId: M:Apizr.MicrosoftCachingOptionsBuilderExtensions.WithInMemoryCacheHandler``1(``0)
  parent: Apizr.MicrosoftCachingOptionsBuilderExtensions
  definition: Apizr.MicrosoftCachingOptionsBuilderExtensions.WithInMemoryCacheHandler``1(``0)
  href: Apizr.MicrosoftCachingOptionsBuilderExtensions.html#Apizr_MicrosoftCachingOptionsBuilderExtensions_WithInMemoryCacheHandler__1___0_
  name: WithInMemoryCacheHandler<IApizrExtendedManagerOptionsBuilderBase>(IApizrExtendedManagerOptionsBuilderBase)
  nameWithType: MicrosoftCachingOptionsBuilderExtensions.WithInMemoryCacheHandler<IApizrExtendedManagerOptionsBuilderBase>(IApizrExtendedManagerOptionsBuilderBase)
  fullName: Apizr.MicrosoftCachingOptionsBuilderExtensions.WithInMemoryCacheHandler<Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase>(Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase)
  nameWithType.vb: MicrosoftCachingOptionsBuilderExtensions.WithInMemoryCacheHandler(Of IApizrExtendedManagerOptionsBuilderBase)(IApizrExtendedManagerOptionsBuilderBase)
  fullName.vb: Apizr.MicrosoftCachingOptionsBuilderExtensions.WithInMemoryCacheHandler(Of Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase)(Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase)
  name.vb: WithInMemoryCacheHandler(Of IApizrExtendedManagerOptionsBuilderBase)(IApizrExtendedManagerOptionsBuilderBase)
  spec.csharp:
  - uid: Apizr.MicrosoftCachingOptionsBuilderExtensions.WithInMemoryCacheHandler``1(Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase)
    name: WithInMemoryCacheHandler
    href: Apizr.MicrosoftCachingOptionsBuilderExtensions.html#Apizr_MicrosoftCachingOptionsBuilderExtensions_WithInMemoryCacheHandler__1___0_
  - name: <
  - uid: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase
    name: IApizrExtendedManagerOptionsBuilderBase
    href: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase.html
  - name: '>'
  - name: (
  - uid: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase
    name: IApizrExtendedManagerOptionsBuilderBase
    href: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase.html
  - name: )
  spec.vb:
  - uid: Apizr.MicrosoftCachingOptionsBuilderExtensions.WithInMemoryCacheHandler``1(Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase)
    name: WithInMemoryCacheHandler
    href: Apizr.MicrosoftCachingOptionsBuilderExtensions.html#Apizr_MicrosoftCachingOptionsBuilderExtensions_WithInMemoryCacheHandler__1___0_
  - name: (
  - name: Of
  - name: " "
  - uid: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase
    name: IApizrExtendedManagerOptionsBuilderBase
    href: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase.html
  - name: )
  - name: (
  - uid: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase
    name: IApizrExtendedManagerOptionsBuilderBase
    href: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase.html
  - name: )
- uid: Apizr.MicrosoftCachingOptionsBuilderExtensions.WithDistributedCacheHandler``2(``0)
  commentId: M:Apizr.MicrosoftCachingOptionsBuilderExtensions.WithDistributedCacheHandler``2(``0)
  href: Apizr.MicrosoftCachingOptionsBuilderExtensions.html#Apizr_MicrosoftCachingOptionsBuilderExtensions_WithDistributedCacheHandler__2___0_
  name: WithDistributedCacheHandler<TBuilder, TCache>(TBuilder)
  nameWithType: MicrosoftCachingOptionsBuilderExtensions.WithDistributedCacheHandler<TBuilder, TCache>(TBuilder)
  fullName: Apizr.MicrosoftCachingOptionsBuilderExtensions.WithDistributedCacheHandler<TBuilder, TCache>(TBuilder)
  nameWithType.vb: MicrosoftCachingOptionsBuilderExtensions.WithDistributedCacheHandler(Of TBuilder, TCache)(TBuilder)
  fullName.vb: Apizr.MicrosoftCachingOptionsBuilderExtensions.WithDistributedCacheHandler(Of TBuilder, TCache)(TBuilder)
  name.vb: WithDistributedCacheHandler(Of TBuilder, TCache)(TBuilder)
  spec.csharp:
  - uid: Apizr.MicrosoftCachingOptionsBuilderExtensions.WithDistributedCacheHandler``2(``0)
    name: WithDistributedCacheHandler
    href: Apizr.MicrosoftCachingOptionsBuilderExtensions.html#Apizr_MicrosoftCachingOptionsBuilderExtensions_WithDistributedCacheHandler__2___0_
  - name: <
  - name: TBuilder
  - name: ','
  - name: " "
  - name: TCache
  - name: '>'
  - name: (
  - name: TBuilder
  - name: )
  spec.vb:
  - uid: Apizr.MicrosoftCachingOptionsBuilderExtensions.WithDistributedCacheHandler``2(``0)
    name: WithDistributedCacheHandler
    href: Apizr.MicrosoftCachingOptionsBuilderExtensions.html#Apizr_MicrosoftCachingOptionsBuilderExtensions_WithDistributedCacheHandler__2___0_
  - name: (
  - name: Of
  - name: " "
  - name: TBuilder
  - name: ','
  - name: " "
  - name: TCache
  - name: )
  - name: (
  - name: TBuilder
  - name: )
- uid: Apizr.MicrosoftCachingOptionsBuilderExtensions
  commentId: T:Apizr.MicrosoftCachingOptionsBuilderExtensions
  parent: Apizr
  href: Apizr.MicrosoftCachingOptionsBuilderExtensions.html
  name: MicrosoftCachingOptionsBuilderExtensions
  nameWithType: MicrosoftCachingOptionsBuilderExtensions
  fullName: Apizr.MicrosoftCachingOptionsBuilderExtensions
- uid: Apizr.MicrosoftCachingOptionsBuilderExtensions.WithInMemoryCacheHandler``1(``0)
  commentId: M:Apizr.MicrosoftCachingOptionsBuilderExtensions.WithInMemoryCacheHandler``1(``0)
  href: Apizr.MicrosoftCachingOptionsBuilderExtensions.html#Apizr_MicrosoftCachingOptionsBuilderExtensions_WithInMemoryCacheHandler__1___0_
  name: WithInMemoryCacheHandler<TBuilder>(TBuilder)
  nameWithType: MicrosoftCachingOptionsBuilderExtensions.WithInMemoryCacheHandler<TBuilder>(TBuilder)
  fullName: Apizr.MicrosoftCachingOptionsBuilderExtensions.WithInMemoryCacheHandler<TBuilder>(TBuilder)
  nameWithType.vb: MicrosoftCachingOptionsBuilderExtensions.WithInMemoryCacheHandler(Of TBuilder)(TBuilder)
  fullName.vb: Apizr.MicrosoftCachingOptionsBuilderExtensions.WithInMemoryCacheHandler(Of TBuilder)(TBuilder)
  name.vb: WithInMemoryCacheHandler(Of TBuilder)(TBuilder)
  spec.csharp:
  - uid: Apizr.MicrosoftCachingOptionsBuilderExtensions.WithInMemoryCacheHandler``1(``0)
    name: WithInMemoryCacheHandler
    href: Apizr.MicrosoftCachingOptionsBuilderExtensions.html#Apizr_MicrosoftCachingOptionsBuilderExtensions_WithInMemoryCacheHandler__1___0_
  - name: <
  - name: TBuilder
  - name: '>'
  - name: (
  - name: TBuilder
  - name: )
  spec.vb:
  - uid: Apizr.MicrosoftCachingOptionsBuilderExtensions.WithInMemoryCacheHandler``1(``0)
    name: WithInMemoryCacheHandler
    href: Apizr.MicrosoftCachingOptionsBuilderExtensions.html#Apizr_MicrosoftCachingOptionsBuilderExtensions_WithInMemoryCacheHandler__1___0_
  - name: (
  - name: Of
  - name: " "
  - name: TBuilder
  - name: )
  - name: (
  - name: TBuilder
  - name: )
- uid: Apizr
  commentId: N:Apizr
  href: Apizr.html
  name: Apizr
  nameWithType: Apizr
  fullName: Apizr
