### YamlMime:ManagedReference
items:
- uid: Apizr.Extending.Configuring.Shared
  commentId: N:Apizr.Extending.Configuring.Shared
  id: Apizr.Extending.Configuring.Shared
  children:
  - Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptions
  - Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptionsBase
  - Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptionsBuilder`2
  langs:
  - csharp
  - vb
  name: Apizr.Extending.Configuring.Shared
  nameWithType: Apizr.Extending.Configuring.Shared
  fullName: Apizr.Extending.Configuring.Shared
  type: Namespace
  assemblies:
  - Apizr.Extensions.Microsoft.DependencyInjection
references:
- uid: Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptions
  commentId: T:Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptions
  parent: Apizr.Extending.Configuring.Shared
  href: Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptions.html
  name: IApizrExtendedSharedOptions
  nameWithType: IApizrExtendedSharedOptions
  fullName: Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptions
- uid: Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptionsBase
  commentId: T:Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptionsBase
  parent: Apizr.Extending.Configuring.Shared
  href: Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptionsBase.html
  name: IApizrExtendedSharedOptionsBase
  nameWithType: IApizrExtendedSharedOptionsBase
  fullName: Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptionsBase
- uid: Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptionsBuilder`2
  commentId: T:Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptionsBuilder`2
  href: Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptionsBuilder-2.html
  name: IApizrExtendedSharedOptionsBuilder<TApizrExtendedSharedOptions, TApizrExtendedSharedOptionsBuilder>
  nameWithType: IApizrExtendedSharedOptionsBuilder<TApizrExtendedSharedOptions, TApizrExtendedSharedOptionsBuilder>
  fullName: Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptionsBuilder<TApizrExtendedSharedOptions, TApizrExtendedSharedOptionsBuilder>
  nameWithType.vb: IApizrExtendedSharedOptionsBuilder(Of TApizrExtendedSharedOptions, TApizrExtendedSharedOptionsBuilder)
  fullName.vb: Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptionsBuilder(Of TApizrExtendedSharedOptions, TApizrExtendedSharedOptionsBuilder)
  name.vb: IApizrExtendedSharedOptionsBuilder(Of TApizrExtendedSharedOptions, TApizrExtendedSharedOptionsBuilder)
  spec.csharp:
  - uid: Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptionsBuilder`2
    name: IApizrExtendedSharedOptionsBuilder
    href: Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptionsBuilder-2.html
  - name: <
  - name: TApizrExtendedSharedOptions
  - name: ','
  - name: " "
  - name: TApizrExtendedSharedOptionsBuilder
  - name: '>'
  spec.vb:
  - uid: Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptionsBuilder`2
    name: IApizrExtendedSharedOptionsBuilder
    href: Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptionsBuilder-2.html
  - name: (
  - name: Of
  - name: " "
  - name: TApizrExtendedSharedOptions
  - name: ','
  - name: " "
  - name: TApizrExtendedSharedOptionsBuilder
  - name: )
- uid: Apizr.Extending.Configuring.Shared
  commentId: N:Apizr.Extending.Configuring.Shared
  href: Apizr.html
  name: Apizr.Extending.Configuring.Shared
  nameWithType: Apizr.Extending.Configuring.Shared
  fullName: Apizr.Extending.Configuring.Shared
  spec.csharp:
  - uid: Apizr
    name: Apizr
    href: Apizr.html
  - name: .
  - uid: Apizr.Extending
    name: Extending
    href: Apizr.Extending.html
  - name: .
  - uid: Apizr.Extending.Configuring
    name: Configuring
    href: Apizr.Extending.Configuring.html
  - name: .
  - uid: Apizr.Extending.Configuring.Shared
    name: Shared
    href: Apizr.Extending.Configuring.Shared.html
  spec.vb:
  - uid: Apizr
    name: Apizr
    href: Apizr.html
  - name: .
  - uid: Apizr.Extending
    name: Extending
    href: Apizr.Extending.html
  - name: .
  - uid: Apizr.Extending.Configuring
    name: Configuring
    href: Apizr.Extending.Configuring.html
  - name: .
  - uid: Apizr.Extending.Configuring.Shared
    name: Shared
    href: Apizr.Extending.Configuring.Shared.html
