### YamlMime:ManagedReference
items:
- uid: Apizr.Configuring.Shared.IApizrSharedOptionsBase
  commentId: T:Apizr.Configuring.Shared.IApizrSharedOptionsBase
  id: IApizrSharedOptionsBase
  parent: Apizr.Configuring.Shared
  children:
  - Apizr.Configuring.Shared.IApizrSharedOptionsBase.HttpTracerMode
  - Apizr.Configuring.Shared.IApizrSharedOptionsBase.LogLevel
  - Apizr.Configuring.Shared.IApizrSharedOptionsBase.TrafficVerbosity
  langs:
  - csharp
  - vb
  name: IApizrSharedOptionsBase
  nameWithType: IApizrSharedOptionsBase
  fullName: Apizr.Configuring.Shared.IApizrSharedOptionsBase
  type: Interface
  source:
    remote:
      path: Apizr/Apizr/Configuring/Shared/IApizrSharedOptionsBase.cs
      branch: lab
      repo: https://github.com/Respawnsive/Apizr.git
    id: IApizrSharedOptionsBase
    path: ../../Apizr/Configuring/Shared/IApizrSharedOptionsBase.cs
    startLine: 5
  assemblies:
  - Apizr
  namespace: Apizr.Configuring.Shared
  syntax:
    content: public interface IApizrSharedOptionsBase
    content.vb: Public Interface IApizrSharedOptionsBase
  extensionMethods:
  - System.Object.Apizr.Extending.ObjectExtensions.ToString(System.String,System.String)
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Apizr.Configuring.Shared.IApizrSharedOptionsBase.HttpTracerMode
  commentId: P:Apizr.Configuring.Shared.IApizrSharedOptionsBase.HttpTracerMode
  id: HttpTracerMode
  parent: Apizr.Configuring.Shared.IApizrSharedOptionsBase
  langs:
  - csharp
  - vb
  name: HttpTracerMode
  nameWithType: IApizrSharedOptionsBase.HttpTracerMode
  fullName: Apizr.Configuring.Shared.IApizrSharedOptionsBase.HttpTracerMode
  type: Property
  source:
    remote:
      path: Apizr/Apizr/Configuring/Shared/IApizrSharedOptionsBase.cs
      branch: lab
      repo: https://github.com/Respawnsive/Apizr.git
    id: HttpTracerMode
    path: ../../Apizr/Configuring/Shared/IApizrSharedOptionsBase.cs
    startLine: 10
  assemblies:
  - Apizr
  namespace: Apizr.Configuring.Shared
  summary: "\nHttp traffic tracing mode\n"
  example: []
  syntax:
    content: HttpTracerMode HttpTracerMode { get; }
    parameters: []
    return:
      type: Apizr.Logging.HttpTracerMode
    content.vb: ReadOnly Property HttpTracerMode As HttpTracerMode
  overload: Apizr.Configuring.Shared.IApizrSharedOptionsBase.HttpTracerMode*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: Apizr.Configuring.Shared.IApizrSharedOptionsBase.TrafficVerbosity
  commentId: P:Apizr.Configuring.Shared.IApizrSharedOptionsBase.TrafficVerbosity
  id: TrafficVerbosity
  parent: Apizr.Configuring.Shared.IApizrSharedOptionsBase
  langs:
  - csharp
  - vb
  name: TrafficVerbosity
  nameWithType: IApizrSharedOptionsBase.TrafficVerbosity
  fullName: Apizr.Configuring.Shared.IApizrSharedOptionsBase.TrafficVerbosity
  type: Property
  source:
    remote:
      path: Apizr/Apizr/Configuring/Shared/IApizrSharedOptionsBase.cs
      branch: lab
      repo: https://github.com/Respawnsive/Apizr.git
    id: TrafficVerbosity
    path: ../../Apizr/Configuring/Shared/IApizrSharedOptionsBase.cs
    startLine: 15
  assemblies:
  - Apizr
  namespace: Apizr.Configuring.Shared
  summary: "\nHttp traffic tracing verbosity\n"
  example: []
  syntax:
    content: HttpMessageParts TrafficVerbosity { get; }
    parameters: []
    return:
      type: Apizr.Logging.HttpMessageParts
    content.vb: ReadOnly Property TrafficVerbosity As HttpMessageParts
  overload: Apizr.Configuring.Shared.IApizrSharedOptionsBase.TrafficVerbosity*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: Apizr.Configuring.Shared.IApizrSharedOptionsBase.LogLevel
  commentId: P:Apizr.Configuring.Shared.IApizrSharedOptionsBase.LogLevel
  id: LogLevel
  parent: Apizr.Configuring.Shared.IApizrSharedOptionsBase
  langs:
  - csharp
  - vb
  name: LogLevel
  nameWithType: IApizrSharedOptionsBase.LogLevel
  fullName: Apizr.Configuring.Shared.IApizrSharedOptionsBase.LogLevel
  type: Property
  source:
    remote:
      path: Apizr/Apizr/Configuring/Shared/IApizrSharedOptionsBase.cs
      branch: lab
      repo: https://github.com/Respawnsive/Apizr.git
    id: LogLevel
    path: ../../Apizr/Configuring/Shared/IApizrSharedOptionsBase.cs
    startLine: 20
  assemblies:
  - Apizr
  namespace: Apizr.Configuring.Shared
  summary: "\nLog level while writing\n"
  example: []
  syntax:
    content: LogLevel LogLevel { get; }
    parameters: []
    return:
      type: Microsoft.Extensions.Logging.LogLevel
    content.vb: ReadOnly Property LogLevel As LogLevel
  overload: Apizr.Configuring.Shared.IApizrSharedOptionsBase.LogLevel*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
references:
- uid: Apizr.Configuring.Shared
  commentId: N:Apizr.Configuring.Shared
  name: Apizr.Configuring.Shared
  nameWithType: Apizr.Configuring.Shared
  fullName: Apizr.Configuring.Shared
- uid: System.Object.Apizr.Extending.ObjectExtensions.ToString(System.String,System.String)
  commentId: M:Apizr.Extending.ObjectExtensions.ToString(System.Object,System.String,System.String)
  parent: Apizr.Extending.ObjectExtensions
  definition: Apizr.Extending.ObjectExtensions.ToString(System.Object,System.String,System.String)
  name: ToString(String, String)
  nameWithType: ObjectExtensions.ToString(String, String)
  fullName: Apizr.Extending.ObjectExtensions.ToString(System.String, System.String)
  spec.csharp:
  - uid: Apizr.Extending.ObjectExtensions.ToString(System.String,System.String)
    name: ToString
    nameWithType: ObjectExtensions.ToString
    fullName: Apizr.Extending.ObjectExtensions.ToString
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Apizr.Extending.ObjectExtensions.ToString(System.String,System.String)
    name: ToString
    nameWithType: ObjectExtensions.ToString
    fullName: Apizr.Extending.ObjectExtensions.ToString
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Apizr.Extending.ObjectExtensions.ToString(System.Object,System.String,System.String)
  commentId: M:Apizr.Extending.ObjectExtensions.ToString(System.Object,System.String,System.String)
  isExternal: true
  name: ToString(Object, String, String)
  nameWithType: ObjectExtensions.ToString(Object, String, String)
  fullName: Apizr.Extending.ObjectExtensions.ToString(System.Object, System.String, System.String)
  spec.csharp:
  - uid: Apizr.Extending.ObjectExtensions.ToString(System.Object,System.String,System.String)
    name: ToString
    nameWithType: ObjectExtensions.ToString
    fullName: Apizr.Extending.ObjectExtensions.ToString
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Apizr.Extending.ObjectExtensions.ToString(System.Object,System.String,System.String)
    name: ToString
    nameWithType: ObjectExtensions.ToString
    fullName: Apizr.Extending.ObjectExtensions.ToString
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Apizr.Extending.ObjectExtensions
  commentId: T:Apizr.Extending.ObjectExtensions
  parent: Apizr.Extending
  name: ObjectExtensions
  nameWithType: ObjectExtensions
  fullName: Apizr.Extending.ObjectExtensions
- uid: Apizr.Extending
  commentId: N:Apizr.Extending
  name: Apizr.Extending
  nameWithType: Apizr.Extending
  fullName: Apizr.Extending
- uid: Apizr.Configuring.Shared.IApizrSharedOptionsBase.HttpTracerMode*
  commentId: Overload:Apizr.Configuring.Shared.IApizrSharedOptionsBase.HttpTracerMode
  name: HttpTracerMode
  nameWithType: IApizrSharedOptionsBase.HttpTracerMode
  fullName: Apizr.Configuring.Shared.IApizrSharedOptionsBase.HttpTracerMode
- uid: Apizr.Logging.HttpTracerMode
  commentId: T:Apizr.Logging.HttpTracerMode
  parent: Apizr.Logging
  name: HttpTracerMode
  nameWithType: HttpTracerMode
  fullName: Apizr.Logging.HttpTracerMode
- uid: Apizr.Logging
  commentId: N:Apizr.Logging
  name: Apizr.Logging
  nameWithType: Apizr.Logging
  fullName: Apizr.Logging
- uid: Apizr.Configuring.Shared.IApizrSharedOptionsBase.TrafficVerbosity*
  commentId: Overload:Apizr.Configuring.Shared.IApizrSharedOptionsBase.TrafficVerbosity
  name: TrafficVerbosity
  nameWithType: IApizrSharedOptionsBase.TrafficVerbosity
  fullName: Apizr.Configuring.Shared.IApizrSharedOptionsBase.TrafficVerbosity
- uid: Apizr.Logging.HttpMessageParts
  commentId: T:Apizr.Logging.HttpMessageParts
  parent: Apizr.Logging
  name: HttpMessageParts
  nameWithType: HttpMessageParts
  fullName: Apizr.Logging.HttpMessageParts
- uid: Apizr.Configuring.Shared.IApizrSharedOptionsBase.LogLevel*
  commentId: Overload:Apizr.Configuring.Shared.IApizrSharedOptionsBase.LogLevel
  name: LogLevel
  nameWithType: IApizrSharedOptionsBase.LogLevel
  fullName: Apizr.Configuring.Shared.IApizrSharedOptionsBase.LogLevel
- uid: Microsoft.Extensions.Logging.LogLevel
  commentId: T:Microsoft.Extensions.Logging.LogLevel
  parent: Microsoft.Extensions.Logging
  isExternal: true
  name: LogLevel
  nameWithType: LogLevel
  fullName: Microsoft.Extensions.Logging.LogLevel
- uid: Microsoft.Extensions.Logging
  commentId: N:Microsoft.Extensions.Logging
  isExternal: true
  name: Microsoft.Extensions.Logging
  nameWithType: Microsoft.Extensions.Logging
  fullName: Microsoft.Extensions.Logging
