### YamlMime:ManagedReference
items:
- uid: Apizr.Configuring.Common
  commentId: N:Apizr.Configuring.Common
  id: Apizr.Configuring.Common
  children:
  - Apizr.Configuring.Common.ApizrCommonOptions
  - Apizr.Configuring.Common.ApizrCommonOptionsBase
  - Apizr.Configuring.Common.ApizrCommonOptionsBuilder
  - Apizr.Configuring.Common.IApizrCommonOptions
  - Apizr.Configuring.Common.IApizrCommonOptionsBase
  - Apizr.Configuring.Common.IApizrCommonOptionsBuilder
  - Apizr.Configuring.Common.IApizrCommonOptionsBuilderBase
  - Apizr.Configuring.Common.IApizrCommonOptionsBuilderBase`2
  - Apizr.Configuring.Common.IApizrCommonOptionsBuilder`2
  - Apizr.Configuring.Common.IApizrExtendedCommonOptionsBuilderBase
  - Apizr.Configuring.Common.IApizrGlobalCommonOptionsBuilderBase
  - Apizr.Configuring.Common.IApizrGlobalCommonOptionsBuilderBase`2
  langs:
  - csharp
  - vb
  name: Apizr.Configuring.Common
  nameWithType: Apizr.Configuring.Common
  fullName: Apizr.Configuring.Common
  type: Namespace
  assemblies:
  - Apizr
references:
- uid: Apizr.Configuring.Common.ApizrCommonOptions
  commentId: T:Apizr.Configuring.Common.ApizrCommonOptions
  parent: Apizr.Configuring.Common
  href: Apizr.Configuring.Common.ApizrCommonOptions.html
  name: ApizrCommonOptions
  nameWithType: ApizrCommonOptions
  fullName: Apizr.Configuring.Common.ApizrCommonOptions
- uid: Apizr.Configuring.Common.ApizrCommonOptionsBase
  commentId: T:Apizr.Configuring.Common.ApizrCommonOptionsBase
  parent: Apizr.Configuring.Common
  href: Apizr.Configuring.Common.ApizrCommonOptionsBase.html
  name: ApizrCommonOptionsBase
  nameWithType: ApizrCommonOptionsBase
  fullName: Apizr.Configuring.Common.ApizrCommonOptionsBase
- uid: Apizr.Configuring.Common.ApizrCommonOptionsBuilder
  commentId: T:Apizr.Configuring.Common.ApizrCommonOptionsBuilder
  href: Apizr.Configuring.Common.ApizrCommonOptionsBuilder.html
  name: ApizrCommonOptionsBuilder
  nameWithType: ApizrCommonOptionsBuilder
  fullName: Apizr.Configuring.Common.ApizrCommonOptionsBuilder
- uid: Apizr.Configuring.Common.IApizrCommonOptions
  commentId: T:Apizr.Configuring.Common.IApizrCommonOptions
  parent: Apizr.Configuring.Common
  href: Apizr.Configuring.Common.IApizrCommonOptions.html
  name: IApizrCommonOptions
  nameWithType: IApizrCommonOptions
  fullName: Apizr.Configuring.Common.IApizrCommonOptions
- uid: Apizr.Configuring.Common.IApizrCommonOptionsBase
  commentId: T:Apizr.Configuring.Common.IApizrCommonOptionsBase
  parent: Apizr.Configuring.Common
  href: Apizr.Configuring.Common.IApizrCommonOptionsBase.html
  name: IApizrCommonOptionsBase
  nameWithType: IApizrCommonOptionsBase
  fullName: Apizr.Configuring.Common.IApizrCommonOptionsBase
- uid: Apizr.Configuring.Common.IApizrCommonOptionsBuilder`2
  commentId: T:Apizr.Configuring.Common.IApizrCommonOptionsBuilder`2
  href: Apizr.Configuring.Common.IApizrCommonOptionsBuilder-2.html
  name: IApizrCommonOptionsBuilder<TApizrCommonOptions, TApizrCommonOptionsBuilder>
  nameWithType: IApizrCommonOptionsBuilder<TApizrCommonOptions, TApizrCommonOptionsBuilder>
  fullName: Apizr.Configuring.Common.IApizrCommonOptionsBuilder<TApizrCommonOptions, TApizrCommonOptionsBuilder>
  nameWithType.vb: IApizrCommonOptionsBuilder(Of TApizrCommonOptions, TApizrCommonOptionsBuilder)
  fullName.vb: Apizr.Configuring.Common.IApizrCommonOptionsBuilder(Of TApizrCommonOptions, TApizrCommonOptionsBuilder)
  name.vb: IApizrCommonOptionsBuilder(Of TApizrCommonOptions, TApizrCommonOptionsBuilder)
  spec.csharp:
  - uid: Apizr.Configuring.Common.IApizrCommonOptionsBuilder`2
    name: IApizrCommonOptionsBuilder
    href: Apizr.Configuring.Common.IApizrCommonOptionsBuilder-2.html
  - name: <
  - name: TApizrCommonOptions
  - name: ','
  - name: " "
  - name: TApizrCommonOptionsBuilder
  - name: '>'
  spec.vb:
  - uid: Apizr.Configuring.Common.IApizrCommonOptionsBuilder`2
    name: IApizrCommonOptionsBuilder
    href: Apizr.Configuring.Common.IApizrCommonOptionsBuilder-2.html
  - name: (
  - name: Of
  - name: " "
  - name: TApizrCommonOptions
  - name: ','
  - name: " "
  - name: TApizrCommonOptionsBuilder
  - name: )
- uid: Apizr.Configuring.Common.IApizrCommonOptionsBuilder
  commentId: T:Apizr.Configuring.Common.IApizrCommonOptionsBuilder
  parent: Apizr.Configuring.Common
  href: Apizr.Configuring.Common.IApizrCommonOptionsBuilder.html
  name: IApizrCommonOptionsBuilder
  nameWithType: IApizrCommonOptionsBuilder
  fullName: Apizr.Configuring.Common.IApizrCommonOptionsBuilder
- uid: Apizr.Configuring.Common.IApizrCommonOptionsBuilderBase
  commentId: T:Apizr.Configuring.Common.IApizrCommonOptionsBuilderBase
  parent: Apizr.Configuring.Common
  href: Apizr.Configuring.Common.IApizrCommonOptionsBuilderBase.html
  name: IApizrCommonOptionsBuilderBase
  nameWithType: IApizrCommonOptionsBuilderBase
  fullName: Apizr.Configuring.Common.IApizrCommonOptionsBuilderBase
- uid: Apizr.Configuring.Common.IApizrCommonOptionsBuilderBase`2
  commentId: T:Apizr.Configuring.Common.IApizrCommonOptionsBuilderBase`2
  href: Apizr.Configuring.Common.IApizrCommonOptionsBuilderBase-2.html
  name: IApizrCommonOptionsBuilderBase<TApizrCommonOptions, TApizrCommonOptionsBuilder>
  nameWithType: IApizrCommonOptionsBuilderBase<TApizrCommonOptions, TApizrCommonOptionsBuilder>
  fullName: Apizr.Configuring.Common.IApizrCommonOptionsBuilderBase<TApizrCommonOptions, TApizrCommonOptionsBuilder>
  nameWithType.vb: IApizrCommonOptionsBuilderBase(Of TApizrCommonOptions, TApizrCommonOptionsBuilder)
  fullName.vb: Apizr.Configuring.Common.IApizrCommonOptionsBuilderBase(Of TApizrCommonOptions, TApizrCommonOptionsBuilder)
  name.vb: IApizrCommonOptionsBuilderBase(Of TApizrCommonOptions, TApizrCommonOptionsBuilder)
  spec.csharp:
  - uid: Apizr.Configuring.Common.IApizrCommonOptionsBuilderBase`2
    name: IApizrCommonOptionsBuilderBase
    href: Apizr.Configuring.Common.IApizrCommonOptionsBuilderBase-2.html
  - name: <
  - name: TApizrCommonOptions
  - name: ','
  - name: " "
  - name: TApizrCommonOptionsBuilder
  - name: '>'
  spec.vb:
  - uid: Apizr.Configuring.Common.IApizrCommonOptionsBuilderBase`2
    name: IApizrCommonOptionsBuilderBase
    href: Apizr.Configuring.Common.IApizrCommonOptionsBuilderBase-2.html
  - name: (
  - name: Of
  - name: " "
  - name: TApizrCommonOptions
  - name: ','
  - name: " "
  - name: TApizrCommonOptionsBuilder
  - name: )
- uid: Apizr.Configuring.Common.IApizrExtendedCommonOptionsBuilderBase
  commentId: T:Apizr.Configuring.Common.IApizrExtendedCommonOptionsBuilderBase
  parent: Apizr.Configuring.Common
  href: Apizr.Configuring.Common.IApizrExtendedCommonOptionsBuilderBase.html
  name: IApizrExtendedCommonOptionsBuilderBase
  nameWithType: IApizrExtendedCommonOptionsBuilderBase
  fullName: Apizr.Configuring.Common.IApizrExtendedCommonOptionsBuilderBase
- uid: Apizr.Configuring.Common.IApizrGlobalCommonOptionsBuilderBase
  commentId: T:Apizr.Configuring.Common.IApizrGlobalCommonOptionsBuilderBase
  parent: Apizr.Configuring.Common
  href: Apizr.Configuring.Common.IApizrGlobalCommonOptionsBuilderBase.html
  name: IApizrGlobalCommonOptionsBuilderBase
  nameWithType: IApizrGlobalCommonOptionsBuilderBase
  fullName: Apizr.Configuring.Common.IApizrGlobalCommonOptionsBuilderBase
- uid: Apizr.Configuring.Common.IApizrGlobalCommonOptionsBuilderBase`2
  commentId: T:Apizr.Configuring.Common.IApizrGlobalCommonOptionsBuilderBase`2
  href: Apizr.Configuring.Common.IApizrGlobalCommonOptionsBuilderBase-2.html
  name: IApizrGlobalCommonOptionsBuilderBase<TApizrCommonOptions, TApizrCommonOptionsBuilder>
  nameWithType: IApizrGlobalCommonOptionsBuilderBase<TApizrCommonOptions, TApizrCommonOptionsBuilder>
  fullName: Apizr.Configuring.Common.IApizrGlobalCommonOptionsBuilderBase<TApizrCommonOptions, TApizrCommonOptionsBuilder>
  nameWithType.vb: IApizrGlobalCommonOptionsBuilderBase(Of TApizrCommonOptions, TApizrCommonOptionsBuilder)
  fullName.vb: Apizr.Configuring.Common.IApizrGlobalCommonOptionsBuilderBase(Of TApizrCommonOptions, TApizrCommonOptionsBuilder)
  name.vb: IApizrGlobalCommonOptionsBuilderBase(Of TApizrCommonOptions, TApizrCommonOptionsBuilder)
  spec.csharp:
  - uid: Apizr.Configuring.Common.IApizrGlobalCommonOptionsBuilderBase`2
    name: IApizrGlobalCommonOptionsBuilderBase
    href: Apizr.Configuring.Common.IApizrGlobalCommonOptionsBuilderBase-2.html
  - name: <
  - name: TApizrCommonOptions
  - name: ','
  - name: " "
  - name: TApizrCommonOptionsBuilder
  - name: '>'
  spec.vb:
  - uid: Apizr.Configuring.Common.IApizrGlobalCommonOptionsBuilderBase`2
    name: IApizrGlobalCommonOptionsBuilderBase
    href: Apizr.Configuring.Common.IApizrGlobalCommonOptionsBuilderBase-2.html
  - name: (
  - name: Of
  - name: " "
  - name: TApizrCommonOptions
  - name: ','
  - name: " "
  - name: TApizrCommonOptionsBuilder
  - name: )
- uid: Apizr.Configuring.Common
  commentId: N:Apizr.Configuring.Common
  href: Apizr.html
  name: Apizr.Configuring.Common
  nameWithType: Apizr.Configuring.Common
  fullName: Apizr.Configuring.Common
  spec.csharp:
  - uid: Apizr
    name: Apizr
    href: Apizr.html
  - name: .
  - uid: Apizr.Configuring
    name: Configuring
    href: Apizr.Configuring.html
  - name: .
  - uid: Apizr.Configuring.Common
    name: Common
    href: Apizr.Configuring.Common.html
  spec.vb:
  - uid: Apizr
    name: Apizr
    href: Apizr.html
  - name: .
  - uid: Apizr.Configuring
    name: Configuring
    href: Apizr.Configuring.html
  - name: .
  - uid: Apizr.Configuring.Common
    name: Common
    href: Apizr.Configuring.Common.html
