### YamlMime:ManagedReference
items:
- uid: Apizr.Configuring.IApizrOptions
  commentId: T:Apizr.Configuring.IApizrOptions
  id: IApizrOptions
  parent: Apizr.Configuring
  children: []
  langs:
  - csharp
  - vb
  name: IApizrOptions
  nameWithType: IApizrOptions
  fullName: Apizr.Configuring.IApizrOptions
  type: Interface
  source:
    id: IApizrOptions
    path: C:\Dev\Community\Apizr\Apizr\Apizr\Configuring\IApizrOptions.cs
    startLine: 5
  assemblies:
  - Apizr
  namespace: Apizr.Configuring
  syntax:
    content: 'public interface IApizrOptions : IApizrOptionsBase, IApizrCommonOptions, IApizrCommonOptionsBase, IApizrProperOptions, IApizrProperOptionsBase, IApizrSharedOptions, IApizrSharedOptionsBase'
    content.vb: >-
      Public Interface IApizrOptions
          Inherits IApizrOptionsBase, IApizrCommonOptions, IApizrProperOptions
  inheritedMembers:
  - Apizr.Configuring.Common.IApizrCommonOptions.LoggerFactoryFactory
  - Apizr.Configuring.Common.IApizrCommonOptions.PolicyRegistryFactory
  - Apizr.Configuring.Common.IApizrCommonOptions.RefitSettingsFactory
  - Apizr.Configuring.Common.IApizrCommonOptions.ConnectivityHandlerFactory
  - Apizr.Configuring.Common.IApizrCommonOptions.CacheHandlerFactory
  - Apizr.Configuring.Common.IApizrCommonOptions.MappingHandlerFactory
  - Apizr.Configuring.Common.IApizrCommonOptionsBase.RefitSettings
  - Apizr.Configuring.Proper.IApizrProperOptions.LoggerFactory
  - Apizr.Configuring.Proper.IApizrProperOptionsBase.WebApiType
  - Apizr.Configuring.Proper.IApizrProperOptionsBase.PolicyRegistryKeys
  - Apizr.Configuring.Proper.IApizrProperOptionsBase.Logger
  - Apizr.Configuring.Shared.IApizrSharedOptions.BaseUriFactory
  - Apizr.Configuring.Shared.IApizrSharedOptions.BaseAddressFactory
  - Apizr.Configuring.Shared.IApizrSharedOptions.BasePathFactory
  - Apizr.Configuring.Shared.IApizrSharedOptions.HttpTracerModeFactory
  - Apizr.Configuring.Shared.IApizrSharedOptions.TrafficVerbosityFactory
  - Apizr.Configuring.Shared.IApizrSharedOptions.LogLevelsFactory
  - Apizr.Configuring.Shared.IApizrSharedOptions.HttpClientHandlerFactory
  - Apizr.Configuring.Shared.IApizrSharedOptions.DelegatingHandlersFactories
  - Apizr.Configuring.Shared.IApizrSharedOptionsBase.BaseUri
  - Apizr.Configuring.Shared.IApizrSharedOptionsBase.BaseAddress
  - Apizr.Configuring.Shared.IApizrSharedOptionsBase.BasePath
  - Apizr.Configuring.Shared.IApizrSharedOptionsBase.HttpTracerMode
  - Apizr.Configuring.Shared.IApizrSharedOptionsBase.TrafficVerbosity
  - Apizr.Configuring.Shared.IApizrSharedOptionsBase.LogLevels
  extensionMethods:
  - System.Object.Apizr.Extending.ObjectExtensions.ToString(System.String,System.String)
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
references:
- uid: Apizr.Configuring
  commentId: N:Apizr.Configuring
  name: Apizr.Configuring
  nameWithType: Apizr.Configuring
  fullName: Apizr.Configuring
- uid: Apizr.Configuring.Common.IApizrCommonOptions.LoggerFactoryFactory
  commentId: P:Apizr.Configuring.Common.IApizrCommonOptions.LoggerFactoryFactory
  parent: Apizr.Configuring.Common.IApizrCommonOptions
  name: LoggerFactoryFactory
  nameWithType: IApizrCommonOptions.LoggerFactoryFactory
  fullName: Apizr.Configuring.Common.IApizrCommonOptions.LoggerFactoryFactory
- uid: Apizr.Configuring.Common.IApizrCommonOptions.PolicyRegistryFactory
  commentId: P:Apizr.Configuring.Common.IApizrCommonOptions.PolicyRegistryFactory
  parent: Apizr.Configuring.Common.IApizrCommonOptions
  name: PolicyRegistryFactory
  nameWithType: IApizrCommonOptions.PolicyRegistryFactory
  fullName: Apizr.Configuring.Common.IApizrCommonOptions.PolicyRegistryFactory
- uid: Apizr.Configuring.Common.IApizrCommonOptions.RefitSettingsFactory
  commentId: P:Apizr.Configuring.Common.IApizrCommonOptions.RefitSettingsFactory
  parent: Apizr.Configuring.Common.IApizrCommonOptions
  name: RefitSettingsFactory
  nameWithType: IApizrCommonOptions.RefitSettingsFactory
  fullName: Apizr.Configuring.Common.IApizrCommonOptions.RefitSettingsFactory
- uid: Apizr.Configuring.Common.IApizrCommonOptions.ConnectivityHandlerFactory
  commentId: P:Apizr.Configuring.Common.IApizrCommonOptions.ConnectivityHandlerFactory
  parent: Apizr.Configuring.Common.IApizrCommonOptions
  name: ConnectivityHandlerFactory
  nameWithType: IApizrCommonOptions.ConnectivityHandlerFactory
  fullName: Apizr.Configuring.Common.IApizrCommonOptions.ConnectivityHandlerFactory
- uid: Apizr.Configuring.Common.IApizrCommonOptions.CacheHandlerFactory
  commentId: P:Apizr.Configuring.Common.IApizrCommonOptions.CacheHandlerFactory
  parent: Apizr.Configuring.Common.IApizrCommonOptions
  name: CacheHandlerFactory
  nameWithType: IApizrCommonOptions.CacheHandlerFactory
  fullName: Apizr.Configuring.Common.IApizrCommonOptions.CacheHandlerFactory
- uid: Apizr.Configuring.Common.IApizrCommonOptions.MappingHandlerFactory
  commentId: P:Apizr.Configuring.Common.IApizrCommonOptions.MappingHandlerFactory
  parent: Apizr.Configuring.Common.IApizrCommonOptions
  name: MappingHandlerFactory
  nameWithType: IApizrCommonOptions.MappingHandlerFactory
  fullName: Apizr.Configuring.Common.IApizrCommonOptions.MappingHandlerFactory
- uid: Apizr.Configuring.Common.IApizrCommonOptionsBase.RefitSettings
  commentId: P:Apizr.Configuring.Common.IApizrCommonOptionsBase.RefitSettings
  parent: Apizr.Configuring.Common.IApizrCommonOptionsBase
  name: RefitSettings
  nameWithType: IApizrCommonOptionsBase.RefitSettings
  fullName: Apizr.Configuring.Common.IApizrCommonOptionsBase.RefitSettings
- uid: Apizr.Configuring.Proper.IApizrProperOptions.LoggerFactory
  commentId: P:Apizr.Configuring.Proper.IApizrProperOptions.LoggerFactory
  parent: Apizr.Configuring.Proper.IApizrProperOptions
  name: LoggerFactory
  nameWithType: IApizrProperOptions.LoggerFactory
  fullName: Apizr.Configuring.Proper.IApizrProperOptions.LoggerFactory
- uid: Apizr.Configuring.Proper.IApizrProperOptionsBase.WebApiType
  commentId: P:Apizr.Configuring.Proper.IApizrProperOptionsBase.WebApiType
  parent: Apizr.Configuring.Proper.IApizrProperOptionsBase
  name: WebApiType
  nameWithType: IApizrProperOptionsBase.WebApiType
  fullName: Apizr.Configuring.Proper.IApizrProperOptionsBase.WebApiType
- uid: Apizr.Configuring.Proper.IApizrProperOptionsBase.PolicyRegistryKeys
  commentId: P:Apizr.Configuring.Proper.IApizrProperOptionsBase.PolicyRegistryKeys
  parent: Apizr.Configuring.Proper.IApizrProperOptionsBase
  name: PolicyRegistryKeys
  nameWithType: IApizrProperOptionsBase.PolicyRegistryKeys
  fullName: Apizr.Configuring.Proper.IApizrProperOptionsBase.PolicyRegistryKeys
- uid: Apizr.Configuring.Proper.IApizrProperOptionsBase.Logger
  commentId: P:Apizr.Configuring.Proper.IApizrProperOptionsBase.Logger
  parent: Apizr.Configuring.Proper.IApizrProperOptionsBase
  name: Logger
  nameWithType: IApizrProperOptionsBase.Logger
  fullName: Apizr.Configuring.Proper.IApizrProperOptionsBase.Logger
- uid: Apizr.Configuring.Shared.IApizrSharedOptions.BaseUriFactory
  commentId: P:Apizr.Configuring.Shared.IApizrSharedOptions.BaseUriFactory
  parent: Apizr.Configuring.Shared.IApizrSharedOptions
  name: BaseUriFactory
  nameWithType: IApizrSharedOptions.BaseUriFactory
  fullName: Apizr.Configuring.Shared.IApizrSharedOptions.BaseUriFactory
- uid: Apizr.Configuring.Shared.IApizrSharedOptions.BaseAddressFactory
  commentId: P:Apizr.Configuring.Shared.IApizrSharedOptions.BaseAddressFactory
  parent: Apizr.Configuring.Shared.IApizrSharedOptions
  name: BaseAddressFactory
  nameWithType: IApizrSharedOptions.BaseAddressFactory
  fullName: Apizr.Configuring.Shared.IApizrSharedOptions.BaseAddressFactory
- uid: Apizr.Configuring.Shared.IApizrSharedOptions.BasePathFactory
  commentId: P:Apizr.Configuring.Shared.IApizrSharedOptions.BasePathFactory
  parent: Apizr.Configuring.Shared.IApizrSharedOptions
  name: BasePathFactory
  nameWithType: IApizrSharedOptions.BasePathFactory
  fullName: Apizr.Configuring.Shared.IApizrSharedOptions.BasePathFactory
- uid: Apizr.Configuring.Shared.IApizrSharedOptions.HttpTracerModeFactory
  commentId: P:Apizr.Configuring.Shared.IApizrSharedOptions.HttpTracerModeFactory
  parent: Apizr.Configuring.Shared.IApizrSharedOptions
  name: HttpTracerModeFactory
  nameWithType: IApizrSharedOptions.HttpTracerModeFactory
  fullName: Apizr.Configuring.Shared.IApizrSharedOptions.HttpTracerModeFactory
- uid: Apizr.Configuring.Shared.IApizrSharedOptions.TrafficVerbosityFactory
  commentId: P:Apizr.Configuring.Shared.IApizrSharedOptions.TrafficVerbosityFactory
  parent: Apizr.Configuring.Shared.IApizrSharedOptions
  name: TrafficVerbosityFactory
  nameWithType: IApizrSharedOptions.TrafficVerbosityFactory
  fullName: Apizr.Configuring.Shared.IApizrSharedOptions.TrafficVerbosityFactory
- uid: Apizr.Configuring.Shared.IApizrSharedOptions.LogLevelsFactory
  commentId: P:Apizr.Configuring.Shared.IApizrSharedOptions.LogLevelsFactory
  parent: Apizr.Configuring.Shared.IApizrSharedOptions
  name: LogLevelsFactory
  nameWithType: IApizrSharedOptions.LogLevelsFactory
  fullName: Apizr.Configuring.Shared.IApizrSharedOptions.LogLevelsFactory
- uid: Apizr.Configuring.Shared.IApizrSharedOptions.HttpClientHandlerFactory
  commentId: P:Apizr.Configuring.Shared.IApizrSharedOptions.HttpClientHandlerFactory
  parent: Apizr.Configuring.Shared.IApizrSharedOptions
  name: HttpClientHandlerFactory
  nameWithType: IApizrSharedOptions.HttpClientHandlerFactory
  fullName: Apizr.Configuring.Shared.IApizrSharedOptions.HttpClientHandlerFactory
- uid: Apizr.Configuring.Shared.IApizrSharedOptions.DelegatingHandlersFactories
  commentId: P:Apizr.Configuring.Shared.IApizrSharedOptions.DelegatingHandlersFactories
  parent: Apizr.Configuring.Shared.IApizrSharedOptions
  name: DelegatingHandlersFactories
  nameWithType: IApizrSharedOptions.DelegatingHandlersFactories
  fullName: Apizr.Configuring.Shared.IApizrSharedOptions.DelegatingHandlersFactories
- uid: Apizr.Configuring.Shared.IApizrSharedOptionsBase.BaseUri
  commentId: P:Apizr.Configuring.Shared.IApizrSharedOptionsBase.BaseUri
  parent: Apizr.Configuring.Shared.IApizrSharedOptionsBase
  name: BaseUri
  nameWithType: IApizrSharedOptionsBase.BaseUri
  fullName: Apizr.Configuring.Shared.IApizrSharedOptionsBase.BaseUri
- uid: Apizr.Configuring.Shared.IApizrSharedOptionsBase.BaseAddress
  commentId: P:Apizr.Configuring.Shared.IApizrSharedOptionsBase.BaseAddress
  parent: Apizr.Configuring.Shared.IApizrSharedOptionsBase
  name: BaseAddress
  nameWithType: IApizrSharedOptionsBase.BaseAddress
  fullName: Apizr.Configuring.Shared.IApizrSharedOptionsBase.BaseAddress
- uid: Apizr.Configuring.Shared.IApizrSharedOptionsBase.BasePath
  commentId: P:Apizr.Configuring.Shared.IApizrSharedOptionsBase.BasePath
  parent: Apizr.Configuring.Shared.IApizrSharedOptionsBase
  name: BasePath
  nameWithType: IApizrSharedOptionsBase.BasePath
  fullName: Apizr.Configuring.Shared.IApizrSharedOptionsBase.BasePath
- uid: Apizr.Configuring.Shared.IApizrSharedOptionsBase.HttpTracerMode
  commentId: P:Apizr.Configuring.Shared.IApizrSharedOptionsBase.HttpTracerMode
  parent: Apizr.Configuring.Shared.IApizrSharedOptionsBase
  name: HttpTracerMode
  nameWithType: IApizrSharedOptionsBase.HttpTracerMode
  fullName: Apizr.Configuring.Shared.IApizrSharedOptionsBase.HttpTracerMode
- uid: Apizr.Configuring.Shared.IApizrSharedOptionsBase.TrafficVerbosity
  commentId: P:Apizr.Configuring.Shared.IApizrSharedOptionsBase.TrafficVerbosity
  parent: Apizr.Configuring.Shared.IApizrSharedOptionsBase
  name: TrafficVerbosity
  nameWithType: IApizrSharedOptionsBase.TrafficVerbosity
  fullName: Apizr.Configuring.Shared.IApizrSharedOptionsBase.TrafficVerbosity
- uid: Apizr.Configuring.Shared.IApizrSharedOptionsBase.LogLevels
  commentId: P:Apizr.Configuring.Shared.IApizrSharedOptionsBase.LogLevels
  parent: Apizr.Configuring.Shared.IApizrSharedOptionsBase
  name: LogLevels
  nameWithType: IApizrSharedOptionsBase.LogLevels
  fullName: Apizr.Configuring.Shared.IApizrSharedOptionsBase.LogLevels
- uid: System.Object.Apizr.Extending.ObjectExtensions.ToString(System.String,System.String)
  commentId: M:Apizr.Extending.ObjectExtensions.ToString(System.Object,System.String,System.String)
  parent: Apizr.Extending.ObjectExtensions
  definition: Apizr.Extending.ObjectExtensions.ToString(System.Object,System.String,System.String)
  name: ToString(String, String)
  nameWithType: ObjectExtensions.ToString(String, String)
  fullName: Apizr.Extending.ObjectExtensions.ToString(System.String, System.String)
  spec.csharp:
  - uid: Apizr.Extending.ObjectExtensions.ToString(System.String,System.String)
    name: ToString
    nameWithType: ObjectExtensions.ToString
    fullName: Apizr.Extending.ObjectExtensions.ToString
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Apizr.Extending.ObjectExtensions.ToString(System.String,System.String)
    name: ToString
    nameWithType: ObjectExtensions.ToString
    fullName: Apizr.Extending.ObjectExtensions.ToString
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Apizr.Configuring.Common.IApizrCommonOptions
  commentId: T:Apizr.Configuring.Common.IApizrCommonOptions
  parent: Apizr.Configuring.Common
  name: IApizrCommonOptions
  nameWithType: IApizrCommonOptions
  fullName: Apizr.Configuring.Common.IApizrCommonOptions
- uid: Apizr.Configuring.Common.IApizrCommonOptionsBase
  commentId: T:Apizr.Configuring.Common.IApizrCommonOptionsBase
  parent: Apizr.Configuring.Common
  name: IApizrCommonOptionsBase
  nameWithType: IApizrCommonOptionsBase
  fullName: Apizr.Configuring.Common.IApizrCommonOptionsBase
- uid: Apizr.Configuring.Proper.IApizrProperOptions
  commentId: T:Apizr.Configuring.Proper.IApizrProperOptions
  parent: Apizr.Configuring.Proper
  name: IApizrProperOptions
  nameWithType: IApizrProperOptions
  fullName: Apizr.Configuring.Proper.IApizrProperOptions
- uid: Apizr.Configuring.Proper.IApizrProperOptionsBase
  commentId: T:Apizr.Configuring.Proper.IApizrProperOptionsBase
  parent: Apizr.Configuring.Proper
  name: IApizrProperOptionsBase
  nameWithType: IApizrProperOptionsBase
  fullName: Apizr.Configuring.Proper.IApizrProperOptionsBase
- uid: Apizr.Configuring.Shared.IApizrSharedOptions
  commentId: T:Apizr.Configuring.Shared.IApizrSharedOptions
  parent: Apizr.Configuring.Shared
  name: IApizrSharedOptions
  nameWithType: IApizrSharedOptions
  fullName: Apizr.Configuring.Shared.IApizrSharedOptions
- uid: Apizr.Configuring.Shared.IApizrSharedOptionsBase
  commentId: T:Apizr.Configuring.Shared.IApizrSharedOptionsBase
  parent: Apizr.Configuring.Shared
  name: IApizrSharedOptionsBase
  nameWithType: IApizrSharedOptionsBase
  fullName: Apizr.Configuring.Shared.IApizrSharedOptionsBase
- uid: Apizr.Extending.ObjectExtensions.ToString(System.Object,System.String,System.String)
  commentId: M:Apizr.Extending.ObjectExtensions.ToString(System.Object,System.String,System.String)
  isExternal: true
  name: ToString(Object, String, String)
  nameWithType: ObjectExtensions.ToString(Object, String, String)
  fullName: Apizr.Extending.ObjectExtensions.ToString(System.Object, System.String, System.String)
  spec.csharp:
  - uid: Apizr.Extending.ObjectExtensions.ToString(System.Object,System.String,System.String)
    name: ToString
    nameWithType: ObjectExtensions.ToString
    fullName: Apizr.Extending.ObjectExtensions.ToString
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Apizr.Extending.ObjectExtensions.ToString(System.Object,System.String,System.String)
    name: ToString
    nameWithType: ObjectExtensions.ToString
    fullName: Apizr.Extending.ObjectExtensions.ToString
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Apizr.Extending.ObjectExtensions
  commentId: T:Apizr.Extending.ObjectExtensions
  parent: Apizr.Extending
  name: ObjectExtensions
  nameWithType: ObjectExtensions
  fullName: Apizr.Extending.ObjectExtensions
- uid: Apizr.Configuring.Common
  commentId: N:Apizr.Configuring.Common
  name: Apizr.Configuring.Common
  nameWithType: Apizr.Configuring.Common
  fullName: Apizr.Configuring.Common
- uid: Apizr.Configuring.Proper
  commentId: N:Apizr.Configuring.Proper
  name: Apizr.Configuring.Proper
  nameWithType: Apizr.Configuring.Proper
  fullName: Apizr.Configuring.Proper
- uid: Apizr.Configuring.Shared
  commentId: N:Apizr.Configuring.Shared
  name: Apizr.Configuring.Shared
  nameWithType: Apizr.Configuring.Shared
  fullName: Apizr.Configuring.Shared
- uid: Apizr.Extending
  commentId: N:Apizr.Extending
  name: Apizr.Extending
  nameWithType: Apizr.Extending
  fullName: Apizr.Extending
