### YamlMime:ManagedReference
items:
- uid: Apizr.Configuring.Shared.Context.ApizrResilienceContextOptionsBuilder
  commentId: T:Apizr.Configuring.Shared.Context.ApizrResilienceContextOptionsBuilder
  id: ApizrResilienceContextOptionsBuilder
  parent: Apizr.Configuring.Shared.Context
  children:
  - Apizr.Configuring.Shared.Context.ApizrResilienceContextOptionsBuilder.ContinueOnCapturedContext(System.Boolean)
  - Apizr.Configuring.Shared.Context.ApizrResilienceContextOptionsBuilder.Options
  - Apizr.Configuring.Shared.Context.ApizrResilienceContextOptionsBuilder.ReturnToPoolOnComplete(System.Boolean)
  langs:
  - csharp
  - vb
  name: ApizrResilienceContextOptionsBuilder
  nameWithType: ApizrResilienceContextOptionsBuilder
  fullName: Apizr.Configuring.Shared.Context.ApizrResilienceContextOptionsBuilder
  type: Class
  source:
    remote:
      path: Apizr/Src/Apizr/Configuring/Shared/Context/ApizrResilienceContextOptionsBuilder.cs
      branch: feat/resilience
      repo: https://github.com/Respawnsive/Apizr.git
    id: ApizrResilienceContextOptionsBuilder
    path: ../../Src/Apizr/Configuring/Shared/Context/ApizrResilienceContextOptionsBuilder.cs
    startLine: 2
  assemblies:
  - Apizr
  namespace: Apizr.Configuring.Shared.Context
  syntax:
    content: 'public class ApizrResilienceContextOptionsBuilder : IApizrResilienceContextOptionsBuilder'
    content.vb: >-
      Public Class ApizrResilienceContextOptionsBuilder
          Implements IApizrResilienceContextOptionsBuilder
  inheritance:
  - System.Object
  implements:
  - Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Apizr.Configuring.Shared.Context.ApizrResilienceContextOptionsBuilder.Options
  commentId: F:Apizr.Configuring.Shared.Context.ApizrResilienceContextOptionsBuilder.Options
  id: Options
  parent: Apizr.Configuring.Shared.Context.ApizrResilienceContextOptionsBuilder
  langs:
  - csharp
  - vb
  name: Options
  nameWithType: ApizrResilienceContextOptionsBuilder.Options
  fullName: Apizr.Configuring.Shared.Context.ApizrResilienceContextOptionsBuilder.Options
  type: Field
  source:
    remote:
      path: Apizr/Src/Apizr/Configuring/Shared/Context/ApizrResilienceContextOptionsBuilder.cs
      branch: feat/resilience
      repo: https://github.com/Respawnsive/Apizr.git
    id: Options
    path: ../../Src/Apizr/Configuring/Shared/Context/ApizrResilienceContextOptionsBuilder.cs
    startLine: 7
  assemblies:
  - Apizr
  namespace: Apizr.Configuring.Shared.Context
  summary: "\nThe common options\n"
  example: []
  syntax:
    content: protected readonly ApizrResilienceContextOptions Options
    return:
      type: Apizr.Configuring.Shared.Context.ApizrResilienceContextOptions
    content.vb: Protected ReadOnly Options As ApizrResilienceContextOptions
  modifiers.csharp:
  - protected
  - readonly
  modifiers.vb:
  - Protected
  - ReadOnly
- uid: Apizr.Configuring.Shared.Context.ApizrResilienceContextOptionsBuilder.ContinueOnCapturedContext(System.Boolean)
  commentId: M:Apizr.Configuring.Shared.Context.ApizrResilienceContextOptionsBuilder.ContinueOnCapturedContext(System.Boolean)
  id: ContinueOnCapturedContext(System.Boolean)
  parent: Apizr.Configuring.Shared.Context.ApizrResilienceContextOptionsBuilder
  langs:
  - csharp
  - vb
  name: ContinueOnCapturedContext(Boolean)
  nameWithType: ApizrResilienceContextOptionsBuilder.ContinueOnCapturedContext(Boolean)
  fullName: Apizr.Configuring.Shared.Context.ApizrResilienceContextOptionsBuilder.ContinueOnCapturedContext(System.Boolean)
  type: Method
  source:
    remote:
      path: Apizr/Src/Apizr/Configuring/Shared/Context/ApizrResilienceContextOptionsBuilder.cs
      branch: feat/resilience
      repo: https://github.com/Respawnsive/Apizr.git
    id: ContinueOnCapturedContext
    path: ../../Src/Apizr/Configuring/Shared/Context/ApizrResilienceContextOptionsBuilder.cs
    startLine: 18
  assemblies:
  - Apizr
  namespace: Apizr.Configuring.Shared.Context
  example: []
  syntax:
    content: public IApizrResilienceContextOptionsBuilder ContinueOnCapturedContext(bool continueOnCapturedContext)
    parameters:
    - id: continueOnCapturedContext
      type: System.Boolean
    return:
      type: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder
    content.vb: Public Function ContinueOnCapturedContext(continueOnCapturedContext As Boolean) As IApizrResilienceContextOptionsBuilder
  overload: Apizr.Configuring.Shared.Context.ApizrResilienceContextOptionsBuilder.ContinueOnCapturedContext*
  implements:
  - Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder.ContinueOnCapturedContext(System.Boolean)
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Apizr.Configuring.Shared.Context.ApizrResilienceContextOptionsBuilder.ReturnToPoolOnComplete(System.Boolean)
  commentId: M:Apizr.Configuring.Shared.Context.ApizrResilienceContextOptionsBuilder.ReturnToPoolOnComplete(System.Boolean)
  id: ReturnToPoolOnComplete(System.Boolean)
  parent: Apizr.Configuring.Shared.Context.ApizrResilienceContextOptionsBuilder
  langs:
  - csharp
  - vb
  name: ReturnToPoolOnComplete(Boolean)
  nameWithType: ApizrResilienceContextOptionsBuilder.ReturnToPoolOnComplete(Boolean)
  fullName: Apizr.Configuring.Shared.Context.ApizrResilienceContextOptionsBuilder.ReturnToPoolOnComplete(System.Boolean)
  type: Method
  source:
    remote:
      path: Apizr/Src/Apizr/Configuring/Shared/Context/ApizrResilienceContextOptionsBuilder.cs
      branch: feat/resilience
      repo: https://github.com/Respawnsive/Apizr.git
    id: ReturnToPoolOnComplete
    path: ../../Src/Apizr/Configuring/Shared/Context/ApizrResilienceContextOptionsBuilder.cs
    startLine: 26
  assemblies:
  - Apizr
  namespace: Apizr.Configuring.Shared.Context
  example: []
  syntax:
    content: public IApizrResilienceContextOptionsBuilder ReturnToPoolOnComplete(bool returnToPoolOnComplete)
    parameters:
    - id: returnToPoolOnComplete
      type: System.Boolean
    return:
      type: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder
    content.vb: Public Function ReturnToPoolOnComplete(returnToPoolOnComplete As Boolean) As IApizrResilienceContextOptionsBuilder
  overload: Apizr.Configuring.Shared.Context.ApizrResilienceContextOptionsBuilder.ReturnToPoolOnComplete*
  implements:
  - Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder.ReturnToPoolOnComplete(System.Boolean)
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Apizr.Configuring.Shared.Context
  commentId: N:Apizr.Configuring.Shared.Context
  name: Apizr.Configuring.Shared.Context
  nameWithType: Apizr.Configuring.Shared.Context
  fullName: Apizr.Configuring.Shared.Context
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder
  commentId: T:Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder
  parent: Apizr.Configuring.Shared.Context
  name: IApizrResilienceContextOptionsBuilder
  nameWithType: IApizrResilienceContextOptionsBuilder
  fullName: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Apizr.Configuring.Shared.Context.ApizrResilienceContextOptions
  commentId: T:Apizr.Configuring.Shared.Context.ApizrResilienceContextOptions
  parent: Apizr.Configuring.Shared.Context
  name: ApizrResilienceContextOptions
  nameWithType: ApizrResilienceContextOptions
  fullName: Apizr.Configuring.Shared.Context.ApizrResilienceContextOptions
- uid: Apizr.Configuring.Shared.Context.ApizrResilienceContextOptionsBuilder.ContinueOnCapturedContext*
  commentId: Overload:Apizr.Configuring.Shared.Context.ApizrResilienceContextOptionsBuilder.ContinueOnCapturedContext
  name: ContinueOnCapturedContext
  nameWithType: ApizrResilienceContextOptionsBuilder.ContinueOnCapturedContext
  fullName: Apizr.Configuring.Shared.Context.ApizrResilienceContextOptionsBuilder.ContinueOnCapturedContext
- uid: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder.ContinueOnCapturedContext(System.Boolean)
  commentId: M:Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder.ContinueOnCapturedContext(System.Boolean)
  parent: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder
  isExternal: true
  name: ContinueOnCapturedContext(Boolean)
  nameWithType: IApizrResilienceContextOptionsBuilder.ContinueOnCapturedContext(Boolean)
  fullName: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder.ContinueOnCapturedContext(System.Boolean)
  spec.csharp:
  - uid: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder.ContinueOnCapturedContext(System.Boolean)
    name: ContinueOnCapturedContext
    nameWithType: IApizrResilienceContextOptionsBuilder.ContinueOnCapturedContext
    fullName: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder.ContinueOnCapturedContext
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Boolean
    name: Boolean
    nameWithType: Boolean
    fullName: System.Boolean
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder.ContinueOnCapturedContext(System.Boolean)
    name: ContinueOnCapturedContext
    nameWithType: IApizrResilienceContextOptionsBuilder.ContinueOnCapturedContext
    fullName: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder.ContinueOnCapturedContext
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Boolean
    name: Boolean
    nameWithType: Boolean
    fullName: System.Boolean
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: Apizr.Configuring.Shared.Context.ApizrResilienceContextOptionsBuilder.ReturnToPoolOnComplete*
  commentId: Overload:Apizr.Configuring.Shared.Context.ApizrResilienceContextOptionsBuilder.ReturnToPoolOnComplete
  name: ReturnToPoolOnComplete
  nameWithType: ApizrResilienceContextOptionsBuilder.ReturnToPoolOnComplete
  fullName: Apizr.Configuring.Shared.Context.ApizrResilienceContextOptionsBuilder.ReturnToPoolOnComplete
- uid: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder.ReturnToPoolOnComplete(System.Boolean)
  commentId: M:Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder.ReturnToPoolOnComplete(System.Boolean)
  parent: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder
  isExternal: true
  name: ReturnToPoolOnComplete(Boolean)
  nameWithType: IApizrResilienceContextOptionsBuilder.ReturnToPoolOnComplete(Boolean)
  fullName: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder.ReturnToPoolOnComplete(System.Boolean)
  spec.csharp:
  - uid: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder.ReturnToPoolOnComplete(System.Boolean)
    name: ReturnToPoolOnComplete
    nameWithType: IApizrResilienceContextOptionsBuilder.ReturnToPoolOnComplete
    fullName: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder.ReturnToPoolOnComplete
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Boolean
    name: Boolean
    nameWithType: Boolean
    fullName: System.Boolean
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder.ReturnToPoolOnComplete(System.Boolean)
    name: ReturnToPoolOnComplete
    nameWithType: IApizrResilienceContextOptionsBuilder.ReturnToPoolOnComplete
    fullName: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder.ReturnToPoolOnComplete
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Boolean
    name: Boolean
    nameWithType: Boolean
    fullName: System.Boolean
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
