### YamlMime:ManagedReference
items:
- uid: Apizr.Resiliencing.ApizrResilienceContextSettings
  commentId: T:Apizr.Resiliencing.ApizrResilienceContextSettings
  id: ApizrResilienceContextSettings
  parent: Apizr.Resiliencing
  children:
  - Apizr.Resiliencing.ApizrResilienceContextSettings.#ctor(System.Nullable{System.Boolean},System.Nullable{System.Boolean})
  - Apizr.Resiliencing.ApizrResilienceContextSettings.ContinueOnCapturedContext
  - Apizr.Resiliencing.ApizrResilienceContextSettings.ReturnToPoolOnComplete
  langs:
  - csharp
  - vb
  name: ApizrResilienceContextSettings
  nameWithType: ApizrResilienceContextSettings
  fullName: Apizr.Resiliencing.ApizrResilienceContextSettings
  type: Struct
  source:
    remote:
      path: Apizr/Src/Apizr/Resiliencing/ApizrResilienceContextSettings.cs
      branch: feat/response
      repo: https://github.com/Respawnsive/Apizr.git
    id: ApizrResilienceContextSettings
    path: ../../Src/Apizr/Resiliencing/ApizrResilienceContextSettings.cs
    startLine: 9
  assemblies:
  - Apizr
  namespace: Apizr.Resiliencing
  summary: Settings used by Apizr when dealing with <xref href="Polly.ResilienceContext" data-throw-if-not-resolved="false"></xref>.
  example: []
  syntax:
    content: public readonly struct ApizrResilienceContextSettings
    content.vb: Public Structure ApizrResilienceContextSettings
  inheritedMembers:
  - System.ValueType.Equals(System.Object)
  - System.ValueType.GetHashCode
  - System.ValueType.ToString
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.ReferenceEquals(System.Object,System.Object)
- uid: Apizr.Resiliencing.ApizrResilienceContextSettings.#ctor(System.Nullable{System.Boolean},System.Nullable{System.Boolean})
  commentId: M:Apizr.Resiliencing.ApizrResilienceContextSettings.#ctor(System.Nullable{System.Boolean},System.Nullable{System.Boolean})
  id: '#ctor(System.Nullable{System.Boolean},System.Nullable{System.Boolean})'
  parent: Apizr.Resiliencing.ApizrResilienceContextSettings
  langs:
  - csharp
  - vb
  name: ApizrResilienceContextSettings(bool?, bool?)
  nameWithType: ApizrResilienceContextSettings.ApizrResilienceContextSettings(bool?, bool?)
  fullName: Apizr.Resiliencing.ApizrResilienceContextSettings.ApizrResilienceContextSettings(bool?, bool?)
  type: Constructor
  source:
    remote:
      path: Apizr/Src/Apizr/Resiliencing/ApizrResilienceContextSettings.cs
      branch: feat/response
      repo: https://github.com/Respawnsive/Apizr.git
    id: .ctor
    path: ../../Src/Apizr/Resiliencing/ApizrResilienceContextSettings.cs
    startLine: 16
  assemblies:
  - Apizr
  namespace: Apizr.Resiliencing
  summary: Initializes a new instance of the <xref href="Apizr.Resiliencing.ApizrResilienceContextSettings" data-throw-if-not-resolved="false"></xref> struct.
  example: []
  syntax:
    content: public ApizrResilienceContextSettings(bool? continueOnCapturedContext = null, bool? returnToPoolOnComplete = null)
    parameters:
    - id: continueOnCapturedContext
      type: System.Nullable{System.Boolean}
      description: Value indicating whether to continue on captured context.
    - id: returnToPoolOnComplete
      type: System.Nullable{System.Boolean}
      description: ''
    content.vb: Public Sub New(continueOnCapturedContext As Boolean? = Nothing, returnToPoolOnComplete As Boolean? = Nothing)
  overload: Apizr.Resiliencing.ApizrResilienceContextSettings.#ctor*
  nameWithType.vb: ApizrResilienceContextSettings.New(Boolean?, Boolean?)
  fullName.vb: Apizr.Resiliencing.ApizrResilienceContextSettings.New(Boolean?, Boolean?)
  name.vb: New(Boolean?, Boolean?)
- uid: Apizr.Resiliencing.ApizrResilienceContextSettings.ContinueOnCapturedContext
  commentId: P:Apizr.Resiliencing.ApizrResilienceContextSettings.ContinueOnCapturedContext
  id: ContinueOnCapturedContext
  parent: Apizr.Resiliencing.ApizrResilienceContextSettings
  langs:
  - csharp
  - vb
  name: ContinueOnCapturedContext
  nameWithType: ApizrResilienceContextSettings.ContinueOnCapturedContext
  fullName: Apizr.Resiliencing.ApizrResilienceContextSettings.ContinueOnCapturedContext
  type: Property
  source:
    remote:
      path: Apizr/Src/Apizr/Resiliencing/ApizrResilienceContextSettings.cs
      branch: feat/response
      repo: https://github.com/Respawnsive/Apizr.git
    id: ContinueOnCapturedContext
    path: ../../Src/Apizr/Resiliencing/ApizrResilienceContextSettings.cs
    startLine: 25
  assemblies:
  - Apizr
  namespace: Apizr.Resiliencing
  summary: Gets the value indicating whether to continue on captured context, if any.
  example: []
  syntax:
    content: public bool? ContinueOnCapturedContext { get; }
    parameters: []
    return:
      type: System.Nullable{System.Boolean}
    content.vb: Public ReadOnly Property ContinueOnCapturedContext As Boolean?
  overload: Apizr.Resiliencing.ApizrResilienceContextSettings.ContinueOnCapturedContext*
- uid: Apizr.Resiliencing.ApizrResilienceContextSettings.ReturnToPoolOnComplete
  commentId: P:Apizr.Resiliencing.ApizrResilienceContextSettings.ReturnToPoolOnComplete
  id: ReturnToPoolOnComplete
  parent: Apizr.Resiliencing.ApizrResilienceContextSettings
  langs:
  - csharp
  - vb
  name: ReturnToPoolOnComplete
  nameWithType: ApizrResilienceContextSettings.ReturnToPoolOnComplete
  fullName: Apizr.Resiliencing.ApizrResilienceContextSettings.ReturnToPoolOnComplete
  type: Property
  source:
    remote:
      path: Apizr/Src/Apizr/Resiliencing/ApizrResilienceContextSettings.cs
      branch: feat/response
      repo: https://github.com/Respawnsive/Apizr.git
    id: ReturnToPoolOnComplete
    path: ../../Src/Apizr/Resiliencing/ApizrResilienceContextSettings.cs
    startLine: 30
  assemblies:
  - Apizr
  namespace: Apizr.Resiliencing
  summary: Gets the value indicating whether to return the context to the pool, when request completes.
  example: []
  syntax:
    content: public bool? ReturnToPoolOnComplete { get; }
    parameters: []
    return:
      type: System.Nullable{System.Boolean}
    content.vb: Public ReadOnly Property ReturnToPoolOnComplete As Boolean?
  overload: Apizr.Resiliencing.ApizrResilienceContextSettings.ReturnToPoolOnComplete*
references:
- uid: Polly.ResilienceContext
  commentId: T:Polly.ResilienceContext
  parent: Polly
  isExternal: true
  href: https://github.com/App-vNext/Polly/blob/ede127ff7f3a7a4e44e34efeb8685e4491438816/src/Polly.Core/ResilienceContext.cs
  name: ResilienceContext
  nameWithType: ResilienceContext
  fullName: Polly.ResilienceContext
- uid: Apizr.Resiliencing
  commentId: N:Apizr.Resiliencing
  href: Apizr.html
  name: Apizr.Resiliencing
  nameWithType: Apizr.Resiliencing
  fullName: Apizr.Resiliencing
  spec.csharp:
  - uid: Apizr
    name: Apizr
    href: Apizr.html
  - name: .
  - uid: Apizr.Resiliencing
    name: Resiliencing
    href: Apizr.Resiliencing.html
  spec.vb:
  - uid: Apizr
    name: Apizr
    href: Apizr.html
  - name: .
  - uid: Apizr.Resiliencing
    name: Resiliencing
    href: Apizr.Resiliencing.html
- uid: System.ValueType.Equals(System.Object)
  commentId: M:System.ValueType.Equals(System.Object)
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  name: Equals(object)
  nameWithType: ValueType.Equals(object)
  fullName: System.ValueType.Equals(object)
  nameWithType.vb: ValueType.Equals(Object)
  fullName.vb: System.ValueType.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.ValueType.GetHashCode
  commentId: M:System.ValueType.GetHashCode
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  name: GetHashCode()
  nameWithType: ValueType.GetHashCode()
  fullName: System.ValueType.GetHashCode()
  spec.csharp:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
- uid: System.ValueType.ToString
  commentId: M:System.ValueType.ToString
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  name: ToString()
  nameWithType: ValueType.ToString()
  fullName: System.ValueType.ToString()
  spec.csharp:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: Polly
  commentId: N:Polly
  isExternal: true
  name: Polly
  nameWithType: Polly
  fullName: Polly
- uid: System.ValueType
  commentId: T:System.ValueType
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype
  name: ValueType
  nameWithType: ValueType
  fullName: System.ValueType
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Apizr.Resiliencing.ApizrResilienceContextSettings
  commentId: T:Apizr.Resiliencing.ApizrResilienceContextSettings
  href: Apizr.Resiliencing.ApizrResilienceContextSettings.html
  name: ApizrResilienceContextSettings
  nameWithType: ApizrResilienceContextSettings
  fullName: Apizr.Resiliencing.ApizrResilienceContextSettings
- uid: Apizr.Resiliencing.ApizrResilienceContextSettings.#ctor*
  commentId: Overload:Apizr.Resiliencing.ApizrResilienceContextSettings.#ctor
  href: Apizr.Resiliencing.ApizrResilienceContextSettings.html#Apizr_Resiliencing_ApizrResilienceContextSettings__ctor_System_Nullable_System_Boolean__System_Nullable_System_Boolean__
  name: ApizrResilienceContextSettings
  nameWithType: ApizrResilienceContextSettings.ApizrResilienceContextSettings
  fullName: Apizr.Resiliencing.ApizrResilienceContextSettings.ApizrResilienceContextSettings
  nameWithType.vb: ApizrResilienceContextSettings.New
  fullName.vb: Apizr.Resiliencing.ApizrResilienceContextSettings.New
  name.vb: New
- uid: System.Nullable{System.Boolean}
  commentId: T:System.Nullable{System.Boolean}
  parent: System
  definition: System.Nullable`1
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool?
  nameWithType: bool?
  fullName: bool?
  nameWithType.vb: Boolean?
  fullName.vb: Boolean?
  name.vb: Boolean?
  spec.csharp:
  - uid: System.Boolean
    name: bool
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: '?'
  spec.vb:
  - uid: System.Boolean
    name: Boolean
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: '?'
- uid: System.Nullable`1
  commentId: T:System.Nullable`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.nullable-1
  name: Nullable<T>
  nameWithType: Nullable<T>
  fullName: System.Nullable<T>
  nameWithType.vb: Nullable(Of T)
  fullName.vb: System.Nullable(Of T)
  name.vb: Nullable(Of T)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.nullable-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.nullable-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: Apizr.Resiliencing.ApizrResilienceContextSettings.ContinueOnCapturedContext*
  commentId: Overload:Apizr.Resiliencing.ApizrResilienceContextSettings.ContinueOnCapturedContext
  href: Apizr.Resiliencing.ApizrResilienceContextSettings.html#Apizr_Resiliencing_ApizrResilienceContextSettings_ContinueOnCapturedContext
  name: ContinueOnCapturedContext
  nameWithType: ApizrResilienceContextSettings.ContinueOnCapturedContext
  fullName: Apizr.Resiliencing.ApizrResilienceContextSettings.ContinueOnCapturedContext
- uid: Apizr.Resiliencing.ApizrResilienceContextSettings.ReturnToPoolOnComplete*
  commentId: Overload:Apizr.Resiliencing.ApizrResilienceContextSettings.ReturnToPoolOnComplete
  href: Apizr.Resiliencing.ApizrResilienceContextSettings.html#Apizr_Resiliencing_ApizrResilienceContextSettings_ReturnToPoolOnComplete
  name: ReturnToPoolOnComplete
  nameWithType: ApizrResilienceContextSettings.ReturnToPoolOnComplete
  fullName: Apizr.Resiliencing.ApizrResilienceContextSettings.ReturnToPoolOnComplete
