### YamlMime:ManagedReference
items:
- uid: Apizr.Configuring.Registry.IApizrRegistryBuilderBase
  commentId: T:Apizr.Configuring.Registry.IApizrRegistryBuilderBase
  id: IApizrRegistryBuilderBase
  parent: Apizr.Configuring.Registry
  children: []
  langs:
  - csharp
  - vb
  name: IApizrRegistryBuilderBase
  nameWithType: IApizrRegistryBuilderBase
  fullName: Apizr.Configuring.Registry.IApizrRegistryBuilderBase
  type: Interface
  source:
    remote:
      path: Apizr/Src/Apizr/Configuring/Registry/IApizrRegistryBuilderBase.cs
      branch: feat/response
      repo: https://github.com/Respawnsive/Apizr.git
    id: IApizrRegistryBuilderBase
    path: ../../Src/Apizr/Configuring/Registry/IApizrRegistryBuilderBase.cs
    startLine: 10
  assemblies:
  - Apizr
  namespace: Apizr.Configuring.Registry
  summary: Registry builder options available for both static and extended registrations
  example: []
  syntax:
    content: public interface IApizrRegistryBuilderBase
    content.vb: Public Interface IApizrRegistryBuilderBase
references:
- uid: Apizr.Configuring.Registry
  commentId: N:Apizr.Configuring.Registry
  href: Apizr.html
  name: Apizr.Configuring.Registry
  nameWithType: Apizr.Configuring.Registry
  fullName: Apizr.Configuring.Registry
  spec.csharp:
  - uid: Apizr
    name: Apizr
    href: Apizr.html
  - name: .
  - uid: Apizr.Configuring
    name: Configuring
    href: Apizr.Configuring.html
  - name: .
  - uid: Apizr.Configuring.Registry
    name: Registry
    href: Apizr.Configuring.Registry.html
  spec.vb:
  - uid: Apizr
    name: Apizr
    href: Apizr.html
  - name: .
  - uid: Apizr.Configuring
    name: Configuring
    href: Apizr.Configuring.html
  - name: .
  - uid: Apizr.Configuring.Registry
    name: Registry
    href: Apizr.Configuring.Registry.html
