### YamlMime:ManagedReference
items:
- uid: Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistryBase
  commentId: T:Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistryBase
  id: IApizrExtendedConcurrentRegistryBase
  parent: Apizr.Extending.Configuring.Registry
  children:
  - Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistryBase.AddOrUpdateManager(System.Type)
  langs:
  - csharp
  - vb
  name: IApizrExtendedConcurrentRegistryBase
  nameWithType: IApizrExtendedConcurrentRegistryBase
  fullName: Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistryBase
  type: Interface
  source:
    remote:
      path: Apizr/Src/Apizr.Extensions.Microsoft.DependencyInjection/Extending/Configuring/Registry/IApizrExtendedConcurrentRegistryBase.cs
      branch: lab
      repo: https://github.com/Respawnsive/Apizr.git
    id: IApizrExtendedConcurrentRegistryBase
    path: ../../Src/Apizr.Extensions.Microsoft.DependencyInjection/Extending/Configuring/Registry/IApizrExtendedConcurrentRegistryBase.cs
    startLine: 7
  assemblies:
  - Apizr.Extensions.Microsoft.DependencyInjection
  namespace: Apizr.Extending.Configuring.Registry
  summary: Registry options available for extended registrations
  example: []
  syntax:
    content: public interface IApizrExtendedConcurrentRegistryBase
    content.vb: Public Interface IApizrExtendedConcurrentRegistryBase
- uid: Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistryBase.AddOrUpdateManager(System.Type)
  commentId: M:Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistryBase.AddOrUpdateManager(System.Type)
  id: AddOrUpdateManager(System.Type)
  parent: Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistryBase
  langs:
  - csharp
  - vb
  name: AddOrUpdateManager(Type)
  nameWithType: IApizrExtendedConcurrentRegistryBase.AddOrUpdateManager(Type)
  fullName: Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistryBase.AddOrUpdateManager(System.Type)
  type: Method
  source:
    remote:
      path: Apizr/Src/Apizr.Extensions.Microsoft.DependencyInjection/Extending/Configuring/Registry/IApizrExtendedConcurrentRegistryBase.cs
      branch: lab
      repo: https://github.com/Respawnsive/Apizr.git
    id: AddOrUpdateManager
    path: ../../Src/Apizr.Extensions.Microsoft.DependencyInjection/Extending/Configuring/Registry/IApizrExtendedConcurrentRegistryBase.cs
    startLine: 9
  assemblies:
  - Apizr.Extensions.Microsoft.DependencyInjection
  namespace: Apizr.Extending.Configuring.Registry
  syntax:
    content: void AddOrUpdateManager(Type managerType)
    parameters:
    - id: managerType
      type: System.Type
    content.vb: Sub AddOrUpdateManager(managerType As Type)
  overload: Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistryBase.AddOrUpdateManager*
references:
- uid: Apizr.Extending.Configuring.Registry
  commentId: N:Apizr.Extending.Configuring.Registry
  href: Apizr.html
  name: Apizr.Extending.Configuring.Registry
  nameWithType: Apizr.Extending.Configuring.Registry
  fullName: Apizr.Extending.Configuring.Registry
  spec.csharp:
  - uid: Apizr
    name: Apizr
    href: Apizr.html
  - name: .
  - uid: Apizr.Extending
    name: Extending
    href: Apizr.Extending.html
  - name: .
  - uid: Apizr.Extending.Configuring
    name: Configuring
    href: Apizr.Extending.Configuring.html
  - name: .
  - uid: Apizr.Extending.Configuring.Registry
    name: Registry
    href: Apizr.Extending.Configuring.Registry.html
  spec.vb:
  - uid: Apizr
    name: Apizr
    href: Apizr.html
  - name: .
  - uid: Apizr.Extending
    name: Extending
    href: Apizr.Extending.html
  - name: .
  - uid: Apizr.Extending.Configuring
    name: Configuring
    href: Apizr.Extending.Configuring.html
  - name: .
  - uid: Apizr.Extending.Configuring.Registry
    name: Registry
    href: Apizr.Extending.Configuring.Registry.html
- uid: Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistryBase.AddOrUpdateManager*
  commentId: Overload:Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistryBase.AddOrUpdateManager
  href: Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistryBase.html#Apizr_Extending_Configuring_Registry_IApizrExtendedConcurrentRegistryBase_AddOrUpdateManager_System_Type_
  name: AddOrUpdateManager
  nameWithType: IApizrExtendedConcurrentRegistryBase.AddOrUpdateManager
  fullName: Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistryBase.AddOrUpdateManager
- uid: System.Type
  commentId: T:System.Type
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.type
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
