### YamlMime:ManagedReference
items:
- uid: Apizr.Configuring.Common.ApizrCommonOptionsBase
  commentId: T:Apizr.Configuring.Common.ApizrCommonOptionsBase
  id: ApizrCommonOptionsBase
  parent: Apizr.Configuring.Common
  children:
  - Apizr.Configuring.Common.ApizrCommonOptionsBase.#ctor
  - Apizr.Configuring.Common.ApizrCommonOptionsBase.RefitSettings
  langs:
  - csharp
  - vb
  name: ApizrCommonOptionsBase
  nameWithType: ApizrCommonOptionsBase
  fullName: Apizr.Configuring.Common.ApizrCommonOptionsBase
  type: Class
  source:
    id: ApizrCommonOptionsBase
    path: C:\Dev\Community\Apizr\Apizr\Apizr\Configuring\Common\ApizrCommonOptionsBase.cs
    startLine: 5
  assemblies:
  - Apizr
  namespace: Apizr.Configuring.Common
  syntax:
    content: 'public abstract class ApizrCommonOptionsBase : ApizrSharedOptionsBase, IApizrCommonOptionsBase, IApizrSharedOptionsBase'
    content.vb: >-
      Public MustInherit Class ApizrCommonOptionsBase
          Inherits ApizrSharedOptionsBase
          Implements IApizrCommonOptionsBase, IApizrSharedOptionsBase
  inheritance:
  - System.Object
  - Apizr.Configuring.Shared.ApizrSharedOptionsBase
  derivedClasses:
  - Apizr.Configuring.Common.ApizrCommonOptions
  - Apizr.Extending.Configuring.Common.ApizrExtendedCommonOptions
  implements:
  - Apizr.Configuring.Common.IApizrCommonOptionsBase
  - Apizr.Configuring.Shared.IApizrSharedOptionsBase
  inheritedMembers:
  - Apizr.Configuring.Shared.ApizrSharedOptionsBase.BaseUri
  - Apizr.Configuring.Shared.ApizrSharedOptionsBase.BaseAddress
  - Apizr.Configuring.Shared.ApizrSharedOptionsBase.BasePath
  - Apizr.Configuring.Shared.ApizrSharedOptionsBase.HttpTracerMode
  - Apizr.Configuring.Shared.ApizrSharedOptionsBase.TrafficVerbosity
  - Apizr.Configuring.Shared.ApizrSharedOptionsBase.LogLevels
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  extensionMethods:
  - System.Object.Apizr.Extending.ObjectExtensions.ToString(System.String,System.String)
  modifiers.csharp:
  - public
  - abstract
  - class
  modifiers.vb:
  - Public
  - MustInherit
  - Class
- uid: Apizr.Configuring.Common.ApizrCommonOptionsBase.#ctor
  commentId: M:Apizr.Configuring.Common.ApizrCommonOptionsBase.#ctor
  id: '#ctor'
  parent: Apizr.Configuring.Common.ApizrCommonOptionsBase
  langs:
  - csharp
  - vb
  name: ApizrCommonOptionsBase()
  nameWithType: ApizrCommonOptionsBase.ApizrCommonOptionsBase()
  fullName: Apizr.Configuring.Common.ApizrCommonOptionsBase.ApizrCommonOptionsBase()
  type: Constructor
  source:
    id: .ctor
    path: C:\Dev\Community\Apizr\Apizr\Apizr\Configuring\Common\ApizrCommonOptionsBase.cs
    startLine: 7
  assemblies:
  - Apizr
  namespace: Apizr.Configuring.Common
  syntax:
    content: protected ApizrCommonOptionsBase()
    content.vb: Protected Sub New
  overload: Apizr.Configuring.Common.ApizrCommonOptionsBase.#ctor*
  modifiers.csharp:
  - protected
  modifiers.vb:
  - Protected
- uid: Apizr.Configuring.Common.ApizrCommonOptionsBase.RefitSettings
  commentId: P:Apizr.Configuring.Common.ApizrCommonOptionsBase.RefitSettings
  id: RefitSettings
  parent: Apizr.Configuring.Common.ApizrCommonOptionsBase
  langs:
  - csharp
  - vb
  name: RefitSettings
  nameWithType: ApizrCommonOptionsBase.RefitSettings
  fullName: Apizr.Configuring.Common.ApizrCommonOptionsBase.RefitSettings
  type: Property
  source:
    id: RefitSettings
    path: C:\Dev\Community\Apizr\Apizr\Apizr\Configuring\Common\ApizrCommonOptionsBase.cs
    startLine: 11
  assemblies:
  - Apizr
  namespace: Apizr.Configuring.Common
  syntax:
    content: public RefitSettings RefitSettings { get; protected set; }
    parameters: []
    return:
      type: Refit.RefitSettings
    content.vb: Public Property RefitSettings As RefitSettings
  overload: Apizr.Configuring.Common.ApizrCommonOptionsBase.RefitSettings*
  implements:
  - Apizr.Configuring.Common.IApizrCommonOptionsBase.RefitSettings
  modifiers.csharp:
  - public
  - get
  - protected set
  modifiers.vb:
  - Public
  - Get
  - Protected Set
references:
- uid: Apizr.Configuring.Common
  commentId: N:Apizr.Configuring.Common
  name: Apizr.Configuring.Common
  nameWithType: Apizr.Configuring.Common
  fullName: Apizr.Configuring.Common
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Apizr.Configuring.Shared.ApizrSharedOptionsBase
  commentId: T:Apizr.Configuring.Shared.ApizrSharedOptionsBase
  parent: Apizr.Configuring.Shared
  name: ApizrSharedOptionsBase
  nameWithType: ApizrSharedOptionsBase
  fullName: Apizr.Configuring.Shared.ApizrSharedOptionsBase
- uid: Apizr.Configuring.Common.IApizrCommonOptionsBase
  commentId: T:Apizr.Configuring.Common.IApizrCommonOptionsBase
  parent: Apizr.Configuring.Common
  name: IApizrCommonOptionsBase
  nameWithType: IApizrCommonOptionsBase
  fullName: Apizr.Configuring.Common.IApizrCommonOptionsBase
- uid: Apizr.Configuring.Shared.IApizrSharedOptionsBase
  commentId: T:Apizr.Configuring.Shared.IApizrSharedOptionsBase
  parent: Apizr.Configuring.Shared
  name: IApizrSharedOptionsBase
  nameWithType: IApizrSharedOptionsBase
  fullName: Apizr.Configuring.Shared.IApizrSharedOptionsBase
- uid: Apizr.Configuring.Shared.ApizrSharedOptionsBase.BaseUri
  commentId: P:Apizr.Configuring.Shared.ApizrSharedOptionsBase.BaseUri
  parent: Apizr.Configuring.Shared.ApizrSharedOptionsBase
  name: BaseUri
  nameWithType: ApizrSharedOptionsBase.BaseUri
  fullName: Apizr.Configuring.Shared.ApizrSharedOptionsBase.BaseUri
- uid: Apizr.Configuring.Shared.ApizrSharedOptionsBase.BaseAddress
  commentId: P:Apizr.Configuring.Shared.ApizrSharedOptionsBase.BaseAddress
  parent: Apizr.Configuring.Shared.ApizrSharedOptionsBase
  name: BaseAddress
  nameWithType: ApizrSharedOptionsBase.BaseAddress
  fullName: Apizr.Configuring.Shared.ApizrSharedOptionsBase.BaseAddress
- uid: Apizr.Configuring.Shared.ApizrSharedOptionsBase.BasePath
  commentId: P:Apizr.Configuring.Shared.ApizrSharedOptionsBase.BasePath
  parent: Apizr.Configuring.Shared.ApizrSharedOptionsBase
  name: BasePath
  nameWithType: ApizrSharedOptionsBase.BasePath
  fullName: Apizr.Configuring.Shared.ApizrSharedOptionsBase.BasePath
- uid: Apizr.Configuring.Shared.ApizrSharedOptionsBase.HttpTracerMode
  commentId: P:Apizr.Configuring.Shared.ApizrSharedOptionsBase.HttpTracerMode
  parent: Apizr.Configuring.Shared.ApizrSharedOptionsBase
  name: HttpTracerMode
  nameWithType: ApizrSharedOptionsBase.HttpTracerMode
  fullName: Apizr.Configuring.Shared.ApizrSharedOptionsBase.HttpTracerMode
- uid: Apizr.Configuring.Shared.ApizrSharedOptionsBase.TrafficVerbosity
  commentId: P:Apizr.Configuring.Shared.ApizrSharedOptionsBase.TrafficVerbosity
  parent: Apizr.Configuring.Shared.ApizrSharedOptionsBase
  name: TrafficVerbosity
  nameWithType: ApizrSharedOptionsBase.TrafficVerbosity
  fullName: Apizr.Configuring.Shared.ApizrSharedOptionsBase.TrafficVerbosity
- uid: Apizr.Configuring.Shared.ApizrSharedOptionsBase.LogLevels
  commentId: P:Apizr.Configuring.Shared.ApizrSharedOptionsBase.LogLevels
  parent: Apizr.Configuring.Shared.ApizrSharedOptionsBase
  name: LogLevels
  nameWithType: ApizrSharedOptionsBase.LogLevels
  fullName: Apizr.Configuring.Shared.ApizrSharedOptionsBase.LogLevels
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Apizr.Extending.ObjectExtensions.ToString(System.String,System.String)
  commentId: M:Apizr.Extending.ObjectExtensions.ToString(System.Object,System.String,System.String)
  parent: Apizr.Extending.ObjectExtensions
  definition: Apizr.Extending.ObjectExtensions.ToString(System.Object,System.String,System.String)
  name: ToString(String, String)
  nameWithType: ObjectExtensions.ToString(String, String)
  fullName: Apizr.Extending.ObjectExtensions.ToString(System.String, System.String)
  spec.csharp:
  - uid: Apizr.Extending.ObjectExtensions.ToString(System.String,System.String)
    name: ToString
    nameWithType: ObjectExtensions.ToString
    fullName: Apizr.Extending.ObjectExtensions.ToString
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Apizr.Extending.ObjectExtensions.ToString(System.String,System.String)
    name: ToString
    nameWithType: ObjectExtensions.ToString
    fullName: Apizr.Extending.ObjectExtensions.ToString
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Apizr.Configuring.Shared
  commentId: N:Apizr.Configuring.Shared
  name: Apizr.Configuring.Shared
  nameWithType: Apizr.Configuring.Shared
  fullName: Apizr.Configuring.Shared
- uid: Apizr.Extending.ObjectExtensions.ToString(System.Object,System.String,System.String)
  commentId: M:Apizr.Extending.ObjectExtensions.ToString(System.Object,System.String,System.String)
  isExternal: true
  name: ToString(Object, String, String)
  nameWithType: ObjectExtensions.ToString(Object, String, String)
  fullName: Apizr.Extending.ObjectExtensions.ToString(System.Object, System.String, System.String)
  spec.csharp:
  - uid: Apizr.Extending.ObjectExtensions.ToString(System.Object,System.String,System.String)
    name: ToString
    nameWithType: ObjectExtensions.ToString
    fullName: Apizr.Extending.ObjectExtensions.ToString
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Apizr.Extending.ObjectExtensions.ToString(System.Object,System.String,System.String)
    name: ToString
    nameWithType: ObjectExtensions.ToString
    fullName: Apizr.Extending.ObjectExtensions.ToString
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Apizr.Extending.ObjectExtensions
  commentId: T:Apizr.Extending.ObjectExtensions
  parent: Apizr.Extending
  name: ObjectExtensions
  nameWithType: ObjectExtensions
  fullName: Apizr.Extending.ObjectExtensions
- uid: Apizr.Extending
  commentId: N:Apizr.Extending
  name: Apizr.Extending
  nameWithType: Apizr.Extending
  fullName: Apizr.Extending
- uid: Apizr.Configuring.Common.ApizrCommonOptionsBase.#ctor*
  commentId: Overload:Apizr.Configuring.Common.ApizrCommonOptionsBase.#ctor
  name: ApizrCommonOptionsBase
  nameWithType: ApizrCommonOptionsBase.ApizrCommonOptionsBase
  fullName: Apizr.Configuring.Common.ApizrCommonOptionsBase.ApizrCommonOptionsBase
- uid: Apizr.Configuring.Common.ApizrCommonOptionsBase.RefitSettings*
  commentId: Overload:Apizr.Configuring.Common.ApizrCommonOptionsBase.RefitSettings
  name: RefitSettings
  nameWithType: ApizrCommonOptionsBase.RefitSettings
  fullName: Apizr.Configuring.Common.ApizrCommonOptionsBase.RefitSettings
- uid: Apizr.Configuring.Common.IApizrCommonOptionsBase.RefitSettings
  commentId: P:Apizr.Configuring.Common.IApizrCommonOptionsBase.RefitSettings
  parent: Apizr.Configuring.Common.IApizrCommonOptionsBase
  name: RefitSettings
  nameWithType: IApizrCommonOptionsBase.RefitSettings
  fullName: Apizr.Configuring.Common.IApizrCommonOptionsBase.RefitSettings
- uid: Refit.RefitSettings
  commentId: T:Refit.RefitSettings
  parent: Refit
  isExternal: true
  name: RefitSettings
  nameWithType: RefitSettings
  fullName: Refit.RefitSettings
- uid: Refit
  commentId: N:Refit
  isExternal: true
  name: Refit
  nameWithType: Refit
  fullName: Refit
