### YamlMime:ManagedReference
items:
- uid: Apizr.Configuring.Shared.IApizrSharedOptionsBuilderBase
  commentId: T:Apizr.Configuring.Shared.IApizrSharedOptionsBuilderBase
  id: IApizrSharedOptionsBuilderBase
  parent: Apizr.Configuring.Shared
  children: []
  langs:
  - csharp
  - vb
  name: IApizrSharedOptionsBuilderBase
  nameWithType: IApizrSharedOptionsBuilderBase
  fullName: Apizr.Configuring.Shared.IApizrSharedOptionsBuilderBase
  type: Interface
  source:
    id: IApizrSharedOptionsBuilderBase
    path: C:\Dev\Community\Apizr\Apizr\Apizr\Configuring\Shared\IApizrSharedOptionsBuilderBase.cs
    startLine: 7
  assemblies:
  - Apizr
  namespace: Apizr.Configuring.Shared
  summary: "\nBuilder options available at both common and proper level for both static and extended registrations\n"
  example: []
  syntax:
    content: 'public interface IApizrSharedOptionsBuilderBase : IApizrGlobalSharedOptionsBuilderBase'
    content.vb: >-
      Public Interface IApizrSharedOptionsBuilderBase
          Inherits IApizrGlobalSharedOptionsBuilderBase
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
references:
- uid: Apizr.Configuring.Shared
  commentId: N:Apizr.Configuring.Shared
  name: Apizr.Configuring.Shared
  nameWithType: Apizr.Configuring.Shared
  fullName: Apizr.Configuring.Shared
