### YamlMime:ManagedReference
items:
- uid: Apizr.Configuring.Common.IApizrCommonOptionsBase
  commentId: T:Apizr.Configuring.Common.IApizrCommonOptionsBase
  id: IApizrCommonOptionsBase
  parent: Apizr.Configuring.Common
  children:
  - Apizr.Configuring.Common.IApizrCommonOptionsBase.RefitSettings
  langs:
  - csharp
  - vb
  name: IApizrCommonOptionsBase
  nameWithType: IApizrCommonOptionsBase
  fullName: Apizr.Configuring.Common.IApizrCommonOptionsBase
  type: Interface
  source:
    remote:
      path: Apizr/Src/Apizr/Configuring/Common/IApizrCommonOptionsBase.cs
      branch: dev
      repo: https://github.com/Respawnsive/Apizr.git
    id: IApizrCommonOptionsBase
    path: ../../Src/Apizr/Configuring/Common/IApizrCommonOptionsBase.cs
    startLine: 8
  assemblies:
  - Apizr
  namespace: Apizr.Configuring.Common
  summary: "\nOptions available at common level for both static and extended registrations\n"
  example: []
  syntax:
    content: 'public interface IApizrCommonOptionsBase : IApizrSharedRegistrationOptionsBase, IApizrGlobalSharedRegistrationOptionsBase, IApizrGlobalSharedOptionsBase'
    content.vb: >-
      Public Interface IApizrCommonOptionsBase
          Inherits IApizrSharedRegistrationOptionsBase
  inheritedMembers:
  - Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase.BaseUri
  - Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase.BaseAddress
  - Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase.BasePath
  - Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase.ContextFactory
  - Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase.PrimaryHandlerFactory
  - Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.HttpTracerMode
  - Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.TrafficVerbosity
  - Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.LogLevels
  - Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.OnException
  - Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.LetThrowOnExceptionWithEmptyCache
  - Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.HandlersParameters
  - Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.Headers
  - Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.OperationTimeout
  - Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.RequestTimeout
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Apizr.Configuring.Common.IApizrCommonOptionsBase.RefitSettings
  commentId: P:Apizr.Configuring.Common.IApizrCommonOptionsBase.RefitSettings
  id: RefitSettings
  parent: Apizr.Configuring.Common.IApizrCommonOptionsBase
  langs:
  - csharp
  - vb
  name: RefitSettings
  nameWithType: IApizrCommonOptionsBase.RefitSettings
  fullName: Apizr.Configuring.Common.IApizrCommonOptionsBase.RefitSettings
  type: Property
  source:
    remote:
      path: Apizr/Src/Apizr/Configuring/Common/IApizrCommonOptionsBase.cs
      branch: dev
      repo: https://github.com/Respawnsive/Apizr.git
    id: RefitSettings
    path: ../../Src/Apizr/Configuring/Common/IApizrCommonOptionsBase.cs
    startLine: 13
  assemblies:
  - Apizr
  namespace: Apizr.Configuring.Common
  summary: "\nRefit settings\n"
  example: []
  syntax:
    content: RefitSettings RefitSettings { get; }
    parameters: []
    return:
      type: Refit.RefitSettings
    content.vb: ReadOnly Property RefitSettings As RefitSettings
  overload: Apizr.Configuring.Common.IApizrCommonOptionsBase.RefitSettings*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
references:
- uid: Apizr.Configuring.Common
  commentId: N:Apizr.Configuring.Common
  name: Apizr.Configuring.Common
  nameWithType: Apizr.Configuring.Common
  fullName: Apizr.Configuring.Common
- uid: Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase.BaseUri
  commentId: P:Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase.BaseUri
  parent: Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase
  name: BaseUri
  nameWithType: IApizrGlobalSharedRegistrationOptionsBase.BaseUri
  fullName: Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase.BaseUri
- uid: Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase.BaseAddress
  commentId: P:Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase.BaseAddress
  parent: Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase
  name: BaseAddress
  nameWithType: IApizrGlobalSharedRegistrationOptionsBase.BaseAddress
  fullName: Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase.BaseAddress
- uid: Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase.BasePath
  commentId: P:Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase.BasePath
  parent: Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase
  name: BasePath
  nameWithType: IApizrGlobalSharedRegistrationOptionsBase.BasePath
  fullName: Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase.BasePath
- uid: Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase.ContextFactory
  commentId: P:Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase.ContextFactory
  parent: Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase
  name: ContextFactory
  nameWithType: IApizrGlobalSharedRegistrationOptionsBase.ContextFactory
  fullName: Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase.ContextFactory
- uid: Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase.PrimaryHandlerFactory
  commentId: P:Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase.PrimaryHandlerFactory
  parent: Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase
  name: PrimaryHandlerFactory
  nameWithType: IApizrGlobalSharedRegistrationOptionsBase.PrimaryHandlerFactory
  fullName: Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase.PrimaryHandlerFactory
- uid: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.HttpTracerMode
  commentId: P:Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.HttpTracerMode
  parent: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase
  name: HttpTracerMode
  nameWithType: IApizrGlobalSharedOptionsBase.HttpTracerMode
  fullName: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.HttpTracerMode
- uid: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.TrafficVerbosity
  commentId: P:Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.TrafficVerbosity
  parent: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase
  name: TrafficVerbosity
  nameWithType: IApizrGlobalSharedOptionsBase.TrafficVerbosity
  fullName: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.TrafficVerbosity
- uid: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.LogLevels
  commentId: P:Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.LogLevels
  parent: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase
  name: LogLevels
  nameWithType: IApizrGlobalSharedOptionsBase.LogLevels
  fullName: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.LogLevels
- uid: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.OnException
  commentId: P:Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.OnException
  parent: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase
  name: OnException
  nameWithType: IApizrGlobalSharedOptionsBase.OnException
  fullName: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.OnException
- uid: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.LetThrowOnExceptionWithEmptyCache
  commentId: P:Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.LetThrowOnExceptionWithEmptyCache
  parent: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase
  name: LetThrowOnExceptionWithEmptyCache
  nameWithType: IApizrGlobalSharedOptionsBase.LetThrowOnExceptionWithEmptyCache
  fullName: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.LetThrowOnExceptionWithEmptyCache
- uid: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.HandlersParameters
  commentId: P:Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.HandlersParameters
  parent: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase
  name: HandlersParameters
  nameWithType: IApizrGlobalSharedOptionsBase.HandlersParameters
  fullName: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.HandlersParameters
- uid: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.Headers
  commentId: P:Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.Headers
  parent: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase
  name: Headers
  nameWithType: IApizrGlobalSharedOptionsBase.Headers
  fullName: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.Headers
- uid: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.OperationTimeout
  commentId: P:Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.OperationTimeout
  parent: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase
  name: OperationTimeout
  nameWithType: IApizrGlobalSharedOptionsBase.OperationTimeout
  fullName: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.OperationTimeout
- uid: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.RequestTimeout
  commentId: P:Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.RequestTimeout
  parent: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase
  name: RequestTimeout
  nameWithType: IApizrGlobalSharedOptionsBase.RequestTimeout
  fullName: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.RequestTimeout
- uid: Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase
  commentId: T:Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase
  parent: Apizr.Configuring.Shared
  name: IApizrGlobalSharedRegistrationOptionsBase
  nameWithType: IApizrGlobalSharedRegistrationOptionsBase
  fullName: Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase
- uid: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase
  commentId: T:Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase
  parent: Apizr.Configuring.Shared
  name: IApizrGlobalSharedOptionsBase
  nameWithType: IApizrGlobalSharedOptionsBase
  fullName: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase
- uid: Apizr.Configuring.Shared
  commentId: N:Apizr.Configuring.Shared
  name: Apizr.Configuring.Shared
  nameWithType: Apizr.Configuring.Shared
  fullName: Apizr.Configuring.Shared
- uid: Apizr.Configuring.Common.IApizrCommonOptionsBase.RefitSettings*
  commentId: Overload:Apizr.Configuring.Common.IApizrCommonOptionsBase.RefitSettings
  name: RefitSettings
  nameWithType: IApizrCommonOptionsBase.RefitSettings
  fullName: Apizr.Configuring.Common.IApizrCommonOptionsBase.RefitSettings
- uid: Refit.RefitSettings
  commentId: T:Refit.RefitSettings
  parent: Refit
  isExternal: true
  name: RefitSettings
  nameWithType: RefitSettings
  fullName: Refit.RefitSettings
- uid: Refit
  commentId: N:Refit
  isExternal: true
  name: Refit
  nameWithType: Refit
  fullName: Refit
