### YamlMime:ManagedReference
items:
- uid: Apizr.Mediation.Configuring.Registry
  commentId: N:Apizr.Mediation.Configuring.Registry
  id: Apizr.Mediation.Configuring.Registry
  children:
  - Apizr.Mediation.Configuring.Registry.ApizrMediationRegistry
  - Apizr.Mediation.Configuring.Registry.ApizrMediationRegistryBase
  - Apizr.Mediation.Configuring.Registry.IApizrMediationConcurrentRegistry
  - Apizr.Mediation.Configuring.Registry.IApizrMediationEnumerableRegistry
  - Apizr.Mediation.Configuring.Registry.IApizrMediationRegistry
  langs:
  - csharp
  - vb
  name: Apizr.Mediation.Configuring.Registry
  nameWithType: Apizr.Mediation.Configuring.Registry
  fullName: Apizr.Mediation.Configuring.Registry
  type: Namespace
  assemblies:
  - Apizr.Integrations.MediatR
references:
- uid: Apizr.Mediation.Configuring.Registry.ApizrMediationRegistry
  commentId: T:Apizr.Mediation.Configuring.Registry.ApizrMediationRegistry
  name: ApizrMediationRegistry
  nameWithType: ApizrMediationRegistry
  fullName: Apizr.Mediation.Configuring.Registry.ApizrMediationRegistry
- uid: Apizr.Mediation.Configuring.Registry.ApizrMediationRegistryBase
  commentId: T:Apizr.Mediation.Configuring.Registry.ApizrMediationRegistryBase
  parent: Apizr.Mediation.Configuring.Registry
  name: ApizrMediationRegistryBase
  nameWithType: ApizrMediationRegistryBase
  fullName: Apizr.Mediation.Configuring.Registry.ApizrMediationRegistryBase
- uid: Apizr.Mediation.Configuring.Registry.IApizrMediationConcurrentRegistry
  commentId: T:Apizr.Mediation.Configuring.Registry.IApizrMediationConcurrentRegistry
  parent: Apizr.Mediation.Configuring.Registry
  name: IApizrMediationConcurrentRegistry
  nameWithType: IApizrMediationConcurrentRegistry
  fullName: Apizr.Mediation.Configuring.Registry.IApizrMediationConcurrentRegistry
- uid: Apizr.Mediation.Configuring.Registry.IApizrMediationEnumerableRegistry
  commentId: T:Apizr.Mediation.Configuring.Registry.IApizrMediationEnumerableRegistry
  parent: Apizr.Mediation.Configuring.Registry
  name: IApizrMediationEnumerableRegistry
  nameWithType: IApizrMediationEnumerableRegistry
  fullName: Apizr.Mediation.Configuring.Registry.IApizrMediationEnumerableRegistry
- uid: Apizr.Mediation.Configuring.Registry.IApizrMediationRegistry
  commentId: T:Apizr.Mediation.Configuring.Registry.IApizrMediationRegistry
  parent: Apizr.Mediation.Configuring.Registry
  name: IApizrMediationRegistry
  nameWithType: IApizrMediationRegistry
  fullName: Apizr.Mediation.Configuring.Registry.IApizrMediationRegistry
- uid: Apizr.Mediation.Configuring.Registry
  commentId: N:Apizr.Mediation.Configuring.Registry
  name: Apizr.Mediation.Configuring.Registry
  nameWithType: Apizr.Mediation.Configuring.Registry
  fullName: Apizr.Mediation.Configuring.Registry
