### YamlMime:ManagedReference
items:
- uid: Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBuilderBase
  commentId: T:Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBuilderBase
  id: IApizrGlobalSharedRegistrationOptionsBuilderBase
  parent: Apizr.Configuring.Shared
  children: []
  langs:
  - csharp
  - vb
  name: IApizrGlobalSharedRegistrationOptionsBuilderBase
  nameWithType: IApizrGlobalSharedRegistrationOptionsBuilderBase
  fullName: Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBuilderBase
  type: Interface
  source:
    id: IApizrGlobalSharedRegistrationOptionsBuilderBase
    path: C:\Dev\Community\Apizr\Apizr\Apizr\Configuring\Shared\IApizrGlobalSharedRegistrationOptionsBuilderBase.cs
    startLine: 12
  assemblies:
  - Apizr
  namespace: Apizr.Configuring.Shared
  summary: "\nBuilder options available at both common and proper level for both static and extended registrations\n"
  example: []
  syntax:
    content: 'public interface IApizrGlobalSharedRegistrationOptionsBuilderBase : IApizrGlobalSharedOptionsBuilderBase'
    content.vb: >-
      Public Interface IApizrGlobalSharedRegistrationOptionsBuilderBase
          Inherits IApizrGlobalSharedOptionsBuilderBase
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
references:
- uid: Apizr.Configuring.Shared
  commentId: N:Apizr.Configuring.Shared
  name: Apizr.Configuring.Shared
  nameWithType: Apizr.Configuring.Shared
  fullName: Apizr.Configuring.Shared
