### YamlMime:ManagedReference
items:
- uid: Apizr.Extending.Configuring.Proper
  commentId: N:Apizr.Extending.Configuring.Proper
  id: Apizr.Extending.Configuring.Proper
  children:
  - Apizr.Extending.Configuring.Proper.ApizrExtendedProperOptions
  - Apizr.Extending.Configuring.Proper.ApizrExtendedProperOptionsBuilder
  - Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptions
  - Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBase
  - Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBuilder
  - Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBuilder`2
  langs:
  - csharp
  - vb
  name: Apizr.Extending.Configuring.Proper
  nameWithType: Apizr.Extending.Configuring.Proper
  fullName: Apizr.Extending.Configuring.Proper
  type: Namespace
  assemblies:
  - Apizr.Extensions.Microsoft.DependencyInjection
references:
- uid: Apizr.Extending.Configuring.Proper.ApizrExtendedProperOptions
  commentId: T:Apizr.Extending.Configuring.Proper.ApizrExtendedProperOptions
  parent: Apizr.Extending.Configuring.Proper
  name: ApizrExtendedProperOptions
  nameWithType: ApizrExtendedProperOptions
  fullName: Apizr.Extending.Configuring.Proper.ApizrExtendedProperOptions
- uid: Apizr.Extending.Configuring.Proper.ApizrExtendedProperOptionsBuilder
  commentId: T:Apizr.Extending.Configuring.Proper.ApizrExtendedProperOptionsBuilder
  name: ApizrExtendedProperOptionsBuilder
  nameWithType: ApizrExtendedProperOptionsBuilder
  fullName: Apizr.Extending.Configuring.Proper.ApizrExtendedProperOptionsBuilder
- uid: Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptions
  commentId: T:Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptions
  parent: Apizr.Extending.Configuring.Proper
  name: IApizrExtendedProperOptions
  nameWithType: IApizrExtendedProperOptions
  fullName: Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptions
- uid: Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBase
  commentId: T:Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBase
  parent: Apizr.Extending.Configuring.Proper
  name: IApizrExtendedProperOptionsBase
  nameWithType: IApizrExtendedProperOptionsBase
  fullName: Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBase
- uid: Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBuilder`2
  commentId: T:Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBuilder`2
  name: IApizrExtendedProperOptionsBuilder<TApizrExtendedProperOptions, TApizrExtendedProperOptionsBuilder>
  nameWithType: IApizrExtendedProperOptionsBuilder<TApizrExtendedProperOptions, TApizrExtendedProperOptionsBuilder>
  fullName: Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBuilder<TApizrExtendedProperOptions, TApizrExtendedProperOptionsBuilder>
  nameWithType.vb: IApizrExtendedProperOptionsBuilder(Of TApizrExtendedProperOptions, TApizrExtendedProperOptionsBuilder)
  fullName.vb: Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBuilder(Of TApizrExtendedProperOptions, TApizrExtendedProperOptionsBuilder)
  name.vb: IApizrExtendedProperOptionsBuilder(Of TApizrExtendedProperOptions, TApizrExtendedProperOptionsBuilder)
  spec.csharp:
  - uid: Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBuilder`2
    name: IApizrExtendedProperOptionsBuilder
    nameWithType: IApizrExtendedProperOptionsBuilder
    fullName: Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBuilder
  - name: <
    nameWithType: <
    fullName: <
  - name: TApizrExtendedProperOptions
    nameWithType: TApizrExtendedProperOptions
    fullName: TApizrExtendedProperOptions
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TApizrExtendedProperOptionsBuilder
    nameWithType: TApizrExtendedProperOptionsBuilder
    fullName: TApizrExtendedProperOptionsBuilder
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBuilder`2
    name: IApizrExtendedProperOptionsBuilder
    nameWithType: IApizrExtendedProperOptionsBuilder
    fullName: Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBuilder
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TApizrExtendedProperOptions
    nameWithType: TApizrExtendedProperOptions
    fullName: TApizrExtendedProperOptions
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TApizrExtendedProperOptionsBuilder
    nameWithType: TApizrExtendedProperOptionsBuilder
    fullName: TApizrExtendedProperOptionsBuilder
  - name: )
    nameWithType: )
    fullName: )
- uid: Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBuilder
  commentId: T:Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBuilder
  parent: Apizr.Extending.Configuring.Proper
  name: IApizrExtendedProperOptionsBuilder
  nameWithType: IApizrExtendedProperOptionsBuilder
  fullName: Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBuilder
- uid: Apizr.Extending.Configuring.Proper
  commentId: N:Apizr.Extending.Configuring.Proper
  name: Apizr.Extending.Configuring.Proper
  nameWithType: Apizr.Extending.Configuring.Proper
  fullName: Apizr.Extending.Configuring.Proper
