### YamlMime:ManagedReference
items:
- uid: Apizr.Configuring.Manager
  commentId: N:Apizr.Configuring.Manager
  id: Apizr.Configuring.Manager
  children:
  - Apizr.Configuring.Manager.ApizrManagerOptions
  - Apizr.Configuring.Manager.ApizrManagerOptionsBase
  - Apizr.Configuring.Manager.ApizrManagerOptionsBuilder
  - Apizr.Configuring.Manager.ApizrManagerOptions`1
  - Apizr.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase
  - Apizr.Configuring.Manager.IApizrGlobalManagerOptionsBuilderBase
  - Apizr.Configuring.Manager.IApizrGlobalManagerOptionsBuilderBase`2
  - Apizr.Configuring.Manager.IApizrManagerOptions
  - Apizr.Configuring.Manager.IApizrManagerOptionsBase
  - Apizr.Configuring.Manager.IApizrManagerOptionsBuilder
  - Apizr.Configuring.Manager.IApizrManagerOptionsBuilderBase
  - Apizr.Configuring.Manager.IApizrManagerOptionsBuilderBase`2
  - Apizr.Configuring.Manager.IApizrManagerOptionsBuilder`2
  - Apizr.Configuring.Manager.IApizrManagerOptions`1
  langs:
  - csharp
  - vb
  name: Apizr.Configuring.Manager
  nameWithType: Apizr.Configuring.Manager
  fullName: Apizr.Configuring.Manager
  type: Namespace
  assemblies:
  - Apizr
references:
- uid: Apizr.Configuring.Manager.ApizrManagerOptions
  commentId: T:Apizr.Configuring.Manager.ApizrManagerOptions
  parent: Apizr.Configuring.Manager
  href: Apizr.Configuring.Manager.ApizrManagerOptions.html
  name: ApizrManagerOptions
  nameWithType: ApizrManagerOptions
  fullName: Apizr.Configuring.Manager.ApizrManagerOptions
- uid: Apizr.Configuring.Manager.ApizrManagerOptions`1
  commentId: T:Apizr.Configuring.Manager.ApizrManagerOptions`1
  href: Apizr.Configuring.Manager.ApizrManagerOptions-1.html
  name: ApizrManagerOptions<TWebApi>
  nameWithType: ApizrManagerOptions<TWebApi>
  fullName: Apizr.Configuring.Manager.ApizrManagerOptions<TWebApi>
  nameWithType.vb: ApizrManagerOptions(Of TWebApi)
  fullName.vb: Apizr.Configuring.Manager.ApizrManagerOptions(Of TWebApi)
  name.vb: ApizrManagerOptions(Of TWebApi)
  spec.csharp:
  - uid: Apizr.Configuring.Manager.ApizrManagerOptions`1
    name: ApizrManagerOptions
    href: Apizr.Configuring.Manager.ApizrManagerOptions-1.html
  - name: <
  - name: TWebApi
  - name: '>'
  spec.vb:
  - uid: Apizr.Configuring.Manager.ApizrManagerOptions`1
    name: ApizrManagerOptions
    href: Apizr.Configuring.Manager.ApizrManagerOptions-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TWebApi
  - name: )
- uid: Apizr.Configuring.Manager.ApizrManagerOptionsBase
  commentId: T:Apizr.Configuring.Manager.ApizrManagerOptionsBase
  parent: Apizr.Configuring.Manager
  href: Apizr.Configuring.Manager.ApizrManagerOptionsBase.html
  name: ApizrManagerOptionsBase
  nameWithType: ApizrManagerOptionsBase
  fullName: Apizr.Configuring.Manager.ApizrManagerOptionsBase
- uid: Apizr.Configuring.Manager.ApizrManagerOptionsBuilder
  commentId: T:Apizr.Configuring.Manager.ApizrManagerOptionsBuilder
  href: Apizr.Configuring.Manager.ApizrManagerOptionsBuilder.html
  name: ApizrManagerOptionsBuilder
  nameWithType: ApizrManagerOptionsBuilder
  fullName: Apizr.Configuring.Manager.ApizrManagerOptionsBuilder
- uid: Apizr.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase
  commentId: T:Apizr.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase
  href: Apizr.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase.html
  name: IApizrExtendedManagerOptionsBuilderBase
  nameWithType: IApizrExtendedManagerOptionsBuilderBase
  fullName: Apizr.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase
- uid: Apizr.Configuring.Manager.IApizrGlobalManagerOptionsBuilderBase
  commentId: T:Apizr.Configuring.Manager.IApizrGlobalManagerOptionsBuilderBase
  parent: Apizr.Configuring.Manager
  href: Apizr.Configuring.Manager.IApizrGlobalManagerOptionsBuilderBase.html
  name: IApizrGlobalManagerOptionsBuilderBase
  nameWithType: IApizrGlobalManagerOptionsBuilderBase
  fullName: Apizr.Configuring.Manager.IApizrGlobalManagerOptionsBuilderBase
- uid: Apizr.Configuring.Manager.IApizrGlobalManagerOptionsBuilderBase`2
  commentId: T:Apizr.Configuring.Manager.IApizrGlobalManagerOptionsBuilderBase`2
  href: Apizr.Configuring.Manager.IApizrGlobalManagerOptionsBuilderBase-2.html
  name: IApizrGlobalManagerOptionsBuilderBase<TApizrOptions, TApizrOptionsBuilder>
  nameWithType: IApizrGlobalManagerOptionsBuilderBase<TApizrOptions, TApizrOptionsBuilder>
  fullName: Apizr.Configuring.Manager.IApizrGlobalManagerOptionsBuilderBase<TApizrOptions, TApizrOptionsBuilder>
  nameWithType.vb: IApizrGlobalManagerOptionsBuilderBase(Of TApizrOptions, TApizrOptionsBuilder)
  fullName.vb: Apizr.Configuring.Manager.IApizrGlobalManagerOptionsBuilderBase(Of TApizrOptions, TApizrOptionsBuilder)
  name.vb: IApizrGlobalManagerOptionsBuilderBase(Of TApizrOptions, TApizrOptionsBuilder)
  spec.csharp:
  - uid: Apizr.Configuring.Manager.IApizrGlobalManagerOptionsBuilderBase`2
    name: IApizrGlobalManagerOptionsBuilderBase
    href: Apizr.Configuring.Manager.IApizrGlobalManagerOptionsBuilderBase-2.html
  - name: <
  - name: TApizrOptions
  - name: ','
  - name: " "
  - name: TApizrOptionsBuilder
  - name: '>'
  spec.vb:
  - uid: Apizr.Configuring.Manager.IApizrGlobalManagerOptionsBuilderBase`2
    name: IApizrGlobalManagerOptionsBuilderBase
    href: Apizr.Configuring.Manager.IApizrGlobalManagerOptionsBuilderBase-2.html
  - name: (
  - name: Of
  - name: " "
  - name: TApizrOptions
  - name: ','
  - name: " "
  - name: TApizrOptionsBuilder
  - name: )
- uid: Apizr.Configuring.Manager.IApizrManagerOptions
  commentId: T:Apizr.Configuring.Manager.IApizrManagerOptions
  parent: Apizr.Configuring.Manager
  href: Apizr.Configuring.Manager.IApizrManagerOptions.html
  name: IApizrManagerOptions
  nameWithType: IApizrManagerOptions
  fullName: Apizr.Configuring.Manager.IApizrManagerOptions
- uid: Apizr.Configuring.Manager.IApizrManagerOptions`1
  commentId: T:Apizr.Configuring.Manager.IApizrManagerOptions`1
  href: Apizr.Configuring.Manager.IApizrManagerOptions-1.html
  name: IApizrManagerOptions<TWebApi>
  nameWithType: IApizrManagerOptions<TWebApi>
  fullName: Apizr.Configuring.Manager.IApizrManagerOptions<TWebApi>
  nameWithType.vb: IApizrManagerOptions(Of TWebApi)
  fullName.vb: Apizr.Configuring.Manager.IApizrManagerOptions(Of TWebApi)
  name.vb: IApizrManagerOptions(Of TWebApi)
  spec.csharp:
  - uid: Apizr.Configuring.Manager.IApizrManagerOptions`1
    name: IApizrManagerOptions
    href: Apizr.Configuring.Manager.IApizrManagerOptions-1.html
  - name: <
  - name: TWebApi
  - name: '>'
  spec.vb:
  - uid: Apizr.Configuring.Manager.IApizrManagerOptions`1
    name: IApizrManagerOptions
    href: Apizr.Configuring.Manager.IApizrManagerOptions-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TWebApi
  - name: )
- uid: Apizr.Configuring.Manager.IApizrManagerOptionsBase
  commentId: T:Apizr.Configuring.Manager.IApizrManagerOptionsBase
  parent: Apizr.Configuring.Manager
  href: Apizr.Configuring.Manager.IApizrManagerOptionsBase.html
  name: IApizrManagerOptionsBase
  nameWithType: IApizrManagerOptionsBase
  fullName: Apizr.Configuring.Manager.IApizrManagerOptionsBase
- uid: Apizr.Configuring.Manager.IApizrManagerOptionsBuilder`2
  commentId: T:Apizr.Configuring.Manager.IApizrManagerOptionsBuilder`2
  href: Apizr.Configuring.Manager.IApizrManagerOptionsBuilder-2.html
  name: IApizrManagerOptionsBuilder<TApizrOptions, TApizrOptionsBuilder>
  nameWithType: IApizrManagerOptionsBuilder<TApizrOptions, TApizrOptionsBuilder>
  fullName: Apizr.Configuring.Manager.IApizrManagerOptionsBuilder<TApizrOptions, TApizrOptionsBuilder>
  nameWithType.vb: IApizrManagerOptionsBuilder(Of TApizrOptions, TApizrOptionsBuilder)
  fullName.vb: Apizr.Configuring.Manager.IApizrManagerOptionsBuilder(Of TApizrOptions, TApizrOptionsBuilder)
  name.vb: IApizrManagerOptionsBuilder(Of TApizrOptions, TApizrOptionsBuilder)
  spec.csharp:
  - uid: Apizr.Configuring.Manager.IApizrManagerOptionsBuilder`2
    name: IApizrManagerOptionsBuilder
    href: Apizr.Configuring.Manager.IApizrManagerOptionsBuilder-2.html
  - name: <
  - name: TApizrOptions
  - name: ','
  - name: " "
  - name: TApizrOptionsBuilder
  - name: '>'
  spec.vb:
  - uid: Apizr.Configuring.Manager.IApizrManagerOptionsBuilder`2
    name: IApizrManagerOptionsBuilder
    href: Apizr.Configuring.Manager.IApizrManagerOptionsBuilder-2.html
  - name: (
  - name: Of
  - name: " "
  - name: TApizrOptions
  - name: ','
  - name: " "
  - name: TApizrOptionsBuilder
  - name: )
- uid: Apizr.Configuring.Manager.IApizrManagerOptionsBuilder
  commentId: T:Apizr.Configuring.Manager.IApizrManagerOptionsBuilder
  parent: Apizr.Configuring.Manager
  href: Apizr.Configuring.Manager.IApizrManagerOptionsBuilder.html
  name: IApizrManagerOptionsBuilder
  nameWithType: IApizrManagerOptionsBuilder
  fullName: Apizr.Configuring.Manager.IApizrManagerOptionsBuilder
- uid: Apizr.Configuring.Manager.IApizrManagerOptionsBuilderBase
  commentId: T:Apizr.Configuring.Manager.IApizrManagerOptionsBuilderBase
  parent: Apizr.Configuring.Manager
  href: Apizr.Configuring.Manager.IApizrManagerOptionsBuilderBase.html
  name: IApizrManagerOptionsBuilderBase
  nameWithType: IApizrManagerOptionsBuilderBase
  fullName: Apizr.Configuring.Manager.IApizrManagerOptionsBuilderBase
- uid: Apizr.Configuring.Manager.IApizrManagerOptionsBuilderBase`2
  commentId: T:Apizr.Configuring.Manager.IApizrManagerOptionsBuilderBase`2
  href: Apizr.Configuring.Manager.IApizrManagerOptionsBuilderBase-2.html
  name: IApizrManagerOptionsBuilderBase<TApizrOptions, TApizrOptionsBuilder>
  nameWithType: IApizrManagerOptionsBuilderBase<TApizrOptions, TApizrOptionsBuilder>
  fullName: Apizr.Configuring.Manager.IApizrManagerOptionsBuilderBase<TApizrOptions, TApizrOptionsBuilder>
  nameWithType.vb: IApizrManagerOptionsBuilderBase(Of TApizrOptions, TApizrOptionsBuilder)
  fullName.vb: Apizr.Configuring.Manager.IApizrManagerOptionsBuilderBase(Of TApizrOptions, TApizrOptionsBuilder)
  name.vb: IApizrManagerOptionsBuilderBase(Of TApizrOptions, TApizrOptionsBuilder)
  spec.csharp:
  - uid: Apizr.Configuring.Manager.IApizrManagerOptionsBuilderBase`2
    name: IApizrManagerOptionsBuilderBase
    href: Apizr.Configuring.Manager.IApizrManagerOptionsBuilderBase-2.html
  - name: <
  - name: TApizrOptions
  - name: ','
  - name: " "
  - name: TApizrOptionsBuilder
  - name: '>'
  spec.vb:
  - uid: Apizr.Configuring.Manager.IApizrManagerOptionsBuilderBase`2
    name: IApizrManagerOptionsBuilderBase
    href: Apizr.Configuring.Manager.IApizrManagerOptionsBuilderBase-2.html
  - name: (
  - name: Of
  - name: " "
  - name: TApizrOptions
  - name: ','
  - name: " "
  - name: TApizrOptionsBuilder
  - name: )
- uid: Apizr.Configuring.Manager
  commentId: N:Apizr.Configuring.Manager
  href: Apizr.html
  name: Apizr.Configuring.Manager
  nameWithType: Apizr.Configuring.Manager
  fullName: Apizr.Configuring.Manager
  spec.csharp:
  - uid: Apizr
    name: Apizr
    href: Apizr.html
  - name: .
  - uid: Apizr.Configuring
    name: Configuring
    href: Apizr.Configuring.html
  - name: .
  - uid: Apizr.Configuring.Manager
    name: Manager
    href: Apizr.Configuring.Manager.html
  spec.vb:
  - uid: Apizr
    name: Apizr
    href: Apizr.html
  - name: .
  - uid: Apizr.Configuring
    name: Configuring
    href: Apizr.Configuring.html
  - name: .
  - uid: Apizr.Configuring.Manager
    name: Manager
    href: Apizr.Configuring.Manager.html
