### YamlMime:ManagedReference
items:
- uid: Apizr.Configuring.Proper
  commentId: N:Apizr.Configuring.Proper
  id: Apizr.Configuring.Proper
  children:
  - Apizr.Configuring.Proper.ApizrProperOptions
  - Apizr.Configuring.Proper.ApizrProperOptionsBase
  - Apizr.Configuring.Proper.ApizrProperOptionsBuilder
  - Apizr.Configuring.Proper.IApizrExtendedProperOptionsBuilderBase
  - Apizr.Configuring.Proper.IApizrGlobalProperOptionsBuilderBase
  - Apizr.Configuring.Proper.IApizrGlobalProperOptionsBuilderBase`2
  - Apizr.Configuring.Proper.IApizrProperOptions
  - Apizr.Configuring.Proper.IApizrProperOptionsBase
  - Apizr.Configuring.Proper.IApizrProperOptionsBuilder
  - Apizr.Configuring.Proper.IApizrProperOptionsBuilderBase
  - Apizr.Configuring.Proper.IApizrProperOptionsBuilderBase`2
  - Apizr.Configuring.Proper.IApizrProperOptionsBuilder`2
  langs:
  - csharp
  - vb
  name: Apizr.Configuring.Proper
  nameWithType: Apizr.Configuring.Proper
  fullName: Apizr.Configuring.Proper
  type: Namespace
  assemblies:
  - Apizr
references:
- uid: Apizr.Configuring.Proper.ApizrProperOptions
  commentId: T:Apizr.Configuring.Proper.ApizrProperOptions
  parent: Apizr.Configuring.Proper
  href: Apizr.Configuring.Proper.ApizrProperOptions.html
  name: ApizrProperOptions
  nameWithType: ApizrProperOptions
  fullName: Apizr.Configuring.Proper.ApizrProperOptions
- uid: Apizr.Configuring.Proper.ApizrProperOptionsBase
  commentId: T:Apizr.Configuring.Proper.ApizrProperOptionsBase
  parent: Apizr.Configuring.Proper
  href: Apizr.Configuring.Proper.ApizrProperOptionsBase.html
  name: ApizrProperOptionsBase
  nameWithType: ApizrProperOptionsBase
  fullName: Apizr.Configuring.Proper.ApizrProperOptionsBase
- uid: Apizr.Configuring.Proper.ApizrProperOptionsBuilder
  commentId: T:Apizr.Configuring.Proper.ApizrProperOptionsBuilder
  href: Apizr.Configuring.Proper.ApizrProperOptionsBuilder.html
  name: ApizrProperOptionsBuilder
  nameWithType: ApizrProperOptionsBuilder
  fullName: Apizr.Configuring.Proper.ApizrProperOptionsBuilder
- uid: Apizr.Configuring.Proper.IApizrExtendedProperOptionsBuilderBase
  commentId: T:Apizr.Configuring.Proper.IApizrExtendedProperOptionsBuilderBase
  parent: Apizr.Configuring.Proper
  href: Apizr.Configuring.Proper.IApizrExtendedProperOptionsBuilderBase.html
  name: IApizrExtendedProperOptionsBuilderBase
  nameWithType: IApizrExtendedProperOptionsBuilderBase
  fullName: Apizr.Configuring.Proper.IApizrExtendedProperOptionsBuilderBase
- uid: Apizr.Configuring.Proper.IApizrGlobalProperOptionsBuilderBase
  commentId: T:Apizr.Configuring.Proper.IApizrGlobalProperOptionsBuilderBase
  parent: Apizr.Configuring.Proper
  href: Apizr.Configuring.Proper.IApizrGlobalProperOptionsBuilderBase.html
  name: IApizrGlobalProperOptionsBuilderBase
  nameWithType: IApizrGlobalProperOptionsBuilderBase
  fullName: Apizr.Configuring.Proper.IApizrGlobalProperOptionsBuilderBase
- uid: Apizr.Configuring.Proper.IApizrGlobalProperOptionsBuilderBase`2
  commentId: T:Apizr.Configuring.Proper.IApizrGlobalProperOptionsBuilderBase`2
  href: Apizr.Configuring.Proper.IApizrGlobalProperOptionsBuilderBase-2.html
  name: IApizrGlobalProperOptionsBuilderBase<TApizrProperOptions, TApizrProperOptionsBuilder>
  nameWithType: IApizrGlobalProperOptionsBuilderBase<TApizrProperOptions, TApizrProperOptionsBuilder>
  fullName: Apizr.Configuring.Proper.IApizrGlobalProperOptionsBuilderBase<TApizrProperOptions, TApizrProperOptionsBuilder>
  nameWithType.vb: IApizrGlobalProperOptionsBuilderBase(Of TApizrProperOptions, TApizrProperOptionsBuilder)
  fullName.vb: Apizr.Configuring.Proper.IApizrGlobalProperOptionsBuilderBase(Of TApizrProperOptions, TApizrProperOptionsBuilder)
  name.vb: IApizrGlobalProperOptionsBuilderBase(Of TApizrProperOptions, TApizrProperOptionsBuilder)
  spec.csharp:
  - uid: Apizr.Configuring.Proper.IApizrGlobalProperOptionsBuilderBase`2
    name: IApizrGlobalProperOptionsBuilderBase
    href: Apizr.Configuring.Proper.IApizrGlobalProperOptionsBuilderBase-2.html
  - name: <
  - name: TApizrProperOptions
  - name: ','
  - name: " "
  - name: TApizrProperOptionsBuilder
  - name: '>'
  spec.vb:
  - uid: Apizr.Configuring.Proper.IApizrGlobalProperOptionsBuilderBase`2
    name: IApizrGlobalProperOptionsBuilderBase
    href: Apizr.Configuring.Proper.IApizrGlobalProperOptionsBuilderBase-2.html
  - name: (
  - name: Of
  - name: " "
  - name: TApizrProperOptions
  - name: ','
  - name: " "
  - name: TApizrProperOptionsBuilder
  - name: )
- uid: Apizr.Configuring.Proper.IApizrProperOptions
  commentId: T:Apizr.Configuring.Proper.IApizrProperOptions
  parent: Apizr.Configuring.Proper
  href: Apizr.Configuring.Proper.IApizrProperOptions.html
  name: IApizrProperOptions
  nameWithType: IApizrProperOptions
  fullName: Apizr.Configuring.Proper.IApizrProperOptions
- uid: Apizr.Configuring.Proper.IApizrProperOptionsBase
  commentId: T:Apizr.Configuring.Proper.IApizrProperOptionsBase
  parent: Apizr.Configuring.Proper
  href: Apizr.Configuring.Proper.IApizrProperOptionsBase.html
  name: IApizrProperOptionsBase
  nameWithType: IApizrProperOptionsBase
  fullName: Apizr.Configuring.Proper.IApizrProperOptionsBase
- uid: Apizr.Configuring.Proper.IApizrProperOptionsBuilder`2
  commentId: T:Apizr.Configuring.Proper.IApizrProperOptionsBuilder`2
  href: Apizr.Configuring.Proper.IApizrProperOptionsBuilder-2.html
  name: IApizrProperOptionsBuilder<TApizrProperOptions, TApizrProperOptionsBuilder>
  nameWithType: IApizrProperOptionsBuilder<TApizrProperOptions, TApizrProperOptionsBuilder>
  fullName: Apizr.Configuring.Proper.IApizrProperOptionsBuilder<TApizrProperOptions, TApizrProperOptionsBuilder>
  nameWithType.vb: IApizrProperOptionsBuilder(Of TApizrProperOptions, TApizrProperOptionsBuilder)
  fullName.vb: Apizr.Configuring.Proper.IApizrProperOptionsBuilder(Of TApizrProperOptions, TApizrProperOptionsBuilder)
  name.vb: IApizrProperOptionsBuilder(Of TApizrProperOptions, TApizrProperOptionsBuilder)
  spec.csharp:
  - uid: Apizr.Configuring.Proper.IApizrProperOptionsBuilder`2
    name: IApizrProperOptionsBuilder
    href: Apizr.Configuring.Proper.IApizrProperOptionsBuilder-2.html
  - name: <
  - name: TApizrProperOptions
  - name: ','
  - name: " "
  - name: TApizrProperOptionsBuilder
  - name: '>'
  spec.vb:
  - uid: Apizr.Configuring.Proper.IApizrProperOptionsBuilder`2
    name: IApizrProperOptionsBuilder
    href: Apizr.Configuring.Proper.IApizrProperOptionsBuilder-2.html
  - name: (
  - name: Of
  - name: " "
  - name: TApizrProperOptions
  - name: ','
  - name: " "
  - name: TApizrProperOptionsBuilder
  - name: )
- uid: Apizr.Configuring.Proper.IApizrProperOptionsBuilder
  commentId: T:Apizr.Configuring.Proper.IApizrProperOptionsBuilder
  parent: Apizr.Configuring.Proper
  href: Apizr.Configuring.Proper.IApizrProperOptionsBuilder.html
  name: IApizrProperOptionsBuilder
  nameWithType: IApizrProperOptionsBuilder
  fullName: Apizr.Configuring.Proper.IApizrProperOptionsBuilder
- uid: Apizr.Configuring.Proper.IApizrProperOptionsBuilderBase
  commentId: T:Apizr.Configuring.Proper.IApizrProperOptionsBuilderBase
  parent: Apizr.Configuring.Proper
  href: Apizr.Configuring.Proper.IApizrProperOptionsBuilderBase.html
  name: IApizrProperOptionsBuilderBase
  nameWithType: IApizrProperOptionsBuilderBase
  fullName: Apizr.Configuring.Proper.IApizrProperOptionsBuilderBase
- uid: Apizr.Configuring.Proper.IApizrProperOptionsBuilderBase`2
  commentId: T:Apizr.Configuring.Proper.IApizrProperOptionsBuilderBase`2
  href: Apizr.Configuring.Proper.IApizrProperOptionsBuilderBase-2.html
  name: IApizrProperOptionsBuilderBase<TApizrProperOptions, TApizrProperOptionsBuilder>
  nameWithType: IApizrProperOptionsBuilderBase<TApizrProperOptions, TApizrProperOptionsBuilder>
  fullName: Apizr.Configuring.Proper.IApizrProperOptionsBuilderBase<TApizrProperOptions, TApizrProperOptionsBuilder>
  nameWithType.vb: IApizrProperOptionsBuilderBase(Of TApizrProperOptions, TApizrProperOptionsBuilder)
  fullName.vb: Apizr.Configuring.Proper.IApizrProperOptionsBuilderBase(Of TApizrProperOptions, TApizrProperOptionsBuilder)
  name.vb: IApizrProperOptionsBuilderBase(Of TApizrProperOptions, TApizrProperOptionsBuilder)
  spec.csharp:
  - uid: Apizr.Configuring.Proper.IApizrProperOptionsBuilderBase`2
    name: IApizrProperOptionsBuilderBase
    href: Apizr.Configuring.Proper.IApizrProperOptionsBuilderBase-2.html
  - name: <
  - name: TApizrProperOptions
  - name: ','
  - name: " "
  - name: TApizrProperOptionsBuilder
  - name: '>'
  spec.vb:
  - uid: Apizr.Configuring.Proper.IApizrProperOptionsBuilderBase`2
    name: IApizrProperOptionsBuilderBase
    href: Apizr.Configuring.Proper.IApizrProperOptionsBuilderBase-2.html
  - name: (
  - name: Of
  - name: " "
  - name: TApizrProperOptions
  - name: ','
  - name: " "
  - name: TApizrProperOptionsBuilder
  - name: )
- uid: Apizr.Configuring.Proper
  commentId: N:Apizr.Configuring.Proper
  href: Apizr.html
  name: Apizr.Configuring.Proper
  nameWithType: Apizr.Configuring.Proper
  fullName: Apizr.Configuring.Proper
  spec.csharp:
  - uid: Apizr
    name: Apizr
    href: Apizr.html
  - name: .
  - uid: Apizr.Configuring
    name: Configuring
    href: Apizr.Configuring.html
  - name: .
  - uid: Apizr.Configuring.Proper
    name: Proper
    href: Apizr.Configuring.Proper.html
  spec.vb:
  - uid: Apizr
    name: Apizr
    href: Apizr.html
  - name: .
  - uid: Apizr.Configuring
    name: Configuring
    href: Apizr.Configuring.html
  - name: .
  - uid: Apizr.Configuring.Proper
    name: Proper
    href: Apizr.Configuring.Proper.html
