### YamlMime:ManagedReference
items:
- uid: Apizr.Configuring.Proper
  commentId: N:Apizr.Configuring.Proper
  id: Apizr.Configuring.Proper
  children:
  - Apizr.Configuring.Proper.ApizrProperOptions
  - Apizr.Configuring.Proper.ApizrProperOptionsBase
  - Apizr.Configuring.Proper.ApizrProperOptionsBuilder
  - Apizr.Configuring.Proper.IApizrExtendedProperOptionsBuilderBase
  - Apizr.Configuring.Proper.IApizrGlobalProperOptionsBuilderBase
  - Apizr.Configuring.Proper.IApizrGlobalProperOptionsBuilderBase`2
  - Apizr.Configuring.Proper.IApizrProperOptions
  - Apizr.Configuring.Proper.IApizrProperOptionsBase
  - Apizr.Configuring.Proper.IApizrProperOptionsBuilder
  - Apizr.Configuring.Proper.IApizrProperOptionsBuilder`2
  - Apizr.Configuring.Proper.IApizrProperOptionsBuilderBase
  - Apizr.Configuring.Proper.IApizrProperOptionsBuilderBase`2
  langs:
  - csharp
  - vb
  name: Apizr.Configuring.Proper
  nameWithType: Apizr.Configuring.Proper
  fullName: Apizr.Configuring.Proper
  type: Namespace
  assemblies:
  - Apizr
references:
- uid: Apizr.Configuring.Proper.ApizrProperOptions
  commentId: T:Apizr.Configuring.Proper.ApizrProperOptions
  parent: Apizr.Configuring.Proper
  name: ApizrProperOptions
  nameWithType: ApizrProperOptions
  fullName: Apizr.Configuring.Proper.ApizrProperOptions
- uid: Apizr.Configuring.Proper.ApizrProperOptionsBase
  commentId: T:Apizr.Configuring.Proper.ApizrProperOptionsBase
  parent: Apizr.Configuring.Proper
  name: ApizrProperOptionsBase
  nameWithType: ApizrProperOptionsBase
  fullName: Apizr.Configuring.Proper.ApizrProperOptionsBase
- uid: Apizr.Configuring.Proper.ApizrProperOptionsBuilder
  commentId: T:Apizr.Configuring.Proper.ApizrProperOptionsBuilder
  name: ApizrProperOptionsBuilder
  nameWithType: ApizrProperOptionsBuilder
  fullName: Apizr.Configuring.Proper.ApizrProperOptionsBuilder
- uid: Apizr.Configuring.Proper.IApizrExtendedProperOptionsBuilderBase
  commentId: T:Apizr.Configuring.Proper.IApizrExtendedProperOptionsBuilderBase
  parent: Apizr.Configuring.Proper
  name: IApizrExtendedProperOptionsBuilderBase
  nameWithType: IApizrExtendedProperOptionsBuilderBase
  fullName: Apizr.Configuring.Proper.IApizrExtendedProperOptionsBuilderBase
- uid: Apizr.Configuring.Proper.IApizrGlobalProperOptionsBuilderBase
  commentId: T:Apizr.Configuring.Proper.IApizrGlobalProperOptionsBuilderBase
  parent: Apizr.Configuring.Proper
  name: IApizrGlobalProperOptionsBuilderBase
  nameWithType: IApizrGlobalProperOptionsBuilderBase
  fullName: Apizr.Configuring.Proper.IApizrGlobalProperOptionsBuilderBase
- uid: Apizr.Configuring.Proper.IApizrGlobalProperOptionsBuilderBase`2
  commentId: T:Apizr.Configuring.Proper.IApizrGlobalProperOptionsBuilderBase`2
  name: IApizrGlobalProperOptionsBuilderBase<TApizrProperOptions, TApizrProperOptionsBuilder>
  nameWithType: IApizrGlobalProperOptionsBuilderBase<TApizrProperOptions, TApizrProperOptionsBuilder>
  fullName: Apizr.Configuring.Proper.IApizrGlobalProperOptionsBuilderBase<TApizrProperOptions, TApizrProperOptionsBuilder>
  nameWithType.vb: IApizrGlobalProperOptionsBuilderBase(Of TApizrProperOptions, TApizrProperOptionsBuilder)
  fullName.vb: Apizr.Configuring.Proper.IApizrGlobalProperOptionsBuilderBase(Of TApizrProperOptions, TApizrProperOptionsBuilder)
  name.vb: IApizrGlobalProperOptionsBuilderBase(Of TApizrProperOptions, TApizrProperOptionsBuilder)
  spec.csharp:
  - uid: Apizr.Configuring.Proper.IApizrGlobalProperOptionsBuilderBase`2
    name: IApizrGlobalProperOptionsBuilderBase
    nameWithType: IApizrGlobalProperOptionsBuilderBase
    fullName: Apizr.Configuring.Proper.IApizrGlobalProperOptionsBuilderBase
  - name: <
    nameWithType: <
    fullName: <
  - name: TApizrProperOptions
    nameWithType: TApizrProperOptions
    fullName: TApizrProperOptions
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TApizrProperOptionsBuilder
    nameWithType: TApizrProperOptionsBuilder
    fullName: TApizrProperOptionsBuilder
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Apizr.Configuring.Proper.IApizrGlobalProperOptionsBuilderBase`2
    name: IApizrGlobalProperOptionsBuilderBase
    nameWithType: IApizrGlobalProperOptionsBuilderBase
    fullName: Apizr.Configuring.Proper.IApizrGlobalProperOptionsBuilderBase
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TApizrProperOptions
    nameWithType: TApizrProperOptions
    fullName: TApizrProperOptions
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TApizrProperOptionsBuilder
    nameWithType: TApizrProperOptionsBuilder
    fullName: TApizrProperOptionsBuilder
  - name: )
    nameWithType: )
    fullName: )
- uid: Apizr.Configuring.Proper.IApizrProperOptions
  commentId: T:Apizr.Configuring.Proper.IApizrProperOptions
  parent: Apizr.Configuring.Proper
  name: IApizrProperOptions
  nameWithType: IApizrProperOptions
  fullName: Apizr.Configuring.Proper.IApizrProperOptions
- uid: Apizr.Configuring.Proper.IApizrProperOptionsBase
  commentId: T:Apizr.Configuring.Proper.IApizrProperOptionsBase
  parent: Apizr.Configuring.Proper
  name: IApizrProperOptionsBase
  nameWithType: IApizrProperOptionsBase
  fullName: Apizr.Configuring.Proper.IApizrProperOptionsBase
- uid: Apizr.Configuring.Proper.IApizrProperOptionsBuilder`2
  commentId: T:Apizr.Configuring.Proper.IApizrProperOptionsBuilder`2
  name: IApizrProperOptionsBuilder<TApizrProperOptions, TApizrProperOptionsBuilder>
  nameWithType: IApizrProperOptionsBuilder<TApizrProperOptions, TApizrProperOptionsBuilder>
  fullName: Apizr.Configuring.Proper.IApizrProperOptionsBuilder<TApizrProperOptions, TApizrProperOptionsBuilder>
  nameWithType.vb: IApizrProperOptionsBuilder(Of TApizrProperOptions, TApizrProperOptionsBuilder)
  fullName.vb: Apizr.Configuring.Proper.IApizrProperOptionsBuilder(Of TApizrProperOptions, TApizrProperOptionsBuilder)
  name.vb: IApizrProperOptionsBuilder(Of TApizrProperOptions, TApizrProperOptionsBuilder)
  spec.csharp:
  - uid: Apizr.Configuring.Proper.IApizrProperOptionsBuilder`2
    name: IApizrProperOptionsBuilder
    nameWithType: IApizrProperOptionsBuilder
    fullName: Apizr.Configuring.Proper.IApizrProperOptionsBuilder
  - name: <
    nameWithType: <
    fullName: <
  - name: TApizrProperOptions
    nameWithType: TApizrProperOptions
    fullName: TApizrProperOptions
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TApizrProperOptionsBuilder
    nameWithType: TApizrProperOptionsBuilder
    fullName: TApizrProperOptionsBuilder
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Apizr.Configuring.Proper.IApizrProperOptionsBuilder`2
    name: IApizrProperOptionsBuilder
    nameWithType: IApizrProperOptionsBuilder
    fullName: Apizr.Configuring.Proper.IApizrProperOptionsBuilder
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TApizrProperOptions
    nameWithType: TApizrProperOptions
    fullName: TApizrProperOptions
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TApizrProperOptionsBuilder
    nameWithType: TApizrProperOptionsBuilder
    fullName: TApizrProperOptionsBuilder
  - name: )
    nameWithType: )
    fullName: )
- uid: Apizr.Configuring.Proper.IApizrProperOptionsBuilder
  commentId: T:Apizr.Configuring.Proper.IApizrProperOptionsBuilder
  parent: Apizr.Configuring.Proper
  name: IApizrProperOptionsBuilder
  nameWithType: IApizrProperOptionsBuilder
  fullName: Apizr.Configuring.Proper.IApizrProperOptionsBuilder
- uid: Apizr.Configuring.Proper.IApizrProperOptionsBuilderBase
  commentId: T:Apizr.Configuring.Proper.IApizrProperOptionsBuilderBase
  parent: Apizr.Configuring.Proper
  name: IApizrProperOptionsBuilderBase
  nameWithType: IApizrProperOptionsBuilderBase
  fullName: Apizr.Configuring.Proper.IApizrProperOptionsBuilderBase
- uid: Apizr.Configuring.Proper.IApizrProperOptionsBuilderBase`2
  commentId: T:Apizr.Configuring.Proper.IApizrProperOptionsBuilderBase`2
  name: IApizrProperOptionsBuilderBase<TApizrProperOptions, TApizrProperOptionsBuilder>
  nameWithType: IApizrProperOptionsBuilderBase<TApizrProperOptions, TApizrProperOptionsBuilder>
  fullName: Apizr.Configuring.Proper.IApizrProperOptionsBuilderBase<TApizrProperOptions, TApizrProperOptionsBuilder>
  nameWithType.vb: IApizrProperOptionsBuilderBase(Of TApizrProperOptions, TApizrProperOptionsBuilder)
  fullName.vb: Apizr.Configuring.Proper.IApizrProperOptionsBuilderBase(Of TApizrProperOptions, TApizrProperOptionsBuilder)
  name.vb: IApizrProperOptionsBuilderBase(Of TApizrProperOptions, TApizrProperOptionsBuilder)
  spec.csharp:
  - uid: Apizr.Configuring.Proper.IApizrProperOptionsBuilderBase`2
    name: IApizrProperOptionsBuilderBase
    nameWithType: IApizrProperOptionsBuilderBase
    fullName: Apizr.Configuring.Proper.IApizrProperOptionsBuilderBase
  - name: <
    nameWithType: <
    fullName: <
  - name: TApizrProperOptions
    nameWithType: TApizrProperOptions
    fullName: TApizrProperOptions
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TApizrProperOptionsBuilder
    nameWithType: TApizrProperOptionsBuilder
    fullName: TApizrProperOptionsBuilder
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Apizr.Configuring.Proper.IApizrProperOptionsBuilderBase`2
    name: IApizrProperOptionsBuilderBase
    nameWithType: IApizrProperOptionsBuilderBase
    fullName: Apizr.Configuring.Proper.IApizrProperOptionsBuilderBase
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TApizrProperOptions
    nameWithType: TApizrProperOptions
    fullName: TApizrProperOptions
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TApizrProperOptionsBuilder
    nameWithType: TApizrProperOptionsBuilder
    fullName: TApizrProperOptionsBuilder
  - name: )
    nameWithType: )
    fullName: )
- uid: Apizr.Configuring.Proper
  commentId: N:Apizr.Configuring.Proper
  name: Apizr.Configuring.Proper
  nameWithType: Apizr.Configuring.Proper
  fullName: Apizr.Configuring.Proper
