### YamlMime:ManagedReference
items:
- uid: Apizr.Extending.Configuring.Manager
  commentId: N:Apizr.Extending.Configuring.Manager
  id: Apizr.Extending.Configuring.Manager
  children:
  - Apizr.Extending.Configuring.Manager.ApizrExtendedManagerOptions
  - Apizr.Extending.Configuring.Manager.ApizrExtendedManagerOptionsBase
  - Apizr.Extending.Configuring.Manager.ApizrExtendedManagerOptionsBuilder
  - Apizr.Extending.Configuring.Manager.ApizrExtendedManagerOptions`1
  - Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptions
  - Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBase
  - Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilder
  - Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase
  - Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase`2
  - Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilder`2
  - Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptions`1
  langs:
  - csharp
  - vb
  name: Apizr.Extending.Configuring.Manager
  nameWithType: Apizr.Extending.Configuring.Manager
  fullName: Apizr.Extending.Configuring.Manager
  type: Namespace
  assemblies:
  - Apizr.Extensions.Microsoft.DependencyInjection
references:
- uid: Apizr.Extending.Configuring.Manager.ApizrExtendedManagerOptions
  commentId: T:Apizr.Extending.Configuring.Manager.ApizrExtendedManagerOptions
  parent: Apizr.Extending.Configuring.Manager
  href: Apizr.Extending.Configuring.Manager.ApizrExtendedManagerOptions.html
  name: ApizrExtendedManagerOptions
  nameWithType: ApizrExtendedManagerOptions
  fullName: Apizr.Extending.Configuring.Manager.ApizrExtendedManagerOptions
- uid: Apizr.Extending.Configuring.Manager.ApizrExtendedManagerOptions`1
  commentId: T:Apizr.Extending.Configuring.Manager.ApizrExtendedManagerOptions`1
  href: Apizr.Extending.Configuring.Manager.ApizrExtendedManagerOptions-1.html
  name: ApizrExtendedManagerOptions<TWebApi>
  nameWithType: ApizrExtendedManagerOptions<TWebApi>
  fullName: Apizr.Extending.Configuring.Manager.ApizrExtendedManagerOptions<TWebApi>
  nameWithType.vb: ApizrExtendedManagerOptions(Of TWebApi)
  fullName.vb: Apizr.Extending.Configuring.Manager.ApizrExtendedManagerOptions(Of TWebApi)
  name.vb: ApizrExtendedManagerOptions(Of TWebApi)
  spec.csharp:
  - uid: Apizr.Extending.Configuring.Manager.ApizrExtendedManagerOptions`1
    name: ApizrExtendedManagerOptions
    href: Apizr.Extending.Configuring.Manager.ApizrExtendedManagerOptions-1.html
  - name: <
  - name: TWebApi
  - name: '>'
  spec.vb:
  - uid: Apizr.Extending.Configuring.Manager.ApizrExtendedManagerOptions`1
    name: ApizrExtendedManagerOptions
    href: Apizr.Extending.Configuring.Manager.ApizrExtendedManagerOptions-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TWebApi
  - name: )
- uid: Apizr.Extending.Configuring.Manager.ApizrExtendedManagerOptionsBase
  commentId: T:Apizr.Extending.Configuring.Manager.ApizrExtendedManagerOptionsBase
  parent: Apizr.Extending.Configuring.Manager
  href: Apizr.Extending.Configuring.Manager.ApizrExtendedManagerOptionsBase.html
  name: ApizrExtendedManagerOptionsBase
  nameWithType: ApizrExtendedManagerOptionsBase
  fullName: Apizr.Extending.Configuring.Manager.ApizrExtendedManagerOptionsBase
- uid: Apizr.Extending.Configuring.Manager.ApizrExtendedManagerOptionsBuilder
  commentId: T:Apizr.Extending.Configuring.Manager.ApizrExtendedManagerOptionsBuilder
  href: Apizr.Extending.Configuring.Manager.ApizrExtendedManagerOptionsBuilder.html
  name: ApizrExtendedManagerOptionsBuilder
  nameWithType: ApizrExtendedManagerOptionsBuilder
  fullName: Apizr.Extending.Configuring.Manager.ApizrExtendedManagerOptionsBuilder
- uid: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptions
  commentId: T:Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptions
  parent: Apizr.Extending.Configuring.Manager
  href: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptions.html
  name: IApizrExtendedManagerOptions
  nameWithType: IApizrExtendedManagerOptions
  fullName: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptions
- uid: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptions`1
  commentId: T:Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptions`1
  href: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptions-1.html
  name: IApizrExtendedManagerOptions<TWebApi>
  nameWithType: IApizrExtendedManagerOptions<TWebApi>
  fullName: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptions<TWebApi>
  nameWithType.vb: IApizrExtendedManagerOptions(Of TWebApi)
  fullName.vb: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptions(Of TWebApi)
  name.vb: IApizrExtendedManagerOptions(Of TWebApi)
  spec.csharp:
  - uid: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptions`1
    name: IApizrExtendedManagerOptions
    href: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptions-1.html
  - name: <
  - name: TWebApi
  - name: '>'
  spec.vb:
  - uid: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptions`1
    name: IApizrExtendedManagerOptions
    href: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptions-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TWebApi
  - name: )
- uid: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBase
  commentId: T:Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBase
  parent: Apizr.Extending.Configuring.Manager
  href: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBase.html
  name: IApizrExtendedManagerOptionsBase
  nameWithType: IApizrExtendedManagerOptionsBase
  fullName: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBase
- uid: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilder`2
  commentId: T:Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilder`2
  href: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilder-2.html
  name: IApizrExtendedManagerOptionsBuilder<TApizrExtendedOptions, TApizrExtendedOptionsBuilder>
  nameWithType: IApizrExtendedManagerOptionsBuilder<TApizrExtendedOptions, TApizrExtendedOptionsBuilder>
  fullName: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilder<TApizrExtendedOptions, TApizrExtendedOptionsBuilder>
  nameWithType.vb: IApizrExtendedManagerOptionsBuilder(Of TApizrExtendedOptions, TApizrExtendedOptionsBuilder)
  fullName.vb: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilder(Of TApizrExtendedOptions, TApizrExtendedOptionsBuilder)
  name.vb: IApizrExtendedManagerOptionsBuilder(Of TApizrExtendedOptions, TApizrExtendedOptionsBuilder)
  spec.csharp:
  - uid: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilder`2
    name: IApizrExtendedManagerOptionsBuilder
    href: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilder-2.html
  - name: <
  - name: TApizrExtendedOptions
  - name: ','
  - name: " "
  - name: TApizrExtendedOptionsBuilder
  - name: '>'
  spec.vb:
  - uid: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilder`2
    name: IApizrExtendedManagerOptionsBuilder
    href: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilder-2.html
  - name: (
  - name: Of
  - name: " "
  - name: TApizrExtendedOptions
  - name: ','
  - name: " "
  - name: TApizrExtendedOptionsBuilder
  - name: )
- uid: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilder
  commentId: T:Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilder
  parent: Apizr.Extending.Configuring.Manager
  href: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilder.html
  name: IApizrExtendedManagerOptionsBuilder
  nameWithType: IApizrExtendedManagerOptionsBuilder
  fullName: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilder
- uid: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase
  commentId: T:Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase
  parent: Apizr.Extending.Configuring.Manager
  href: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase.html
  name: IApizrExtendedManagerOptionsBuilderBase
  nameWithType: IApizrExtendedManagerOptionsBuilderBase
  fullName: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase
- uid: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase`2
  commentId: T:Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase`2
  href: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase-2.html
  name: IApizrExtendedManagerOptionsBuilderBase<TApizrExtendedOptions, TApizrExtendedOptionsBuilder>
  nameWithType: IApizrExtendedManagerOptionsBuilderBase<TApizrExtendedOptions, TApizrExtendedOptionsBuilder>
  fullName: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase<TApizrExtendedOptions, TApizrExtendedOptionsBuilder>
  nameWithType.vb: IApizrExtendedManagerOptionsBuilderBase(Of TApizrExtendedOptions, TApizrExtendedOptionsBuilder)
  fullName.vb: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase(Of TApizrExtendedOptions, TApizrExtendedOptionsBuilder)
  name.vb: IApizrExtendedManagerOptionsBuilderBase(Of TApizrExtendedOptions, TApizrExtendedOptionsBuilder)
  spec.csharp:
  - uid: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase`2
    name: IApizrExtendedManagerOptionsBuilderBase
    href: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase-2.html
  - name: <
  - name: TApizrExtendedOptions
  - name: ','
  - name: " "
  - name: TApizrExtendedOptionsBuilder
  - name: '>'
  spec.vb:
  - uid: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase`2
    name: IApizrExtendedManagerOptionsBuilderBase
    href: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase-2.html
  - name: (
  - name: Of
  - name: " "
  - name: TApizrExtendedOptions
  - name: ','
  - name: " "
  - name: TApizrExtendedOptionsBuilder
  - name: )
- uid: Apizr.Extending.Configuring.Manager
  commentId: N:Apizr.Extending.Configuring.Manager
  href: Apizr.html
  name: Apizr.Extending.Configuring.Manager
  nameWithType: Apizr.Extending.Configuring.Manager
  fullName: Apizr.Extending.Configuring.Manager
  spec.csharp:
  - uid: Apizr
    name: Apizr
    href: Apizr.html
  - name: .
  - uid: Apizr.Extending
    name: Extending
    href: Apizr.Extending.html
  - name: .
  - uid: Apizr.Extending.Configuring
    name: Configuring
    href: Apizr.Extending.Configuring.html
  - name: .
  - uid: Apizr.Extending.Configuring.Manager
    name: Manager
    href: Apizr.Extending.Configuring.Manager.html
  spec.vb:
  - uid: Apizr
    name: Apizr
    href: Apizr.html
  - name: .
  - uid: Apizr.Extending
    name: Extending
    href: Apizr.Extending.html
  - name: .
  - uid: Apizr.Extending.Configuring
    name: Configuring
    href: Apizr.Extending.Configuring.html
  - name: .
  - uid: Apizr.Extending.Configuring.Manager
    name: Manager
    href: Apizr.Extending.Configuring.Manager.html
