### YamlMime:ManagedReference
items:
- uid: Apizr.Configuring.Proper.IApizrGlobalProperOptionsBuilderBase
  commentId: T:Apizr.Configuring.Proper.IApizrGlobalProperOptionsBuilderBase
  id: IApizrGlobalProperOptionsBuilderBase
  parent: Apizr.Configuring.Proper
  children: []
  langs:
  - csharp
  - vb
  name: IApizrGlobalProperOptionsBuilderBase
  nameWithType: IApizrGlobalProperOptionsBuilderBase
  fullName: Apizr.Configuring.Proper.IApizrGlobalProperOptionsBuilderBase
  type: Interface
  source:
    id: IApizrGlobalProperOptionsBuilderBase
    path: C:\Dev\Community\Apizr\Apizr\Apizr\Configuring\Proper\IApizrGlobalProperOptionsBuilderBase.cs
    startLine: 7
  assemblies:
  - Apizr
  namespace: Apizr.Configuring.Proper
  summary: "\nBuilder options available at proper level for both static and extended registrations\n"
  example: []
  syntax:
    content: 'public interface IApizrGlobalProperOptionsBuilderBase : IApizrGlobalSharedRegistrationOptionsBuilderBase, IApizrGlobalSharedOptionsBuilderBase'
    content.vb: >-
      Public Interface IApizrGlobalProperOptionsBuilderBase
          Inherits IApizrGlobalSharedRegistrationOptionsBuilderBase
  extensionMethods:
  - Apizr.Configuring.Proper.IApizrGlobalProperOptionsBuilderBase.Apizr.FusilladeOptionsBuilderExtensions.WithPriority``1
  - Apizr.Configuring.Proper.IApizrGlobalProperOptionsBuilderBase.Apizr.FusilladeOptionsBuilderExtensions.WithPriority``1(Fusillade.Priority)
  - Apizr.Configuring.Proper.IApizrGlobalProperOptionsBuilderBase.Apizr.FusilladeOptionsBuilderExtensions.WithPriority``1(System.Int32)
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
references:
- uid: Apizr.Configuring.Proper
  commentId: N:Apizr.Configuring.Proper
  name: Apizr.Configuring.Proper
  nameWithType: Apizr.Configuring.Proper
  fullName: Apizr.Configuring.Proper
- uid: Apizr.Configuring.Proper.IApizrGlobalProperOptionsBuilderBase.Apizr.FusilladeOptionsBuilderExtensions.WithPriority``1
  commentId: M:Apizr.FusilladeOptionsBuilderExtensions.WithPriority``1(``0)
  parent: Apizr.FusilladeOptionsBuilderExtensions
  definition: Apizr.FusilladeOptionsBuilderExtensions.WithPriority``1(``0)
  name: WithPriority<IApizrGlobalProperOptionsBuilderBase>()
  nameWithType: FusilladeOptionsBuilderExtensions.WithPriority<IApizrGlobalProperOptionsBuilderBase>()
  fullName: Apizr.FusilladeOptionsBuilderExtensions.WithPriority<Apizr.Configuring.Proper.IApizrGlobalProperOptionsBuilderBase>()
  nameWithType.vb: FusilladeOptionsBuilderExtensions.WithPriority(Of IApizrGlobalProperOptionsBuilderBase)()
  fullName.vb: Apizr.FusilladeOptionsBuilderExtensions.WithPriority(Of Apizr.Configuring.Proper.IApizrGlobalProperOptionsBuilderBase)()
  name.vb: WithPriority(Of IApizrGlobalProperOptionsBuilderBase)()
  spec.csharp:
  - uid: Apizr.FusilladeOptionsBuilderExtensions.WithPriority``1
    name: WithPriority<IApizrGlobalProperOptionsBuilderBase>
    nameWithType: FusilladeOptionsBuilderExtensions.WithPriority<IApizrGlobalProperOptionsBuilderBase>
    fullName: Apizr.FusilladeOptionsBuilderExtensions.WithPriority<Apizr.Configuring.Proper.IApizrGlobalProperOptionsBuilderBase>
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Apizr.FusilladeOptionsBuilderExtensions.WithPriority``1
    name: WithPriority(Of IApizrGlobalProperOptionsBuilderBase)
    nameWithType: FusilladeOptionsBuilderExtensions.WithPriority(Of IApizrGlobalProperOptionsBuilderBase)
    fullName: Apizr.FusilladeOptionsBuilderExtensions.WithPriority(Of Apizr.Configuring.Proper.IApizrGlobalProperOptionsBuilderBase)
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Apizr.Configuring.Proper.IApizrGlobalProperOptionsBuilderBase.Apizr.FusilladeOptionsBuilderExtensions.WithPriority``1(Fusillade.Priority)
  commentId: M:Apizr.FusilladeOptionsBuilderExtensions.WithPriority``1(``0,Fusillade.Priority)
  parent: Apizr.FusilladeOptionsBuilderExtensions
  definition: Apizr.FusilladeOptionsBuilderExtensions.WithPriority``1(``0,Fusillade.Priority)
  name: WithPriority<IApizrGlobalProperOptionsBuilderBase>(Priority)
  nameWithType: FusilladeOptionsBuilderExtensions.WithPriority<IApizrGlobalProperOptionsBuilderBase>(Priority)
  fullName: Apizr.FusilladeOptionsBuilderExtensions.WithPriority<Apizr.Configuring.Proper.IApizrGlobalProperOptionsBuilderBase>(Fusillade.Priority)
  nameWithType.vb: FusilladeOptionsBuilderExtensions.WithPriority(Of IApizrGlobalProperOptionsBuilderBase)(Priority)
  fullName.vb: Apizr.FusilladeOptionsBuilderExtensions.WithPriority(Of Apizr.Configuring.Proper.IApizrGlobalProperOptionsBuilderBase)(Fusillade.Priority)
  name.vb: WithPriority(Of IApizrGlobalProperOptionsBuilderBase)(Priority)
  spec.csharp:
  - uid: Apizr.FusilladeOptionsBuilderExtensions.WithPriority``1(Fusillade.Priority)
    name: WithPriority<IApizrGlobalProperOptionsBuilderBase>
    nameWithType: FusilladeOptionsBuilderExtensions.WithPriority<IApizrGlobalProperOptionsBuilderBase>
    fullName: Apizr.FusilladeOptionsBuilderExtensions.WithPriority<Apizr.Configuring.Proper.IApizrGlobalProperOptionsBuilderBase>
  - name: (
    nameWithType: (
    fullName: (
  - uid: Fusillade.Priority
    name: Priority
    nameWithType: Priority
    fullName: Fusillade.Priority
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Apizr.FusilladeOptionsBuilderExtensions.WithPriority``1(Fusillade.Priority)
    name: WithPriority(Of IApizrGlobalProperOptionsBuilderBase)
    nameWithType: FusilladeOptionsBuilderExtensions.WithPriority(Of IApizrGlobalProperOptionsBuilderBase)
    fullName: Apizr.FusilladeOptionsBuilderExtensions.WithPriority(Of Apizr.Configuring.Proper.IApizrGlobalProperOptionsBuilderBase)
  - name: (
    nameWithType: (
    fullName: (
  - uid: Fusillade.Priority
    name: Priority
    nameWithType: Priority
    fullName: Fusillade.Priority
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Apizr.Configuring.Proper.IApizrGlobalProperOptionsBuilderBase.Apizr.FusilladeOptionsBuilderExtensions.WithPriority``1(System.Int32)
  commentId: M:Apizr.FusilladeOptionsBuilderExtensions.WithPriority``1(``0,System.Int32)
  parent: Apizr.FusilladeOptionsBuilderExtensions
  definition: Apizr.FusilladeOptionsBuilderExtensions.WithPriority``1(``0,System.Int32)
  name: WithPriority<IApizrGlobalProperOptionsBuilderBase>(Int32)
  nameWithType: FusilladeOptionsBuilderExtensions.WithPriority<IApizrGlobalProperOptionsBuilderBase>(Int32)
  fullName: Apizr.FusilladeOptionsBuilderExtensions.WithPriority<Apizr.Configuring.Proper.IApizrGlobalProperOptionsBuilderBase>(System.Int32)
  nameWithType.vb: FusilladeOptionsBuilderExtensions.WithPriority(Of IApizrGlobalProperOptionsBuilderBase)(Int32)
  fullName.vb: Apizr.FusilladeOptionsBuilderExtensions.WithPriority(Of Apizr.Configuring.Proper.IApizrGlobalProperOptionsBuilderBase)(System.Int32)
  name.vb: WithPriority(Of IApizrGlobalProperOptionsBuilderBase)(Int32)
  spec.csharp:
  - uid: Apizr.FusilladeOptionsBuilderExtensions.WithPriority``1(System.Int32)
    name: WithPriority<IApizrGlobalProperOptionsBuilderBase>
    nameWithType: FusilladeOptionsBuilderExtensions.WithPriority<IApizrGlobalProperOptionsBuilderBase>
    fullName: Apizr.FusilladeOptionsBuilderExtensions.WithPriority<Apizr.Configuring.Proper.IApizrGlobalProperOptionsBuilderBase>
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Int32
    name: Int32
    nameWithType: Int32
    fullName: System.Int32
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Apizr.FusilladeOptionsBuilderExtensions.WithPriority``1(System.Int32)
    name: WithPriority(Of IApizrGlobalProperOptionsBuilderBase)
    nameWithType: FusilladeOptionsBuilderExtensions.WithPriority(Of IApizrGlobalProperOptionsBuilderBase)
    fullName: Apizr.FusilladeOptionsBuilderExtensions.WithPriority(Of Apizr.Configuring.Proper.IApizrGlobalProperOptionsBuilderBase)
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Int32
    name: Int32
    nameWithType: Int32
    fullName: System.Int32
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Apizr.FusilladeOptionsBuilderExtensions.WithPriority``1(``0)
  commentId: M:Apizr.FusilladeOptionsBuilderExtensions.WithPriority``1(``0)
  name: WithPriority<T>(T)
  nameWithType: FusilladeOptionsBuilderExtensions.WithPriority<T>(T)
  fullName: Apizr.FusilladeOptionsBuilderExtensions.WithPriority<T>(T)
  nameWithType.vb: FusilladeOptionsBuilderExtensions.WithPriority(Of T)(T)
  fullName.vb: Apizr.FusilladeOptionsBuilderExtensions.WithPriority(Of T)(T)
  name.vb: WithPriority(Of T)(T)
  spec.csharp:
  - uid: Apizr.FusilladeOptionsBuilderExtensions.WithPriority``1(``0)
    name: WithPriority<T>
    nameWithType: FusilladeOptionsBuilderExtensions.WithPriority<T>
    fullName: Apizr.FusilladeOptionsBuilderExtensions.WithPriority<T>
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Apizr.FusilladeOptionsBuilderExtensions.WithPriority``1(``0)
    name: WithPriority(Of T)
    nameWithType: FusilladeOptionsBuilderExtensions.WithPriority(Of T)
    fullName: Apizr.FusilladeOptionsBuilderExtensions.WithPriority(Of T)
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: Apizr.FusilladeOptionsBuilderExtensions
  commentId: T:Apizr.FusilladeOptionsBuilderExtensions
  parent: Apizr
  name: FusilladeOptionsBuilderExtensions
  nameWithType: FusilladeOptionsBuilderExtensions
  fullName: Apizr.FusilladeOptionsBuilderExtensions
- uid: Apizr.FusilladeOptionsBuilderExtensions.WithPriority``1(``0,Fusillade.Priority)
  commentId: M:Apizr.FusilladeOptionsBuilderExtensions.WithPriority``1(``0,Fusillade.Priority)
  isExternal: true
  name: WithPriority<T>(T, Priority)
  nameWithType: FusilladeOptionsBuilderExtensions.WithPriority<T>(T, Priority)
  fullName: Apizr.FusilladeOptionsBuilderExtensions.WithPriority<T>(T, Fusillade.Priority)
  nameWithType.vb: FusilladeOptionsBuilderExtensions.WithPriority(Of T)(T, Priority)
  fullName.vb: Apizr.FusilladeOptionsBuilderExtensions.WithPriority(Of T)(T, Fusillade.Priority)
  name.vb: WithPriority(Of T)(T, Priority)
  spec.csharp:
  - uid: Apizr.FusilladeOptionsBuilderExtensions.WithPriority``1(``0,Fusillade.Priority)
    name: WithPriority<T>
    nameWithType: FusilladeOptionsBuilderExtensions.WithPriority<T>
    fullName: Apizr.FusilladeOptionsBuilderExtensions.WithPriority<T>
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: Fusillade.Priority
    name: Priority
    nameWithType: Priority
    fullName: Fusillade.Priority
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Apizr.FusilladeOptionsBuilderExtensions.WithPriority``1(``0,Fusillade.Priority)
    name: WithPriority(Of T)
    nameWithType: FusilladeOptionsBuilderExtensions.WithPriority(Of T)
    fullName: Apizr.FusilladeOptionsBuilderExtensions.WithPriority(Of T)
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: Fusillade.Priority
    name: Priority
    nameWithType: Priority
    fullName: Fusillade.Priority
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Apizr.FusilladeOptionsBuilderExtensions.WithPriority``1(``0,System.Int32)
  commentId: M:Apizr.FusilladeOptionsBuilderExtensions.WithPriority``1(``0,System.Int32)
  isExternal: true
  name: WithPriority<T>(T, Int32)
  nameWithType: FusilladeOptionsBuilderExtensions.WithPriority<T>(T, Int32)
  fullName: Apizr.FusilladeOptionsBuilderExtensions.WithPriority<T>(T, System.Int32)
  nameWithType.vb: FusilladeOptionsBuilderExtensions.WithPriority(Of T)(T, Int32)
  fullName.vb: Apizr.FusilladeOptionsBuilderExtensions.WithPriority(Of T)(T, System.Int32)
  name.vb: WithPriority(Of T)(T, Int32)
  spec.csharp:
  - uid: Apizr.FusilladeOptionsBuilderExtensions.WithPriority``1(``0,System.Int32)
    name: WithPriority<T>
    nameWithType: FusilladeOptionsBuilderExtensions.WithPriority<T>
    fullName: Apizr.FusilladeOptionsBuilderExtensions.WithPriority<T>
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Int32
    name: Int32
    nameWithType: Int32
    fullName: System.Int32
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Apizr.FusilladeOptionsBuilderExtensions.WithPriority``1(``0,System.Int32)
    name: WithPriority(Of T)
    nameWithType: FusilladeOptionsBuilderExtensions.WithPriority(Of T)
    fullName: Apizr.FusilladeOptionsBuilderExtensions.WithPriority(Of T)
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Int32
    name: Int32
    nameWithType: Int32
    fullName: System.Int32
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Apizr
  commentId: N:Apizr
  name: Apizr
  nameWithType: Apizr
  fullName: Apizr
