### YamlMime:ManagedReference
items:
- uid: Apizr.Configuring.Proper.IApizrGlobalProperOptionsBuilderBase
  commentId: T:Apizr.Configuring.Proper.IApizrGlobalProperOptionsBuilderBase
  id: IApizrGlobalProperOptionsBuilderBase
  parent: Apizr.Configuring.Proper
  children: []
  langs:
  - csharp
  - vb
  name: IApizrGlobalProperOptionsBuilderBase
  nameWithType: IApizrGlobalProperOptionsBuilderBase
  fullName: Apizr.Configuring.Proper.IApizrGlobalProperOptionsBuilderBase
  type: Interface
  source:
    id: IApizrGlobalProperOptionsBuilderBase
    path: C:\Dev\Community\Apizr\Apizr\Apizr\Configuring\Proper\IApizrGlobalProperOptionsBuilderBase.cs
    startLine: 7
  assemblies:
  - Apizr
  namespace: Apizr.Configuring.Proper
  summary: "\nBuilder options available at proper level for both static and extended registrations\n"
  example: []
  syntax:
    content: 'public interface IApizrGlobalProperOptionsBuilderBase : IApizrGlobalSharedOptionsBuilderBase'
    content.vb: >-
      Public Interface IApizrGlobalProperOptionsBuilderBase
          Inherits IApizrGlobalSharedOptionsBuilderBase
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
references:
- uid: Apizr.Configuring.Proper
  commentId: N:Apizr.Configuring.Proper
  name: Apizr.Configuring.Proper
  nameWithType: Apizr.Configuring.Proper
  fullName: Apizr.Configuring.Proper
