### YamlMime:ManagedReference
items:
- uid: Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistryBase
  commentId: T:Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistryBase
  id: IApizrExtendedConcurrentRegistryBase
  parent: Apizr.Extending.Configuring.Registry
  children:
  - Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistryBase.AddOrUpdate(System.Type,System.Type)
  langs:
  - csharp
  - vb
  name: IApizrExtendedConcurrentRegistryBase
  nameWithType: IApizrExtendedConcurrentRegistryBase
  fullName: Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistryBase
  type: Interface
  source:
    id: IApizrExtendedConcurrentRegistryBase
    path: C:\Dev\Community\Apizr\Apizr\Apizr.Extensions.Microsoft.DependencyInjection\Extending\Configuring\Registry\IApizrExtendedConcurrentRegistryBase.cs
    startLine: 4
  assemblies:
  - Apizr.Extensions.Microsoft.DependencyInjection
  namespace: Apizr.Extending.Configuring.Registry
  syntax:
    content: public interface IApizrExtendedConcurrentRegistryBase
    content.vb: Public Interface IApizrExtendedConcurrentRegistryBase
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistryBase.AddOrUpdate(System.Type,System.Type)
  commentId: M:Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistryBase.AddOrUpdate(System.Type,System.Type)
  id: AddOrUpdate(System.Type,System.Type)
  parent: Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistryBase
  langs:
  - csharp
  - vb
  name: AddOrUpdate(Type, Type)
  nameWithType: IApizrExtendedConcurrentRegistryBase.AddOrUpdate(Type, Type)
  fullName: Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistryBase.AddOrUpdate(System.Type, System.Type)
  type: Method
  source:
    id: AddOrUpdate
    path: C:\Dev\Community\Apizr\Apizr\Apizr.Extensions.Microsoft.DependencyInjection\Extending\Configuring\Registry\IApizrExtendedConcurrentRegistryBase.cs
    startLine: 6
  assemblies:
  - Apizr.Extensions.Microsoft.DependencyInjection
  namespace: Apizr.Extending.Configuring.Registry
  syntax:
    content: void AddOrUpdate(Type webApiType, Type serviceType)
    parameters:
    - id: webApiType
      type: System.Type
    - id: serviceType
      type: System.Type
    content.vb: Sub AddOrUpdate(webApiType As Type, serviceType As Type)
  overload: Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistryBase.AddOrUpdate*
references:
- uid: Apizr.Extending.Configuring.Registry
  commentId: N:Apizr.Extending.Configuring.Registry
  name: Apizr.Extending.Configuring.Registry
  nameWithType: Apizr.Extending.Configuring.Registry
  fullName: Apizr.Extending.Configuring.Registry
- uid: Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistryBase.AddOrUpdate*
  commentId: Overload:Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistryBase.AddOrUpdate
  name: AddOrUpdate
  nameWithType: IApizrExtendedConcurrentRegistryBase.AddOrUpdate
  fullName: Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistryBase.AddOrUpdate
- uid: System.Type
  commentId: T:System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
