### YamlMime:ManagedReference
items:
- uid: Apizr.Configuring.Registry
  commentId: N:Apizr.Configuring.Registry
  id: Apizr.Configuring.Registry
  children:
  - Apizr.Configuring.Registry.ApizrRegistry
  - Apizr.Configuring.Registry.ApizrRegistryBase
  - Apizr.Configuring.Registry.ApizrRegistryBuilder
  - Apizr.Configuring.Registry.IApizrEnumerableRegistry
  - Apizr.Configuring.Registry.IApizrRegistry
  - Apizr.Configuring.Registry.IApizrRegistryBuilder
  - Apizr.Configuring.Registry.IApizrRegistryBuilderBase
  - Apizr.Configuring.Registry.IApizrRegistryBuilderBase`4
  - Apizr.Configuring.Registry.IApizrRegistryBuilder`4
  langs:
  - csharp
  - vb
  name: Apizr.Configuring.Registry
  nameWithType: Apizr.Configuring.Registry
  fullName: Apizr.Configuring.Registry
  type: Namespace
  assemblies:
  - Apizr
references:
- uid: Apizr.Configuring.Registry.ApizrRegistry
  commentId: T:Apizr.Configuring.Registry.ApizrRegistry
  parent: Apizr.Configuring.Registry
  href: Apizr.Configuring.Registry.ApizrRegistry.html
  name: ApizrRegistry
  nameWithType: ApizrRegistry
  fullName: Apizr.Configuring.Registry.ApizrRegistry
- uid: Apizr.Configuring.Registry.ApizrRegistryBase
  commentId: T:Apizr.Configuring.Registry.ApizrRegistryBase
  parent: Apizr.Configuring.Registry
  href: Apizr.Configuring.Registry.ApizrRegistryBase.html
  name: ApizrRegistryBase
  nameWithType: ApizrRegistryBase
  fullName: Apizr.Configuring.Registry.ApizrRegistryBase
- uid: Apizr.Configuring.Registry.ApizrRegistryBuilder
  commentId: T:Apizr.Configuring.Registry.ApizrRegistryBuilder
  href: Apizr.Configuring.Registry.ApizrRegistryBuilder.html
  name: ApizrRegistryBuilder
  nameWithType: ApizrRegistryBuilder
  fullName: Apizr.Configuring.Registry.ApizrRegistryBuilder
- uid: Apizr.Configuring.Registry.IApizrEnumerableRegistry
  commentId: T:Apizr.Configuring.Registry.IApizrEnumerableRegistry
  parent: Apizr.Configuring.Registry
  href: Apizr.Configuring.Registry.IApizrEnumerableRegistry.html
  name: IApizrEnumerableRegistry
  nameWithType: IApizrEnumerableRegistry
  fullName: Apizr.Configuring.Registry.IApizrEnumerableRegistry
- uid: Apizr.Configuring.Registry.IApizrRegistry
  commentId: T:Apizr.Configuring.Registry.IApizrRegistry
  parent: Apizr.Configuring.Registry
  href: Apizr.Configuring.Registry.IApizrRegistry.html
  name: IApizrRegistry
  nameWithType: IApizrRegistry
  fullName: Apizr.Configuring.Registry.IApizrRegistry
- uid: Apizr.Configuring.Registry.IApizrRegistryBuilder`4
  commentId: T:Apizr.Configuring.Registry.IApizrRegistryBuilder`4
  href: Apizr.Configuring.Registry.IApizrRegistryBuilder-4.html
  name: IApizrRegistryBuilder<TApizrRegistry, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder>
  nameWithType: IApizrRegistryBuilder<TApizrRegistry, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder>
  fullName: Apizr.Configuring.Registry.IApizrRegistryBuilder<TApizrRegistry, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder>
  nameWithType.vb: IApizrRegistryBuilder(Of TApizrRegistry, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder)
  fullName.vb: Apizr.Configuring.Registry.IApizrRegistryBuilder(Of TApizrRegistry, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder)
  name.vb: IApizrRegistryBuilder(Of TApizrRegistry, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder)
  spec.csharp:
  - uid: Apizr.Configuring.Registry.IApizrRegistryBuilder`4
    name: IApizrRegistryBuilder
    href: Apizr.Configuring.Registry.IApizrRegistryBuilder-4.html
  - name: <
  - name: TApizrRegistry
  - name: ','
  - name: " "
  - name: TApizrRegistryBuilder
  - name: ','
  - name: " "
  - name: TApizrProperOptionsBuilder
  - name: ','
  - name: " "
  - name: TApizrCommonOptionsBuilder
  - name: '>'
  spec.vb:
  - uid: Apizr.Configuring.Registry.IApizrRegistryBuilder`4
    name: IApizrRegistryBuilder
    href: Apizr.Configuring.Registry.IApizrRegistryBuilder-4.html
  - name: (
  - name: Of
  - name: " "
  - name: TApizrRegistry
  - name: ','
  - name: " "
  - name: TApizrRegistryBuilder
  - name: ','
  - name: " "
  - name: TApizrProperOptionsBuilder
  - name: ','
  - name: " "
  - name: TApizrCommonOptionsBuilder
  - name: )
- uid: Apizr.Configuring.Registry.IApizrRegistryBuilder
  commentId: T:Apizr.Configuring.Registry.IApizrRegistryBuilder
  parent: Apizr.Configuring.Registry
  href: Apizr.Configuring.Registry.IApizrRegistryBuilder.html
  name: IApizrRegistryBuilder
  nameWithType: IApizrRegistryBuilder
  fullName: Apizr.Configuring.Registry.IApizrRegistryBuilder
- uid: Apizr.Configuring.Registry.IApizrRegistryBuilderBase
  commentId: T:Apizr.Configuring.Registry.IApizrRegistryBuilderBase
  parent: Apizr.Configuring.Registry
  href: Apizr.Configuring.Registry.IApizrRegistryBuilderBase.html
  name: IApizrRegistryBuilderBase
  nameWithType: IApizrRegistryBuilderBase
  fullName: Apizr.Configuring.Registry.IApizrRegistryBuilderBase
- uid: Apizr.Configuring.Registry.IApizrRegistryBuilderBase`4
  commentId: T:Apizr.Configuring.Registry.IApizrRegistryBuilderBase`4
  href: Apizr.Configuring.Registry.IApizrRegistryBuilderBase-4.html
  name: IApizrRegistryBuilderBase<TApizrRegistry, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder>
  nameWithType: IApizrRegistryBuilderBase<TApizrRegistry, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder>
  fullName: Apizr.Configuring.Registry.IApizrRegistryBuilderBase<TApizrRegistry, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder>
  nameWithType.vb: IApizrRegistryBuilderBase(Of TApizrRegistry, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder)
  fullName.vb: Apizr.Configuring.Registry.IApizrRegistryBuilderBase(Of TApizrRegistry, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder)
  name.vb: IApizrRegistryBuilderBase(Of TApizrRegistry, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder)
  spec.csharp:
  - uid: Apizr.Configuring.Registry.IApizrRegistryBuilderBase`4
    name: IApizrRegistryBuilderBase
    href: Apizr.Configuring.Registry.IApizrRegistryBuilderBase-4.html
  - name: <
  - name: TApizrRegistry
  - name: ','
  - name: " "
  - name: TApizrRegistryBuilder
  - name: ','
  - name: " "
  - name: TApizrProperOptionsBuilder
  - name: ','
  - name: " "
  - name: TApizrCommonOptionsBuilder
  - name: '>'
  spec.vb:
  - uid: Apizr.Configuring.Registry.IApizrRegistryBuilderBase`4
    name: IApizrRegistryBuilderBase
    href: Apizr.Configuring.Registry.IApizrRegistryBuilderBase-4.html
  - name: (
  - name: Of
  - name: " "
  - name: TApizrRegistry
  - name: ','
  - name: " "
  - name: TApizrRegistryBuilder
  - name: ','
  - name: " "
  - name: TApizrProperOptionsBuilder
  - name: ','
  - name: " "
  - name: TApizrCommonOptionsBuilder
  - name: )
- uid: Apizr.Configuring.Registry
  commentId: N:Apizr.Configuring.Registry
  href: Apizr.html
  name: Apizr.Configuring.Registry
  nameWithType: Apizr.Configuring.Registry
  fullName: Apizr.Configuring.Registry
  spec.csharp:
  - uid: Apizr
    name: Apizr
    href: Apizr.html
  - name: .
  - uid: Apizr.Configuring
    name: Configuring
    href: Apizr.Configuring.html
  - name: .
  - uid: Apizr.Configuring.Registry
    name: Registry
    href: Apizr.Configuring.Registry.html
  spec.vb:
  - uid: Apizr
    name: Apizr
    href: Apizr.html
  - name: .
  - uid: Apizr.Configuring
    name: Configuring
    href: Apizr.Configuring.html
  - name: .
  - uid: Apizr.Configuring.Registry
    name: Registry
    href: Apizr.Configuring.Registry.html
