### YamlMime:ManagedReference
items:
- uid: Apizr.Configuring.Registry.IApizrDownloadRegistryBuilderBase`4
  commentId: T:Apizr.Configuring.Registry.IApizrDownloadRegistryBuilderBase`4
  id: IApizrDownloadRegistryBuilderBase`4
  parent: Apizr.Configuring.Registry
  children:
  - Apizr.Configuring.Registry.IApizrDownloadRegistryBuilderBase`4.AddFor``1(System.Action{`2})
  - Apizr.Configuring.Registry.IApizrDownloadRegistryBuilderBase`4.AddFor``2(System.Action{`2})
  langs:
  - csharp
  - vb
  name: IApizrDownloadRegistryBuilderBase<TApizrDownloadRegistryBuilder, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder>
  nameWithType: IApizrDownloadRegistryBuilderBase<TApizrDownloadRegistryBuilder, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder>
  fullName: Apizr.Configuring.Registry.IApizrDownloadRegistryBuilderBase<TApizrDownloadRegistryBuilder, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder>
  type: Interface
  source:
    id: IApizrDownloadRegistryBuilderBase
    path: C:\Dev\Community\Apizr\Apizr\Src\Transferring\Apizr.Integrations.FileTransfer\Configuring\Registry\IApizrDownloadRegistryBuilderBase.cs
    startLine: 7
  assemblies:
  - Apizr.Integrations.FileTransfer
  namespace: Apizr.Configuring.Registry
  syntax:
    content: >-
      public interface IApizrDownloadRegistryBuilderBase<out TApizrDownloadRegistryBuilder, out TApizrRegistryBuilder, out TApizrProperOptionsBuilder, out TApizrCommonOptionsBuilder>
          where TApizrDownloadRegistryBuilder : IApizrDownloadRegistryBuilderBase<TApizrDownloadRegistryBuilder, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder> where TApizrRegistryBuilder : IApizrRegistryBuilderBase where TApizrProperOptionsBuilder : IApizrGlobalProperOptionsBuilderBase where TApizrCommonOptionsBuilder : IApizrGlobalCommonOptionsBuilderBase
    typeParameters:
    - id: TApizrDownloadRegistryBuilder
    - id: TApizrRegistryBuilder
    - id: TApizrProperOptionsBuilder
    - id: TApizrCommonOptionsBuilder
    content.vb: Public Interface IApizrDownloadRegistryBuilderBase(Of Out TApizrDownloadRegistryBuilder As IApizrDownloadRegistryBuilderBase(Of TApizrDownloadRegistryBuilder, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder), Out TApizrRegistryBuilder As IApizrRegistryBuilderBase, Out TApizrProperOptionsBuilder As IApizrGlobalProperOptionsBuilderBase, Out TApizrCommonOptionsBuilder As IApizrGlobalCommonOptionsBuilderBase)
  nameWithType.vb: IApizrDownloadRegistryBuilderBase(Of TApizrDownloadRegistryBuilder, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder)
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
  fullName.vb: Apizr.Configuring.Registry.IApizrDownloadRegistryBuilderBase(Of TApizrDownloadRegistryBuilder, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder)
  name.vb: IApizrDownloadRegistryBuilderBase(Of TApizrDownloadRegistryBuilder, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder)
- uid: Apizr.Configuring.Registry.IApizrDownloadRegistryBuilderBase`4.AddFor``1(System.Action{`2})
  commentId: M:Apizr.Configuring.Registry.IApizrDownloadRegistryBuilderBase`4.AddFor``1(System.Action{`2})
  id: AddFor``1(System.Action{`2})
  parent: Apizr.Configuring.Registry.IApizrDownloadRegistryBuilderBase`4
  langs:
  - csharp
  - vb
  name: AddFor<TDownloadApi>(Action<TApizrProperOptionsBuilder>)
  nameWithType: IApizrDownloadRegistryBuilderBase<TApizrDownloadRegistryBuilder, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder>.AddFor<TDownloadApi>(Action<TApizrProperOptionsBuilder>)
  fullName: Apizr.Configuring.Registry.IApizrDownloadRegistryBuilderBase<TApizrDownloadRegistryBuilder, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder>.AddFor<TDownloadApi>(System.Action<TApizrProperOptionsBuilder>)
  type: Method
  source:
    id: AddFor
    path: C:\Dev\Community\Apizr\Apizr\Src\Transferring\Apizr.Integrations.FileTransfer\Configuring\Registry\IApizrDownloadRegistryBuilderBase.cs
    startLine: 13
  assemblies:
  - Apizr.Integrations.FileTransfer
  namespace: Apizr.Configuring.Registry
  syntax:
    content: >-
      TApizrDownloadRegistryBuilder AddFor<TDownloadApi>(Action<TApizrProperOptionsBuilder> optionsBuilder = null)
          where TDownloadApi : IDownloadApi
    parameters:
    - id: optionsBuilder
      type: System.Action{{TApizrProperOptionsBuilder}}
    typeParameters:
    - id: TDownloadApi
    return:
      type: '{TApizrDownloadRegistryBuilder}'
    content.vb: Function AddFor(Of TDownloadApi As IDownloadApi)(optionsBuilder As Action(Of TApizrProperOptionsBuilder) = Nothing) As TApizrDownloadRegistryBuilder
  overload: Apizr.Configuring.Registry.IApizrDownloadRegistryBuilderBase`4.AddFor*
  nameWithType.vb: IApizrDownloadRegistryBuilderBase(Of TApizrDownloadRegistryBuilder, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder).AddFor(Of TDownloadApi)(Action(Of TApizrProperOptionsBuilder))
  fullName.vb: Apizr.Configuring.Registry.IApizrDownloadRegistryBuilderBase(Of TApizrDownloadRegistryBuilder, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder).AddFor(Of TDownloadApi)(System.Action(Of TApizrProperOptionsBuilder))
  name.vb: AddFor(Of TDownloadApi)(Action(Of TApizrProperOptionsBuilder))
- uid: Apizr.Configuring.Registry.IApizrDownloadRegistryBuilderBase`4.AddFor``2(System.Action{`2})
  commentId: M:Apizr.Configuring.Registry.IApizrDownloadRegistryBuilderBase`4.AddFor``2(System.Action{`2})
  id: AddFor``2(System.Action{`2})
  parent: Apizr.Configuring.Registry.IApizrDownloadRegistryBuilderBase`4
  langs:
  - csharp
  - vb
  name: AddFor<TDownloadApi, TDownloadParams>(Action<TApizrProperOptionsBuilder>)
  nameWithType: IApizrDownloadRegistryBuilderBase<TApizrDownloadRegistryBuilder, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder>.AddFor<TDownloadApi, TDownloadParams>(Action<TApizrProperOptionsBuilder>)
  fullName: Apizr.Configuring.Registry.IApizrDownloadRegistryBuilderBase<TApizrDownloadRegistryBuilder, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder>.AddFor<TDownloadApi, TDownloadParams>(System.Action<TApizrProperOptionsBuilder>)
  type: Method
  source:
    id: AddFor
    path: C:\Dev\Community\Apizr\Apizr\Src\Transferring\Apizr.Integrations.FileTransfer\Configuring\Registry\IApizrDownloadRegistryBuilderBase.cs
    startLine: 16
  assemblies:
  - Apizr.Integrations.FileTransfer
  namespace: Apizr.Configuring.Registry
  syntax:
    content: >-
      TApizrDownloadRegistryBuilder AddFor<TDownloadApi, TDownloadParams>(Action<TApizrProperOptionsBuilder> optionsBuilder = null)
          where TDownloadApi : IDownloadApi<TDownloadParams>
    parameters:
    - id: optionsBuilder
      type: System.Action{{TApizrProperOptionsBuilder}}
    typeParameters:
    - id: TDownloadApi
    - id: TDownloadParams
    return:
      type: '{TApizrDownloadRegistryBuilder}'
    content.vb: Function AddFor(Of TDownloadApi As IDownloadApi(Of TDownloadParams), TDownloadParams)(optionsBuilder As Action(Of TApizrProperOptionsBuilder) = Nothing) As TApizrDownloadRegistryBuilder
  overload: Apizr.Configuring.Registry.IApizrDownloadRegistryBuilderBase`4.AddFor*
  nameWithType.vb: IApizrDownloadRegistryBuilderBase(Of TApizrDownloadRegistryBuilder, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder).AddFor(Of TDownloadApi, TDownloadParams)(Action(Of TApizrProperOptionsBuilder))
  fullName.vb: Apizr.Configuring.Registry.IApizrDownloadRegistryBuilderBase(Of TApizrDownloadRegistryBuilder, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder).AddFor(Of TDownloadApi, TDownloadParams)(System.Action(Of TApizrProperOptionsBuilder))
  name.vb: AddFor(Of TDownloadApi, TDownloadParams)(Action(Of TApizrProperOptionsBuilder))
references:
- uid: Apizr.Configuring.Registry
  commentId: N:Apizr.Configuring.Registry
  name: Apizr.Configuring.Registry
  nameWithType: Apizr.Configuring.Registry
  fullName: Apizr.Configuring.Registry
- uid: Apizr.Configuring.Registry.IApizrDownloadRegistryBuilderBase`4.AddFor*
  commentId: Overload:Apizr.Configuring.Registry.IApizrDownloadRegistryBuilderBase`4.AddFor
  name: AddFor
  nameWithType: IApizrDownloadRegistryBuilderBase<TApizrDownloadRegistryBuilder, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder>.AddFor
  fullName: Apizr.Configuring.Registry.IApizrDownloadRegistryBuilderBase<TApizrDownloadRegistryBuilder, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder>.AddFor
  nameWithType.vb: IApizrDownloadRegistryBuilderBase(Of TApizrDownloadRegistryBuilder, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder).AddFor
  fullName.vb: Apizr.Configuring.Registry.IApizrDownloadRegistryBuilderBase(Of TApizrDownloadRegistryBuilder, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder).AddFor
- uid: System.Action{{TApizrProperOptionsBuilder}}
  commentId: T:System.Action{`2}
  parent: System
  definition: System.Action`1
  name: Action<TApizrProperOptionsBuilder>
  nameWithType: Action<TApizrProperOptionsBuilder>
  fullName: System.Action<TApizrProperOptionsBuilder>
  nameWithType.vb: Action(Of TApizrProperOptionsBuilder)
  fullName.vb: System.Action(Of TApizrProperOptionsBuilder)
  name.vb: Action(Of TApizrProperOptionsBuilder)
  spec.csharp:
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: TApizrProperOptionsBuilder
    nameWithType: TApizrProperOptionsBuilder
    fullName: TApizrProperOptionsBuilder
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TApizrProperOptionsBuilder
    nameWithType: TApizrProperOptionsBuilder
    fullName: TApizrProperOptionsBuilder
  - name: )
    nameWithType: )
    fullName: )
- uid: '{TApizrDownloadRegistryBuilder}'
  commentId: '!:TApizrDownloadRegistryBuilder'
  definition: TApizrDownloadRegistryBuilder
  name: TApizrDownloadRegistryBuilder
  nameWithType: TApizrDownloadRegistryBuilder
  fullName: TApizrDownloadRegistryBuilder
- uid: System.Action`1
  commentId: T:System.Action`1
  isExternal: true
  name: Action<T>
  nameWithType: Action<T>
  fullName: System.Action<T>
  nameWithType.vb: Action(Of T)
  fullName.vb: System.Action(Of T)
  name.vb: Action(Of T)
  spec.csharp:
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: TApizrDownloadRegistryBuilder
  name: TApizrDownloadRegistryBuilder
  nameWithType: TApizrDownloadRegistryBuilder
  fullName: TApizrDownloadRegistryBuilder
