### YamlMime:ManagedReference
items:
- uid: Apizr.Configuring.ApizrRegistrationMode
  commentId: T:Apizr.Configuring.ApizrRegistrationMode
  id: ApizrRegistrationMode
  parent: Apizr.Configuring
  children:
  - Apizr.Configuring.ApizrRegistrationMode.Set
  - Apizr.Configuring.ApizrRegistrationMode.Store
  langs:
  - csharp
  - vb
  name: ApizrRegistrationMode
  nameWithType: ApizrRegistrationMode
  fullName: Apizr.Configuring.ApizrRegistrationMode
  type: Enum
  source:
    remote:
      path: Apizr/Src/Apizr/Configuring/ApizrRegistrationMode.cs
      branch: dev
      repo: https://github.com/Respawnsive/Apizr.git
    id: ApizrRegistrationMode
    path: ../../Src/Apizr/Configuring/ApizrRegistrationMode.cs
    startLine: 6
  assemblies:
  - Apizr
  namespace: Apizr.Configuring
  syntax:
    content: public enum ApizrRegistrationMode
    content.vb: Public Enum ApizrRegistrationMode
- uid: Apizr.Configuring.ApizrRegistrationMode.Set
  commentId: F:Apizr.Configuring.ApizrRegistrationMode.Set
  id: Set
  parent: Apizr.Configuring.ApizrRegistrationMode
  langs:
  - csharp
  - vb
  name: Set
  nameWithType: ApizrRegistrationMode.Set
  fullName: Apizr.Configuring.ApizrRegistrationMode.Set
  type: Field
  source:
    remote:
      path: Apizr/Src/Apizr/Configuring/ApizrRegistrationMode.cs
      branch: dev
      repo: https://github.com/Respawnsive/Apizr.git
    id: Set
    path: ../../Src/Apizr/Configuring/ApizrRegistrationMode.cs
    startLine: 8
  assemblies:
  - Apizr
  namespace: Apizr.Configuring
  syntax:
    content: Set = 0
    return:
      type: Apizr.Configuring.ApizrRegistrationMode
- uid: Apizr.Configuring.ApizrRegistrationMode.Store
  commentId: F:Apizr.Configuring.ApizrRegistrationMode.Store
  id: Store
  parent: Apizr.Configuring.ApizrRegistrationMode
  langs:
  - csharp
  - vb
  name: Store
  nameWithType: ApizrRegistrationMode.Store
  fullName: Apizr.Configuring.ApizrRegistrationMode.Store
  type: Field
  source:
    remote:
      path: Apizr/Src/Apizr/Configuring/ApizrRegistrationMode.cs
      branch: dev
      repo: https://github.com/Respawnsive/Apizr.git
    id: Store
    path: ../../Src/Apizr/Configuring/ApizrRegistrationMode.cs
    startLine: 9
  assemblies:
  - Apizr
  namespace: Apizr.Configuring
  syntax:
    content: Store = 1
    return:
      type: Apizr.Configuring.ApizrRegistrationMode
references:
- uid: Apizr.Configuring
  commentId: N:Apizr.Configuring
  href: Apizr.html
  name: Apizr.Configuring
  nameWithType: Apizr.Configuring
  fullName: Apizr.Configuring
  spec.csharp:
  - uid: Apizr
    name: Apizr
    href: Apizr.html
  - name: .
  - uid: Apizr.Configuring
    name: Configuring
    href: Apizr.Configuring.html
  spec.vb:
  - uid: Apizr
    name: Apizr
    href: Apizr.html
  - name: .
  - uid: Apizr.Configuring
    name: Configuring
    href: Apizr.Configuring.html
- uid: Apizr.Configuring.ApizrRegistrationMode
  commentId: T:Apizr.Configuring.ApizrRegistrationMode
  parent: Apizr.Configuring
  href: Apizr.Configuring.ApizrRegistrationMode.html
  name: ApizrRegistrationMode
  nameWithType: ApizrRegistrationMode
  fullName: Apizr.Configuring.ApizrRegistrationMode
