### YamlMime:ManagedReference
items:
- uid: Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptions
  commentId: T:Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptions
  id: IApizrExtendedProperOptions
  parent: Apizr.Extending.Configuring.Proper
  children:
  - Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptions.ApizrManagerType
  - Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptions.LoggerFactory
  langs:
  - csharp
  - vb
  name: IApizrExtendedProperOptions
  nameWithType: IApizrExtendedProperOptions
  fullName: Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptions
  type: Interface
  source:
    id: IApizrExtendedProperOptions
    path: C:\Dev\Community\Apizr\Apizr\Apizr.Extensions.Microsoft.DependencyInjection\Extending\Configuring\Proper\IApizrExtendedProperOptions.cs
    startLine: 6
  assemblies:
  - Apizr.Extensions.Microsoft.DependencyInjection
  namespace: Apizr.Extending.Configuring.Proper
  syntax:
    content: 'public interface IApizrExtendedProperOptions : IApizrExtendedProperOptionsBase, IApizrProperOptionsBase, IApizrExtendedSharedOptions, IApizrExtendedSharedOptionsBase, IApizrSharedOptionsBase'
    content.vb: >-
      Public Interface IApizrExtendedProperOptions
          Inherits IApizrExtendedProperOptionsBase, IApizrExtendedSharedOptions
  inheritedMembers:
  - Apizr.Configuring.Proper.IApizrProperOptionsBase.WebApiType
  - Apizr.Configuring.Proper.IApizrProperOptionsBase.PolicyRegistryKeys
  - Apizr.Configuring.Proper.IApizrProperOptionsBase.Logger
  - Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptions.BaseUriFactory
  - Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptions.BaseAddressFactory
  - Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptions.BasePathFactory
  - Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptions.HttpTracerModeFactory
  - Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptions.TrafficVerbosityFactory
  - Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptions.LogLevelsFactory
  - Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptions.HttpClientHandlerFactory
  - Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptions.HttpClientBuilder
  - Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptionsBase.DelegatingHandlersExtendedFactories
  - Apizr.Configuring.Shared.IApizrSharedOptionsBase.BaseUri
  - Apizr.Configuring.Shared.IApizrSharedOptionsBase.BaseAddress
  - Apizr.Configuring.Shared.IApizrSharedOptionsBase.BasePath
  - Apizr.Configuring.Shared.IApizrSharedOptionsBase.HttpTracerMode
  - Apizr.Configuring.Shared.IApizrSharedOptionsBase.TrafficVerbosity
  - Apizr.Configuring.Shared.IApizrSharedOptionsBase.LogLevels
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptions.ApizrManagerType
  commentId: P:Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptions.ApizrManagerType
  id: ApizrManagerType
  parent: Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptions
  langs:
  - csharp
  - vb
  name: ApizrManagerType
  nameWithType: IApizrExtendedProperOptions.ApizrManagerType
  fullName: Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptions.ApizrManagerType
  type: Property
  source:
    id: ApizrManagerType
    path: C:\Dev\Community\Apizr\Apizr\Apizr.Extensions.Microsoft.DependencyInjection\Extending\Configuring\Proper\IApizrExtendedProperOptions.cs
    startLine: 11
  assemblies:
  - Apizr.Extensions.Microsoft.DependencyInjection
  namespace: Apizr.Extending.Configuring.Proper
  summary: "\nType of the manager\n"
  example: []
  syntax:
    content: Type ApizrManagerType { get; }
    parameters: []
    return:
      type: System.Type
    content.vb: ReadOnly Property ApizrManagerType As Type
  overload: Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptions.ApizrManagerType*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptions.LoggerFactory
  commentId: P:Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptions.LoggerFactory
  id: LoggerFactory
  parent: Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptions
  langs:
  - csharp
  - vb
  name: LoggerFactory
  nameWithType: IApizrExtendedProperOptions.LoggerFactory
  fullName: Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptions.LoggerFactory
  type: Property
  source:
    id: LoggerFactory
    path: C:\Dev\Community\Apizr\Apizr\Apizr.Extensions.Microsoft.DependencyInjection\Extending\Configuring\Proper\IApizrExtendedProperOptions.cs
    startLine: 16
  assemblies:
  - Apizr.Extensions.Microsoft.DependencyInjection
  namespace: Apizr.Extending.Configuring.Proper
  summary: "\nThe Logger factory\n"
  example: []
  syntax:
    content: Func<IServiceProvider, string, ILogger> LoggerFactory { get; }
    parameters: []
    return:
      type: System.Func{System.IServiceProvider,System.String,Microsoft.Extensions.Logging.ILogger}
    content.vb: ReadOnly Property LoggerFactory As Func(Of IServiceProvider, String, ILogger)
  overload: Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptions.LoggerFactory*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
references:
- uid: Apizr.Extending.Configuring.Proper
  commentId: N:Apizr.Extending.Configuring.Proper
  name: Apizr.Extending.Configuring.Proper
  nameWithType: Apizr.Extending.Configuring.Proper
  fullName: Apizr.Extending.Configuring.Proper
- uid: Apizr.Configuring.Proper.IApizrProperOptionsBase.WebApiType
  commentId: P:Apizr.Configuring.Proper.IApizrProperOptionsBase.WebApiType
  parent: Apizr.Configuring.Proper.IApizrProperOptionsBase
  name: WebApiType
  nameWithType: IApizrProperOptionsBase.WebApiType
  fullName: Apizr.Configuring.Proper.IApizrProperOptionsBase.WebApiType
- uid: Apizr.Configuring.Proper.IApizrProperOptionsBase.PolicyRegistryKeys
  commentId: P:Apizr.Configuring.Proper.IApizrProperOptionsBase.PolicyRegistryKeys
  parent: Apizr.Configuring.Proper.IApizrProperOptionsBase
  name: PolicyRegistryKeys
  nameWithType: IApizrProperOptionsBase.PolicyRegistryKeys
  fullName: Apizr.Configuring.Proper.IApizrProperOptionsBase.PolicyRegistryKeys
- uid: Apizr.Configuring.Proper.IApizrProperOptionsBase.Logger
  commentId: P:Apizr.Configuring.Proper.IApizrProperOptionsBase.Logger
  parent: Apizr.Configuring.Proper.IApizrProperOptionsBase
  name: Logger
  nameWithType: IApizrProperOptionsBase.Logger
  fullName: Apizr.Configuring.Proper.IApizrProperOptionsBase.Logger
- uid: Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptions.BaseUriFactory
  commentId: P:Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptions.BaseUriFactory
  parent: Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptions
  name: BaseUriFactory
  nameWithType: IApizrExtendedSharedOptions.BaseUriFactory
  fullName: Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptions.BaseUriFactory
- uid: Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptions.BaseAddressFactory
  commentId: P:Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptions.BaseAddressFactory
  parent: Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptions
  name: BaseAddressFactory
  nameWithType: IApizrExtendedSharedOptions.BaseAddressFactory
  fullName: Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptions.BaseAddressFactory
- uid: Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptions.BasePathFactory
  commentId: P:Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptions.BasePathFactory
  parent: Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptions
  name: BasePathFactory
  nameWithType: IApizrExtendedSharedOptions.BasePathFactory
  fullName: Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptions.BasePathFactory
- uid: Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptions.HttpTracerModeFactory
  commentId: P:Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptions.HttpTracerModeFactory
  parent: Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptions
  name: HttpTracerModeFactory
  nameWithType: IApizrExtendedSharedOptions.HttpTracerModeFactory
  fullName: Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptions.HttpTracerModeFactory
- uid: Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptions.TrafficVerbosityFactory
  commentId: P:Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptions.TrafficVerbosityFactory
  parent: Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptions
  name: TrafficVerbosityFactory
  nameWithType: IApizrExtendedSharedOptions.TrafficVerbosityFactory
  fullName: Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptions.TrafficVerbosityFactory
- uid: Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptions.LogLevelsFactory
  commentId: P:Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptions.LogLevelsFactory
  parent: Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptions
  name: LogLevelsFactory
  nameWithType: IApizrExtendedSharedOptions.LogLevelsFactory
  fullName: Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptions.LogLevelsFactory
- uid: Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptions.HttpClientHandlerFactory
  commentId: P:Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptions.HttpClientHandlerFactory
  parent: Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptions
  name: HttpClientHandlerFactory
  nameWithType: IApizrExtendedSharedOptions.HttpClientHandlerFactory
  fullName: Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptions.HttpClientHandlerFactory
- uid: Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptions.HttpClientBuilder
  commentId: P:Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptions.HttpClientBuilder
  parent: Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptions
  name: HttpClientBuilder
  nameWithType: IApizrExtendedSharedOptions.HttpClientBuilder
  fullName: Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptions.HttpClientBuilder
- uid: Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptionsBase.DelegatingHandlersExtendedFactories
  commentId: P:Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptionsBase.DelegatingHandlersExtendedFactories
  parent: Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptionsBase
  name: DelegatingHandlersExtendedFactories
  nameWithType: IApizrExtendedSharedOptionsBase.DelegatingHandlersExtendedFactories
  fullName: Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptionsBase.DelegatingHandlersExtendedFactories
- uid: Apizr.Configuring.Shared.IApizrSharedOptionsBase.BaseUri
  commentId: P:Apizr.Configuring.Shared.IApizrSharedOptionsBase.BaseUri
  parent: Apizr.Configuring.Shared.IApizrSharedOptionsBase
  name: BaseUri
  nameWithType: IApizrSharedOptionsBase.BaseUri
  fullName: Apizr.Configuring.Shared.IApizrSharedOptionsBase.BaseUri
- uid: Apizr.Configuring.Shared.IApizrSharedOptionsBase.BaseAddress
  commentId: P:Apizr.Configuring.Shared.IApizrSharedOptionsBase.BaseAddress
  parent: Apizr.Configuring.Shared.IApizrSharedOptionsBase
  name: BaseAddress
  nameWithType: IApizrSharedOptionsBase.BaseAddress
  fullName: Apizr.Configuring.Shared.IApizrSharedOptionsBase.BaseAddress
- uid: Apizr.Configuring.Shared.IApizrSharedOptionsBase.BasePath
  commentId: P:Apizr.Configuring.Shared.IApizrSharedOptionsBase.BasePath
  parent: Apizr.Configuring.Shared.IApizrSharedOptionsBase
  name: BasePath
  nameWithType: IApizrSharedOptionsBase.BasePath
  fullName: Apizr.Configuring.Shared.IApizrSharedOptionsBase.BasePath
- uid: Apizr.Configuring.Shared.IApizrSharedOptionsBase.HttpTracerMode
  commentId: P:Apizr.Configuring.Shared.IApizrSharedOptionsBase.HttpTracerMode
  parent: Apizr.Configuring.Shared.IApizrSharedOptionsBase
  name: HttpTracerMode
  nameWithType: IApizrSharedOptionsBase.HttpTracerMode
  fullName: Apizr.Configuring.Shared.IApizrSharedOptionsBase.HttpTracerMode
- uid: Apizr.Configuring.Shared.IApizrSharedOptionsBase.TrafficVerbosity
  commentId: P:Apizr.Configuring.Shared.IApizrSharedOptionsBase.TrafficVerbosity
  parent: Apizr.Configuring.Shared.IApizrSharedOptionsBase
  name: TrafficVerbosity
  nameWithType: IApizrSharedOptionsBase.TrafficVerbosity
  fullName: Apizr.Configuring.Shared.IApizrSharedOptionsBase.TrafficVerbosity
- uid: Apizr.Configuring.Shared.IApizrSharedOptionsBase.LogLevels
  commentId: P:Apizr.Configuring.Shared.IApizrSharedOptionsBase.LogLevels
  parent: Apizr.Configuring.Shared.IApizrSharedOptionsBase
  name: LogLevels
  nameWithType: IApizrSharedOptionsBase.LogLevels
  fullName: Apizr.Configuring.Shared.IApizrSharedOptionsBase.LogLevels
- uid: Apizr.Configuring.Proper.IApizrProperOptionsBase
  commentId: T:Apizr.Configuring.Proper.IApizrProperOptionsBase
  parent: Apizr.Configuring.Proper
  name: IApizrProperOptionsBase
  nameWithType: IApizrProperOptionsBase
  fullName: Apizr.Configuring.Proper.IApizrProperOptionsBase
- uid: Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptions
  commentId: T:Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptions
  parent: Apizr.Extending.Configuring.Shared
  name: IApizrExtendedSharedOptions
  nameWithType: IApizrExtendedSharedOptions
  fullName: Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptions
- uid: Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptionsBase
  commentId: T:Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptionsBase
  parent: Apizr.Extending.Configuring.Shared
  name: IApizrExtendedSharedOptionsBase
  nameWithType: IApizrExtendedSharedOptionsBase
  fullName: Apizr.Extending.Configuring.Shared.IApizrExtendedSharedOptionsBase
- uid: Apizr.Configuring.Shared.IApizrSharedOptionsBase
  commentId: T:Apizr.Configuring.Shared.IApizrSharedOptionsBase
  parent: Apizr.Configuring.Shared
  name: IApizrSharedOptionsBase
  nameWithType: IApizrSharedOptionsBase
  fullName: Apizr.Configuring.Shared.IApizrSharedOptionsBase
- uid: Apizr.Configuring.Proper
  commentId: N:Apizr.Configuring.Proper
  name: Apizr.Configuring.Proper
  nameWithType: Apizr.Configuring.Proper
  fullName: Apizr.Configuring.Proper
- uid: Apizr.Extending.Configuring.Shared
  commentId: N:Apizr.Extending.Configuring.Shared
  name: Apizr.Extending.Configuring.Shared
  nameWithType: Apizr.Extending.Configuring.Shared
  fullName: Apizr.Extending.Configuring.Shared
- uid: Apizr.Configuring.Shared
  commentId: N:Apizr.Configuring.Shared
  name: Apizr.Configuring.Shared
  nameWithType: Apizr.Configuring.Shared
  fullName: Apizr.Configuring.Shared
- uid: Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptions.ApizrManagerType*
  commentId: Overload:Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptions.ApizrManagerType
  name: ApizrManagerType
  nameWithType: IApizrExtendedProperOptions.ApizrManagerType
  fullName: Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptions.ApizrManagerType
- uid: System.Type
  commentId: T:System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptions.LoggerFactory*
  commentId: Overload:Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptions.LoggerFactory
  name: LoggerFactory
  nameWithType: IApizrExtendedProperOptions.LoggerFactory
  fullName: Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptions.LoggerFactory
- uid: System.Func{System.IServiceProvider,System.String,Microsoft.Extensions.Logging.ILogger}
  commentId: T:System.Func{System.IServiceProvider,System.String,Microsoft.Extensions.Logging.ILogger}
  parent: System
  definition: System.Func`3
  name: Func<IServiceProvider, String, ILogger>
  nameWithType: Func<IServiceProvider, String, ILogger>
  fullName: System.Func<System.IServiceProvider, System.String, Microsoft.Extensions.Logging.ILogger>
  nameWithType.vb: Func(Of IServiceProvider, String, ILogger)
  fullName.vb: System.Func(Of System.IServiceProvider, System.String, Microsoft.Extensions.Logging.ILogger)
  name.vb: Func(Of IServiceProvider, String, ILogger)
  spec.csharp:
  - uid: System.Func`3
    name: Func
    nameWithType: Func
    fullName: System.Func
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.IServiceProvider
    name: IServiceProvider
    nameWithType: IServiceProvider
    fullName: System.IServiceProvider
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: Microsoft.Extensions.Logging.ILogger
    name: ILogger
    nameWithType: ILogger
    fullName: Microsoft.Extensions.Logging.ILogger
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Func`3
    name: Func
    nameWithType: Func
    fullName: System.Func
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.IServiceProvider
    name: IServiceProvider
    nameWithType: IServiceProvider
    fullName: System.IServiceProvider
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: Microsoft.Extensions.Logging.ILogger
    name: ILogger
    nameWithType: ILogger
    fullName: Microsoft.Extensions.Logging.ILogger
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Func`3
  commentId: T:System.Func`3
  isExternal: true
  name: Func<T1, T2, TResult>
  nameWithType: Func<T1, T2, TResult>
  fullName: System.Func<T1, T2, TResult>
  nameWithType.vb: Func(Of T1, T2, TResult)
  fullName.vb: System.Func(Of T1, T2, TResult)
  name.vb: Func(Of T1, T2, TResult)
  spec.csharp:
  - uid: System.Func`3
    name: Func
    nameWithType: Func
    fullName: System.Func
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T1
    nameWithType: T1
    fullName: T1
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: T2
    nameWithType: T2
    fullName: T2
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TResult
    nameWithType: TResult
    fullName: TResult
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Func`3
    name: Func
    nameWithType: Func
    fullName: System.Func
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T1
    nameWithType: T1
    fullName: T1
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: T2
    nameWithType: T2
    fullName: T2
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TResult
    nameWithType: TResult
    fullName: TResult
  - name: )
    nameWithType: )
    fullName: )
