### YamlMime:ManagedReference
items:
- uid: Apizr.Configuring.Registry.IApizrUploadRegistryBuilderBase`4
  commentId: T:Apizr.Configuring.Registry.IApizrUploadRegistryBuilderBase`4
  id: IApizrUploadRegistryBuilderBase`4
  parent: Apizr.Configuring.Registry
  children:
  - Apizr.Configuring.Registry.IApizrUploadRegistryBuilderBase`4.AddFor``1(System.Action{`2})
  langs:
  - csharp
  - vb
  name: IApizrUploadRegistryBuilderBase<TApizrUploadRegistryBuilder, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder>
  nameWithType: IApizrUploadRegistryBuilderBase<TApizrUploadRegistryBuilder, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder>
  fullName: Apizr.Configuring.Registry.IApizrUploadRegistryBuilderBase<TApizrUploadRegistryBuilder, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder>
  type: Interface
  source:
    id: IApizrUploadRegistryBuilderBase
    path: C:\Dev\Community\Apizr\Apizr\Src\Transferring\Apizr.Integrations.FileTransfer\Configuring\Registry\IApizrUploadRegistryBuilderBase.cs
    startLine: 7
  assemblies:
  - Apizr.Integrations.FileTransfer
  namespace: Apizr.Configuring.Registry
  syntax:
    content: >-
      public interface IApizrUploadRegistryBuilderBase<out TApizrUploadRegistryBuilder, out TApizrRegistryBuilder, out TApizrProperOptionsBuilder, out TApizrCommonOptionsBuilder>
          where TApizrUploadRegistryBuilder : IApizrUploadRegistryBuilderBase<TApizrUploadRegistryBuilder, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder> where TApizrRegistryBuilder : IApizrRegistryBuilderBase where TApizrProperOptionsBuilder : IApizrGlobalProperOptionsBuilderBase where TApizrCommonOptionsBuilder : IApizrGlobalCommonOptionsBuilderBase
    typeParameters:
    - id: TApizrUploadRegistryBuilder
    - id: TApizrRegistryBuilder
    - id: TApizrProperOptionsBuilder
    - id: TApizrCommonOptionsBuilder
    content.vb: Public Interface IApizrUploadRegistryBuilderBase(Of Out TApizrUploadRegistryBuilder As IApizrUploadRegistryBuilderBase(Of TApizrUploadRegistryBuilder, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder), Out TApizrRegistryBuilder As IApizrRegistryBuilderBase, Out TApizrProperOptionsBuilder As IApizrGlobalProperOptionsBuilderBase, Out TApizrCommonOptionsBuilder As IApizrGlobalCommonOptionsBuilderBase)
  nameWithType.vb: IApizrUploadRegistryBuilderBase(Of TApizrUploadRegistryBuilder, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder)
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
  fullName.vb: Apizr.Configuring.Registry.IApizrUploadRegistryBuilderBase(Of TApizrUploadRegistryBuilder, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder)
  name.vb: IApizrUploadRegistryBuilderBase(Of TApizrUploadRegistryBuilder, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder)
- uid: Apizr.Configuring.Registry.IApizrUploadRegistryBuilderBase`4.AddFor``1(System.Action{`2})
  commentId: M:Apizr.Configuring.Registry.IApizrUploadRegistryBuilderBase`4.AddFor``1(System.Action{`2})
  id: AddFor``1(System.Action{`2})
  parent: Apizr.Configuring.Registry.IApizrUploadRegistryBuilderBase`4
  langs:
  - csharp
  - vb
  name: AddFor<TUploadApi>(Action<TApizrProperOptionsBuilder>)
  nameWithType: IApizrUploadRegistryBuilderBase<TApizrUploadRegistryBuilder, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder>.AddFor<TUploadApi>(Action<TApizrProperOptionsBuilder>)
  fullName: Apizr.Configuring.Registry.IApizrUploadRegistryBuilderBase<TApizrUploadRegistryBuilder, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder>.AddFor<TUploadApi>(System.Action<TApizrProperOptionsBuilder>)
  type: Method
  source:
    id: AddFor
    path: C:\Dev\Community\Apizr\Apizr\Src\Transferring\Apizr.Integrations.FileTransfer\Configuring\Registry\IApizrUploadRegistryBuilderBase.cs
    startLine: 13
  assemblies:
  - Apizr.Integrations.FileTransfer
  namespace: Apizr.Configuring.Registry
  syntax:
    content: >-
      TApizrUploadRegistryBuilder AddFor<TUploadApi>(Action<TApizrProperOptionsBuilder> optionsBuilder = null)
          where TUploadApi : IUploadApi
    parameters:
    - id: optionsBuilder
      type: System.Action{{TApizrProperOptionsBuilder}}
    typeParameters:
    - id: TUploadApi
    return:
      type: '{TApizrUploadRegistryBuilder}'
    content.vb: Function AddFor(Of TUploadApi As IUploadApi)(optionsBuilder As Action(Of TApizrProperOptionsBuilder) = Nothing) As TApizrUploadRegistryBuilder
  overload: Apizr.Configuring.Registry.IApizrUploadRegistryBuilderBase`4.AddFor*
  nameWithType.vb: IApizrUploadRegistryBuilderBase(Of TApizrUploadRegistryBuilder, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder).AddFor(Of TUploadApi)(Action(Of TApizrProperOptionsBuilder))
  fullName.vb: Apizr.Configuring.Registry.IApizrUploadRegistryBuilderBase(Of TApizrUploadRegistryBuilder, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder).AddFor(Of TUploadApi)(System.Action(Of TApizrProperOptionsBuilder))
  name.vb: AddFor(Of TUploadApi)(Action(Of TApizrProperOptionsBuilder))
references:
- uid: Apizr.Configuring.Registry
  commentId: N:Apizr.Configuring.Registry
  name: Apizr.Configuring.Registry
  nameWithType: Apizr.Configuring.Registry
  fullName: Apizr.Configuring.Registry
- uid: Apizr.Configuring.Registry.IApizrUploadRegistryBuilderBase`4.AddFor*
  commentId: Overload:Apizr.Configuring.Registry.IApizrUploadRegistryBuilderBase`4.AddFor
  name: AddFor
  nameWithType: IApizrUploadRegistryBuilderBase<TApizrUploadRegistryBuilder, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder>.AddFor
  fullName: Apizr.Configuring.Registry.IApizrUploadRegistryBuilderBase<TApizrUploadRegistryBuilder, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder>.AddFor
  nameWithType.vb: IApizrUploadRegistryBuilderBase(Of TApizrUploadRegistryBuilder, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder).AddFor
  fullName.vb: Apizr.Configuring.Registry.IApizrUploadRegistryBuilderBase(Of TApizrUploadRegistryBuilder, TApizrRegistryBuilder, TApizrProperOptionsBuilder, TApizrCommonOptionsBuilder).AddFor
- uid: System.Action{{TApizrProperOptionsBuilder}}
  commentId: T:System.Action{`2}
  parent: System
  definition: System.Action`1
  name: Action<TApizrProperOptionsBuilder>
  nameWithType: Action<TApizrProperOptionsBuilder>
  fullName: System.Action<TApizrProperOptionsBuilder>
  nameWithType.vb: Action(Of TApizrProperOptionsBuilder)
  fullName.vb: System.Action(Of TApizrProperOptionsBuilder)
  name.vb: Action(Of TApizrProperOptionsBuilder)
  spec.csharp:
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: TApizrProperOptionsBuilder
    nameWithType: TApizrProperOptionsBuilder
    fullName: TApizrProperOptionsBuilder
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TApizrProperOptionsBuilder
    nameWithType: TApizrProperOptionsBuilder
    fullName: TApizrProperOptionsBuilder
  - name: )
    nameWithType: )
    fullName: )
- uid: '{TApizrUploadRegistryBuilder}'
  commentId: '!:TApizrUploadRegistryBuilder'
  definition: TApizrUploadRegistryBuilder
  name: TApizrUploadRegistryBuilder
  nameWithType: TApizrUploadRegistryBuilder
  fullName: TApizrUploadRegistryBuilder
- uid: System.Action`1
  commentId: T:System.Action`1
  isExternal: true
  name: Action<T>
  nameWithType: Action<T>
  fullName: System.Action<T>
  nameWithType.vb: Action(Of T)
  fullName.vb: System.Action(Of T)
  name.vb: Action(Of T)
  spec.csharp:
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: TApizrUploadRegistryBuilder
  name: TApizrUploadRegistryBuilder
  nameWithType: TApizrUploadRegistryBuilder
  fullName: TApizrUploadRegistryBuilder
