### YamlMime:ManagedReference
items:
- uid: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptions
  commentId: T:Apizr.Configuring.Shared.Context.IApizrResilienceContextOptions
  id: IApizrResilienceContextOptions
  parent: Apizr.Configuring.Shared.Context
  children:
  - Apizr.Configuring.Shared.Context.IApizrResilienceContextOptions.ContinueOnCapturedContext
  - Apizr.Configuring.Shared.Context.IApizrResilienceContextOptions.ReturnToPoolOnComplete
  langs:
  - csharp
  - vb
  name: IApizrResilienceContextOptions
  nameWithType: IApizrResilienceContextOptions
  fullName: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptions
  type: Interface
  source:
    remote:
      path: Apizr/Src/Apizr/Configuring/Shared/Context/IApizrResilienceContextOptions.cs
      branch: feat/resilience
      repo: https://github.com/Respawnsive/Apizr.git
    id: IApizrResilienceContextOptions
    path: ../../Src/Apizr/Configuring/Shared/Context/IApizrResilienceContextOptions.cs
    startLine: 2
  assemblies:
  - Apizr
  namespace: Apizr.Configuring.Shared.Context
  syntax:
    content: public interface IApizrResilienceContextOptions
    content.vb: Public Interface IApizrResilienceContextOptions
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptions.ContinueOnCapturedContext
  commentId: P:Apizr.Configuring.Shared.Context.IApizrResilienceContextOptions.ContinueOnCapturedContext
  id: ContinueOnCapturedContext
  parent: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptions
  langs:
  - csharp
  - vb
  name: ContinueOnCapturedContext
  nameWithType: IApizrResilienceContextOptions.ContinueOnCapturedContext
  fullName: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptions.ContinueOnCapturedContext
  type: Property
  source:
    remote:
      path: Apizr/Src/Apizr/Configuring/Shared/Context/IApizrResilienceContextOptions.cs
      branch: feat/resilience
      repo: https://github.com/Respawnsive/Apizr.git
    id: ContinueOnCapturedContext
    path: ../../Src/Apizr/Configuring/Shared/Context/IApizrResilienceContextOptions.cs
    startLine: 7
  assemblies:
  - Apizr
  namespace: Apizr.Configuring.Shared.Context
  summary: "\nGets the value indicating whether to continue on captured context, if any.\n"
  example: []
  syntax:
    content: bool? ContinueOnCapturedContext { get; }
    parameters: []
    return:
      type: System.Nullable{System.Boolean}
    content.vb: ReadOnly Property ContinueOnCapturedContext As Boolean?
  overload: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptions.ContinueOnCapturedContext*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptions.ReturnToPoolOnComplete
  commentId: P:Apizr.Configuring.Shared.Context.IApizrResilienceContextOptions.ReturnToPoolOnComplete
  id: ReturnToPoolOnComplete
  parent: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptions
  langs:
  - csharp
  - vb
  name: ReturnToPoolOnComplete
  nameWithType: IApizrResilienceContextOptions.ReturnToPoolOnComplete
  fullName: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptions.ReturnToPoolOnComplete
  type: Property
  source:
    remote:
      path: Apizr/Src/Apizr/Configuring/Shared/Context/IApizrResilienceContextOptions.cs
      branch: feat/resilience
      repo: https://github.com/Respawnsive/Apizr.git
    id: ReturnToPoolOnComplete
    path: ../../Src/Apizr/Configuring/Shared/Context/IApizrResilienceContextOptions.cs
    startLine: 12
  assemblies:
  - Apizr
  namespace: Apizr.Configuring.Shared.Context
  summary: "\nGets the value indicating whether to return the context to the pool, when request completes.\n"
  example: []
  syntax:
    content: bool? ReturnToPoolOnComplete { get; }
    parameters: []
    return:
      type: System.Nullable{System.Boolean}
    content.vb: ReadOnly Property ReturnToPoolOnComplete As Boolean?
  overload: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptions.ReturnToPoolOnComplete*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
references:
- uid: Apizr.Configuring.Shared.Context
  commentId: N:Apizr.Configuring.Shared.Context
  name: Apizr.Configuring.Shared.Context
  nameWithType: Apizr.Configuring.Shared.Context
  fullName: Apizr.Configuring.Shared.Context
- uid: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptions.ContinueOnCapturedContext*
  commentId: Overload:Apizr.Configuring.Shared.Context.IApizrResilienceContextOptions.ContinueOnCapturedContext
  name: ContinueOnCapturedContext
  nameWithType: IApizrResilienceContextOptions.ContinueOnCapturedContext
  fullName: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptions.ContinueOnCapturedContext
- uid: System.Nullable{System.Boolean}
  commentId: T:System.Nullable{System.Boolean}
  parent: System
  definition: System.Nullable`1
  name: Nullable<Boolean>
  nameWithType: Nullable<Boolean>
  fullName: System.Nullable<System.Boolean>
  nameWithType.vb: Nullable(Of Boolean)
  fullName.vb: System.Nullable(Of System.Boolean)
  name.vb: Nullable(Of Boolean)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Boolean
    name: Boolean
    nameWithType: Boolean
    fullName: System.Boolean
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.Boolean
    name: Boolean
    nameWithType: Boolean
    fullName: System.Boolean
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Nullable`1
  commentId: T:System.Nullable`1
  isExternal: true
  name: Nullable<T>
  nameWithType: Nullable<T>
  fullName: System.Nullable<T>
  nameWithType.vb: Nullable(Of T)
  fullName.vb: System.Nullable(Of T)
  name.vb: Nullable(Of T)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptions.ReturnToPoolOnComplete*
  commentId: Overload:Apizr.Configuring.Shared.Context.IApizrResilienceContextOptions.ReturnToPoolOnComplete
  name: ReturnToPoolOnComplete
  nameWithType: IApizrResilienceContextOptions.ReturnToPoolOnComplete
  fullName: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptions.ReturnToPoolOnComplete
