### YamlMime:ManagedReference
items:
- uid: Apizr.Extending.Configuring.Registry
  commentId: N:Apizr.Extending.Configuring.Registry
  id: Apizr.Extending.Configuring.Registry
  children:
  - Apizr.Extending.Configuring.Registry.ApizrExtendedRegistry
  - Apizr.Extending.Configuring.Registry.ApizrExtendedRegistryBuilder
  - Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistry
  - Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistryBase
  - Apizr.Extending.Configuring.Registry.IApizrExtendedRegistry
  - Apizr.Extending.Configuring.Registry.IApizrExtendedRegistryBuilder
  - Apizr.Extending.Configuring.Registry.IApizrExtendedRegistryBuilder`4
  langs:
  - csharp
  - vb
  name: Apizr.Extending.Configuring.Registry
  nameWithType: Apizr.Extending.Configuring.Registry
  fullName: Apizr.Extending.Configuring.Registry
  type: Namespace
  assemblies:
  - Apizr.Extensions.Microsoft.DependencyInjection
references:
- uid: Apizr.Extending.Configuring.Registry.ApizrExtendedRegistry
  commentId: T:Apizr.Extending.Configuring.Registry.ApizrExtendedRegistry
  parent: Apizr.Extending.Configuring.Registry
  name: ApizrExtendedRegistry
  nameWithType: ApizrExtendedRegistry
  fullName: Apizr.Extending.Configuring.Registry.ApizrExtendedRegistry
- uid: Apizr.Extending.Configuring.Registry.ApizrExtendedRegistryBuilder
  commentId: T:Apizr.Extending.Configuring.Registry.ApizrExtendedRegistryBuilder
  name: ApizrExtendedRegistryBuilder
  nameWithType: ApizrExtendedRegistryBuilder
  fullName: Apizr.Extending.Configuring.Registry.ApizrExtendedRegistryBuilder
- uid: Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistry
  commentId: T:Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistry
  parent: Apizr.Extending.Configuring.Registry
  name: IApizrExtendedConcurrentRegistry
  nameWithType: IApizrExtendedConcurrentRegistry
  fullName: Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistry
- uid: Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistryBase
  commentId: T:Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistryBase
  parent: Apizr.Extending.Configuring.Registry
  name: IApizrExtendedConcurrentRegistryBase
  nameWithType: IApizrExtendedConcurrentRegistryBase
  fullName: Apizr.Extending.Configuring.Registry.IApizrExtendedConcurrentRegistryBase
- uid: Apizr.Extending.Configuring.Registry.IApizrExtendedRegistry
  commentId: T:Apizr.Extending.Configuring.Registry.IApizrExtendedRegistry
  parent: Apizr.Extending.Configuring.Registry
  name: IApizrExtendedRegistry
  nameWithType: IApizrExtendedRegistry
  fullName: Apizr.Extending.Configuring.Registry.IApizrExtendedRegistry
- uid: Apizr.Extending.Configuring.Registry.IApizrExtendedRegistryBuilder`4
  commentId: T:Apizr.Extending.Configuring.Registry.IApizrExtendedRegistryBuilder`4
  name: IApizrExtendedRegistryBuilder<TApizrExtendedRegistry, TApizrExtendedRegistryBuilder, TApizrExtendedProperOptionsBuilder, TApizrExtendedCommonOptionsBuilder>
  nameWithType: IApizrExtendedRegistryBuilder<TApizrExtendedRegistry, TApizrExtendedRegistryBuilder, TApizrExtendedProperOptionsBuilder, TApizrExtendedCommonOptionsBuilder>
  fullName: Apizr.Extending.Configuring.Registry.IApizrExtendedRegistryBuilder<TApizrExtendedRegistry, TApizrExtendedRegistryBuilder, TApizrExtendedProperOptionsBuilder, TApizrExtendedCommonOptionsBuilder>
  nameWithType.vb: IApizrExtendedRegistryBuilder(Of TApizrExtendedRegistry, TApizrExtendedRegistryBuilder, TApizrExtendedProperOptionsBuilder, TApizrExtendedCommonOptionsBuilder)
  fullName.vb: Apizr.Extending.Configuring.Registry.IApizrExtendedRegistryBuilder(Of TApizrExtendedRegistry, TApizrExtendedRegistryBuilder, TApizrExtendedProperOptionsBuilder, TApizrExtendedCommonOptionsBuilder)
  name.vb: IApizrExtendedRegistryBuilder(Of TApizrExtendedRegistry, TApizrExtendedRegistryBuilder, TApizrExtendedProperOptionsBuilder, TApizrExtendedCommonOptionsBuilder)
  spec.csharp:
  - uid: Apizr.Extending.Configuring.Registry.IApizrExtendedRegistryBuilder`4
    name: IApizrExtendedRegistryBuilder
    nameWithType: IApizrExtendedRegistryBuilder
    fullName: Apizr.Extending.Configuring.Registry.IApizrExtendedRegistryBuilder
  - name: <
    nameWithType: <
    fullName: <
  - name: TApizrExtendedRegistry
    nameWithType: TApizrExtendedRegistry
    fullName: TApizrExtendedRegistry
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TApizrExtendedRegistryBuilder
    nameWithType: TApizrExtendedRegistryBuilder
    fullName: TApizrExtendedRegistryBuilder
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TApizrExtendedProperOptionsBuilder
    nameWithType: TApizrExtendedProperOptionsBuilder
    fullName: TApizrExtendedProperOptionsBuilder
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TApizrExtendedCommonOptionsBuilder
    nameWithType: TApizrExtendedCommonOptionsBuilder
    fullName: TApizrExtendedCommonOptionsBuilder
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Apizr.Extending.Configuring.Registry.IApizrExtendedRegistryBuilder`4
    name: IApizrExtendedRegistryBuilder
    nameWithType: IApizrExtendedRegistryBuilder
    fullName: Apizr.Extending.Configuring.Registry.IApizrExtendedRegistryBuilder
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TApizrExtendedRegistry
    nameWithType: TApizrExtendedRegistry
    fullName: TApizrExtendedRegistry
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TApizrExtendedRegistryBuilder
    nameWithType: TApizrExtendedRegistryBuilder
    fullName: TApizrExtendedRegistryBuilder
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TApizrExtendedProperOptionsBuilder
    nameWithType: TApizrExtendedProperOptionsBuilder
    fullName: TApizrExtendedProperOptionsBuilder
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TApizrExtendedCommonOptionsBuilder
    nameWithType: TApizrExtendedCommonOptionsBuilder
    fullName: TApizrExtendedCommonOptionsBuilder
  - name: )
    nameWithType: )
    fullName: )
- uid: Apizr.Extending.Configuring.Registry.IApizrExtendedRegistryBuilder
  commentId: T:Apizr.Extending.Configuring.Registry.IApizrExtendedRegistryBuilder
  parent: Apizr.Extending.Configuring.Registry
  name: IApizrExtendedRegistryBuilder
  nameWithType: IApizrExtendedRegistryBuilder
  fullName: Apizr.Extending.Configuring.Registry.IApizrExtendedRegistryBuilder
- uid: Apizr.Extending.Configuring.Registry
  commentId: N:Apizr.Extending.Configuring.Registry
  name: Apizr.Extending.Configuring.Registry
  nameWithType: Apizr.Extending.Configuring.Registry
  fullName: Apizr.Extending.Configuring.Registry
