### YamlMime:ManagedReference
items:
- uid: Apizr.Configuring.Proper.IApizrProperOptions
  commentId: T:Apizr.Configuring.Proper.IApizrProperOptions
  id: IApizrProperOptions
  parent: Apizr.Configuring.Proper
  children:
  - Apizr.Configuring.Proper.IApizrProperOptions.BaseAddressFactory
  - Apizr.Configuring.Proper.IApizrProperOptions.LoggerFactory
  langs:
  - csharp
  - vb
  name: IApizrProperOptions
  nameWithType: IApizrProperOptions
  fullName: Apizr.Configuring.Proper.IApizrProperOptions
  type: Interface
  source:
    id: IApizrProperOptions
    path: C:\Dev\Community\Apizr\Apizr\Apizr\Configuring\Proper\IApizrProperOptions.cs
    startLine: 6
  assemblies:
  - Apizr
  namespace: Apizr.Configuring.Proper
  syntax:
    content: 'public interface IApizrProperOptions : IApizrProperOptionsBase, IApizrSharedOptions, IApizrSharedOptionsBase'
    content.vb: >-
      Public Interface IApizrProperOptions

          Inherits IApizrProperOptionsBase, IApizrSharedOptions
  inheritedMembers:
  - Apizr.Configuring.Proper.IApizrProperOptionsBase.WebApiType
  - Apizr.Configuring.Proper.IApizrProperOptionsBase.BaseAddress
  - Apizr.Configuring.Proper.IApizrProperOptionsBase.PolicyRegistryKeys
  - Apizr.Configuring.Proper.IApizrProperOptionsBase.Logger
  - Apizr.Configuring.Shared.IApizrSharedOptions.HttpTracerModeFactory
  - Apizr.Configuring.Shared.IApizrSharedOptions.TrafficVerbosityFactory
  - Apizr.Configuring.Shared.IApizrSharedOptions.LogLevelsFactory
  - Apizr.Configuring.Shared.IApizrSharedOptions.HttpClientHandlerFactory
  - Apizr.Configuring.Shared.IApizrSharedOptions.DelegatingHandlersFactories
  - Apizr.Configuring.Shared.IApizrSharedOptionsBase.HttpTracerMode
  - Apizr.Configuring.Shared.IApizrSharedOptionsBase.TrafficVerbosity
  - Apizr.Configuring.Shared.IApizrSharedOptionsBase.LogLevels
  extensionMethods:
  - System.Object.Apizr.Extending.ObjectExtensions.ToString(System.String,System.String)
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Apizr.Configuring.Proper.IApizrProperOptions.BaseAddressFactory
  commentId: P:Apizr.Configuring.Proper.IApizrProperOptions.BaseAddressFactory
  id: BaseAddressFactory
  parent: Apizr.Configuring.Proper.IApizrProperOptions
  langs:
  - csharp
  - vb
  name: BaseAddressFactory
  nameWithType: IApizrProperOptions.BaseAddressFactory
  fullName: Apizr.Configuring.Proper.IApizrProperOptions.BaseAddressFactory
  type: Property
  source:
    id: BaseAddressFactory
    path: C:\Dev\Community\Apizr\Apizr\Apizr\Configuring\Proper\IApizrProperOptions.cs
    startLine: 11
  assemblies:
  - Apizr
  namespace: Apizr.Configuring.Proper
  summary: "\nBase address factory\n"
  example: []
  syntax:
    content: Func<Uri> BaseAddressFactory { get; }
    parameters: []
    return:
      type: System.Func{System.Uri}
    content.vb: ReadOnly Property BaseAddressFactory As Func(Of Uri)
  overload: Apizr.Configuring.Proper.IApizrProperOptions.BaseAddressFactory*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: Apizr.Configuring.Proper.IApizrProperOptions.LoggerFactory
  commentId: P:Apizr.Configuring.Proper.IApizrProperOptions.LoggerFactory
  id: LoggerFactory
  parent: Apizr.Configuring.Proper.IApizrProperOptions
  langs:
  - csharp
  - vb
  name: LoggerFactory
  nameWithType: IApizrProperOptions.LoggerFactory
  fullName: Apizr.Configuring.Proper.IApizrProperOptions.LoggerFactory
  type: Property
  source:
    id: LoggerFactory
    path: C:\Dev\Community\Apizr\Apizr\Apizr\Configuring\Proper\IApizrProperOptions.cs
    startLine: 16
  assemblies:
  - Apizr
  namespace: Apizr.Configuring.Proper
  summary: "\nThe Logger factory\n"
  example: []
  syntax:
    content: Func<ILoggerFactory, string, ILogger> LoggerFactory { get; }
    parameters: []
    return:
      type: System.Func{Microsoft.Extensions.Logging.ILoggerFactory,System.String,Microsoft.Extensions.Logging.ILogger}
    content.vb: ReadOnly Property LoggerFactory As Func(Of ILoggerFactory, String, ILogger)
  overload: Apizr.Configuring.Proper.IApizrProperOptions.LoggerFactory*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
references:
- uid: Apizr.Configuring.Proper
  commentId: N:Apizr.Configuring.Proper
  name: Apizr.Configuring.Proper
  nameWithType: Apizr.Configuring.Proper
  fullName: Apizr.Configuring.Proper
- uid: Apizr.Configuring.Proper.IApizrProperOptionsBase.WebApiType
  commentId: P:Apizr.Configuring.Proper.IApizrProperOptionsBase.WebApiType
  parent: Apizr.Configuring.Proper.IApizrProperOptionsBase
  name: WebApiType
  nameWithType: IApizrProperOptionsBase.WebApiType
  fullName: Apizr.Configuring.Proper.IApizrProperOptionsBase.WebApiType
- uid: Apizr.Configuring.Proper.IApizrProperOptionsBase.BaseAddress
  commentId: P:Apizr.Configuring.Proper.IApizrProperOptionsBase.BaseAddress
  parent: Apizr.Configuring.Proper.IApizrProperOptionsBase
  name: BaseAddress
  nameWithType: IApizrProperOptionsBase.BaseAddress
  fullName: Apizr.Configuring.Proper.IApizrProperOptionsBase.BaseAddress
- uid: Apizr.Configuring.Proper.IApizrProperOptionsBase.PolicyRegistryKeys
  commentId: P:Apizr.Configuring.Proper.IApizrProperOptionsBase.PolicyRegistryKeys
  parent: Apizr.Configuring.Proper.IApizrProperOptionsBase
  name: PolicyRegistryKeys
  nameWithType: IApizrProperOptionsBase.PolicyRegistryKeys
  fullName: Apizr.Configuring.Proper.IApizrProperOptionsBase.PolicyRegistryKeys
- uid: Apizr.Configuring.Proper.IApizrProperOptionsBase.Logger
  commentId: P:Apizr.Configuring.Proper.IApizrProperOptionsBase.Logger
  parent: Apizr.Configuring.Proper.IApizrProperOptionsBase
  name: Logger
  nameWithType: IApizrProperOptionsBase.Logger
  fullName: Apizr.Configuring.Proper.IApizrProperOptionsBase.Logger
- uid: Apizr.Configuring.Shared.IApizrSharedOptions.HttpTracerModeFactory
  commentId: P:Apizr.Configuring.Shared.IApizrSharedOptions.HttpTracerModeFactory
  parent: Apizr.Configuring.Shared.IApizrSharedOptions
  name: HttpTracerModeFactory
  nameWithType: IApizrSharedOptions.HttpTracerModeFactory
  fullName: Apizr.Configuring.Shared.IApizrSharedOptions.HttpTracerModeFactory
- uid: Apizr.Configuring.Shared.IApizrSharedOptions.TrafficVerbosityFactory
  commentId: P:Apizr.Configuring.Shared.IApizrSharedOptions.TrafficVerbosityFactory
  parent: Apizr.Configuring.Shared.IApizrSharedOptions
  name: TrafficVerbosityFactory
  nameWithType: IApizrSharedOptions.TrafficVerbosityFactory
  fullName: Apizr.Configuring.Shared.IApizrSharedOptions.TrafficVerbosityFactory
- uid: Apizr.Configuring.Shared.IApizrSharedOptions.LogLevelsFactory
  commentId: P:Apizr.Configuring.Shared.IApizrSharedOptions.LogLevelsFactory
  parent: Apizr.Configuring.Shared.IApizrSharedOptions
  name: LogLevelsFactory
  nameWithType: IApizrSharedOptions.LogLevelsFactory
  fullName: Apizr.Configuring.Shared.IApizrSharedOptions.LogLevelsFactory
- uid: Apizr.Configuring.Shared.IApizrSharedOptions.HttpClientHandlerFactory
  commentId: P:Apizr.Configuring.Shared.IApizrSharedOptions.HttpClientHandlerFactory
  parent: Apizr.Configuring.Shared.IApizrSharedOptions
  name: HttpClientHandlerFactory
  nameWithType: IApizrSharedOptions.HttpClientHandlerFactory
  fullName: Apizr.Configuring.Shared.IApizrSharedOptions.HttpClientHandlerFactory
- uid: Apizr.Configuring.Shared.IApizrSharedOptions.DelegatingHandlersFactories
  commentId: P:Apizr.Configuring.Shared.IApizrSharedOptions.DelegatingHandlersFactories
  parent: Apizr.Configuring.Shared.IApizrSharedOptions
  name: DelegatingHandlersFactories
  nameWithType: IApizrSharedOptions.DelegatingHandlersFactories
  fullName: Apizr.Configuring.Shared.IApizrSharedOptions.DelegatingHandlersFactories
- uid: Apizr.Configuring.Shared.IApizrSharedOptionsBase.HttpTracerMode
  commentId: P:Apizr.Configuring.Shared.IApizrSharedOptionsBase.HttpTracerMode
  parent: Apizr.Configuring.Shared.IApizrSharedOptionsBase
  name: HttpTracerMode
  nameWithType: IApizrSharedOptionsBase.HttpTracerMode
  fullName: Apizr.Configuring.Shared.IApizrSharedOptionsBase.HttpTracerMode
- uid: Apizr.Configuring.Shared.IApizrSharedOptionsBase.TrafficVerbosity
  commentId: P:Apizr.Configuring.Shared.IApizrSharedOptionsBase.TrafficVerbosity
  parent: Apizr.Configuring.Shared.IApizrSharedOptionsBase
  name: TrafficVerbosity
  nameWithType: IApizrSharedOptionsBase.TrafficVerbosity
  fullName: Apizr.Configuring.Shared.IApizrSharedOptionsBase.TrafficVerbosity
- uid: Apizr.Configuring.Shared.IApizrSharedOptionsBase.LogLevels
  commentId: P:Apizr.Configuring.Shared.IApizrSharedOptionsBase.LogLevels
  parent: Apizr.Configuring.Shared.IApizrSharedOptionsBase
  name: LogLevels
  nameWithType: IApizrSharedOptionsBase.LogLevels
  fullName: Apizr.Configuring.Shared.IApizrSharedOptionsBase.LogLevels
- uid: System.Object.Apizr.Extending.ObjectExtensions.ToString(System.String,System.String)
  commentId: M:Apizr.Extending.ObjectExtensions.ToString(System.Object,System.String,System.String)
  parent: Apizr.Extending.ObjectExtensions
  definition: Apizr.Extending.ObjectExtensions.ToString(System.Object,System.String,System.String)
  name: ToString(String, String)
  nameWithType: ObjectExtensions.ToString(String, String)
  fullName: Apizr.Extending.ObjectExtensions.ToString(System.String, System.String)
  spec.csharp:
  - uid: Apizr.Extending.ObjectExtensions.ToString(System.String,System.String)
    name: ToString
    nameWithType: ObjectExtensions.ToString
    fullName: Apizr.Extending.ObjectExtensions.ToString
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Apizr.Extending.ObjectExtensions.ToString(System.String,System.String)
    name: ToString
    nameWithType: ObjectExtensions.ToString
    fullName: Apizr.Extending.ObjectExtensions.ToString
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Apizr.Configuring.Proper.IApizrProperOptionsBase
  commentId: T:Apizr.Configuring.Proper.IApizrProperOptionsBase
  parent: Apizr.Configuring.Proper
  name: IApizrProperOptionsBase
  nameWithType: IApizrProperOptionsBase
  fullName: Apizr.Configuring.Proper.IApizrProperOptionsBase
- uid: Apizr.Configuring.Shared.IApizrSharedOptions
  commentId: T:Apizr.Configuring.Shared.IApizrSharedOptions
  parent: Apizr.Configuring.Shared
  name: IApizrSharedOptions
  nameWithType: IApizrSharedOptions
  fullName: Apizr.Configuring.Shared.IApizrSharedOptions
- uid: Apizr.Configuring.Shared.IApizrSharedOptionsBase
  commentId: T:Apizr.Configuring.Shared.IApizrSharedOptionsBase
  parent: Apizr.Configuring.Shared
  name: IApizrSharedOptionsBase
  nameWithType: IApizrSharedOptionsBase
  fullName: Apizr.Configuring.Shared.IApizrSharedOptionsBase
- uid: Apizr.Extending.ObjectExtensions.ToString(System.Object,System.String,System.String)
  commentId: M:Apizr.Extending.ObjectExtensions.ToString(System.Object,System.String,System.String)
  isExternal: true
  name: ToString(Object, String, String)
  nameWithType: ObjectExtensions.ToString(Object, String, String)
  fullName: Apizr.Extending.ObjectExtensions.ToString(System.Object, System.String, System.String)
  spec.csharp:
  - uid: Apizr.Extending.ObjectExtensions.ToString(System.Object,System.String,System.String)
    name: ToString
    nameWithType: ObjectExtensions.ToString
    fullName: Apizr.Extending.ObjectExtensions.ToString
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Apizr.Extending.ObjectExtensions.ToString(System.Object,System.String,System.String)
    name: ToString
    nameWithType: ObjectExtensions.ToString
    fullName: Apizr.Extending.ObjectExtensions.ToString
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Apizr.Extending.ObjectExtensions
  commentId: T:Apizr.Extending.ObjectExtensions
  parent: Apizr.Extending
  name: ObjectExtensions
  nameWithType: ObjectExtensions
  fullName: Apizr.Extending.ObjectExtensions
- uid: Apizr.Configuring.Shared
  commentId: N:Apizr.Configuring.Shared
  name: Apizr.Configuring.Shared
  nameWithType: Apizr.Configuring.Shared
  fullName: Apizr.Configuring.Shared
- uid: Apizr.Extending
  commentId: N:Apizr.Extending
  name: Apizr.Extending
  nameWithType: Apizr.Extending
  fullName: Apizr.Extending
- uid: Apizr.Configuring.Proper.IApizrProperOptions.BaseAddressFactory*
  commentId: Overload:Apizr.Configuring.Proper.IApizrProperOptions.BaseAddressFactory
  name: BaseAddressFactory
  nameWithType: IApizrProperOptions.BaseAddressFactory
  fullName: Apizr.Configuring.Proper.IApizrProperOptions.BaseAddressFactory
- uid: System.Func{System.Uri}
  commentId: T:System.Func{System.Uri}
  parent: System
  definition: System.Func`1
  name: Func<Uri>
  nameWithType: Func<Uri>
  fullName: System.Func<System.Uri>
  nameWithType.vb: Func(Of Uri)
  fullName.vb: System.Func(Of System.Uri)
  name.vb: Func(Of Uri)
  spec.csharp:
  - uid: System.Func`1
    name: Func
    nameWithType: Func
    fullName: System.Func
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Uri
    name: Uri
    nameWithType: Uri
    fullName: System.Uri
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Func`1
    name: Func
    nameWithType: Func
    fullName: System.Func
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.Uri
    name: Uri
    nameWithType: Uri
    fullName: System.Uri
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Func`1
  commentId: T:System.Func`1
  isExternal: true
  name: Func<TResult>
  nameWithType: Func<TResult>
  fullName: System.Func<TResult>
  nameWithType.vb: Func(Of TResult)
  fullName.vb: System.Func(Of TResult)
  name.vb: Func(Of TResult)
  spec.csharp:
  - uid: System.Func`1
    name: Func
    nameWithType: Func
    fullName: System.Func
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: TResult
    nameWithType: TResult
    fullName: TResult
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Func`1
    name: Func
    nameWithType: Func
    fullName: System.Func
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TResult
    nameWithType: TResult
    fullName: TResult
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Apizr.Configuring.Proper.IApizrProperOptions.LoggerFactory*
  commentId: Overload:Apizr.Configuring.Proper.IApizrProperOptions.LoggerFactory
  name: LoggerFactory
  nameWithType: IApizrProperOptions.LoggerFactory
  fullName: Apizr.Configuring.Proper.IApizrProperOptions.LoggerFactory
- uid: System.Func{Microsoft.Extensions.Logging.ILoggerFactory,System.String,Microsoft.Extensions.Logging.ILogger}
  commentId: T:System.Func{Microsoft.Extensions.Logging.ILoggerFactory,System.String,Microsoft.Extensions.Logging.ILogger}
  parent: System
  definition: System.Func`3
  name: Func<ILoggerFactory, String, ILogger>
  nameWithType: Func<ILoggerFactory, String, ILogger>
  fullName: System.Func<Microsoft.Extensions.Logging.ILoggerFactory, System.String, Microsoft.Extensions.Logging.ILogger>
  nameWithType.vb: Func(Of ILoggerFactory, String, ILogger)
  fullName.vb: System.Func(Of Microsoft.Extensions.Logging.ILoggerFactory, System.String, Microsoft.Extensions.Logging.ILogger)
  name.vb: Func(Of ILoggerFactory, String, ILogger)
  spec.csharp:
  - uid: System.Func`3
    name: Func
    nameWithType: Func
    fullName: System.Func
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: Microsoft.Extensions.Logging.ILoggerFactory
    name: ILoggerFactory
    nameWithType: ILoggerFactory
    fullName: Microsoft.Extensions.Logging.ILoggerFactory
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: Microsoft.Extensions.Logging.ILogger
    name: ILogger
    nameWithType: ILogger
    fullName: Microsoft.Extensions.Logging.ILogger
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Func`3
    name: Func
    nameWithType: Func
    fullName: System.Func
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: Microsoft.Extensions.Logging.ILoggerFactory
    name: ILoggerFactory
    nameWithType: ILoggerFactory
    fullName: Microsoft.Extensions.Logging.ILoggerFactory
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: Microsoft.Extensions.Logging.ILogger
    name: ILogger
    nameWithType: ILogger
    fullName: Microsoft.Extensions.Logging.ILogger
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Func`3
  commentId: T:System.Func`3
  isExternal: true
  name: Func<T1, T2, TResult>
  nameWithType: Func<T1, T2, TResult>
  fullName: System.Func<T1, T2, TResult>
  nameWithType.vb: Func(Of T1, T2, TResult)
  fullName.vb: System.Func(Of T1, T2, TResult)
  name.vb: Func(Of T1, T2, TResult)
  spec.csharp:
  - uid: System.Func`3
    name: Func
    nameWithType: Func
    fullName: System.Func
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T1
    nameWithType: T1
    fullName: T1
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: T2
    nameWithType: T2
    fullName: T2
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TResult
    nameWithType: TResult
    fullName: TResult
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Func`3
    name: Func
    nameWithType: Func
    fullName: System.Func
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T1
    nameWithType: T1
    fullName: T1
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: T2
    nameWithType: T2
    fullName: T2
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TResult
    nameWithType: TResult
    fullName: TResult
  - name: )
    nameWithType: )
    fullName: )
