### YamlMime:ManagedReference
items:
- uid: Apizr.Configuring.Registry
  commentId: N:Apizr.Configuring.Registry
  id: Apizr.Configuring.Registry
  children:
  - Apizr.Configuring.Registry.ApizrRegistry
  - Apizr.Configuring.Registry.ApizrRegistryBase
  - Apizr.Configuring.Registry.ApizrRegistryBuilder
  - Apizr.Configuring.Registry.IApizrEnumerableRegistry
  - Apizr.Configuring.Registry.IApizrRegistry
  - Apizr.Configuring.Registry.IApizrRegistryBuilder
  - Apizr.Configuring.Registry.IApizrRegistryBuilder`3
  - Apizr.Configuring.Registry.IApizrRegistryBuilderBase
  - Apizr.Configuring.Registry.IApizrRegistryBuilderBase`3
  langs:
  - csharp
  - vb
  name: Apizr.Configuring.Registry
  nameWithType: Apizr.Configuring.Registry
  fullName: Apizr.Configuring.Registry
  type: Namespace
  assemblies:
  - Apizr
references:
- uid: Apizr.Configuring.Registry.ApizrRegistry
  commentId: T:Apizr.Configuring.Registry.ApizrRegistry
  parent: Apizr.Configuring.Registry
  name: ApizrRegistry
  nameWithType: ApizrRegistry
  fullName: Apizr.Configuring.Registry.ApizrRegistry
- uid: Apizr.Configuring.Registry.ApizrRegistryBase
  commentId: T:Apizr.Configuring.Registry.ApizrRegistryBase
  parent: Apizr.Configuring.Registry
  name: ApizrRegistryBase
  nameWithType: ApizrRegistryBase
  fullName: Apizr.Configuring.Registry.ApizrRegistryBase
- uid: Apizr.Configuring.Registry.ApizrRegistryBuilder
  commentId: T:Apizr.Configuring.Registry.ApizrRegistryBuilder
  name: ApizrRegistryBuilder
  nameWithType: ApizrRegistryBuilder
  fullName: Apizr.Configuring.Registry.ApizrRegistryBuilder
- uid: Apizr.Configuring.Registry.IApizrEnumerableRegistry
  commentId: T:Apizr.Configuring.Registry.IApizrEnumerableRegistry
  parent: Apizr.Configuring.Registry
  name: IApizrEnumerableRegistry
  nameWithType: IApizrEnumerableRegistry
  fullName: Apizr.Configuring.Registry.IApizrEnumerableRegistry
- uid: Apizr.Configuring.Registry.IApizrRegistry
  commentId: T:Apizr.Configuring.Registry.IApizrRegistry
  parent: Apizr.Configuring.Registry
  name: IApizrRegistry
  nameWithType: IApizrRegistry
  fullName: Apizr.Configuring.Registry.IApizrRegistry
- uid: Apizr.Configuring.Registry.IApizrRegistryBuilder`3
  commentId: T:Apizr.Configuring.Registry.IApizrRegistryBuilder`3
  name: IApizrRegistryBuilder<TApizrRegistry, TApizrRegistryBuilder, TApizrProperOptionsBuilder>
  nameWithType: IApizrRegistryBuilder<TApizrRegistry, TApizrRegistryBuilder, TApizrProperOptionsBuilder>
  fullName: Apizr.Configuring.Registry.IApizrRegistryBuilder<TApizrRegistry, TApizrRegistryBuilder, TApizrProperOptionsBuilder>
  nameWithType.vb: IApizrRegistryBuilder(Of TApizrRegistry, TApizrRegistryBuilder, TApizrProperOptionsBuilder)
  fullName.vb: Apizr.Configuring.Registry.IApizrRegistryBuilder(Of TApizrRegistry, TApizrRegistryBuilder, TApizrProperOptionsBuilder)
  name.vb: IApizrRegistryBuilder(Of TApizrRegistry, TApizrRegistryBuilder, TApizrProperOptionsBuilder)
  spec.csharp:
  - uid: Apizr.Configuring.Registry.IApizrRegistryBuilder`3
    name: IApizrRegistryBuilder
    nameWithType: IApizrRegistryBuilder
    fullName: Apizr.Configuring.Registry.IApizrRegistryBuilder
  - name: <
    nameWithType: <
    fullName: <
  - name: TApizrRegistry
    nameWithType: TApizrRegistry
    fullName: TApizrRegistry
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TApizrRegistryBuilder
    nameWithType: TApizrRegistryBuilder
    fullName: TApizrRegistryBuilder
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TApizrProperOptionsBuilder
    nameWithType: TApizrProperOptionsBuilder
    fullName: TApizrProperOptionsBuilder
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Apizr.Configuring.Registry.IApizrRegistryBuilder`3
    name: IApizrRegistryBuilder
    nameWithType: IApizrRegistryBuilder
    fullName: Apizr.Configuring.Registry.IApizrRegistryBuilder
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TApizrRegistry
    nameWithType: TApizrRegistry
    fullName: TApizrRegistry
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TApizrRegistryBuilder
    nameWithType: TApizrRegistryBuilder
    fullName: TApizrRegistryBuilder
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TApizrProperOptionsBuilder
    nameWithType: TApizrProperOptionsBuilder
    fullName: TApizrProperOptionsBuilder
  - name: )
    nameWithType: )
    fullName: )
- uid: Apizr.Configuring.Registry.IApizrRegistryBuilder
  commentId: T:Apizr.Configuring.Registry.IApizrRegistryBuilder
  parent: Apizr.Configuring.Registry
  name: IApizrRegistryBuilder
  nameWithType: IApizrRegistryBuilder
  fullName: Apizr.Configuring.Registry.IApizrRegistryBuilder
- uid: Apizr.Configuring.Registry.IApizrRegistryBuilderBase
  commentId: T:Apizr.Configuring.Registry.IApizrRegistryBuilderBase
  parent: Apizr.Configuring.Registry
  name: IApizrRegistryBuilderBase
  nameWithType: IApizrRegistryBuilderBase
  fullName: Apizr.Configuring.Registry.IApizrRegistryBuilderBase
- uid: Apizr.Configuring.Registry.IApizrRegistryBuilderBase`3
  commentId: T:Apizr.Configuring.Registry.IApizrRegistryBuilderBase`3
  name: IApizrRegistryBuilderBase<TApizrRegistry, TApizrRegistryBuilder, TApizrProperOptionsBuilder>
  nameWithType: IApizrRegistryBuilderBase<TApizrRegistry, TApizrRegistryBuilder, TApizrProperOptionsBuilder>
  fullName: Apizr.Configuring.Registry.IApizrRegistryBuilderBase<TApizrRegistry, TApizrRegistryBuilder, TApizrProperOptionsBuilder>
  nameWithType.vb: IApizrRegistryBuilderBase(Of TApizrRegistry, TApizrRegistryBuilder, TApizrProperOptionsBuilder)
  fullName.vb: Apizr.Configuring.Registry.IApizrRegistryBuilderBase(Of TApizrRegistry, TApizrRegistryBuilder, TApizrProperOptionsBuilder)
  name.vb: IApizrRegistryBuilderBase(Of TApizrRegistry, TApizrRegistryBuilder, TApizrProperOptionsBuilder)
  spec.csharp:
  - uid: Apizr.Configuring.Registry.IApizrRegistryBuilderBase`3
    name: IApizrRegistryBuilderBase
    nameWithType: IApizrRegistryBuilderBase
    fullName: Apizr.Configuring.Registry.IApizrRegistryBuilderBase
  - name: <
    nameWithType: <
    fullName: <
  - name: TApizrRegistry
    nameWithType: TApizrRegistry
    fullName: TApizrRegistry
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TApizrRegistryBuilder
    nameWithType: TApizrRegistryBuilder
    fullName: TApizrRegistryBuilder
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TApizrProperOptionsBuilder
    nameWithType: TApizrProperOptionsBuilder
    fullName: TApizrProperOptionsBuilder
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Apizr.Configuring.Registry.IApizrRegistryBuilderBase`3
    name: IApizrRegistryBuilderBase
    nameWithType: IApizrRegistryBuilderBase
    fullName: Apizr.Configuring.Registry.IApizrRegistryBuilderBase
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TApizrRegistry
    nameWithType: TApizrRegistry
    fullName: TApizrRegistry
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TApizrRegistryBuilder
    nameWithType: TApizrRegistryBuilder
    fullName: TApizrRegistryBuilder
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TApizrProperOptionsBuilder
    nameWithType: TApizrProperOptionsBuilder
    fullName: TApizrProperOptionsBuilder
  - name: )
    nameWithType: )
    fullName: )
- uid: Apizr.Configuring.Registry
  commentId: N:Apizr.Configuring.Registry
  name: Apizr.Configuring.Registry
  nameWithType: Apizr.Configuring.Registry
  fullName: Apizr.Configuring.Registry
