### YamlMime:ManagedReference
items:
- uid: Apizr.Configuring.Proper.IApizrExtendedProperOptionsBuilderBase
  commentId: T:Apizr.Configuring.Proper.IApizrExtendedProperOptionsBuilderBase
  id: IApizrExtendedProperOptionsBuilderBase
  parent: Apizr.Configuring.Proper
  children: []
  langs:
  - csharp
  - vb
  name: IApizrExtendedProperOptionsBuilderBase
  nameWithType: IApizrExtendedProperOptionsBuilderBase
  fullName: Apizr.Configuring.Proper.IApizrExtendedProperOptionsBuilderBase
  type: Interface
  source:
    id: IApizrExtendedProperOptionsBuilderBase
    path: C:\Dev\Community\Apizr\Apizr\Apizr\Configuring\Proper\IApizrExtendedProperOptionsBuilderBase.cs
    startLine: 5
  assemblies:
  - Apizr
  namespace: Apizr.Configuring.Proper
  summary: "\nBuilder options available at proper level for extended registration\n"
  example: []
  syntax:
    content: 'public interface IApizrExtendedProperOptionsBuilderBase : IApizrGlobalProperOptionsBuilderBase, IApizrGlobalSharedRegistrationOptionsBuilderBase, IApizrGlobalSharedOptionsBuilderBase'
    content.vb: >-
      Public Interface IApizrExtendedProperOptionsBuilderBase
          Inherits IApizrGlobalProperOptionsBuilderBase
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
references:
- uid: Apizr.Configuring.Proper
  commentId: N:Apizr.Configuring.Proper
  name: Apizr.Configuring.Proper
  nameWithType: Apizr.Configuring.Proper
  fullName: Apizr.Configuring.Proper
