### YamlMime:ManagedReference
items:
- uid: Apizr.Extending.Configuring.Proper
  commentId: N:Apizr.Extending.Configuring.Proper
  id: Apizr.Extending.Configuring.Proper
  children:
  - Apizr.Extending.Configuring.Proper.ApizrExtendedProperOptions
  - Apizr.Extending.Configuring.Proper.ApizrExtendedProperOptionsBuilder
  - Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptions
  - Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBase
  - Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBuilder
  - Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBuilder`2
  langs:
  - csharp
  - vb
  name: Apizr.Extending.Configuring.Proper
  nameWithType: Apizr.Extending.Configuring.Proper
  fullName: Apizr.Extending.Configuring.Proper
  type: Namespace
  assemblies:
  - Apizr.Extensions.Microsoft.DependencyInjection
references:
- uid: Apizr.Extending.Configuring.Proper.ApizrExtendedProperOptions
  commentId: T:Apizr.Extending.Configuring.Proper.ApizrExtendedProperOptions
  parent: Apizr.Extending.Configuring.Proper
  href: Apizr.Extending.Configuring.Proper.ApizrExtendedProperOptions.html
  name: ApizrExtendedProperOptions
  nameWithType: ApizrExtendedProperOptions
  fullName: Apizr.Extending.Configuring.Proper.ApizrExtendedProperOptions
- uid: Apizr.Extending.Configuring.Proper.ApizrExtendedProperOptionsBuilder
  commentId: T:Apizr.Extending.Configuring.Proper.ApizrExtendedProperOptionsBuilder
  href: Apizr.Extending.Configuring.Proper.ApizrExtendedProperOptionsBuilder.html
  name: ApizrExtendedProperOptionsBuilder
  nameWithType: ApizrExtendedProperOptionsBuilder
  fullName: Apizr.Extending.Configuring.Proper.ApizrExtendedProperOptionsBuilder
- uid: Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptions
  commentId: T:Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptions
  parent: Apizr.Extending.Configuring.Proper
  href: Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptions.html
  name: IApizrExtendedProperOptions
  nameWithType: IApizrExtendedProperOptions
  fullName: Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptions
- uid: Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBase
  commentId: T:Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBase
  parent: Apizr.Extending.Configuring.Proper
  href: Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBase.html
  name: IApizrExtendedProperOptionsBase
  nameWithType: IApizrExtendedProperOptionsBase
  fullName: Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBase
- uid: Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBuilder`2
  commentId: T:Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBuilder`2
  href: Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBuilder-2.html
  name: IApizrExtendedProperOptionsBuilder<TApizrExtendedProperOptions, TApizrExtendedProperOptionsBuilder>
  nameWithType: IApizrExtendedProperOptionsBuilder<TApizrExtendedProperOptions, TApizrExtendedProperOptionsBuilder>
  fullName: Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBuilder<TApizrExtendedProperOptions, TApizrExtendedProperOptionsBuilder>
  nameWithType.vb: IApizrExtendedProperOptionsBuilder(Of TApizrExtendedProperOptions, TApizrExtendedProperOptionsBuilder)
  fullName.vb: Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBuilder(Of TApizrExtendedProperOptions, TApizrExtendedProperOptionsBuilder)
  name.vb: IApizrExtendedProperOptionsBuilder(Of TApizrExtendedProperOptions, TApizrExtendedProperOptionsBuilder)
  spec.csharp:
  - uid: Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBuilder`2
    name: IApizrExtendedProperOptionsBuilder
    href: Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBuilder-2.html
  - name: <
  - name: TApizrExtendedProperOptions
  - name: ','
  - name: " "
  - name: TApizrExtendedProperOptionsBuilder
  - name: '>'
  spec.vb:
  - uid: Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBuilder`2
    name: IApizrExtendedProperOptionsBuilder
    href: Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBuilder-2.html
  - name: (
  - name: Of
  - name: " "
  - name: TApizrExtendedProperOptions
  - name: ','
  - name: " "
  - name: TApizrExtendedProperOptionsBuilder
  - name: )
- uid: Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBuilder
  commentId: T:Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBuilder
  parent: Apizr.Extending.Configuring.Proper
  href: Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBuilder.html
  name: IApizrExtendedProperOptionsBuilder
  nameWithType: IApizrExtendedProperOptionsBuilder
  fullName: Apizr.Extending.Configuring.Proper.IApizrExtendedProperOptionsBuilder
- uid: Apizr.Extending.Configuring.Proper
  commentId: N:Apizr.Extending.Configuring.Proper
  href: Apizr.html
  name: Apizr.Extending.Configuring.Proper
  nameWithType: Apizr.Extending.Configuring.Proper
  fullName: Apizr.Extending.Configuring.Proper
  spec.csharp:
  - uid: Apizr
    name: Apizr
    href: Apizr.html
  - name: .
  - uid: Apizr.Extending
    name: Extending
    href: Apizr.Extending.html
  - name: .
  - uid: Apizr.Extending.Configuring
    name: Configuring
    href: Apizr.Extending.Configuring.html
  - name: .
  - uid: Apizr.Extending.Configuring.Proper
    name: Proper
    href: Apizr.Extending.Configuring.Proper.html
  spec.vb:
  - uid: Apizr
    name: Apizr
    href: Apizr.html
  - name: .
  - uid: Apizr.Extending
    name: Extending
    href: Apizr.Extending.html
  - name: .
  - uid: Apizr.Extending.Configuring
    name: Configuring
    href: Apizr.Extending.Configuring.html
  - name: .
  - uid: Apizr.Extending.Configuring.Proper
    name: Proper
    href: Apizr.Extending.Configuring.Proper.html
