### YamlMime:ManagedReference
items:
- uid: Apizr.Extending.Configuring.Manager
  commentId: N:Apizr.Extending.Configuring.Manager
  id: Apizr.Extending.Configuring.Manager
  children:
  - Apizr.Extending.Configuring.Manager.ApizrExtendedManagerOptions
  - Apizr.Extending.Configuring.Manager.ApizrExtendedManagerOptions`1
  - Apizr.Extending.Configuring.Manager.ApizrExtendedManagerOptionsBase
  - Apizr.Extending.Configuring.Manager.ApizrExtendedManagerOptionsBuilder
  - Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptions
  - Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptions`1
  - Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBase
  - Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilder
  - Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilder`2
  - Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase
  - Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase`2
  langs:
  - csharp
  - vb
  name: Apizr.Extending.Configuring.Manager
  nameWithType: Apizr.Extending.Configuring.Manager
  fullName: Apizr.Extending.Configuring.Manager
  type: Namespace
  assemblies:
  - Apizr.Extensions.Microsoft.DependencyInjection
references:
- uid: Apizr.Extending.Configuring.Manager.ApizrExtendedManagerOptions
  commentId: T:Apizr.Extending.Configuring.Manager.ApizrExtendedManagerOptions
  parent: Apizr.Extending.Configuring.Manager
  name: ApizrExtendedManagerOptions
  nameWithType: ApizrExtendedManagerOptions
  fullName: Apizr.Extending.Configuring.Manager.ApizrExtendedManagerOptions
- uid: Apizr.Extending.Configuring.Manager.ApizrExtendedManagerOptions`1
  commentId: T:Apizr.Extending.Configuring.Manager.ApizrExtendedManagerOptions`1
  name: ApizrExtendedManagerOptions<TWebApi>
  nameWithType: ApizrExtendedManagerOptions<TWebApi>
  fullName: Apizr.Extending.Configuring.Manager.ApizrExtendedManagerOptions<TWebApi>
  nameWithType.vb: ApizrExtendedManagerOptions(Of TWebApi)
  fullName.vb: Apizr.Extending.Configuring.Manager.ApizrExtendedManagerOptions(Of TWebApi)
  name.vb: ApizrExtendedManagerOptions(Of TWebApi)
  spec.csharp:
  - uid: Apizr.Extending.Configuring.Manager.ApizrExtendedManagerOptions`1
    name: ApizrExtendedManagerOptions
    nameWithType: ApizrExtendedManagerOptions
    fullName: Apizr.Extending.Configuring.Manager.ApizrExtendedManagerOptions
  - name: <
    nameWithType: <
    fullName: <
  - name: TWebApi
    nameWithType: TWebApi
    fullName: TWebApi
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Apizr.Extending.Configuring.Manager.ApizrExtendedManagerOptions`1
    name: ApizrExtendedManagerOptions
    nameWithType: ApizrExtendedManagerOptions
    fullName: Apizr.Extending.Configuring.Manager.ApizrExtendedManagerOptions
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TWebApi
    nameWithType: TWebApi
    fullName: TWebApi
  - name: )
    nameWithType: )
    fullName: )
- uid: Apizr.Extending.Configuring.Manager.ApizrExtendedManagerOptionsBase
  commentId: T:Apizr.Extending.Configuring.Manager.ApizrExtendedManagerOptionsBase
  parent: Apizr.Extending.Configuring.Manager
  name: ApizrExtendedManagerOptionsBase
  nameWithType: ApizrExtendedManagerOptionsBase
  fullName: Apizr.Extending.Configuring.Manager.ApizrExtendedManagerOptionsBase
- uid: Apizr.Extending.Configuring.Manager.ApizrExtendedManagerOptionsBuilder
  commentId: T:Apizr.Extending.Configuring.Manager.ApizrExtendedManagerOptionsBuilder
  name: ApizrExtendedManagerOptionsBuilder
  nameWithType: ApizrExtendedManagerOptionsBuilder
  fullName: Apizr.Extending.Configuring.Manager.ApizrExtendedManagerOptionsBuilder
- uid: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptions
  commentId: T:Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptions
  parent: Apizr.Extending.Configuring.Manager
  name: IApizrExtendedManagerOptions
  nameWithType: IApizrExtendedManagerOptions
  fullName: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptions
- uid: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptions`1
  commentId: T:Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptions`1
  name: IApizrExtendedManagerOptions<TWebApi>
  nameWithType: IApizrExtendedManagerOptions<TWebApi>
  fullName: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptions<TWebApi>
  nameWithType.vb: IApizrExtendedManagerOptions(Of TWebApi)
  fullName.vb: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptions(Of TWebApi)
  name.vb: IApizrExtendedManagerOptions(Of TWebApi)
  spec.csharp:
  - uid: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptions`1
    name: IApizrExtendedManagerOptions
    nameWithType: IApizrExtendedManagerOptions
    fullName: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptions
  - name: <
    nameWithType: <
    fullName: <
  - name: TWebApi
    nameWithType: TWebApi
    fullName: TWebApi
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptions`1
    name: IApizrExtendedManagerOptions
    nameWithType: IApizrExtendedManagerOptions
    fullName: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptions
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TWebApi
    nameWithType: TWebApi
    fullName: TWebApi
  - name: )
    nameWithType: )
    fullName: )
- uid: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBase
  commentId: T:Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBase
  parent: Apizr.Extending.Configuring.Manager
  name: IApizrExtendedManagerOptionsBase
  nameWithType: IApizrExtendedManagerOptionsBase
  fullName: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBase
- uid: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilder`2
  commentId: T:Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilder`2
  name: IApizrExtendedManagerOptionsBuilder<TApizrExtendedOptions, TApizrExtendedOptionsBuilder>
  nameWithType: IApizrExtendedManagerOptionsBuilder<TApizrExtendedOptions, TApizrExtendedOptionsBuilder>
  fullName: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilder<TApizrExtendedOptions, TApizrExtendedOptionsBuilder>
  nameWithType.vb: IApizrExtendedManagerOptionsBuilder(Of TApizrExtendedOptions, TApizrExtendedOptionsBuilder)
  fullName.vb: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilder(Of TApizrExtendedOptions, TApizrExtendedOptionsBuilder)
  name.vb: IApizrExtendedManagerOptionsBuilder(Of TApizrExtendedOptions, TApizrExtendedOptionsBuilder)
  spec.csharp:
  - uid: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilder`2
    name: IApizrExtendedManagerOptionsBuilder
    nameWithType: IApizrExtendedManagerOptionsBuilder
    fullName: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilder
  - name: <
    nameWithType: <
    fullName: <
  - name: TApizrExtendedOptions
    nameWithType: TApizrExtendedOptions
    fullName: TApizrExtendedOptions
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TApizrExtendedOptionsBuilder
    nameWithType: TApizrExtendedOptionsBuilder
    fullName: TApizrExtendedOptionsBuilder
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilder`2
    name: IApizrExtendedManagerOptionsBuilder
    nameWithType: IApizrExtendedManagerOptionsBuilder
    fullName: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilder
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TApizrExtendedOptions
    nameWithType: TApizrExtendedOptions
    fullName: TApizrExtendedOptions
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TApizrExtendedOptionsBuilder
    nameWithType: TApizrExtendedOptionsBuilder
    fullName: TApizrExtendedOptionsBuilder
  - name: )
    nameWithType: )
    fullName: )
- uid: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilder
  commentId: T:Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilder
  parent: Apizr.Extending.Configuring.Manager
  name: IApizrExtendedManagerOptionsBuilder
  nameWithType: IApizrExtendedManagerOptionsBuilder
  fullName: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilder
- uid: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase
  commentId: T:Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase
  parent: Apizr.Extending.Configuring.Manager
  name: IApizrExtendedManagerOptionsBuilderBase
  nameWithType: IApizrExtendedManagerOptionsBuilderBase
  fullName: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase
- uid: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase`2
  commentId: T:Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase`2
  name: IApizrExtendedManagerOptionsBuilderBase<TApizrExtendedOptions, TApizrExtendedOptionsBuilder>
  nameWithType: IApizrExtendedManagerOptionsBuilderBase<TApizrExtendedOptions, TApizrExtendedOptionsBuilder>
  fullName: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase<TApizrExtendedOptions, TApizrExtendedOptionsBuilder>
  nameWithType.vb: IApizrExtendedManagerOptionsBuilderBase(Of TApizrExtendedOptions, TApizrExtendedOptionsBuilder)
  fullName.vb: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase(Of TApizrExtendedOptions, TApizrExtendedOptionsBuilder)
  name.vb: IApizrExtendedManagerOptionsBuilderBase(Of TApizrExtendedOptions, TApizrExtendedOptionsBuilder)
  spec.csharp:
  - uid: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase`2
    name: IApizrExtendedManagerOptionsBuilderBase
    nameWithType: IApizrExtendedManagerOptionsBuilderBase
    fullName: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase
  - name: <
    nameWithType: <
    fullName: <
  - name: TApizrExtendedOptions
    nameWithType: TApizrExtendedOptions
    fullName: TApizrExtendedOptions
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TApizrExtendedOptionsBuilder
    nameWithType: TApizrExtendedOptionsBuilder
    fullName: TApizrExtendedOptionsBuilder
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase`2
    name: IApizrExtendedManagerOptionsBuilderBase
    nameWithType: IApizrExtendedManagerOptionsBuilderBase
    fullName: Apizr.Extending.Configuring.Manager.IApizrExtendedManagerOptionsBuilderBase
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TApizrExtendedOptions
    nameWithType: TApizrExtendedOptions
    fullName: TApizrExtendedOptions
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TApizrExtendedOptionsBuilder
    nameWithType: TApizrExtendedOptionsBuilder
    fullName: TApizrExtendedOptionsBuilder
  - name: )
    nameWithType: )
    fullName: )
- uid: Apizr.Extending.Configuring.Manager
  commentId: N:Apizr.Extending.Configuring.Manager
  name: Apizr.Extending.Configuring.Manager
  nameWithType: Apizr.Extending.Configuring.Manager
  fullName: Apizr.Extending.Configuring.Manager
