### YamlMime:ManagedReference
items:
- uid: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptions
  commentId: T:Apizr.Configuring.Shared.Context.IApizrResilienceContextOptions
  id: IApizrResilienceContextOptions
  parent: Apizr.Configuring.Shared.Context
  children:
  - Apizr.Configuring.Shared.Context.IApizrResilienceContextOptions.ContinueOnCapturedContext
  - Apizr.Configuring.Shared.Context.IApizrResilienceContextOptions.ReturnToPoolOnComplete
  langs:
  - csharp
  - vb
  name: IApizrResilienceContextOptions
  nameWithType: IApizrResilienceContextOptions
  fullName: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptions
  type: Interface
  source:
    remote:
      path: Apizr/Src/Apizr/Configuring/Shared/Context/IApizrResilienceContextOptions.cs
      branch: master
      repo: https://github.com/Respawnsive/Apizr.git
    id: IApizrResilienceContextOptions
    path: ../../Src/Apizr/Configuring/Shared/Context/IApizrResilienceContextOptions.cs
    startLine: 2
  assemblies:
  - Apizr
  namespace: Apizr.Configuring.Shared.Context
  syntax:
    content: public interface IApizrResilienceContextOptions
    content.vb: Public Interface IApizrResilienceContextOptions
- uid: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptions.ContinueOnCapturedContext
  commentId: P:Apizr.Configuring.Shared.Context.IApizrResilienceContextOptions.ContinueOnCapturedContext
  id: ContinueOnCapturedContext
  parent: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptions
  langs:
  - csharp
  - vb
  name: ContinueOnCapturedContext
  nameWithType: IApizrResilienceContextOptions.ContinueOnCapturedContext
  fullName: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptions.ContinueOnCapturedContext
  type: Property
  source:
    remote:
      path: Apizr/Src/Apizr/Configuring/Shared/Context/IApizrResilienceContextOptions.cs
      branch: master
      repo: https://github.com/Respawnsive/Apizr.git
    id: ContinueOnCapturedContext
    path: ../../Src/Apizr/Configuring/Shared/Context/IApizrResilienceContextOptions.cs
    startLine: 7
  assemblies:
  - Apizr
  namespace: Apizr.Configuring.Shared.Context
  summary: Gets the value indicating whether to continue on captured context, if any.
  example: []
  syntax:
    content: bool? ContinueOnCapturedContext { get; }
    parameters: []
    return:
      type: System.Nullable{System.Boolean}
    content.vb: ReadOnly Property ContinueOnCapturedContext As Boolean?
  overload: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptions.ContinueOnCapturedContext*
- uid: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptions.ReturnToPoolOnComplete
  commentId: P:Apizr.Configuring.Shared.Context.IApizrResilienceContextOptions.ReturnToPoolOnComplete
  id: ReturnToPoolOnComplete
  parent: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptions
  langs:
  - csharp
  - vb
  name: ReturnToPoolOnComplete
  nameWithType: IApizrResilienceContextOptions.ReturnToPoolOnComplete
  fullName: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptions.ReturnToPoolOnComplete
  type: Property
  source:
    remote:
      path: Apizr/Src/Apizr/Configuring/Shared/Context/IApizrResilienceContextOptions.cs
      branch: master
      repo: https://github.com/Respawnsive/Apizr.git
    id: ReturnToPoolOnComplete
    path: ../../Src/Apizr/Configuring/Shared/Context/IApizrResilienceContextOptions.cs
    startLine: 12
  assemblies:
  - Apizr
  namespace: Apizr.Configuring.Shared.Context
  summary: Gets the value indicating whether to return the context to the pool, when request completes.
  example: []
  syntax:
    content: bool? ReturnToPoolOnComplete { get; }
    parameters: []
    return:
      type: System.Nullable{System.Boolean}
    content.vb: ReadOnly Property ReturnToPoolOnComplete As Boolean?
  overload: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptions.ReturnToPoolOnComplete*
references:
- uid: Apizr.Configuring.Shared.Context
  commentId: N:Apizr.Configuring.Shared.Context
  href: Apizr.html
  name: Apizr.Configuring.Shared.Context
  nameWithType: Apizr.Configuring.Shared.Context
  fullName: Apizr.Configuring.Shared.Context
  spec.csharp:
  - uid: Apizr
    name: Apizr
    href: Apizr.html
  - name: .
  - uid: Apizr.Configuring
    name: Configuring
    href: Apizr.Configuring.html
  - name: .
  - uid: Apizr.Configuring.Shared
    name: Shared
    href: Apizr.Configuring.Shared.html
  - name: .
  - uid: Apizr.Configuring.Shared.Context
    name: Context
    href: Apizr.Configuring.Shared.Context.html
  spec.vb:
  - uid: Apizr
    name: Apizr
    href: Apizr.html
  - name: .
  - uid: Apizr.Configuring
    name: Configuring
    href: Apizr.Configuring.html
  - name: .
  - uid: Apizr.Configuring.Shared
    name: Shared
    href: Apizr.Configuring.Shared.html
  - name: .
  - uid: Apizr.Configuring.Shared.Context
    name: Context
    href: Apizr.Configuring.Shared.Context.html
- uid: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptions.ContinueOnCapturedContext*
  commentId: Overload:Apizr.Configuring.Shared.Context.IApizrResilienceContextOptions.ContinueOnCapturedContext
  href: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptions.html#Apizr_Configuring_Shared_Context_IApizrResilienceContextOptions_ContinueOnCapturedContext
  name: ContinueOnCapturedContext
  nameWithType: IApizrResilienceContextOptions.ContinueOnCapturedContext
  fullName: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptions.ContinueOnCapturedContext
- uid: System.Nullable{System.Boolean}
  commentId: T:System.Nullable{System.Boolean}
  parent: System
  definition: System.Nullable`1
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool?
  nameWithType: bool?
  fullName: bool?
  nameWithType.vb: Boolean?
  fullName.vb: Boolean?
  name.vb: Boolean?
  spec.csharp:
  - uid: System.Boolean
    name: bool
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: '?'
  spec.vb:
  - uid: System.Boolean
    name: Boolean
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: '?'
- uid: System.Nullable`1
  commentId: T:System.Nullable`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.nullable-1
  name: Nullable<T>
  nameWithType: Nullable<T>
  fullName: System.Nullable<T>
  nameWithType.vb: Nullable(Of T)
  fullName.vb: System.Nullable(Of T)
  name.vb: Nullable(Of T)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.nullable-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.nullable-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptions.ReturnToPoolOnComplete*
  commentId: Overload:Apizr.Configuring.Shared.Context.IApizrResilienceContextOptions.ReturnToPoolOnComplete
  href: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptions.html#Apizr_Configuring_Shared_Context_IApizrResilienceContextOptions_ReturnToPoolOnComplete
  name: ReturnToPoolOnComplete
  nameWithType: IApizrResilienceContextOptions.ReturnToPoolOnComplete
  fullName: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptions.ReturnToPoolOnComplete
