### YamlMime:ManagedReference
items:
- uid: Apizr.Configuring.Proper.IApizrProperOptionsBuilderBase
  commentId: T:Apizr.Configuring.Proper.IApizrProperOptionsBuilderBase
  id: IApizrProperOptionsBuilderBase
  parent: Apizr.Configuring.Proper
  children: []
  langs:
  - csharp
  - vb
  name: IApizrProperOptionsBuilderBase
  nameWithType: IApizrProperOptionsBuilderBase
  fullName: Apizr.Configuring.Proper.IApizrProperOptionsBuilderBase
  type: Interface
  source:
    id: IApizrProperOptionsBuilderBase
    path: C:\Dev\Community\Apizr\Apizr\Apizr\Configuring\Proper\IApizrProperOptionsBuilderBase.cs
    startLine: 7
  assemblies:
  - Apizr
  namespace: Apizr.Configuring.Proper
  summary: "\nBuilder options available at proper level for both static and extended registrations\n"
  example: []
  syntax:
    content: 'public interface IApizrProperOptionsBuilderBase : IApizrGlobalProperOptionsBuilderBase, IApizrSharedOptionsBuilderBase, IApizrGlobalSharedOptionsBuilderBase'
    content.vb: >-
      Public Interface IApizrProperOptionsBuilderBase
          Inherits IApizrGlobalProperOptionsBuilderBase, IApizrSharedOptionsBuilderBase
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
references:
- uid: Apizr.Configuring.Proper
  commentId: N:Apizr.Configuring.Proper
  name: Apizr.Configuring.Proper
  nameWithType: Apizr.Configuring.Proper
  fullName: Apizr.Configuring.Proper
