### YamlMime:ManagedReference
items:
- uid: Apizr.Configuring.Request
  commentId: N:Apizr.Configuring.Request
  id: Apizr.Configuring.Request
  children:
  - Apizr.Configuring.Request.ApizrRequestOptions
  - Apizr.Configuring.Request.ApizrRequestOptionsBase
  - Apizr.Configuring.Request.ApizrRequestOptionsBuilder
  - Apizr.Configuring.Request.IApizrRequestOptions
  - Apizr.Configuring.Request.IApizrRequestOptionsBase
  - Apizr.Configuring.Request.IApizrRequestOptionsBuilder
  - Apizr.Configuring.Request.IApizrRequestOptionsBuilderBase
  - Apizr.Configuring.Request.IApizrRequestOptionsBuilderBase`2
  - Apizr.Configuring.Request.IApizrRequestOptionsBuilder`2
  - Apizr.Configuring.Request.RequestOptionsAttribute
  langs:
  - csharp
  - vb
  name: Apizr.Configuring.Request
  nameWithType: Apizr.Configuring.Request
  fullName: Apizr.Configuring.Request
  type: Namespace
  assemblies:
  - Apizr
references:
- uid: Apizr.Configuring.Request.ApizrRequestOptions
  commentId: T:Apizr.Configuring.Request.ApizrRequestOptions
  parent: Apizr.Configuring.Request
  href: Apizr.Configuring.Request.ApizrRequestOptions.html
  name: ApizrRequestOptions
  nameWithType: ApizrRequestOptions
  fullName: Apizr.Configuring.Request.ApizrRequestOptions
- uid: Apizr.Configuring.Request.ApizrRequestOptionsBase
  commentId: T:Apizr.Configuring.Request.ApizrRequestOptionsBase
  parent: Apizr.Configuring.Request
  href: Apizr.Configuring.Request.ApizrRequestOptionsBase.html
  name: ApizrRequestOptionsBase
  nameWithType: ApizrRequestOptionsBase
  fullName: Apizr.Configuring.Request.ApizrRequestOptionsBase
- uid: Apizr.Configuring.Request.ApizrRequestOptionsBuilder
  commentId: T:Apizr.Configuring.Request.ApizrRequestOptionsBuilder
  href: Apizr.Configuring.Request.ApizrRequestOptionsBuilder.html
  name: ApizrRequestOptionsBuilder
  nameWithType: ApizrRequestOptionsBuilder
  fullName: Apizr.Configuring.Request.ApizrRequestOptionsBuilder
- uid: Apizr.Configuring.Request.IApizrRequestOptions
  commentId: T:Apizr.Configuring.Request.IApizrRequestOptions
  parent: Apizr.Configuring.Request
  href: Apizr.Configuring.Request.IApizrRequestOptions.html
  name: IApizrRequestOptions
  nameWithType: IApizrRequestOptions
  fullName: Apizr.Configuring.Request.IApizrRequestOptions
- uid: Apizr.Configuring.Request.IApizrRequestOptionsBase
  commentId: T:Apizr.Configuring.Request.IApizrRequestOptionsBase
  parent: Apizr.Configuring.Request
  href: Apizr.Configuring.Request.IApizrRequestOptionsBase.html
  name: IApizrRequestOptionsBase
  nameWithType: IApizrRequestOptionsBase
  fullName: Apizr.Configuring.Request.IApizrRequestOptionsBase
- uid: Apizr.Configuring.Request.IApizrRequestOptionsBuilder`2
  commentId: T:Apizr.Configuring.Request.IApizrRequestOptionsBuilder`2
  href: Apizr.Configuring.Request.IApizrRequestOptionsBuilder-2.html
  name: IApizrRequestOptionsBuilder<TApizrOptions, TApizrOptionsBuilder>
  nameWithType: IApizrRequestOptionsBuilder<TApizrOptions, TApizrOptionsBuilder>
  fullName: Apizr.Configuring.Request.IApizrRequestOptionsBuilder<TApizrOptions, TApizrOptionsBuilder>
  nameWithType.vb: IApizrRequestOptionsBuilder(Of TApizrOptions, TApizrOptionsBuilder)
  fullName.vb: Apizr.Configuring.Request.IApizrRequestOptionsBuilder(Of TApizrOptions, TApizrOptionsBuilder)
  name.vb: IApizrRequestOptionsBuilder(Of TApizrOptions, TApizrOptionsBuilder)
  spec.csharp:
  - uid: Apizr.Configuring.Request.IApizrRequestOptionsBuilder`2
    name: IApizrRequestOptionsBuilder
    href: Apizr.Configuring.Request.IApizrRequestOptionsBuilder-2.html
  - name: <
  - name: TApizrOptions
  - name: ','
  - name: " "
  - name: TApizrOptionsBuilder
  - name: '>'
  spec.vb:
  - uid: Apizr.Configuring.Request.IApizrRequestOptionsBuilder`2
    name: IApizrRequestOptionsBuilder
    href: Apizr.Configuring.Request.IApizrRequestOptionsBuilder-2.html
  - name: (
  - name: Of
  - name: " "
  - name: TApizrOptions
  - name: ','
  - name: " "
  - name: TApizrOptionsBuilder
  - name: )
- uid: Apizr.Configuring.Request.IApizrRequestOptionsBuilder
  commentId: T:Apizr.Configuring.Request.IApizrRequestOptionsBuilder
  parent: Apizr.Configuring.Request
  href: Apizr.Configuring.Request.IApizrRequestOptionsBuilder.html
  name: IApizrRequestOptionsBuilder
  nameWithType: IApizrRequestOptionsBuilder
  fullName: Apizr.Configuring.Request.IApizrRequestOptionsBuilder
- uid: Apizr.Configuring.Request.IApizrRequestOptionsBuilderBase
  commentId: T:Apizr.Configuring.Request.IApizrRequestOptionsBuilderBase
  parent: Apizr.Configuring.Request
  href: Apizr.Configuring.Request.IApizrRequestOptionsBuilderBase.html
  name: IApizrRequestOptionsBuilderBase
  nameWithType: IApizrRequestOptionsBuilderBase
  fullName: Apizr.Configuring.Request.IApizrRequestOptionsBuilderBase
- uid: Apizr.Configuring.Request.IApizrRequestOptionsBuilderBase`2
  commentId: T:Apizr.Configuring.Request.IApizrRequestOptionsBuilderBase`2
  href: Apizr.Configuring.Request.IApizrRequestOptionsBuilderBase-2.html
  name: IApizrRequestOptionsBuilderBase<TApizrOptions, TApizrOptionsBuilder>
  nameWithType: IApizrRequestOptionsBuilderBase<TApizrOptions, TApizrOptionsBuilder>
  fullName: Apizr.Configuring.Request.IApizrRequestOptionsBuilderBase<TApizrOptions, TApizrOptionsBuilder>
  nameWithType.vb: IApizrRequestOptionsBuilderBase(Of TApizrOptions, TApizrOptionsBuilder)
  fullName.vb: Apizr.Configuring.Request.IApizrRequestOptionsBuilderBase(Of TApizrOptions, TApizrOptionsBuilder)
  name.vb: IApizrRequestOptionsBuilderBase(Of TApizrOptions, TApizrOptionsBuilder)
  spec.csharp:
  - uid: Apizr.Configuring.Request.IApizrRequestOptionsBuilderBase`2
    name: IApizrRequestOptionsBuilderBase
    href: Apizr.Configuring.Request.IApizrRequestOptionsBuilderBase-2.html
  - name: <
  - name: TApizrOptions
  - name: ','
  - name: " "
  - name: TApizrOptionsBuilder
  - name: '>'
  spec.vb:
  - uid: Apizr.Configuring.Request.IApizrRequestOptionsBuilderBase`2
    name: IApizrRequestOptionsBuilderBase
    href: Apizr.Configuring.Request.IApizrRequestOptionsBuilderBase-2.html
  - name: (
  - name: Of
  - name: " "
  - name: TApizrOptions
  - name: ','
  - name: " "
  - name: TApizrOptionsBuilder
  - name: )
- uid: Apizr.Configuring.Request.RequestOptionsAttribute
  commentId: T:Apizr.Configuring.Request.RequestOptionsAttribute
  parent: Apizr.Configuring.Request
  href: Apizr.Configuring.Request.RequestOptionsAttribute.html
  name: RequestOptionsAttribute
  nameWithType: RequestOptionsAttribute
  fullName: Apizr.Configuring.Request.RequestOptionsAttribute
- uid: Apizr.Configuring.Request
  commentId: N:Apizr.Configuring.Request
  href: Apizr.html
  name: Apizr.Configuring.Request
  nameWithType: Apizr.Configuring.Request
  fullName: Apizr.Configuring.Request
  spec.csharp:
  - uid: Apizr
    name: Apizr
    href: Apizr.html
  - name: .
  - uid: Apizr.Configuring
    name: Configuring
    href: Apizr.Configuring.html
  - name: .
  - uid: Apizr.Configuring.Request
    name: Request
    href: Apizr.Configuring.Request.html
  spec.vb:
  - uid: Apizr
    name: Apizr
    href: Apizr.html
  - name: .
  - uid: Apizr.Configuring
    name: Configuring
    href: Apizr.Configuring.html
  - name: .
  - uid: Apizr.Configuring.Request
    name: Request
    href: Apizr.Configuring.Request.html
