### YamlMime:ManagedReference
items:
- uid: Apizr.Optional.Configuring.Registry
  commentId: N:Apizr.Optional.Configuring.Registry
  id: Apizr.Optional.Configuring.Registry
  children:
  - Apizr.Optional.Configuring.Registry.ApizrOptionalMediationRegistry
  - Apizr.Optional.Configuring.Registry.ApizrOptionalMediationRegistryBase
  - Apizr.Optional.Configuring.Registry.IApizrOptionalMediationConcurrentRegistry
  - Apizr.Optional.Configuring.Registry.IApizrOptionalMediationEnumerableRegistry
  - Apizr.Optional.Configuring.Registry.IApizrOptionalMediationRegistry
  langs:
  - csharp
  - vb
  name: Apizr.Optional.Configuring.Registry
  nameWithType: Apizr.Optional.Configuring.Registry
  fullName: Apizr.Optional.Configuring.Registry
  type: Namespace
  assemblies:
  - Apizr.Integrations.Optional
references:
- uid: Apizr.Optional.Configuring.Registry.ApizrOptionalMediationRegistry
  commentId: T:Apizr.Optional.Configuring.Registry.ApizrOptionalMediationRegistry
  name: ApizrOptionalMediationRegistry
  nameWithType: ApizrOptionalMediationRegistry
  fullName: Apizr.Optional.Configuring.Registry.ApizrOptionalMediationRegistry
- uid: Apizr.Optional.Configuring.Registry.ApizrOptionalMediationRegistryBase
  commentId: T:Apizr.Optional.Configuring.Registry.ApizrOptionalMediationRegistryBase
  parent: Apizr.Optional.Configuring.Registry
  name: ApizrOptionalMediationRegistryBase
  nameWithType: ApizrOptionalMediationRegistryBase
  fullName: Apizr.Optional.Configuring.Registry.ApizrOptionalMediationRegistryBase
- uid: Apizr.Optional.Configuring.Registry.IApizrOptionalMediationConcurrentRegistry
  commentId: T:Apizr.Optional.Configuring.Registry.IApizrOptionalMediationConcurrentRegistry
  parent: Apizr.Optional.Configuring.Registry
  name: IApizrOptionalMediationConcurrentRegistry
  nameWithType: IApizrOptionalMediationConcurrentRegistry
  fullName: Apizr.Optional.Configuring.Registry.IApizrOptionalMediationConcurrentRegistry
- uid: Apizr.Optional.Configuring.Registry.IApizrOptionalMediationEnumerableRegistry
  commentId: T:Apizr.Optional.Configuring.Registry.IApizrOptionalMediationEnumerableRegistry
  parent: Apizr.Optional.Configuring.Registry
  name: IApizrOptionalMediationEnumerableRegistry
  nameWithType: IApizrOptionalMediationEnumerableRegistry
  fullName: Apizr.Optional.Configuring.Registry.IApizrOptionalMediationEnumerableRegistry
- uid: Apizr.Optional.Configuring.Registry.IApizrOptionalMediationRegistry
  commentId: T:Apizr.Optional.Configuring.Registry.IApizrOptionalMediationRegistry
  parent: Apizr.Optional.Configuring.Registry
  name: IApizrOptionalMediationRegistry
  nameWithType: IApizrOptionalMediationRegistry
  fullName: Apizr.Optional.Configuring.Registry.IApizrOptionalMediationRegistry
- uid: Apizr.Optional.Configuring.Registry
  commentId: N:Apizr.Optional.Configuring.Registry
  name: Apizr.Optional.Configuring.Registry
  nameWithType: Apizr.Optional.Configuring.Registry
  fullName: Apizr.Optional.Configuring.Registry
