### YamlMime:ManagedReference
items:
- uid: Apizr.Configuring.Shared.IApizrSharedRegistrationOptionsBase
  commentId: T:Apizr.Configuring.Shared.IApizrSharedRegistrationOptionsBase
  id: IApizrSharedRegistrationOptionsBase
  parent: Apizr.Configuring.Shared
  children: []
  langs:
  - csharp
  - vb
  name: IApizrSharedRegistrationOptionsBase
  nameWithType: IApizrSharedRegistrationOptionsBase
  fullName: Apizr.Configuring.Shared.IApizrSharedRegistrationOptionsBase
  type: Interface
  source:
    remote:
      path: Apizr/Src/Apizr/Configuring/Shared/IApizrSharedRegistrationOptionsBase.cs
      branch: dev
      repo: https://github.com/Respawnsive/Apizr.git
    id: IApizrSharedRegistrationOptionsBase
    path: ../../Src/Apizr/Configuring/Shared/IApizrSharedRegistrationOptionsBase.cs
    startLine: 9
  assemblies:
  - Apizr
  namespace: Apizr.Configuring.Shared
  summary: Options available at both common and proper level for both static and extended registrations
  example: []
  syntax:
    content: 'public interface IApizrSharedRegistrationOptionsBase : IApizrGlobalSharedRegistrationOptionsBase, IApizrGlobalSharedOptionsBase'
    content.vb: Public Interface IApizrSharedRegistrationOptionsBase Inherits IApizrGlobalSharedRegistrationOptionsBase, IApizrGlobalSharedOptionsBase
  inheritedMembers:
  - Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase.BaseUri
  - Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase.BaseAddress
  - Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase.BasePath
  - Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase.PrimaryHandlerFactory
  - Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase.HeadersFactories
  - Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase.Headers
  - Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.HttpTracerMode
  - Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.TrafficVerbosity
  - Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.LogLevels
  - Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.OnException
  - Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.LetThrowOnHandledException
  - Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.HandlersParameters
  - Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.OperationTimeout
  - Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.RequestTimeout
  - Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.ShouldRedactHeaderValue
  - Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.ResiliencePipelineOptions
  - Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.CacheOptions
references:
- uid: Apizr.Configuring.Shared
  commentId: N:Apizr.Configuring.Shared
  href: Apizr.html
  name: Apizr.Configuring.Shared
  nameWithType: Apizr.Configuring.Shared
  fullName: Apizr.Configuring.Shared
  spec.csharp:
  - uid: Apizr
    name: Apizr
    href: Apizr.html
  - name: .
  - uid: Apizr.Configuring
    name: Configuring
    href: Apizr.Configuring.html
  - name: .
  - uid: Apizr.Configuring.Shared
    name: Shared
    href: Apizr.Configuring.Shared.html
  spec.vb:
  - uid: Apizr
    name: Apizr
    href: Apizr.html
  - name: .
  - uid: Apizr.Configuring
    name: Configuring
    href: Apizr.Configuring.html
  - name: .
  - uid: Apizr.Configuring.Shared
    name: Shared
    href: Apizr.Configuring.Shared.html
- uid: Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase.BaseUri
  commentId: P:Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase.BaseUri
  parent: Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase
  href: Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase.html#Apizr_Configuring_Shared_IApizrGlobalSharedRegistrationOptionsBase_BaseUri
  name: BaseUri
  nameWithType: IApizrGlobalSharedRegistrationOptionsBase.BaseUri
  fullName: Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase.BaseUri
- uid: Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase.BaseAddress
  commentId: P:Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase.BaseAddress
  parent: Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase
  href: Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase.html#Apizr_Configuring_Shared_IApizrGlobalSharedRegistrationOptionsBase_BaseAddress
  name: BaseAddress
  nameWithType: IApizrGlobalSharedRegistrationOptionsBase.BaseAddress
  fullName: Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase.BaseAddress
- uid: Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase.BasePath
  commentId: P:Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase.BasePath
  parent: Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase
  href: Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase.html#Apizr_Configuring_Shared_IApizrGlobalSharedRegistrationOptionsBase_BasePath
  name: BasePath
  nameWithType: IApizrGlobalSharedRegistrationOptionsBase.BasePath
  fullName: Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase.BasePath
- uid: Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase.PrimaryHandlerFactory
  commentId: P:Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase.PrimaryHandlerFactory
  parent: Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase
  href: Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase.html#Apizr_Configuring_Shared_IApizrGlobalSharedRegistrationOptionsBase_PrimaryHandlerFactory
  name: PrimaryHandlerFactory
  nameWithType: IApizrGlobalSharedRegistrationOptionsBase.PrimaryHandlerFactory
  fullName: Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase.PrimaryHandlerFactory
- uid: Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase.HeadersFactories
  commentId: P:Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase.HeadersFactories
  parent: Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase
  href: Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase.html#Apizr_Configuring_Shared_IApizrGlobalSharedRegistrationOptionsBase_HeadersFactories
  name: HeadersFactories
  nameWithType: IApizrGlobalSharedRegistrationOptionsBase.HeadersFactories
  fullName: Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase.HeadersFactories
- uid: Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase.Headers
  commentId: P:Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase.Headers
  parent: Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase
  href: Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase.html#Apizr_Configuring_Shared_IApizrGlobalSharedRegistrationOptionsBase_Headers
  name: Headers
  nameWithType: IApizrGlobalSharedRegistrationOptionsBase.Headers
  fullName: Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase.Headers
- uid: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.HttpTracerMode
  commentId: P:Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.HttpTracerMode
  parent: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase
  href: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.html#Apizr_Configuring_Shared_IApizrGlobalSharedOptionsBase_HttpTracerMode
  name: HttpTracerMode
  nameWithType: IApizrGlobalSharedOptionsBase.HttpTracerMode
  fullName: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.HttpTracerMode
- uid: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.TrafficVerbosity
  commentId: P:Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.TrafficVerbosity
  parent: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase
  href: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.html#Apizr_Configuring_Shared_IApizrGlobalSharedOptionsBase_TrafficVerbosity
  name: TrafficVerbosity
  nameWithType: IApizrGlobalSharedOptionsBase.TrafficVerbosity
  fullName: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.TrafficVerbosity
- uid: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.LogLevels
  commentId: P:Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.LogLevels
  parent: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase
  href: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.html#Apizr_Configuring_Shared_IApizrGlobalSharedOptionsBase_LogLevels
  name: LogLevels
  nameWithType: IApizrGlobalSharedOptionsBase.LogLevels
  fullName: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.LogLevels
- uid: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.OnException
  commentId: P:Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.OnException
  parent: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase
  href: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.html#Apizr_Configuring_Shared_IApizrGlobalSharedOptionsBase_OnException
  name: OnException
  nameWithType: IApizrGlobalSharedOptionsBase.OnException
  fullName: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.OnException
- uid: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.LetThrowOnHandledException
  commentId: P:Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.LetThrowOnHandledException
  parent: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase
  href: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.html#Apizr_Configuring_Shared_IApizrGlobalSharedOptionsBase_LetThrowOnHandledException
  name: LetThrowOnHandledException
  nameWithType: IApizrGlobalSharedOptionsBase.LetThrowOnHandledException
  fullName: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.LetThrowOnHandledException
- uid: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.HandlersParameters
  commentId: P:Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.HandlersParameters
  parent: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase
  href: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.html#Apizr_Configuring_Shared_IApizrGlobalSharedOptionsBase_HandlersParameters
  name: HandlersParameters
  nameWithType: IApizrGlobalSharedOptionsBase.HandlersParameters
  fullName: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.HandlersParameters
- uid: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.OperationTimeout
  commentId: P:Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.OperationTimeout
  parent: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase
  href: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.html#Apizr_Configuring_Shared_IApizrGlobalSharedOptionsBase_OperationTimeout
  name: OperationTimeout
  nameWithType: IApizrGlobalSharedOptionsBase.OperationTimeout
  fullName: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.OperationTimeout
- uid: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.RequestTimeout
  commentId: P:Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.RequestTimeout
  parent: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase
  href: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.html#Apizr_Configuring_Shared_IApizrGlobalSharedOptionsBase_RequestTimeout
  name: RequestTimeout
  nameWithType: IApizrGlobalSharedOptionsBase.RequestTimeout
  fullName: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.RequestTimeout
- uid: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.ShouldRedactHeaderValue
  commentId: P:Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.ShouldRedactHeaderValue
  parent: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase
  href: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.html#Apizr_Configuring_Shared_IApizrGlobalSharedOptionsBase_ShouldRedactHeaderValue
  name: ShouldRedactHeaderValue
  nameWithType: IApizrGlobalSharedOptionsBase.ShouldRedactHeaderValue
  fullName: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.ShouldRedactHeaderValue
- uid: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.ResiliencePipelineOptions
  commentId: P:Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.ResiliencePipelineOptions
  parent: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase
  href: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.html#Apizr_Configuring_Shared_IApizrGlobalSharedOptionsBase_ResiliencePipelineOptions
  name: ResiliencePipelineOptions
  nameWithType: IApizrGlobalSharedOptionsBase.ResiliencePipelineOptions
  fullName: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.ResiliencePipelineOptions
- uid: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.CacheOptions
  commentId: P:Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.CacheOptions
  parent: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase
  href: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.html#Apizr_Configuring_Shared_IApizrGlobalSharedOptionsBase_CacheOptions
  name: CacheOptions
  nameWithType: IApizrGlobalSharedOptionsBase.CacheOptions
  fullName: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.CacheOptions
- uid: Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase
  commentId: T:Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase
  parent: Apizr.Configuring.Shared
  href: Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase.html
  name: IApizrGlobalSharedRegistrationOptionsBase
  nameWithType: IApizrGlobalSharedRegistrationOptionsBase
  fullName: Apizr.Configuring.Shared.IApizrGlobalSharedRegistrationOptionsBase
- uid: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase
  commentId: T:Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase
  parent: Apizr.Configuring.Shared
  href: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase.html
  name: IApizrGlobalSharedOptionsBase
  nameWithType: IApizrGlobalSharedOptionsBase
  fullName: Apizr.Configuring.Shared.IApizrGlobalSharedOptionsBase
