### YamlMime:ManagedReference
items:
- uid: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder
  commentId: T:Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder
  id: IApizrResilienceContextOptionsBuilder
  parent: Apizr.Configuring.Shared.Context
  children:
  - Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder.ContinueOnCapturedContext(System.Boolean)
  - Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder.ReturnToPoolOnComplete(System.Boolean)
  langs:
  - csharp
  - vb
  name: IApizrResilienceContextOptionsBuilder
  nameWithType: IApizrResilienceContextOptionsBuilder
  fullName: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder
  type: Interface
  source:
    remote:
      path: Apizr/Src/Apizr/Configuring/Shared/Context/IApizrResilienceContextOptionsBuilder.cs
      branch: dev
      repo: https://github.com/Respawnsive/Apizr.git
    id: IApizrResilienceContextOptionsBuilder
    path: ../../Src/Apizr/Configuring/Shared/Context/IApizrResilienceContextOptionsBuilder.cs
    startLine: 2
  assemblies:
  - Apizr
  namespace: Apizr.Configuring.Shared.Context
  syntax:
    content: public interface IApizrResilienceContextOptionsBuilder
    content.vb: Public Interface IApizrResilienceContextOptionsBuilder
- uid: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder.ContinueOnCapturedContext(System.Boolean)
  commentId: M:Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder.ContinueOnCapturedContext(System.Boolean)
  id: ContinueOnCapturedContext(System.Boolean)
  parent: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder
  langs:
  - csharp
  - vb
  name: ContinueOnCapturedContext(bool)
  nameWithType: IApizrResilienceContextOptionsBuilder.ContinueOnCapturedContext(bool)
  fullName: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder.ContinueOnCapturedContext(bool)
  type: Method
  source:
    remote:
      path: Apizr/Src/Apizr/Configuring/Shared/Context/IApizrResilienceContextOptionsBuilder.cs
      branch: dev
      repo: https://github.com/Respawnsive/Apizr.git
    id: ContinueOnCapturedContext
    path: ../../Src/Apizr/Configuring/Shared/Context/IApizrResilienceContextOptionsBuilder.cs
    startLine: 6
  assemblies:
  - Apizr
  namespace: Apizr.Configuring.Shared.Context
  syntax:
    content: IApizrResilienceContextOptionsBuilder ContinueOnCapturedContext(bool continueOnCapturedContext)
    parameters:
    - id: continueOnCapturedContext
      type: System.Boolean
    return:
      type: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder
    content.vb: Function ContinueOnCapturedContext(continueOnCapturedContext As Boolean) As IApizrResilienceContextOptionsBuilder
  overload: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder.ContinueOnCapturedContext*
  nameWithType.vb: IApizrResilienceContextOptionsBuilder.ContinueOnCapturedContext(Boolean)
  fullName.vb: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder.ContinueOnCapturedContext(Boolean)
  name.vb: ContinueOnCapturedContext(Boolean)
- uid: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder.ReturnToPoolOnComplete(System.Boolean)
  commentId: M:Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder.ReturnToPoolOnComplete(System.Boolean)
  id: ReturnToPoolOnComplete(System.Boolean)
  parent: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder
  langs:
  - csharp
  - vb
  name: ReturnToPoolOnComplete(bool)
  nameWithType: IApizrResilienceContextOptionsBuilder.ReturnToPoolOnComplete(bool)
  fullName: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder.ReturnToPoolOnComplete(bool)
  type: Method
  source:
    remote:
      path: Apizr/Src/Apizr/Configuring/Shared/Context/IApizrResilienceContextOptionsBuilder.cs
      branch: dev
      repo: https://github.com/Respawnsive/Apizr.git
    id: ReturnToPoolOnComplete
    path: ../../Src/Apizr/Configuring/Shared/Context/IApizrResilienceContextOptionsBuilder.cs
    startLine: 8
  assemblies:
  - Apizr
  namespace: Apizr.Configuring.Shared.Context
  syntax:
    content: IApizrResilienceContextOptionsBuilder ReturnToPoolOnComplete(bool returnToPoolOnComplete)
    parameters:
    - id: returnToPoolOnComplete
      type: System.Boolean
    return:
      type: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder
    content.vb: Function ReturnToPoolOnComplete(returnToPoolOnComplete As Boolean) As IApizrResilienceContextOptionsBuilder
  overload: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder.ReturnToPoolOnComplete*
  nameWithType.vb: IApizrResilienceContextOptionsBuilder.ReturnToPoolOnComplete(Boolean)
  fullName.vb: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder.ReturnToPoolOnComplete(Boolean)
  name.vb: ReturnToPoolOnComplete(Boolean)
references:
- uid: Apizr.Configuring.Shared.Context
  commentId: N:Apizr.Configuring.Shared.Context
  href: Apizr.html
  name: Apizr.Configuring.Shared.Context
  nameWithType: Apizr.Configuring.Shared.Context
  fullName: Apizr.Configuring.Shared.Context
  spec.csharp:
  - uid: Apizr
    name: Apizr
    href: Apizr.html
  - name: .
  - uid: Apizr.Configuring
    name: Configuring
    href: Apizr.Configuring.html
  - name: .
  - uid: Apizr.Configuring.Shared
    name: Shared
    href: Apizr.Configuring.Shared.html
  - name: .
  - uid: Apizr.Configuring.Shared.Context
    name: Context
    href: Apizr.Configuring.Shared.Context.html
  spec.vb:
  - uid: Apizr
    name: Apizr
    href: Apizr.html
  - name: .
  - uid: Apizr.Configuring
    name: Configuring
    href: Apizr.Configuring.html
  - name: .
  - uid: Apizr.Configuring.Shared
    name: Shared
    href: Apizr.Configuring.Shared.html
  - name: .
  - uid: Apizr.Configuring.Shared.Context
    name: Context
    href: Apizr.Configuring.Shared.Context.html
- uid: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder.ContinueOnCapturedContext*
  commentId: Overload:Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder.ContinueOnCapturedContext
  href: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder.html#Apizr_Configuring_Shared_Context_IApizrResilienceContextOptionsBuilder_ContinueOnCapturedContext_System_Boolean_
  name: ContinueOnCapturedContext
  nameWithType: IApizrResilienceContextOptionsBuilder.ContinueOnCapturedContext
  fullName: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder.ContinueOnCapturedContext
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder
  commentId: T:Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder
  parent: Apizr.Configuring.Shared.Context
  href: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder.html
  name: IApizrResilienceContextOptionsBuilder
  nameWithType: IApizrResilienceContextOptionsBuilder
  fullName: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder.ReturnToPoolOnComplete*
  commentId: Overload:Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder.ReturnToPoolOnComplete
  href: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder.html#Apizr_Configuring_Shared_Context_IApizrResilienceContextOptionsBuilder_ReturnToPoolOnComplete_System_Boolean_
  name: ReturnToPoolOnComplete
  nameWithType: IApizrResilienceContextOptionsBuilder.ReturnToPoolOnComplete
  fullName: Apizr.Configuring.Shared.Context.IApizrResilienceContextOptionsBuilder.ReturnToPoolOnComplete
