### YamlMime:ManagedReference
items:
- uid: Apizr.Configuring.ApizrDuplicateStrategy
  commentId: T:Apizr.Configuring.ApizrDuplicateStrategy
  id: ApizrDuplicateStrategy
  parent: Apizr.Configuring
  children:
  - Apizr.Configuring.ApizrDuplicateStrategy.Add
  - Apizr.Configuring.ApizrDuplicateStrategy.Ignore
  - Apizr.Configuring.ApizrDuplicateStrategy.Merge
  - Apizr.Configuring.ApizrDuplicateStrategy.Replace
  langs:
  - csharp
  - vb
  name: ApizrDuplicateStrategy
  nameWithType: ApizrDuplicateStrategy
  fullName: Apizr.Configuring.ApizrDuplicateStrategy
  type: Enum
  source:
    remote:
      path: Apizr/Src/Apizr/Configuring/ApizrDuplicateStrategy.cs
      branch: dev
      repo: https://github.com/Respawnsive/Apizr.git
    id: ApizrDuplicateStrategy
    path: ../../Src/Apizr/Configuring/ApizrDuplicateStrategy.cs
    startLine: 5
  assemblies:
  - Apizr
  namespace: Apizr.Configuring
  summary: Duplicate strategy about options registration
  example: []
  syntax:
    content: public enum ApizrDuplicateStrategy
    content.vb: Public Enum ApizrDuplicateStrategy
- uid: Apizr.Configuring.ApizrDuplicateStrategy.Ignore
  commentId: F:Apizr.Configuring.ApizrDuplicateStrategy.Ignore
  id: Ignore
  parent: Apizr.Configuring.ApizrDuplicateStrategy
  langs:
  - csharp
  - vb
  name: Ignore
  nameWithType: ApizrDuplicateStrategy.Ignore
  fullName: Apizr.Configuring.ApizrDuplicateStrategy.Ignore
  type: Field
  source:
    remote:
      path: Apizr/Src/Apizr/Configuring/ApizrDuplicateStrategy.cs
      branch: dev
      repo: https://github.com/Respawnsive/Apizr.git
    id: Ignore
    path: ../../Src/Apizr/Configuring/ApizrDuplicateStrategy.cs
    startLine: 7
  assemblies:
  - Apizr
  namespace: Apizr.Configuring
  syntax:
    content: Ignore = 0
    return:
      type: Apizr.Configuring.ApizrDuplicateStrategy
- uid: Apizr.Configuring.ApizrDuplicateStrategy.Add
  commentId: F:Apizr.Configuring.ApizrDuplicateStrategy.Add
  id: Add
  parent: Apizr.Configuring.ApizrDuplicateStrategy
  langs:
  - csharp
  - vb
  name: Add
  nameWithType: ApizrDuplicateStrategy.Add
  fullName: Apizr.Configuring.ApizrDuplicateStrategy.Add
  type: Field
  source:
    remote:
      path: Apizr/Src/Apizr/Configuring/ApizrDuplicateStrategy.cs
      branch: dev
      repo: https://github.com/Respawnsive/Apizr.git
    id: Add
    path: ../../Src/Apizr/Configuring/ApizrDuplicateStrategy.cs
    startLine: 8
  assemblies:
  - Apizr
  namespace: Apizr.Configuring
  syntax:
    content: Add = 1
    return:
      type: Apizr.Configuring.ApizrDuplicateStrategy
- uid: Apizr.Configuring.ApizrDuplicateStrategy.Replace
  commentId: F:Apizr.Configuring.ApizrDuplicateStrategy.Replace
  id: Replace
  parent: Apizr.Configuring.ApizrDuplicateStrategy
  langs:
  - csharp
  - vb
  name: Replace
  nameWithType: ApizrDuplicateStrategy.Replace
  fullName: Apizr.Configuring.ApizrDuplicateStrategy.Replace
  type: Field
  source:
    remote:
      path: Apizr/Src/Apizr/Configuring/ApizrDuplicateStrategy.cs
      branch: dev
      repo: https://github.com/Respawnsive/Apizr.git
    id: Replace
    path: ../../Src/Apizr/Configuring/ApizrDuplicateStrategy.cs
    startLine: 9
  assemblies:
  - Apizr
  namespace: Apizr.Configuring
  syntax:
    content: Replace = 2
    return:
      type: Apizr.Configuring.ApizrDuplicateStrategy
- uid: Apizr.Configuring.ApizrDuplicateStrategy.Merge
  commentId: F:Apizr.Configuring.ApizrDuplicateStrategy.Merge
  id: Merge
  parent: Apizr.Configuring.ApizrDuplicateStrategy
  langs:
  - csharp
  - vb
  name: Merge
  nameWithType: ApizrDuplicateStrategy.Merge
  fullName: Apizr.Configuring.ApizrDuplicateStrategy.Merge
  type: Field
  source:
    remote:
      path: Apizr/Src/Apizr/Configuring/ApizrDuplicateStrategy.cs
      branch: dev
      repo: https://github.com/Respawnsive/Apizr.git
    id: Merge
    path: ../../Src/Apizr/Configuring/ApizrDuplicateStrategy.cs
    startLine: 10
  assemblies:
  - Apizr
  namespace: Apizr.Configuring
  syntax:
    content: Merge = 3
    return:
      type: Apizr.Configuring.ApizrDuplicateStrategy
references:
- uid: Apizr.Configuring
  commentId: N:Apizr.Configuring
  href: Apizr.html
  name: Apizr.Configuring
  nameWithType: Apizr.Configuring
  fullName: Apizr.Configuring
  spec.csharp:
  - uid: Apizr
    name: Apizr
    href: Apizr.html
  - name: .
  - uid: Apizr.Configuring
    name: Configuring
    href: Apizr.Configuring.html
  spec.vb:
  - uid: Apizr
    name: Apizr
    href: Apizr.html
  - name: .
  - uid: Apizr.Configuring
    name: Configuring
    href: Apizr.Configuring.html
- uid: Apizr.Configuring.ApizrDuplicateStrategy
  commentId: T:Apizr.Configuring.ApizrDuplicateStrategy
  parent: Apizr.Configuring
  href: Apizr.Configuring.ApizrDuplicateStrategy.html
  name: ApizrDuplicateStrategy
  nameWithType: ApizrDuplicateStrategy
  fullName: Apizr.Configuring.ApizrDuplicateStrategy
