### YamlMime:ManagedReference
items:
- uid: Apizr.Mediation.Configuring.Registry
  commentId: N:Apizr.Mediation.Configuring.Registry
  id: Apizr.Mediation.Configuring.Registry
  children:
  - Apizr.Mediation.Configuring.Registry.ApizrMediationRegistry
  - Apizr.Mediation.Configuring.Registry.ApizrMediationRegistryBase
  - Apizr.Mediation.Configuring.Registry.IApizrMediationConcurrentRegistry
  - Apizr.Mediation.Configuring.Registry.IApizrMediationEnumerableRegistry
  - Apizr.Mediation.Configuring.Registry.IApizrMediationRegistry
  langs:
  - csharp
  - vb
  name: Apizr.Mediation.Configuring.Registry
  nameWithType: Apizr.Mediation.Configuring.Registry
  fullName: Apizr.Mediation.Configuring.Registry
  type: Namespace
  assemblies:
  - Apizr.Integrations.MediatR
references:
- uid: Apizr.Mediation.Configuring.Registry.ApizrMediationRegistry
  commentId: T:Apizr.Mediation.Configuring.Registry.ApizrMediationRegistry
  href: Apizr.Mediation.Configuring.Registry.ApizrMediationRegistry.html
  name: ApizrMediationRegistry
  nameWithType: ApizrMediationRegistry
  fullName: Apizr.Mediation.Configuring.Registry.ApizrMediationRegistry
- uid: Apizr.Mediation.Configuring.Registry.ApizrMediationRegistryBase
  commentId: T:Apizr.Mediation.Configuring.Registry.ApizrMediationRegistryBase
  parent: Apizr.Mediation.Configuring.Registry
  href: Apizr.Mediation.Configuring.Registry.ApizrMediationRegistryBase.html
  name: ApizrMediationRegistryBase
  nameWithType: ApizrMediationRegistryBase
  fullName: Apizr.Mediation.Configuring.Registry.ApizrMediationRegistryBase
- uid: Apizr.Mediation.Configuring.Registry.IApizrMediationConcurrentRegistry
  commentId: T:Apizr.Mediation.Configuring.Registry.IApizrMediationConcurrentRegistry
  parent: Apizr.Mediation.Configuring.Registry
  href: Apizr.Mediation.Configuring.Registry.IApizrMediationConcurrentRegistry.html
  name: IApizrMediationConcurrentRegistry
  nameWithType: IApizrMediationConcurrentRegistry
  fullName: Apizr.Mediation.Configuring.Registry.IApizrMediationConcurrentRegistry
- uid: Apizr.Mediation.Configuring.Registry.IApizrMediationEnumerableRegistry
  commentId: T:Apizr.Mediation.Configuring.Registry.IApizrMediationEnumerableRegistry
  parent: Apizr.Mediation.Configuring.Registry
  href: Apizr.Mediation.Configuring.Registry.IApizrMediationEnumerableRegistry.html
  name: IApizrMediationEnumerableRegistry
  nameWithType: IApizrMediationEnumerableRegistry
  fullName: Apizr.Mediation.Configuring.Registry.IApizrMediationEnumerableRegistry
- uid: Apizr.Mediation.Configuring.Registry.IApizrMediationRegistry
  commentId: T:Apizr.Mediation.Configuring.Registry.IApizrMediationRegistry
  parent: Apizr.Mediation.Configuring.Registry
  href: Apizr.Mediation.Configuring.Registry.IApizrMediationRegistry.html
  name: IApizrMediationRegistry
  nameWithType: IApizrMediationRegistry
  fullName: Apizr.Mediation.Configuring.Registry.IApizrMediationRegistry
- uid: Apizr.Mediation.Configuring.Registry
  commentId: N:Apizr.Mediation.Configuring.Registry
  href: Apizr.html
  name: Apizr.Mediation.Configuring.Registry
  nameWithType: Apizr.Mediation.Configuring.Registry
  fullName: Apizr.Mediation.Configuring.Registry
  spec.csharp:
  - uid: Apizr
    name: Apizr
    href: Apizr.html
  - name: .
  - uid: Apizr.Mediation
    name: Mediation
    href: Apizr.Mediation.html
  - name: .
  - uid: Apizr.Mediation.Configuring
    name: Configuring
    href: Apizr.Mediation.Configuring.html
  - name: .
  - uid: Apizr.Mediation.Configuring.Registry
    name: Registry
    href: Apizr.Mediation.Configuring.Registry.html
  spec.vb:
  - uid: Apizr
    name: Apizr
    href: Apizr.html
  - name: .
  - uid: Apizr.Mediation
    name: Mediation
    href: Apizr.Mediation.html
  - name: .
  - uid: Apizr.Mediation.Configuring
    name: Configuring
    href: Apizr.Mediation.Configuring.html
  - name: .
  - uid: Apizr.Mediation.Configuring.Registry
    name: Registry
    href: Apizr.Mediation.Configuring.Registry.html
